### ISSUE TITLE
SFTP

### ISSUE THREAD

**Issue by trinidadcruz** [FreeRDP/Remmina#1005]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): 
- Remmina version (remmina --version): 
- Desktop environment (GNOME, Unity, KDE, ..): 
- Connecting to (OS and version): 
- Connecting via (RDP, VNC, ...): 
- RDP issues only, freerdp version (xfreerdp --version): 
##

**Comment by giox069** [comment]
Hi @trinidadcruz, unfortunately we cannot support remmina 1.1.X.
Have you tried to upgrade remmina to 1.2.X ? Instructions for using the ubuntu PPA with remmina 1.2 are on the [wiki](https://github.com/FreeRDP/Remmina/wiki).

**Comment by ic3d** [comment]
I'm closing this issue because it only affetcs an old version of Remmina.
