### ISSUE TITLE
Panel Icon almost invisible

### ISSUE THREAD

**Issue by joakim-tjernlund** [FreeRDP/Remmina#1006]
![screenshot at 2016-09-30 18-41-52](https://cloud.githubusercontent.com/assets/13720190/18999391/9915395c-873d-11e6-8f0c-d8f65801c678.png)

Looking at the above screenshot it is hard to see the Remmina icon, can you add an black outline
or something similar so it is more visible?
##

**Comment by antenore** [comment]
You have an option for that in the preferences.

**Comment by joakim-tjernlund** [comment]
oh, never occured to me.
Can I make this option system default somehow?

**Comment by antenore** [comment]
Not yet, i'm working on it #818

**Comment by joakim-tjernlund** [comment]
Nice, that will make my life easier as we have some 100 Linux computes here :)

**Comment by giox069** [comment]
@joakim-tjernlund I'm very happy to hear that you are running remmina on many linux machines. Colud you describe better your "installation" and what remmina is used for ? We would be happy to add it to the testimonial section on our [web site](http://www.remmina.org). You can send you story in our [G+ community](https://plus.google.com/communities/106276095923371962010), or write me a personal e-mail at giovanni [at} panozzo.it. Thank you very much.

**Comment by antenore** [comment]
@joakim-tjernlund it's done, as soon as we will release a new version, you'll have the possibility to set up your defaults in your ${XDG_CONFIG_DIRS} (i.e. /etc/xdg/remmina ) directory, the same for default remmina profiles, in the ${XDG_DATA_DIRS} (i.e. /usr/share/remmina ).

**Comment by antenore** [comment]
This issue is solved.
