### ISSUE TITLE
MATE Desktop Environment - survey

### ISSUE THREAD

**Issue by dark-penguin** [FreeRDP/Remmina#1007]
I tried to send you a survey report, but... There are dozens of display managers, even those nobody's ever heard of, but MATE is not there! %) Are GNOME people trying to deny the existence of MATE by sheer willpower? :) 
##

**Comment by antenore** [comment]
Yes, true!

In the next days or couple of weeks I'll remove temporary the survey as I want to refactor it.

At the moment we have some important issues and I also don't want to maintain the webkit dependency.

I'll use this issue to work on the survey in a more general way.

**Comment by antenore** [comment]
I've added Mate, but consider that the Window Manager name is Marco, that was already there :-P
