### ISSUE TITLE
Looking for statistics from package maintainers

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#1008]
Hi to all package maintainers.
In the next post on the remmina blog (and G+), I would like to include some statistics about remmina 1.2 usage.
But... we don't have many data, so we are asking your contribution.

Corrently we have only  the following data:
- The remmina-next ubuntu's PPA shows us that there are about 5000 ubuntu PPA users (via ppastats script)
- Our survey, which automatically starts after some usage (one month ?), has been compiled by 1592 users

Can you contribute with your detailed data from your distribution, if and where available ? (I'm thinking COPR, AUR, ...)

If you know other package maintainers which can provide remmina 1.2 usage stats, please let them know or let us know.

Thank you
Giovanni

@dktrkranz  @nastasi  (not really needed: we already have PPA data)
@hubbitus @weberhofer @ic3d @eworm-de
##

**Comment by dktrkranz** [comment]
Debian popcon stats reveal remmina has about 2200 users:
https://qa.debian.org/popcon-graph.php?packages=remmina&show_vote=on&from_date=&to_date=&hlght_date=&date_fmt=%25Y-%25m&beenhere=1

**Comment by Hubbitus** [comment]
Unfortunately I don't known is there present some statistic of this kind.
