### ISSUE TITLE
remmina fails to compile against freerdp

### ISSUE THREAD

**Issue by juanitotc** [FreeRDP/Remmina#1015]
using remmina and freerdp, both from git yesterday:

cmake -DCMAKE_C_FLAGS="-march=i486 -mtune=i686 -Os -pipe" -DCMAKE_CXX_FLAGS="-march=i486 -mtune=i686 -Os -pipe" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib -DCMAKE_BUILD_TYPE=Release -DWITH_AVAHI=OFF -DWITH_LIBSSH=OFF  -DWITH_APPINDICATOR=OFF -DWITH_TELEPATHY=OFF -DWITH_SPICE=OFF ../

make
...
Scanning dependencies of target remmina-plugin-rdp
[ 89%] Building C object remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o
In file included from /usr/src/Remmina-1.2.0-rcgit.15/remmina-plugins/rdp/rdp_plugin.c:36:0:
/usr/src/Remmina-1.2.0-rcgit.15/remmina-plugins/rdp/rdp_plugin.h:276:2: error: unknown type name 'HCLRCONV'
  HCLRCONV clrconv;

**Comment by giox069** [comment]
Same as issue #1012. You should use an older version of freerdp, for example commit https://github.com/FreeRDP/FreeRDP/commit/1d06087b601a4cc723592e9a6efbf9bee0dc2d12 works fine with remmina.
In the meanwhile we are working to adapt remmina to the newer FreeRDP changes, but we need the current FreeRDP HEAD code to stabilize a bit more: there are at least three open regression bugs on FreeRDP issues page after October 6 commit.

**Comment by juanitotc** [comment]
Thanks - that fixed it.
