### ISSUE TITLE
Remote screen has wrong offset when using hide-toolbar

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#103]
Forwarded from http://bugs.debian.org/681695

Enabling Hide-toolbar-in-tabbed-interfaces in Edit -> Preferences causes the remote OS window to be drawn at a wrong offset. The rest of the remmina window becomes filled black.

This problem has also been reported by Ubuntu users at [1] and [2].

A workaround is to resize the window after it as been opened. It causes the remote display to be redrawn and correctly positioned.

[1] https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/967376
[2] https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/970844

**Comment by muflone** [comment]
Does this issue still exists? It should be fixed a lot of time ago.

If this issue persists please reopen. For the moment I'm closing it.
