### ISSUE TITLE
Host key not working with SPICE plugin connected to KVM client. 

### ISSUE THREAD

**Issue by zzx999** [FreeRDP/Remmina#1035]
When connected via SPICE plugin to KVM client (windows), Host key (usually RCtrl , but changing to other does not help) combination seems to be directly sent to client, and not intercepted for processing.
- Client (OS name and version):  xubuntu 16.10 (also tested on gnome(same box) and linuxmint18-mate
- Remmina version (remmina --version): 1.2.0-rcgit-15
- Desktop environment (GNOME, Unity, KDE, ..):  GNOME, XFCE4, MATE
- Connecting to (OS and version): windows7 ENT .  
- Connecting via (RDP, VNC, ...):  KVM, SPICE/QXL

**Comment by calebcassel** [comment]
I'm experiencing this, too.
* Client: Ubuntu Gnome 17.04
* Remmina version 1.2.0-rcgit-18 
* Desktop environment: GNOME
* Connecting to: Windows 10
* Connecting via: KVM, SPICE

**Comment by antenore** [comment]
Fixed in the last PR. It'll be available in "next" in few minutes or in the rcgit-21, hopefully in a couple of weeks.

**Comment by antenore** [comment]
Yes! It took me less than year closing this bug!!!!

Sorry for this guys...
