### ISSUE TITLE
Password not saved

### ISSUE THREAD

**Issue by rdiez** [FreeRDP/Remmina#1047]
I am using Remmina 1.2.0-rcgit-15 via this Ubuntu PPA:

http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/.

I have Kubuntu 14.04.5 LTS. I am connecting to Windows 7 with RDP.

Remmina is not saving the password. There is no error or warning message that the password could not be stored. That alone could be considered a bug.

Does Remmina need the gnome-keyring? If it does, can I make it store passwords without it? I cannot install gnome-keyring because of this weird package dependency problem:

The following packages have unmet dependencies:
 p11-kit-modules : Depends: libp11-kit0 (= 0.20.2-2ubuntu2) but 0.23.2-3 is to be installed

I do not know why p11-kit-modules insist of fixed version 0.20.2-2ubuntu2. Everything else seems OK in my system, there are no visible issues with the Debian package manager.

By the way, "remmina --version" should print its version and stop, and not start Remmina.

**Comment by damodaranudas** [comment]
Same issue here, after installed Remmina trough snap package on Ubuntu 16.04 I can't save RDP passwords
`
dar@GL355VD:~$ remmina

Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "topmenu-gtk-module"

** (remmina:8188): CRITICAL **: secret_service_load_collections_sync: assertion 'paths != NULL' failed

** (remmina:8188): CRITICAL **: secret_service_read_alias_dbus_path_sync: assertion 'SECRET_IS_SERVICE (self)' failed
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed

(remmina:8188): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(remmina:8188): Gtk-WARNING **: Error loading theme icon 'list-add' for stock: Icon 'list-add' not present in theme mate

(remmina:8188): Gtk-WARNING **: Error loading theme icon 'edit-clear' for stock: 

(remmina:8188): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(remmina:8188): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(remmina:8188): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
** Message: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.324" (uid=1000 pid=8188 comm="remmina ") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.5" (uid=1000 pid=1574 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")

(remmina:8188): GLib-GIO-WARNING **: Error creating IO channel for /proc/mounts: Permission denied (g-file-error-quark, 2)
** Message: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.324" (uid=1000 pid=8188 comm="remmina ") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.5" (uid=1000 pid=1574 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")

`

**Comment by Olmer1st** [comment]
Hi,
same issue.
Remmina: 1.2.0-rcgit-18 
Ubuntu 16.04

**Comment by pmulgaonkar** [comment]
Has this been fixed? Same issue.

**Comment by exactt** [comment]
same here:
Remmina: 1.2.0-rcgit-18
Ubuntu 16.04

**Comment by antenore** [comment]
Sorry for the late answer.
I'm investigating.

**Comment by damoebius** [comment]
Hi,
same issue.
Remmina: 1.2.0-rcgit-18
Xubuntu 17.04

**Comment by giox069** [comment]
@damoebius: how did you install remmina? Via PPA, snap package or by compiling it ?

**Comment by exactt** [comment]
snap package

**Comment by snugam** [comment]
Xubuntu 16.10, installed with snap - same problem, not storing password.

**Comment by tomaszkubacki** [comment]
Ubuntu 17.04 same issue - it's snap - version installed from PPA works perfectly well

**Comment by giox069** [comment]
@3v1n0: it seems that snap packages are unable to access gnome keyring...

**Comment by tomaszkubacki** [comment]
@giox069 tracking snap issue here: https://bugs.launchpad.net/snapd/+bug/1653769

**Comment by giox069** [comment]
Thank you @tomaszkubacki. I will add a comment on the remmina Wiki.

**Comment by saidbakr** [comment]
I have the same issue with Ubuntu 16.04  and `1.2.0-rcgit-18 (git 1d744f6)`

**Comment by alex-mashin** [comment]
Same issue.
1.2.0-rcgit-20 (git v1.2.0-rcgi

**Comment by giox069** [comment]
@alex-mashin are you using the snap version of remmina? Under which distribution?
If you are using the snap version, please note that a snap cannot access the gnome keyring. They fixed it with snapd version 2.27, not yet available in many distributions.

**Comment by alex-mashin** [comment]
Yes, the snap version. Seems newer than apt/dpkg.

**Comment by cmcanulty** [comment]
same issue xubuntu 16.04. I run like 30 computers so is a royal pain, just started today

**Comment by alex-mashin** [comment]
Still there under Snap 2.28.1.

**Comment by giox069** [comment]
@antenore: I think our snapcraft.yaml.in is missing the newer "password-manager-service" interface...

**Comment by erichoog** [comment]
I also have this issue under Arch Linux, KDE Plasma, Remmina (1.2.0-rcgit-21)

**Comment by 3v1n0** [comment]
I think this is fixed as per commit f73b2b79.

**Comment by alex-mashin** [comment]
Still doesn't save my passwords.

**Comment by antenore** [comment]
@alex-mashin which Remmina version

**Comment by alex-mashin** [comment]
1.2.0-rcgit-24 (git 202d17f)

**Comment by giox069** [comment]
Pease do not reuse this issue. It contins old and misleading informations, mixing different remmina versions and packaging systems (snap, PPA, compilation by hand).
If you still have problems with passwords savings, reopen a new issue and describe with more details your setup including:

1. The remmina version tou are using (remmina --version from commandline, include the full output)
2. How did you get remmina (by compilation following our wiki, PPA, SNAP, FlatPack, AUR...)
3. Which linux distribution, CPU architecture and desktop you are using.
4. If you are using some kind of nonstandard distribution (i.e.: without some important system component, like dbus and/or a keyring)

We have reports that password saving is currently *working* out of the box on all major distributions by default, including when SNAP package is used. So if your specific setup is not working, we need more precise data to describe it and find possible bugs.

**Comment by giox069** [comment]
For people interesting in current remmina SNAP problems happening with some distributions, please follow issues #1404 and #1288 (@3v1n0 if you can take a look at issue #1404 you are welcome, thank you :))
