### ISSUE TITLE
When "Server" GtkComboBox is selected, TAB key doesn't work

### ISSUE THREAD

**Issue by ppsshh** [FreeRDP/Remmina#1049]
Subj.

Unable to switch to the next input field using keyboard TAB button if "Server" ComboBox is focused/selected (in "New Connection" and "Edit Connection" windows)

Bug introduced in b54ea4af146f3692dfea45e3b2c9794687f5c999 by the line
```c
  gtk_widget_set_can_focus (widget, TRUE);
```

When compiled without that line, everything works as expected.

**Comment by antenore** [comment]
Thanks a lot! If you want to have your real name and email or a pseudo in the AUTHORS and about widget le me know.

**Comment by ppsshh** [comment]
This fix is too minor, so there is no need for credits =)
Thanks for creating and merging that pull request.

**Comment by antenore** [comment]
:-)
