### ISSUE TITLE
Cannot connect to neoma-bs RDP server

### ISSUE THREAD

**Issue by raffamaiden** [FreeRDP/Remmina#1056]
Hi,

My university provides a RDP file to establish a VPN connection. This file doesn't work in Remmina.
The file is imported correctly, but when I click
 "connect" on the imported entry, it is supposed to ask for username and password. Instead it just gives a message box which says "Unable to connect to RDP server farmetufr.neoma-bs.fr"

I attach the information you requested + the RDP file and console output.

I used Remmina compiled from git repository. I use the "next" branch.

* Client (OS name and version): Fedora 25, kernel version 4.8.8-300.fc25.x86_64 
* Remmina version (remmina --version): Version 1.2.0-rcgit-16 (git a97eb33)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME 3 (GNOME Shell 3.22.1)
* Connecting to (OS and version):  ?? (probably Windows?)
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 2.0.0-dev (git n/a)

**CONSOLE LOG:**

> [18:13:47:215] [11304:11309] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[18:13:47:215] [11304:11309] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[18:13:47:215] [11304:11309] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[18:14:02:234] [11304:11309] [ERROR][com.freerdp.core] - failed to connect to farmetufr.neoma-bs.fr
[18:14:02:234] [11304:11309] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[18:14:02:234] [11304:11309] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[18:14:02:234] [11304:11309] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**RDP FILE:**

>screen mode id:i:1
use multimon:i:0
desktopwidth:i:1920
desktopheight:i:1080
session bpp:i:32
winposstr:s:0,1,2663,209,3463,809
compression:i:1
keyboardhook:i:2
audiocapturemode:i:0
videoplaybackmode:i:1
connection type:i:7
networkautodetect:i:1
bandwidthautodetect:i:1
displayconnectionbar:i:1
enableworkspacereconnect:i:0
disable wallpaper:i:0
allow font smoothing:i:0
allow desktop composition:i:0
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:0
disable cursor setting:i:0
bitmapcachepersistenable:i:1
full address:s:farmetufr.neoma-bs.fr
audiomode:i:0
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
redirectclipboard:i:1
redirectposdevices:i:0
autoreconnection enabled:i:1
authentication level:i:2
prompt for credentials:i:0
negotiate security layer:i:1
remoteapplicationmode:i:0
alternate shell:s:
shell working directory:s:
gatewayhostname:s:gwadm.neoma-bs.fr
gatewayusagemethod:i:2
gatewaycredentialssource:i:4
gatewayprofileusagemethod:i:1
promptcredentialonce:i:0
gatewaybrokeringtype:i:0
use redirection server name:i:0
rdgiskdcproxy:i:0
kdcproxyname:s:`

**Comment by giox069** [comment]
I have really no idea. Maybe your server is not supporting the profile Security settings.
Edit the profile, choose the "Advanced" tab, and try a different setting for "Security".

**Comment by raffamaiden** [comment]
Hi,

changing the security settings didn't work. There is no better error log than " Error: protocol security negotiation or connection failure"?

**Comment by raffamaiden** [comment]
As suggested [here](http://askubuntu.com/questions/337441/using-windows-exported-rdp-file-from-ubuntu) I removed the profile generated by importing the RDP file

Instead I created a new profile with the built-in wizard, and I copied the hostname and gateway from the RDP file I opened in gedit

After asking me to accept a few certificates it seems to be working

So I think is more of an issue in importing the RDP file

**Comment by raffamaiden** [comment]
I think I found the problem. The RDP file importer doesn't import the RD gateway server. Than of course, after doing that, should ask for username and password

**Comment by antenore** [comment]
@raffamaiden right, adding it is quite straight forward. ASAP I'll add it. In the mean time if you guys want to try to do it yourself....

**Comment by antenore** [comment]
Well, I was impatient to fix this. So here it is  1f281cb .
I've submitted the PR #1068 and I'll merge it. This week-end, probably, we will release a new version and it should be available in the PPA very soon.

I hope it works correctly as I don't have a gateway to test.
