### ISSUE TITLE
Remmina shuts down immediately upon connecting to RDP client

### ISSUE THREAD

**Issue by linxpatrick** [FreeRDP/Remmina#1057]
OpenSuSE Linux Leap 42.1 with all known updates. Just ran a freerdp update this morning.
Remmina 1.2.0-rcgit-16 (git n/a) but has been a problem since 1.2. v1.0 still works.
Same issue as issue #699 
Attempting to connect to a Windows 2012 R2 server through RDP
xfreerdp v1.0.2

When attempting to open an RDP client, Remmina immediately closes with no error messages. Tried 15, 16, 24 and 32 bit video settings. Tried various resolutions. No change

Had the problem earlier in the month and earlier in the year. Tried completely reinstalling Remmina and tried downgrading to v1.0. I keep going back to a v1.0 version because it works. The last time I updated, Remmina, which was a couple days ago, the first connection attempt worked but after rebooting the host box it stops working. That was the same issue I had earlier in the month.

Remmina v1.2.x works within a VirtualBox v5.1.10 VM running the same version of OpenSuSE and v1.0.2 of FreeRDP. The VirtualBox version doesn't seem to matter. The big difference is that the host uses Nvidia drivers and the VM uses a more basic video driver.

Using repository obs://build.opensuse.org/home:so_it_team to install Remmina.

I posted about this once before but can't find the original post. If you find it, please close the older post as this one contains a more accurate description.

Just before posting this earlier I checked the version of freerdp and discovered it was 1.0.2. I have since installed v2.0 so now the YaST software utility reports back that both v1.0.2 and 2.0.0 are installed. xfreerdp -- version reports "This is FreeRDP version 2.0.0-dev (git n/a)" So far Remmina is working again. Even survived a reboot. So, now the question is if v2.0 is required, why didn't it upgrade or install with the upgrade or installation of Remmina v1.2.x? Just to reiterate, my VM still has v1.0.2 of FreeRDP installed, as well.

**Comment by giox069** [comment]
Remmina 1.2 needs libfreerdp 2.0, that's correct.
About OpenSuSE packaging/dependencies... I don't think this is the right place to ask: here we develop the core remmina, we don't package it. What do you think @weberhofer ?

**Comment by weberhofer** [comment]
CUrrent openSUSE do no longer distribute old freerdp packages, so this problem should no longer exist. Please open a new issue if this problem occures with supported openSUSE versions.
