### ISSUE TITLE
Win key stays pressed in remote desktop when remmina loses focus

### ISSUE THREAD

**Issue by ppsshh** [FreeRDP/Remmina#1058]
This happens if WM (any WM) has a hotkey that uses `Win Key + any other key` to switch between windows/desktops or any other action that causes *losing focus* of remmina.

For example, I'm using `Win Key + 1/2/3/4` to switch between my desktops. So when I'm using this shortcut, Win key stays pushed in remote desktop and when I'm back to remmina and start typing, all kind of windows starts to open =) Like action center, explorer, lock screen, run dialog, etc...

Simple "press-release Win key" solves this problem until next switch between desktops.

I've tried to fix this bug myself, but I haven't enough skills yet. But I've found what part of code causes that bug and which commit first introduced it: 09fe6ed31a5e5539b78ca1619957cb817bf321a3
Before that commit, everything regarding that issue was ok.

* Client (OS name and version): ArchLinux
* Remmina version: 1.2.0-rcgit-16
* Desktop environment/WM: openbox
* Connecting to: Windows (any version)
* Connecting via: RDP and VNC
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0-dev (git 6e15931)

**Comment by giox069** [comment]
Which version of remmina are you using ?

**Comment by giox069** [comment]
Never mind... I was too quick to answer. Thank you for reporting.

**Comment by notpentadactyl** [comment]
I can confirm this issue, extremely annoying.

Example (using Xmonad, this should also apply to other WMs like Awesome) to reproduce unintended screen lock: 

- Let's say you are on Desktop 4 and in an open RDP session
- Now you want to check something out on Desktop 1, you press Win+1
- Next you want to get back to Desktop 4, you press Alt+Tab or Win+4
- When you now start type anything with the letter "l" (L) your screen will get locked.

Workaround: press the Win key once (or twice if Win8{,.1}).

**Comment by hubutui** [comment]
I can confirm this issue, too. remmina version 1:1.2.0rcgit.21.

**Comment by giox069** [comment]
Just a copuple of questions:

- The "Grab all keyboard events" icon on the toolbar, is enabled or not?
- Confirm me that you are running under Xorg and not Wayland

thank you

**Comment by ppsshh** [comment]
@giox069 
* Grab all keyboard events" is enabled
* I'm using Xorg

I have an unconfirmed report that under Gnome3 there is no such bug, but I didn't have the opportunity to verify this information by myself. So far I can confirm that this bug still appears when Remmina is being used on Openbox or Awesome (and, by information from @notpentadactyl in Xmonad). It would be nice if @hubutui will also provide information about his DE/WM.

Thanks for paying attention to this bug.

**Comment by giox069** [comment]
It's very hard to understand what is happening and reproduce the problem correctly for me. Events are sent by different window managers in different ways.
I have published a small possible fix, in the branch issue_1058_unfocus.
Could anyone try to compile remmina and test on openbox from the ssue_1058_unfocus branch?

**Comment by ppsshh** [comment]
@giox069 thanks for your response.

I've checked out db33495, and yes, remmina now acts better.
When I'm switching to another window/virtual desktop, the remote server also receives 'win release' keycode (after 'win press') resulting in 'Start' menu being opened. And this is much better than when 'win' key stays 'pessed' :)

I think this issue now may be closed. Thank you :)

**Comment by giox069** [comment]
Yes, I guess leaving the menu "start" open is not really comfortable, but is definitely more correct than leaving the Win key pressed at the remote server. Unfortunately I can't see a way to do better.
Almost every change I do in the focus-in focus-out code to fix something under a specific WM has unwanted side effects with other WMs :( I hope this commit will not break something else.
I'm merging the commit into "next" and this issue should close automatically.
Thank you very much for reporting and testing :+1:
