### ISSUE TITLE
Full screen problem when changing screen arrangement

### ISSUE THREAD

**Issue by romu70** [FreeRDP/Remmina#1059]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Fedora 25 64 bit
* Remmina version (remmina --version): 1.2.0-rcgit-15
* Desktop environment (GNOME, Unity, KDE, ..): Gnome
* Connecting to (OS and version): WS2016
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): na

My setup:
* Dell Laptop
* External screen

Before:
* External on the laptop left
* Main screen: external

Now:
* External on the laptop right
* Main screen: external

Problem: when I click to full screen to the my VM on the whole screen area, it automatically switches to the laptop screen (so on the left, left was the position of the main screen in my previous setup) and I've now way to bring the screen back on the main screen...except to not be in full screen.

**Comment by antenore** [comment]
#873 should have fixed this

**Comment by antenore** [comment]
My bad. Please check if this is duplicated of #124

**Comment by romu70** [comment]
Yes definitely duplicates #124.

**Comment by antenore** [comment]
Thank you
