### ISSUE TITLE
Russian translation fixes

### ISSUE THREAD

**Issue by IgorFilth** [FreeRDP/Remmina#1071]
Hi guys !
Tnx for updating Russian translation: #1070.
Please correct these strings:

"Отключить пароль хранения" -> "Отключить запоминание пароля"  (string 83)
"Подключение к серверу RDP% S не удалось."  ->  "Подключение к серверу RDP %s не удалось."   (string 326) 
"Загрузить Информацию Баланс" -> "Информация для балансировки нагрузки" (string 430)
"Пдключить" -> "Подключить" (string 1170)
"Remmina веб сайт" –> "Веб-сайт Remmina" (string 1835)

Best regards, 
Igor

**Comment by antenore** [comment]
Thanks Igor,  sorry I'm still learning Russian. I'll do it ASAP

**Comment by IgorFilth** [comment]
Your learning Russian is much better, than my learning English))

A little more fixes:
"_Прекратить" -> "_Выйти" (string 1314)
"Вклады" -> "Пожертвования на развитие проекта" (string 1939)  
(phrase "на развитие проекта" is optional, may be used simply "Пожертвования")

**Comment by antenore** [comment]
I\'ve updated the translations in a separated branch, I'm going to submit a pull request\n. Can you please take a look and comment over there?\n\n Thanks a lot!
