### ISSUE TITLE
Remmina windows unmovable/unresizable

### ISSUE THREAD

**Issue by HuboAdmins** [FreeRDP/Remmina#1073]
Since the upgrade to Remmina rcgit.17 I've had a lot of issues with remmina window management.
Windows of open connections often become "stuck", in which state I can maximize/minimize the windows but not move (drag) or resize.
When one of my rdp connection windows has this issue, the affected window will sometimes start flashing and all the other remmina windows get a thick black border around them.

At first I believed this was due to my old saved connections, but I've recreated multiple now that seemed to work at first but have the issue return some time after. Anything "obvious" I might be missing here?

My previous version was rcgit15, I'm running Ubuntu 14.04.5 LTS.
Current remmina version: 14.04.5 LTS
Desktop: Gnome
Connecting to: multiple OS's (windows Server 2008 (R2) / Server 2012 (R2,...)
Connecting via RDP
xfreerdp not installed.

Kind regards

**Comment by HuboAdmins** [comment]
I ended up purging the remmina install and all related RDP packages / files / saved connections.
It appears the issue is no longer present, I'm assuming something must've gone awry during the upgrade process. 

Kind regards

**Comment by giox069** [comment]
@HuboAdmins let us know if it will happen again. I noticed some strange behaviors with compiz window manager in ubuntu 16.04 and 16.10, but I can't say where the problem is.
