### ISSUE TITLE
problem with tui interfaces in remmina

### ISSUE THREAD

**Issue by worldskat** [FreeRDP/Remmina#1076]
Hi.

Client (OS name and version):
ubuntu 14.04 & ubuntu 16.04
Remmina version (remmina --version):
remmina - Version 1.2.0-rcgit-15 (git n/a)
Desktop environment (GNOME, Unity, KDE, ..):
awesome
Connecting to (OS and version):
ubuntu 14.04 & 16.04
Connecting via (RDP, VNC, ...):
ssh

in my work i use some software with tui, like  ranger and sngrep. 
When i connect to servers via Remmina and use this soft, picture crumbles.

**Comment by antenore** [comment]
Can you share a screenshot?

**Comment by worldskat** [comment]
First picture is work with ranger via gnome terminal. 
Other is via Remmina. 
Picture change while i make some moves by cursor. This picture i maked just push "down" , "left"  and "right"


![good](https://user-images.githubusercontent.com/24825418/26962979-93807724-4cf2-11e7-8521-3ba3094d283f.png)
![bad1](https://user-images.githubusercontent.com/24825418/26962978-937f8206-4cf2-11e7-9d02-b8ab3946f857.png)
![bad2](https://user-images.githubusercontent.com/24825418/26962976-937f2c52-4cf2-11e7-8650-50276d95c7a1.png)
![bad3](https://user-images.githubusercontent.com/24825418/26962975-937d86f4-4cf2-11e7-956d-cacab9bca554.png)
![bad4](https://user-images.githubusercontent.com/24825418/26962977-937efb88-4cf2-11e7-8367-c1c4be9775b8.png)

**Comment by antenore** [comment]
I've the same problem, I'll take a look

**Comment by antenore** [comment]
https://stackoverflow.com/questions/13707137/ncurses-resizing-glitch#13707598 I found this that can be related.
I'll take a look at our resize callbacks.

**Comment by antenore** [comment]
Found and fixed
