### ISSUE TITLE
New connection type: VNC Reverse Connection

### ISSUE THREAD

**Issue by ronnystandtke** [FreeRDP/Remmina#108]
Until now we use some VNC command line tools for user support.
The supporters start ```xtightvncviewer -listen``` and the customers start ```x11vnc -connect <IP address of supporter>```. This works great but we would love to switch to Remmina.

I noticed that the supporters can use "VNC Incoming Connection" in Remmina. This already works really great.

What is still missing is the customer part, where the reverse connection is started. It would be great if Remmina would offer a new connection type "VNC Reverse Connection" that would take care of the ```x11vnc -connect <IP address of supporter>```-part.

**Comment by muflone** [comment]
This issue is invalid, Remmina doesn't provide any VNC server therefore cannot start any server connecting feature.
