### ISSUE TITLE
Remote Windows program crashes when accessed by Remmina RDP

### ISSUE THREAD

**Issue by oblongau** [FreeRDP/Remmina#1083]
* Client (OS name and version): Linux Mint 17.3 (also 18.1)
* Remmina version (remmina --version): 1.2.0-rcgit-17 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): MATE
* Connecting to (OS and version): Windows Small Business Server 2011 Standard
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): "xfreerdp: error while loading shared libraries: libfreerdp-core.so.1.0: cannot open shared object file: No such file or directory"

I can successfully connect to the Windows Server. I can run the remote Windows program. However, after doing a couple of operations within the program it crashes. 
----------
Golf Manager has stopped working
Problem Event Name: BEX
...
Fault Module Name: libeay32.dll
-----------
The problem does not arise when using Microsoft Remote Desktop Connection in Windows XP as virtual machine, or in standalone Windows 7 machine.

How does the remote Windows program "know" how it is being accessed, so that it crashes depending on the access method?

Is the problem with Remmina, RDP plugin, or something at the remote Windows Server?

Thanks.

**Comment by oblongau** [comment]
Minutes after submitting the issue, there was an update to FreeRDP in my Update Manager:

xfreerdp --version
[12:59:00:186] [8687:8687] [INFO][com.freerdp.utils] - Registering signal hook...
This is FreeRDP version 2.0.0~dev (git n/a)
However, that did not solve the problem.

**Comment by giox069** [comment]
@oblongau: some specific windows features are directly sent via RDP protocol to a specific libfreerdp plugin: sound, printer... so a buggy M$ library can crash in response to a unexpected behavior of a libfreerdp plugin. It could happen.
I think you have some old freerdp package installed too, can you paste the output of
```dpkg --list | fgrep freerdp``` ?

**Comment by oblongau** [comment]
```
$ dpkg --list | fgrep freerdp
ii  freerdp-x11                                                 2.0.0~dev201612151502+dfsg-1ubuntu0~git2b91654~trusty amd64        RDP client for Windows Terminal Services
ii  libfreerdp-plugins-standard:amd64                           2.0.0~dev201612151502+dfsg-1ubuntu0~git2b91654~trusty amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp1:amd64                                           2.0.0~dev201612151502+dfsg-1ubuntu0~git2b91654~trusty amd64        RDP client for Windows Terminal Services (library)
ii  libpam-freerdp                                              1.0.1+13.10.20130724-0ubuntu1                         amd64        PAM Module to auth against an RDP server using FreeRDP
```

**Comment by giox069** [comment]
Nothing harmful. You could try to remove libpam-freerdp
```sudo apt purge libpam-freerdp```

**Comment by giox069** [comment]
Another source for debugging: start remmina inside a linux terminal and connect. Look at the text in the terminal. When a program crashes, return to the terminal and try to see if some extra debug informations have been added there. Copy&paste here.

**Comment by oblongau** [comment]
libpam-freerdp removed. Running remmina from terminal shows absolutely nothing extra in the terminal, either when the remote program crashes or when remmina exits normally. The remote server does not give permission to check the Windows logs there.

Currently the user involved is using as a work-around Microsoft Remote Desktop in Windows XP in Virtualbox!

**Comment by giox069** [comment]
I have really no other ideas. Try to reduce color depth, or disable RemoteFX if enabled, disable sound, printer sharing, smartcard sharing.

**Comment by oblongau** [comment]
Colour depth is already 256 (the lowest) and other settings were off. But that gave me an idea. So I changed colour to High Color (16 bpp) and the remote program did not crash! It's been tested now from a couple of client PCs with success. Many thanks for your help.

**Comment by antenore** [comment]
@giox069 this (crash with 8bit graphics) sometimes happens also with VNC... Strange coincidence?

**Comment by giox069** [comment]
I have no idea. I have never seen windows application crashing when used with remmina :(

**Comment by giox069** [comment]
@oblongau I'm closing this issue. If you will find more problems, reopen it or open a new one.
