### ISSUE TITLE
No move or resize terminal window

### ISSUE THREAD

**Issue by ComputingFroggy** [FreeRDP/Remmina#1087]
Hi,
I can not move or resize the widows of opened terminals using RDP or VNC.
I can use the windows minimize, maximize buttons but there's no access to the system menu.

Basically, once the terminal window is opened I can not move it or resize it, I can just unmaximize or minimize the window.

I think this was not the case with previous versions.

Please give us some details about the systems you are using:
* Client (OS name and version): Xubuntu 16.04
 Remmina version (remmina --version): 1.2.0-rcgit-17
* Desktop environment (GNOME, Unity, KDE, ..): XFCE
* Connecting to (OS and version): all
* Connecting via (RDP, VNC, ...): all
* RDP issues only, freerdp version (xfreerdp --version): not installed

**Comment by ComputingFroggy** [comment]
I have the same problem using elementaryOS Loki (on another computer) ... which is not surprising as Loki is based on Ubuntu 16.04 !

**Comment by ShaunMaher** [comment]
I'm having this same issue with Ubuntu 14.04 with Unity and Ubuntu Budgie 16.10.

**Comment by ComputingFroggy** [comment]
Glad to see I am not the only one (I was beginning to think, that was a problem with my set up) ... even though we don't make much progress ! ! :-(

**Comment by ComputingFroggy** [comment]
Thanks to **Johnzooi**, there's a workaround that he mentioned in another bug report ( #1096).
Just disable the capture of keyboard events (keyboard button in the tool bar), and you will be able to move your window.

**Comment by ShaunMaher** [comment]
Just to add to the mystery, I just noticed that I can move/resize the window when I have one tab selected but not when I move to another tab.

**Comment by giox069** [comment]
Remmina 1.2.0-rcgit-18 is now on the remmina-next PPA. It should fixes this issue. Can anyone test?

**Comment by HuboAdmins** [comment]
I can confirm this issue no longer appears present in Remmina 1.2.0-rcgit-18.
Thanks!

**Comment by giox069** [comment]
Thank you, I'm closing this issue.

**Comment by ComputingFroggy** [comment]
I can also confirm this issue is fixed with Remmina 1.2.0-rcgit-18.

Thanks a lot, for your work.
