### ISSUE TITLE
Remmina-1.2.0-rcgit.17 build error

### ISSUE THREAD

**Issue by MegaMcVolt** [FreeRDP/Remmina#1090]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): 
Slackware 14.2
Linux 4.4.38 (x86_64)
* Remmina version (remmina --version): 
Remmina-1.2.0-rcgit.17
* Desktop environment (GNOME, Unity, KDE, ..): 
XFCE 4
* Connecting to (OS and version): -----
* Connecting via (RDP, VNC, ...): -----
* RDP issues only, freerdp version (xfreerdp --version): 
freerdp-git20160509

The part where the errors occurred when compiling the program:
---------------------------------------------------------------------------
Scanning dependencies of target remmina-plugin-rdp
make[2]: выход из каталога «/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/build»
make -f remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build.make remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build
make[2]: вход в каталог «/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/build»
[ 72%] Building C object remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o
cd /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/build/remmina-plugins/rdp && /usr/bin/cc  -DFREERDP_REQUIRED_MAJOR=2 -DFREERDP_REQUIRED_MINOR=0 -DFREERDP_REQUIRED_REVISION=0 -DHAVE_LIBAVAHI_CLIENT -DHAVE_LIBAVAHI_UI -DHAVE_LIBGCRYPT -DHAVE_LIBSSH -DWITH_MANPAGES -Dremmina_plugin_rdp_EXPORTS -I/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/. -I/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina/include -I/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freerdp2 -I/usr/include/winpr2  -O2 -fPIC -lz -lssl -lcrypto -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -O3 -DNDEBUG -fPIC   -o CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o   -c /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c
In file included from /usr/include/freerdp2/freerdp/codecs.h:25:0,
                 from /usr/include/freerdp2/freerdp/freerdp.h:46,
                 from /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.h:40,
                 from /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:36:
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c: В функции «rf_get_local_color_format»:
/usr/include/freerdp2/freerdp/codec/color.h:97:72: ошибка: «FREERDP_PIXEL_FORMAT_TYPE_RGBA» undeclared (first use in this function)
 IXEL_FORMAT_R8G8B8A8_F(_flip) FREERDP_PIXEL_FORMAT(_flip, 32, FREERDP_PIX
                                                               ^
/usr/include/freerdp2/freerdp/codec/color.h:37:35: замечание: in definition of macro «FREERDP_PIXEL_FORMAT»
  ((_flip << 30) | (_bpp << 24) | (_type << 16) | (_a << 12) | (_r << 8) |
                                   ^
/usr/include/freerdp2/freerdp/codec/color.h:98:32: замечание: in expansion of macro «PIXEL_FORMAT_R8G8B8A8_F»
 #define PIXEL_FORMAT_R8G8B8A8  PIXEL_FORMAT_R8G8B8A8_F(0)
                                ^
/usr/include/freerdp2/freerdp/codec/color.h:99:30: замечание: in expansion of macro «PIXEL_FORMAT_R8G8B8A8»
 #define PIXEL_FORMAT_RGBA32  PIXEL_FORMAT_R8G8B8A8
                              ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:462:27: замечание: in expansion of macro «PIXEL_FORMAT_RGBA32»
   DstFormat = (!invert) ? PIXEL_FORMAT_RGBA32 : PIXEL_FORMAT_BGRA32;
                           ^
/usr/include/freerdp2/freerdp/codec/color.h:97:72: замечание: each undeclared identifier is reported only once for each function it appears in
 IXEL_FORMAT_R8G8B8A8_F(_flip) FREERDP_PIXEL_FORMAT(_flip, 32, FREERDP_PIX
                                                               ^
/usr/include/freerdp2/freerdp/codec/color.h:37:35: замечание: in definition of macro «FREERDP_PIXEL_FORMAT»
  ((_flip << 30) | (_bpp << 24) | (_type << 16) | (_a << 12) | (_r << 8) |
                                   ^
/usr/include/freerdp2/freerdp/codec/color.h:98:32: замечание: in expansion of macro «PIXEL_FORMAT_R8G8B8A8_F»
 #define PIXEL_FORMAT_R8G8B8A8  PIXEL_FORMAT_R8G8B8A8_F(0)
                                ^
/usr/include/freerdp2/freerdp/codec/color.h:99:30: замечание: in expansion of macro «PIXEL_FORMAT_R8G8B8A8»
 #define PIXEL_FORMAT_RGBA32  PIXEL_FORMAT_R8G8B8A8
                              ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:462:27: замечание: in expansion of macro «PIXEL_FORMAT_RGBA32»
   DstFormat = (!invert) ? PIXEL_FORMAT_RGBA32 : PIXEL_FORMAT_BGRA32;
                           ^
/usr/include/freerdp2/freerdp/codec/color.h:85:72: ошибка: «FREERDP_PIXEL_FORMAT_TYPE_BGRA» undeclared (first use in this function)
 IXEL_FORMAT_B8G8R8A8_F(_flip) FREERDP_PIXEL_FORMAT(_flip, 32, FREERDP_PIX
                                                               ^
/usr/include/freerdp2/freerdp/codec/color.h:37:35: замечание: in definition of macro «FREERDP_PIXEL_FORMAT»
  ((_flip << 30) | (_bpp << 24) | (_type << 16) | (_a << 12) | (_r << 8) |
                                   ^
/usr/include/freerdp2/freerdp/codec/color.h:86:32: замечание: in expansion of macro «PIXEL_FORMAT_B8G8R8A8_F»
 #define PIXEL_FORMAT_B8G8R8A8  PIXEL_FORMAT_B8G8R8A8_F(0)
                                ^
/usr/include/freerdp2/freerdp/codec/color.h:87:30: замечание: in expansion of macro «PIXEL_FORMAT_B8G8R8A8»
 #define PIXEL_FORMAT_BGRA32  PIXEL_FORMAT_B8G8R8A8
                              ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:462:49: замечание: in expansion of macro «PIXEL_FORMAT_BGRA32»
   DstFormat = (!invert) ? PIXEL_FORMAT_RGBA32 : PIXEL_FORMAT_BGRA32;
                                                 ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c: В функции «remmina_rdp_post_connect»:
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:521:2: ошибка: слишком мало аргументов в вызове функции «gdi_init»
  gdi_init(instance, rf_get_local_color_format(rfi, TRUE));
  ^
In file included from /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.h:44:0,
                 from /tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:36:
/usr/include/freerdp2/freerdp/gdi/gdi.h:327:18: замечание: declared here
 FREERDP_API BOOL gdi_init(freerdp* instance, UINT32 flags, BYTE* buffer);
                  ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c: В функции «remmina_rdp_get_screenshot»:
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:1303:19: предупреждение: неявная декларация функции «GetBytesPerPixel» [-Wimplicit-function-declaration]
   bytesPerPixel = GetBytesPerPixel(gdi->hdc->format);
                   ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:1303:44: ошибка: «GDI_DC {aka struct _GDI_DC}» не содержит элемента с именем «format»
   bytesPerPixel = GetBytesPerPixel(gdi->hdc->format);
                                            ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:1304:18: предупреждение: неявная декларация функции «GetBitsPerPixel» [-Wimplicit-function-declaration]
   bitsPerPixel = GetBitsPerPixel(gdi->hdc->format);
                  ^
/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/remmina-plugins/rdp/rdp_plugin.c:1304:42: ошибка: «GDI_DC {aka struct _GDI_DC}» не содержит элемента с именем «format»
   bitsPerPixel = GetBitsPerPixel(gdi->hdc->format);
                                          ^
make[2]: *** [remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build.make:63: remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o] Ошибка 1
make[2]: выход из каталога «/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/build»
make[1]: *** [CMakeFiles/Makefile2:457: remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/all] Ошибка 2
make[1]: выход из каталога «/tmp/build/network/remmina/Remmina-1.2.0-rcgit.17/build»
make: *** [Makefile:128: all] Ошибка 2

**Comment by giox069** [comment]
freerdp-git20160509 is too old. On October 2016 the freerdp team did a huge change on the libfreerdp API, and remmina 1.2.0-rcgit.17 uses the new API. Use an updated freerdp. The latest version (Jan 13 2017), commit https://github.com/FreeRDP/FreeRDP/commit/71ce3378da9044d21575d0331dc4fb97bc4c995c is good.

**Comment by MegaMcVolt** [comment]
Thank you so much!
I have everything compiled!
Thank you for your quick response to my problem. Long life to you, and good health!
Sorry for my English...
