### ISSUE TITLE
Keyboard Events

### ISSUE THREAD

**Issue by lestevam** [FreeRDP/Remmina#1096]
I think this my problem is similar to # 1058.
When the "remmina" loses focus, it loses the effect of "Capturing keyboard events", so when I return focus to the "remmina" I have to click "Capture keyboard events" again.

Client (OS name and version): Ubuntu Gnome
Remmina version: 1.2.0-rcgit-17
Desktop environment (GNOME, Unity, KDE, ..): Gnome
Connecting to: Windows Server 2008 R2 Enterprise e Windows Server 2012
Connecting via: RDP

**Comment by Johnzooi** [comment]
I have the same problem

also perhaps related, i cannot move the window on initial start, only after I disable forward capture keyboard events. I am able to move or resize the window. 

working on cinnamon Kubuntu 16.04

**Comment by ComputingFroggy** [comment]
**@Johnzooi**: you are my hero ! !
I've logged the bug of not moving the window (#1087) ... but at least now, I've got a workaround !
Thanks again Johnzooi

**Comment by giox069** [comment]
I have a similar problem in Ubuntu+Unity, but I was never able to reproduce it seriously. No problems under arch+xfce.
There is something bad with recent keyboard capture modifications in remmina, I will try to investigate further. Thank you for all your reports.

**Comment by giox069** [comment]
Remmina 1.2.0-rcgit-18 is now on the remmina-next PPA. It should fixes this issue. Can anyone test?

**Comment by lestevam** [comment]
Excellent, at first everything perfect! Thank you!!

**Comment by giox069** [comment]
Thank you, I'm closing this issue.
