### ISSUE TITLE
Remove systemd dependency

### ISSUE THREAD

**Issue by JonnyTech** [FreeRDP/Remmina#1100]
I have been using Remmina for a while on [Devuan](http://devuan.org/) (essentially Debian but without systemd) but after updating this month, it is no longer compatible. It looks like a systemd dependency was added recently. Is this really necessary and can it be removed for us non-systemd users?

```
$ sudo apt-get install remmina
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina : Depends: default-dbus-session-bus or
                    dbus-session-bus
E: Unable to correct problems, you have held broken packages.

$ sudo apt-get install dbus-session-bus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'dbus-user-session' instead of 'dbus-session-bus'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dbus-user-session : Depends: dbus (>= 1.10.14-1) but 1.10.8-1+devuan1 is to be installed
                     Depends: libpam-systemd but it is not going to be installed
                     Depends: systemd but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by giox069** [comment]
If you are using the debian/devuan provided remmina pacakge (remmina 1.1.X), you should ask to devuan/debian package maintainers.
Can you also the output of ```apt-cache policy remmina``` ?

**Comment by JonnyTech** [comment]
Thanks, I shall contact them. Requested details:

```
$ apt-cache policy remmina
remmina:
  Installed: (none)
  Candidate: 1.1.2-4
  Version table:
     1.1.2-4 500
        500 http://auto.mirror.devuan.org/merged ceres/main amd64 Packages
        500 http://packages.devuan.org/merged ceres/main amd64 Packages
     1.1.2-3 -1
        100 /var/lib/dpkg/status
```

**Comment by danboid** [comment]
Why does remmina depend on systemd now?

**Comment by giox069** [comment]
@danboid: Remmina code does not depend on systemd, but some packager may have added that dependency. Where did you find this dependency ?

**Comment by danboid** [comment]
That's a question for JonnyTech. I've just checked

https://packages.debian.org/sid/terminator

and I don't see any systemd dep for remmina within regular Debian.

**Comment by JonnyTech** [comment]
@danboid the issue is with Devuan, not Debian, and the dependency seems to be dbus-user-session which in turn depends on systemd, which can be seen by the logs in my original post.

**Comment by giox069** [comment]
I'm closing this issue, since this is related to Debian/Devuan packaging, and should be handled by Debian or Devuan maintainers. Also please note that remmina 1.1 has been removed from Debian Stretch 9, and we are trying to find a way to bring you remmina 1.2 for Stretch.
In the meanwhile, you can try to use the snap version of remmina, but some things are not working very well (acess to .ssh directory and keys, icons...).
