### ISSUE TITLE
Start remmina with fixed language

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#1119]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Kubuntu 16.04.1
* Remmina version (remmina --version): remmina - Version 1.2.0-rcgit-17 (git rcgit-17)
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): -
* Connecting via (RDP, VNC, ...): -
* RDP issues only, freerdp version (xfreerdp --version): -

Hello,

maybe a little noobish question, but can I start remmina with a defined language? For example my desktop environment is configured for german, but I want to use remmina with english texts and buttons. I've already searched github and googled, checked the manpage and remmina.pref in ~/.remmina, but did not find any satisfying answer, so I decided to try my luck here :)

Something like "remmina --language=EN" or similar, when run from commandline.

Thanks and best regards!

**Comment by giox069** [comment]
This is what I usually use to have untranslated strings when I'm testing remmina:
```
LANGUAGE=C remmina
```

**Comment by giox069** [comment]
It seems to work with other languages:
```
LANGUAGE=uz@cyrillic remmina
```
```
LANGUAGE=fr remmina
```
The complete list of available languages, each on its own .po file, is here:
[https://github.com/FreeRDP/Remmina/tree/next/remmina/po](https://github.com/FreeRDP/Remmina/tree/next/remmina/po)

**Comment by CS-JS** [comment]
Thanks! Works like a charm!
