### ISSUE TITLE
option to remove fullscreen toolbar completely

### ISSUE THREAD

**Issue by pcs3rd** [FreeRDP/Remmina#1128]
hiding the toolbar still wastes space when trying to access my upper lxpanel on the host, in my setup, my rpi auitomatically logs in and starts reminna to connect to the host. I don't need it, please add a way to delete a file , edit a config through nano, or add a checkbox that requires agreeing to a warning when it gets checked.

**Comment by antenore** [comment]
You can already move (drag and drop) and hide the toolbar. Which version of remmina are you using?

**Comment by antenore** [comment]
closed by #1135
