### ISSUE TITLE
I always got an error message "SSH public key has changed!"

### ISSUE THREAD

**Issue by lionelvon** [FreeRDP/Remmina#1129]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): UBUNTU 16.10
* Remmina version (remmina --version): 1.2.0-rcgit-18 (git 58f664e)
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): CentOS 7.3
* Connecting via (RDP, VNC, ...): SSH
USER/PASSWORD
After I click the OK button of the Dialog showed "The server is unknow. The public fingerpring is : ... , Do you trust the new public key?" I always got an error message "SSH public key has changed!"

**Comment by lionelvon** [comment]
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

** (remmina:12150): CRITICAL **: secret_service_load_collections_sync: assertion 'paths != NULL' failed

** (remmina:12150): CRITICAL **: secret_service_read_alias_dbus_path_sync: assertion 'SECRET_IS_SERVICE (self)' failed
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:12150): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

**Comment by adamsson6** [comment]
I have the same problem... the debug console says : [SSH] ssh_write_knownhost: Couldn't open known_hosts file /home/user/.ssh/known_hosts for appending: Permission denied

I don't understand... even if I chmod it 777 it says permission denied. Please we need a linux genius to help us.

**Comment by antenore** [comment]
First of all set the right permission to the file, that are, normally 600 (~/.ssh 700 and $HOME to 750 or better 700).

Than try to edit manually the known_hosts and remove the "offending" entry if you have one (the lines containing the host/ips you are connecting to).

If it doesn't work give me the version of libssh and vte

**Comment by adamsson6** [comment]
It still doesn't work with me with these permissions...

But I found a solution !!!
I removed the remmina version instlled from original repository of ubuntu, and added the one of the developers.
	sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
	sudo apt-get update
	sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard

Now ssh is working great.

**Comment by antenore** [comment]
Ah, @adamsson6 yes, of course, we don't support anyway the 0.something version that come by default with most distros, it's based on a code base that almost doesn't exist anymore in the current development/stable branch. :-)

@lionelvon What about you?

**Comment by adamsson6** [comment]
@antenore Thank you for your support !
This app is very useful to manage a lot of rdp / ssh machines. Great job thank you very much.

I hope it will work for @lionelvon

**Comment by Saviq** [comment]
This seems to be a problem with the snap version of Remmina, it lacks access to ~/.ssh for security reasons:

`[164554.472030] audit: type=1400 audit(1490222922.963:401): apparmor="DENIED" operation="open" profile="snap.remmina.remmina" name="/home/user/.ssh/known_hosts" pid=5689 comm="remmina" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000`

Not sure how to tell ssh to look at a different known_hosts (and probably different .ssh altogether).

**Comment by antenore** [comment]
@3v1n0 what do you think, is there anything we can change in the snap package or it's more client side configuration (selinux?) ?

**Comment by 3v1n0** [comment]
@antenore mh, I'm about to try to use `snapcraft-preload` to launch it and in that case it will try to access to `~/snap/remmina/$VERSION/.ssh` instead without causing troubles...
But I need to check that.

Please leave me the steps to reproduce this and I'll give this a try.

**Comment by Saviq** [comment]
@3v1n0 just try any SSH connection after installing the snap...

**Comment by antenore** [comment]
It looks like the Snap package is not correctly linked to libsecret/keyring @3v1n0 can you please support us when you will have time?

In the meanwhile install the PPA package.
