### ISSUE TITLE
Opacity for pop up tool bar is too see-through

### ISSUE THREAD

**Issue by timrichardson** [FreeRDP/Remmina#1131]
![remmina_screenshot_2017-03-06_14-18-37](https://cloud.githubusercontent.com/assets/927458/23595707/13fa22c6-0278-11e7-9664-9200966fb498.png)

In full screen mode, it is very hard to see the contents of the pop-up toolbar because it is nearly 100% transparent.I can't find a setting to control this. Screen shot is attached. This is on Ubuntu 16.04.2 with the XFCE desktop (ie xubuntu). 
 Remmina 1.2.0-rcgit-18 (git rcgit-18)

This is an RDP connection. 

We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): 
* Remmina version (remmina --version): 
* Desktop environment (GNOME, Unity, KDE, ..): 
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): 
* RDP issues only, freerdp version (xfreerdp --version):

**Comment by giox069** [comment]
Try to move the mouse pointer inside the floating toolbar and then use the mouse wheel. The mouse wheel should change the floating toolbar opacity.

**Comment by timrichardson** [comment]
OMG. Great feature. Discoverabilty ... err :)
