### ISSUE TITLE
Missing icons in remote session toolbar

### ISSUE THREAD

**Issue by saberraz** [FreeRDP/Remmina#1136]
* Client (OS name and version):  16.04
* Remmina version (remmina --version): Nightly PPA (1.2.0-rcgit-18 (git rcgit-18))
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): Windows 7
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): Some of the icons in the toolbar are missing. See the attached image:

![image](https://cloud.githubusercontent.com/assets/2649047/23664068/6daff19a-034c-11e7-9267-4081eee52757.png)

**Comment by Freddrickk** [comment]
I have the exact same issue on a slightly different environment.

* OS : Debian stretch
* Remmina version : 1.2.0-rcgit-18 (git 4d8d257)
* Desktop environment : Cinnamon

The same problem occurs if I'm connecting via RDP, VNC, etc.

**Comment by douglasmenger** [comment]
It's the same situation with me.

OS: Debian 9 stretch
Remmina Version: 1.2.0-rcgit-18 (git 1d744f6)
Desktop: Gnome Shell 3.22.2

I made the installation through the snap

**Comment by benshep** [comment]
Me too.

- OS: Lubuntu 17.04
- Remmina version: 1.2.0-rcgit-18 (git 1d744f6)
- Desktop: lxde
- Connecting to (OS and version): Windows 7
- Connecting via (RDP, VNC, ...): RDP

I installed it through snap.

**Comment by saberraz** [comment]
The issue seems to have been resolved now for me in the latest nightly.
