### ISSUE TITLE
FTBFS with both libfreerdp 1.2 and 2.0 installed

### ISSUE THREAD

**Issue by yselkowitz** [FreeRDP/Remmina#1137]
Very recently, FreeRDP versioned their library names, so that you link with -lfreerdp2 -lwinpr2 instead of -lfreerdp -lwinpr.  This allows both 1.2 and 2.0 libraries to be installed in parallel, and distros are starting to do so to allow both remmina (which uses 2.0) and other programs which still use 1.2 (e.g. GNOME's vinagre) to build and install.

Commit 7008e5c0bef9a708d05e5feb327757fff0f9c956 allowed for both names, but gave priority to the unversioned libraries, presumably because the versioned libraries were very recent.  Now, however, with both -devel packages installed, the unversioned 1.2 libraries would be found first.  Fortunately this fails to link due to new symbols being used, but if it hadn't, the result probably would have been a crash.

I don't know if it's too soon to only link against freerdp2 and winpr2, but at a minimum, they should be searched for first.

**Comment by giox069** [comment]
I did not notice the change from libfreerdp to libfreerdp2. You are right, we should start to link to libfreerdp2 and fallback to libfreerdp if not found. @antenore  ?

**Comment by yselkowitz** [comment]
FYI, here is the patch I used for 1.2.0-rcgit.18:

[https://github.com/cygwinports/remmina/blob/master/1.2.0-freerdp2.patch]

**Comment by antenore** [comment]
Yes, I agree, let's ask first to @3v1n0 as he is the author of this change.
What do you think?
@yselkowitz Thanks for the patch!

**Comment by 3v1n0** [comment]
That gives precedence to the freerdp2, which I think it's fine.... So +1 from me.

**Comment by antenore** [comment]
https://travis-ci.org/FreeRDP/Remmina/builds/209574243    looks good

**Comment by ic3d** [comment]
Hi @yselkowitz I've seen this issue is still open? Can you confirm that we can close it? Thanks!

**Comment by yselkowitz** [comment]
This was released with 1.2.0-rcgit.19, so AFAICS this can be closed.
