### ISSUE TITLE
Enhancement - Another User connected to the server, forcing [...] pop-up

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#1141]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version):  Ubuntu 16.04
* Remmina version (remmina --version): remmina - Version 1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): Windows
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 2.0.0~dev (git n/a)

Hi all!

When someone else connects to the same server/client as me, I get a notification pop-up, stating someone else connected to the client and therefore forcing my session to disconnect.
Since I work with multiple sessions open at the same time that I don't memorize critically, the pop-up does not state WHICH session exactly was terminated, leaving me wondering what session I must restart.

Is there a easy way to print the hostname or connection name from remmina into this popup?

![20170316_consato_001](https://cloud.githubusercontent.com/assets/17683794/23994737/9cf8dd76-0a46-11e7-810e-f33a301297f1.png)

Thanks!

**Comment by antenore** [comment]
Good point. It should be feasible. I'll try myself ASAP.

**Comment by antenore** [comment]
Implemented.

Can you please test it? I don't have too many servers at the moment.

**Comment by CS-JS** [comment]
Wow, that was fast :)
Can I just apt update remmina, or do I have to replace files manually?

**Comment by antenore** [comment]
:-)
Well, unlucky you should build it yourself, but finally as it's not so dangerous what I've modified, I can just merge it in next and you will have it in the PPA next nightly build...

Yes, I'm going to merge.

**Comment by CS-JS** [comment]
Don't get me wrong, I didn't want to press you on this one - but I think the changes made in the PR are quite straightforward. Plus I sadly don't have time to build it while I am at work ^^ 

Thank you very much for the quick change! :-) I can build it maybe later!

**Comment by antenore** [comment]
Of course, don't worry :-)
