### ISSUE TITLE
Custom RDP settings?

### ISSUE THREAD

**Issue by agressiv** [FreeRDP/Remmina#1146]
* Client - Ubuntu 16.10
* remmina Version 1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment - Unity
* Connecting via RDP
* xfreerdp not explicitly installed

I'm hoping to use the quality setting "Best (slowest)" but disable "Menu and window animation", which is:

`disable menu anims:i:1`

in a Microsoft RDP file.  It seems to be disabled at medium or lower in remmina, but with Good or lower, font smoothing seems to be turned off, which is completely undesirable.  I want to otherwise leave it at "Best (Slowest)"

Wish list:
* Add a "custom" Quality setting with checkboxes for the individual settings
* If not, at least allow us to customize these settings in the config file.

**Comment by giox069** [comment]
Remmina has 4 prebuilt quality settings you can use in a RDP profile: Poor, Medium, Good, Best.
All theses 4 settings are customizeable in the global preference dialog box, under the "RDP" tab.
So, from the main window, open remmina preferences (CTRL+P) -> RDP, near "Quality settings" choose "Best" and uncheck "Menu animation".
Let us know :)

**Comment by agressiv** [comment]
Got it!  Didn't realize there were global preferences.  Thanks!
