### ISSUE TITLE
Graphical issues when using byobu/tmux

### ISSUE THREAD

**Issue by Saviq** [FreeRDP/Remmina#1151]
Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 17.04
* Remmina version (remmina --version): 1.2.0-rcgit-18
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Ubuntu 16.04
* Connecting via (RDP, VNC, ...): SSH

There are visual glitches when using byobu over SSH, it's as if remmina optimizes out some lines.

Apart from that the colours differ a lot.

Please see the screenshots of the same byobu session under http://imgur.com/a/9qFpd

**Comment by antenore** [comment]
It's not the first report we receive about byobu, so there is something definitively wrong somewhere.
The terminal remmina implementation is still quite poor, I hope in the next releases I'll be able to improve it.
You should have a vte terminal installed, on arch is called  vte2_90, can you test it with byobu?
Can you also try to change the terminal preferences in Remmina (general preferences, Terminal tab) and see if anything change?

**Comment by antenore** [comment]
Welll, I've some problems sing ranger for example, without Byobu, so there is something wrong in Remmina. I'll take a look

**Comment by antenore** [comment]
https://stackoverflow.com/questions/13707137/ncurses-resizing-glitch#13707598 I found this that can be related.
I'll take a look at our resize callbacks.

**Comment by antenore** [comment]
Found and fixed
