### ISSUE TITLE
Remmina window dissapears when clicking on it while alt-tabbed in ubuntu 16.10

### ISSUE THREAD

**Issue by sliddjur** [FreeRDP/Remmina#1153]
When I press alt-tab in ubuntu to bring up all my open apps, I usally click the app with my mouse to open the app. Apps with more than one window open gets their app grouped. When one app is grouped you can click it to expand the windows. 

Since remmina usually have two windows open, connection list and actual remote host, when I click the remmina app, the connection to the remote host just disappears and leaves just the connection list appwindow open.

If double click the app-bar to the left in Unity, it brings up all open remmina windows, and I can properly select the remote host. 

Please give us some details about the systems you are using:
* Client (OS name and version): 
Ubuntu 16.10
* Remmina version (remmina --version): 
remmina - Version 1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment (GNOME, Unity, KDE, ..): 
Unity
* Connecting to (OS and version): 
Windows Server 2012R2
* Connecting via (RDP, VNC, ...): 
RDP
* RDP issues only, freerdp version (xfreerdp --version):

**Comment by zatricky** [comment]
I noticed this today running ArchLinux. Never had the issue before. It seems it happens also if you simply press Alt and click on the Window. In case it is a different issue, can you confirm if that same behaviour affects you?

**Comment by sliddjur** [comment]
I upgraded to Ubuntu Budgie 17.10 and my problems are gone.

**Comment by ic3d** [comment]
I'm closing this issue because it's (problably) already solved. Feel free to open it again if needed.
