### ISSUE TITLE
File Transfers to Share Folder Crashing Remmina 1.2.0-rcgit-18 Each Try

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#1159]
Have there been any code updates (recently) that could potentially effect Remmina's ability to reliably transfer files from a remote desktop to a local share folder? 

In a fully updated Ubuntu 16.04 64bit (Unity Desktop), running Remmina 1.2.0-rcgit-18 (git rcgit-18), Remmina is crashing each time I attempt to do (even very small) file transfers from a Windows 10 Pro remote desktop to a share folder (I've had set up for years) via the "Basic" section of the Remmina Profile dialog.

Perhaps unrelated, but

When I do:
xfreerdp --version

It says that freerdp-x11 is not installed. Is that needed? If so, why did it not install it as a dependency during the initial install that I did using this command? :

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next ; sudo apt-get update ; sudo apt-get install remmina remmina-plugin-rdp

**Update:** I've just installed freerdp-x11, and retested, but this did not resolve the issue.

**Update 2:** Now it is working fine. I wonder if installing freerdp-x11 ultimately did fix this? Please comment about whether that is necessary or not, this way I can be sure to include that package on future installations.

**Comment by giox069** [comment]
Yes, but it has been solved this morning. See issue #1157. Are you experiencing the problem after this morning update ?
As you noticed, xfreerdp is optional, it's the default frontend to libfreerdp, and it is available in our remmina-next PPA.

**Comment by Lonniebiz** [comment]
I'm fully updated according to the Ubuntu updater. It seems to be working fine now. Do you think I should always include the xfreefdp on future installations or was the fact that I installed that probably unrelated to the fact it is working fine now?

**Comment by giox069** [comment]
xfreerdp is not needed by remmina. So it does not get installed by default when you install remmina from the PPA. xfreerdp is useful when doing debugging and reporting issues here.
I also use it in place of remmina when building "fixed configuration" enterprise thin clients PC, where I need to connect to only a single terminal server.

**Comment by Lonniebiz** [comment]
Interesting. Thanks for the reply.
