### ISSUE TITLE
compilation on Debian 9

### ISSUE THREAD

**Issue by ZAJDAN** [FreeRDP/Remmina#1165]
I try to compile latest Remmina version on Debian 9 (32Bit)
but in first step according to Your manual I have a problem with libssl dependecy.
Do anybody have experience how to correctly install/compile Remmina 1.2 on Debian 9 ?
Thank You

**Comment by giox069** [comment]
I think I can reproduce the problem under Debian 9 with
```
root@debian9:~# apt install libssl-dev libssh-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssh-dev : Depends: libssl1.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
But I have no idea on how to solve it: remmina needs both libssh and libssl.

**Comment by giox069** [comment]
The trick is to remove libssl-dev. After removing it, libssh-dev can be installed and libssl1.0-dev will be automatically installed as a dependency of libssh-dev.
I have just updated the wiki page with instructions to [compile remmina on Debian 9](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Debian-9-Stretch).

**Comment by giox069** [comment]
Thank you @mfvescovi for providing support for finding a solution :)

**Comment by ZAJDAN** [comment]
super! thank You
