### ISSUE TITLE
spice support

### ISSUE THREAD

**Issue by tomarch** [FreeRDP/Remmina#117]
Is a spice support is planned ?

there's a spice-gtk widget available

**Comment by marcominetti** [comment]
:+1: I'm daily using remmina to use Windows and Mac virtual machines... The spice protocol improves performance and enables virtual machine feature management (first of all USB redirection)... I think it could be more complex than integrating the widget... any news about that?

**Comment by marcominetti** [comment]
Is there any starting point if I'd like to contribute? I mean... starting from the suggested IDE and an existing plugin for starting reverse engineering and learning towards spice-gtk? Any doc (assuming I'm a beginner with a supercharged learning curve)?

**Comment by antenore** [comment]
@marcominetti thanks a lot for asking.

It should be quite easy to do it.

Take a look at what I'm doing with the X2GO plugin https://github.com/FreeRDP/Remmina/tree/x2goplugin without considering the Xephyr part. 

Contact me privately and I'll be happy to guide you (mail inside the AUTHORS file).

**Comment by marcominetti** [comment]
Thanks @antenore... I'll take a look at your plugin during the weekend...

**Comment by antenore** [comment]
Implemented. PLease open new feature requests or bugs report if needed.
