### ISSUE TITLE
SSH tunneling does not work with RDP server redirection

### ISSUE THREAD

**Issue by kunkku** [FreeRDP/Remmina#1175]
When connecting to an RDP server via an SSH tunnel, server redirection messages are not handled properly. The address of the target server is now resolved locally. The correct behavior would be to resolve the name on the SSH host and set up a tunnel also for the redirected connection.

Details about the system I am using:
* Client: Fedora 25
* Remmina version: 1.2.0-rcgit-18
* Connecting to (OS and version): Windows Server 2016
* Connecting via: RDP
* freerdp version: 2.0.0-dev

**Comment by antenore** [comment]
Any workaround I could put in place, like forwarding names/UDP requests to the stepping stone, it would be a bad practice.
I'll think about this, but it's much better to work on the client side (your pc/server configuration) .

Ping me if I'll forget to keep you posted.

**Comment by antenore** [comment]
FYI, I've just merged some fixes around ssh #1196.
Name resolution through ssh cannot be done, but as I was saying you can configure your local machine to do it.
Closing this, but don't hesitate to challenge me if you need/want more support

**Comment by kunkku** [comment]
My scenario involves connecting to an RDP server which is accessible only in an organization's intranet. Most of the time, the server replies with a redirection message, which includes the DNS name of another server. This is a private DNS name that can be resolved only by the organization's internal DNS servers. Also the initial connection is made using an private DNS name, which resolves just fine over the SSH tunnel. It is the DNS name sent in the redirection message that incorrectly gets resolved locally. Is there any technical reason for not being able to do a second name resolution over SSH?
