### ISSUE TITLE
Remmina profile editor scrolling is broken

### ISSUE THREAD

**Issue by QuAzI** [FreeRDP/Remmina#1179]
* Client (OS name and version): Linux Mint 17.3 AMD64
* Remmina version (remmina --version): 1.2.0-rcgit-18
* Desktop environment (GNOME, Unity, KDE, ..): KDE

By default my settings opened with scroll at bottom. Even if I drag scroll to top and then change settings tab scrollbar moved to bottom again! And scroll eat the header of tab panel.

![screenshot from 2017-05-15 124836](https://cloud.githubusercontent.com/assets/1897605/26053192/8a86c834-3970-11e7-9936-f774cbdfc521.png)

**Comment by antenore** [comment]
We are working on a new "remmina file editor", so you won't have this issue in future releases.

For your specific case, it's much more a theme/kde integration with GTK.

**Comment by QuAzI** [comment]
I think it is not theme issue. Scrollbar out of the tab panel. And tab panel looks like "page content" for scrollbar in this case. Panel with settings must have own scrollbar inside to scroll only internal content (current tab settings).

**Comment by antenore** [comment]
I'll take a look while rewriting it.

**Comment by antenore** [comment]
I've fixed this in a new the https://github.com/FreeRDP/Remmina/tree/issues_933-rdpgateway

Hopefully will be merged soon.

If you want you can join us in the #933 issue
