### ISSUE TITLE
"Public Key (Automatic)" option does not work with ed25519 keys

### ISSUE THREAD

**Issue by rayfoss** [FreeRDP/Remmina#1187]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Fedora 24
* Remmina version (remmina --version): 1.2.0-rcgit.7
* Desktop environment (GNOME, Unity, KDE, ..): Gnome
* Connecting to (OS and version): Windows 7
* Connecting via (RDP, VNC, ...): RDP

I have 2 keys in my .ssh folder, one is an rsa 2048 and the other is an ed25519 key. When manually selected, the ed25519 key works. But with "Public Key (automatic)" it seems to be ignored. I can use the terminal ssh client without specifying identity and log in automatically, obviously with the ed25519 key.

**Comment by antenore** [comment]
Which version of libssh do you have?

BTW, I strongly advice you to upgrade to the latest Remmina version. We fix several bugs at each release. 

https://github.com/FreeRDP/Remmina/blob/next/CHANGELOG.md

**Comment by antenore** [comment]
Working on it, are you available for testing?
It'll be needed to download the source code and compile it.

**Comment by rayfoss** [comment]
closing as pull request available.
