### ISSUE TITLE
Regular Release planned?

### ISSUE THREAD

**Issue by agaida** [FreeRDP/Remmina#1189]
If so - it would be nice to communicate because - as the bugtracker says - the latest release isn't supported any longer and there are no releases that are supported, only prereleases.

That lead to:
Debian Bug report logs - #863302
RM: remmina/1.1.2-4 --RoM; buggy, unsupported by upstream
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863302

**Comment by antenore** [comment]
We are not Debian packagers, and to be frankly we are not packagers at all.

We are aware of  this issue and unlucky we can do really not much except speaking with the Debian maintainers, that it’s something we are doing.
Till the next Debian release Remmina won’t be officially included and you can only blame the Debian policy :-\
In Stretch we will almost probably have the 1.1 and than, hopefully we will have a backport later of 1.2.
Luckily the Debian Remote Team is taking care about this, so I hope they will come out with a solution.

But again, I want to be clear as a lighting bolt, it's not our business what they decide to do in Debian, and honestly the former Remmina maintainer in Debian, was quite open in showing his disgust against our software so I'm not that shocked.

BTW, policies apart, we have an unofficial Debian package and we need help to maintain it... Help is appreciated ;-)

Have to close this as we cannot really do something... Sorry

**Comment by agaida** [comment]
nice to hear that there are packages - to be true about i run mostly sid, are mostly focussed on Qt - but found out that remmina is a tool that does all the things i need reliable - so time will tell.

**Comment by giox069** [comment]
Just a small update from the Debian maintainers: unfortunately there will be no Remmina 1.1 on Debian Stretch9. I hope we will be able to have a 1.2 as backport or external package as soon as we can.
