### ISSUE TITLE
Graphics Flickering

### ISSUE THREAD

**Issue by david300m** [FreeRDP/Remmina#1194]
CLIENT
---------
OS: Arch Linux 
Kernel: x86_64 Linux 4.11.3-1-ARCH
Resolution: 3840x2160
DE: KDE 5.34.0 / Plasma 5.10.1
WM: KWin
CPU: Intel Core i7-6700K @ 8x 4.2GHz [49.5°C]
GPU: GeForce GTX 1060 3GB
RAM: 3025MiB / 32114MiB
Remmina version: 1.2.0-rcgit-18 (git rcgit-18)
Connecting via RDP at max resolution or a smaller size, the problem is the same.
Experience: LAN
Color Depth: true color 32 bpp
Advanced: default
Local network, standard LAN connection between the host and client (two switches)

HOST
-------
Host: Windows 10 Pro
Intel m5-6y57
8GB Ram

Progressively over the last several updates of Win10, the graphics have been getting worse. When minimizing a window, ghost images of that window flicker at a high rate, as if the frame buffer alternates to what it should be and the previous minimized window. Also, when selecting a dropdown item, the contents will not display, just a blank box. Sometimes the dropdown will render, but mostly not in the last Win10 update. 

I tried tweaking the remmina settings and the host group policies without any luck. 

On the same network, I used a Win10 PC to connect to the Host using the standard Windows RDC and it worked fine, even at 4K resolution. 

Currently I am using KRDC and it works fine with exception to a slight lag between keystrokes. I prefer to use Remmina as when it is working fine, the response is great. 

Please let me know if you require addition information, logs, settings, etc for either system.

Hope this helps.
David

**Comment by david300m** [comment]
See attached, minimizing an excel window...
[20170610_154253.zip](https://github.com/FreeRDP/Remmina/files/1066154/20170610_154253.zip)

**Comment by ic3d** [comment]
Hi @darklajid we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by david300m** [comment]
Hello. Thanks for checking back. I have not used it since then. I will
ensure it's updated and try again today. Will let you know. Thanks
David

David Paul
309.339.1278

**Comment by ic3d** [comment]
@david300m do you have any news?

**Comment by david300m** [comment]
I am trying this morning. So far, it seems very responsive. No flickering
yet. I will use it today and report back. Thanks for being persistent.
Regards
David

David Paul
309.339.1278

**Comment by david300m** [comment]
I've been using it for a few hours and no issues, no flickering tiles. I am
running 4K at full settings. Response is much better than before. Nice job.
I'll start using this over KRDC.
Many thanks
David

David Paul
309.339.1278

**Comment by ic3d** [comment]
Hi @david300m you're welcome! Happy to know that everything's fine, closing this issue.
