### ISSUE TITLE
Remmina PPA disappeared!

### ISSUE THREAD

**Issue by angerangel** [FreeRDP/Remmina#1199]
Remmina PPA disappeared!

```
W: Impossibile recuperare http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Impossibile recuperare http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

```

**Comment by antenore** [comment]
I'm not sure you're using the right ppa, I cannot double check right now.

Did you do the following to add it?

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard

In the case you did not, remove the old one

**Comment by ic3d** [comment]
I'm closing this issue because our PPA is still there. :) Let us know if there are any other problem!
