### ISSUE TITLE
Debian 9 - Remmina - RDP Plugin

### ISSUE THREAD

**Issue by mpaivac** [FreeRDP/Remmina#1201]
Hi,

I compiled like in Debian 9 Wiki.
But it didnt show the RDP plugin, all the others are OK.
The file remmina-plugin-rdp.so is in "/opt/remmina-devel/remmina/lib/remmina/plugins

**Comment by giox069** [comment]
Reboot the pc.
Then execute remmina from a terminal, and see the text output on the terminal. Do you see some error while loading the plugin?

**Comment by mpaivac** [comment]
The file is in the directory.

Failed to load plugin: /opt/remmina_devel/remmina/lib/remmina/plugins/remmina-plugin-rdp.so.
Error: libfreerdp2.so.2: cannot open shared object file: Arquivo ou diretório não encontrado
Failed to load plugin: /opt/remmina_devel/remmina/lib/remmina/plugins/remmina-plugins-rdp.so.
Error: libfreerdp2.so.2: cannot open shared object file: Arquivo ou diretório não encontrado
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed

(remmina:1483): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(remmina:1483): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
