### ISSUE TITLE
Upgrading to 1.2 failed

### ISSUE THREAD

**Issue by UrielSalomon** [FreeRDP/Remmina#1202]
I followed the instructions for Ubuntu here:
https://github.com/FreeRDP/Remmina/wiki

But after issuing:
sudo apt-get update
I run:
aptitude versions remmina
and I only see version 1.1.1-1ubuntu1 versions. Am I supposed to see 1.2 versions here?

Package remmina:                        
i   1.1.1-1ubuntu1                                            vivid                                 500 
Package remmina-common:
i A 1.1.1-1ubuntu1                                            vivid                                 500 
Package remmina-dbg:
p   1.1.1-1ubuntu1                                            vivid                                 500 
Package remmina-dbg:i386:
p   1.1.1-1ubuntu1           
...

and after running:
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard

remmina -a (--version doesn't work) returns the about page of Remmina 1.1.0

* Client (OS name and version): Ubuntu 15.4
* Remmina version (remmina --version): upgrading from 1.1.0
* Desktop environment (GNOME, Unity, KDE, ..): GNOME

**Comment by antenore** [comment]
Did you add the ppa?
Yes, you should see the Remmina 1.2

**Comment by UrielSalomon** [comment]
Yes, I added the ppa (that's the first command in the instructions.)

**Comment by giox069** [comment]
The PPA only supports Ubuntu 14.04, 16.04, 16.10 and 17.04.
https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next

**Comment by UrielSalomon** [comment]
Gotcha

**Comment by UrielSalomon** [comment]
Since I'm using 15.04, I'm closing the issue.

**Comment by UrielSalomon** [comment]
Just finished upgrading to 16.04. Followed the installation instructions (including the ppa), but it says I already have the newest version for the requested packages. 
When I open remmina->help->about, the version says 1.1.2 (previously it was 1.1.0, see my comment above) - not 1.2.
What am I missing here?

**Comment by antenore** [comment]
Remove the existing remmina* and freerdp packages

This should do the job (be careful double check)

```
sudo apt-get --purge remove freerdp-x11 \
 remmina remmina-common remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-gnome \
 remmina-plugin-nx remmina-plugin-telepathy remmina-plugin-xdmcp
sudo apt-get --purge remove libfreerdp-dev libfreerdp-plugins-standard libfreerdp1 \
 libfreerdp-utils1.1 libfreerdp-primitives1.1 libfreerdp-locale1.1 \
 libfreerdp-gdi1.1 libfreerdp-crypto1.1 libfreerdp-core1.1 libfreerdp-common1.1.0 \
 libfreerdp-codec1.1 libfreerdp-client1.1 libfreerdp-cache1.1
sudo apt-get --purge remove \
  libfreerdp-rail1.1 libwinpr-asn1-0.1 libwinpr-bcrypt0.1 libwinpr-credentials0.1 libwinpr-credui0.1 \
  libwinpr-crt0.1 libwinpr-crypto0.1 libwinpr-dev libwinpr-dsparse0.1 libwinpr-environment0.1 \
  libwinpr-error0.1 libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1 libwinpr-input0.1 \
  libwinpr-interlocked0.1 libwinpr-io0.1 libwinpr-library0.1 libwinpr-path0.1 libwinpr-pipe0.1 \
  libwinpr-pool0.1 libwinpr-registry0.1 libwinpr-rpc0.1 libwinpr-sspi0.1 libwinpr-sspicli0.1 \
  libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-timezone0.1 libwinpr-utils0.1 \
  libwinpr-winhttp0.1 libwinpr-winsock0.1
```

**Comment by giox069** [comment]
Also try
`sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"`

**Comment by UrielSalomon** [comment]
Still, I see version 1.1.2.
1) I killed the running remmina
2) I purged all the packages that antenore suggested
3) I even purged with giox069's command - with no effect since all the packages were removed already.
4) Installed remmina again, still saw 1.1.2
5) Rebooted, and still saw 1.1.2

1) Any way I can verify that remmina is *completely* gone from my system after the purges above?
2) Any way I can verify that apt-get update does get 1.2? (Maybe it's getting 1.1.2 somehow?) Will `aptitude search remmina` be the way to do this?

This is my current (after installation) `aptitude search remmina`:

> uriel@uriel-desktop ~ $ aptitude search remmina -v
> i   remmina                                      - remote desktop client for GNOME desktop environment   
> p   remmina:i386                                 - remote desktop client for GNOME desktop environment   
> i A remmina-common                               - common files for remmina remote desktop client        
> p   remmina-dbg                                  - remote desktop client - debug pakcage                 
> p   remmina-dbg:i386                             - remote desktop client - debug pakcage                 
> p   remmina-plugin-gnome                         - GNOME plugin for remmina remote desktop client        
> p   remmina-plugin-gnome:i386                    - GNOME plugin for remmina remote desktop client        
> p   remmina-plugin-nx                            - NX plugin for remmina remote desktop client           
> p   remmina-plugin-nx:i386                       - NX plugin for remmina remote desktop client           
> i   remmina-plugin-rdp                           - RDP plugin for remmina remote desktop client          
> p   remmina-plugin-rdp:i386                      - RDP plugin for remmina remote desktop client          
> p   remmina-plugin-telepathy                     - Telepathy plugin for remmina remote desktop client    
> p   remmina-plugin-telepathy:i386                - Telepathy plugin for remmina remote desktop client    
> i A remmina-plugin-vnc                           - VNC plugin for remmina remote desktop client          
> p   remmina-plugin-vnc:i386                      - VNC plugin for remmina remote desktop client          
> p   remmina-plugin-xdmcp                         - XDMCP plugin for remmina remote desktop client        
> p   remmina-plugin-xdmcp:i386                    - XDMCP plugin for remmina remote desktop client

**Comment by giox069** [comment]
6. dpkg --list | fgrep remmina
7. maybe `apt-cache policy remmina` can explain, please copy and paste the output here, so we can see. Also `apt-cache policy libfreerdp`

and also launch
```which remmina```
and paste here the output

**Comment by UrielSalomon** [comment]
6. dpkg returned nothing, which is good.
7. After installation, I ran 

> uriel@uriel-desktop ~ $ apt-cache policy remmina
> remmina:
>   Installed: 1.1.2-2ubuntu3
>   Candidate: 1.1.2-2ubuntu3
>   Version table:
>  *** 1.1.2-2ubuntu3 0
>         500 http://us.archive.ubuntu.com/ubuntu/ wily/main amd64 Packages
>         100 /var/lib/dpkg/status
> 
But I expect to see 1.2.

> uriel@uriel-desktop ~ $ apt-cache policy libfreerdp
> N: Unable to locate package libfreerdp

Maybe it's because the installation line from the instructions (`sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard`) is missing libfreerdp?


 
> uriel@uriel-desktop ~ $ which remmina
> /usr/bin/remmina

**Comment by giox069** [comment]
you are still accessing a repository of ubuntu wily (15.10) according to apt-cache output.
You have some problem in your apt settings... but we are not apt wizards here :(

**Comment by UrielSalomon** [comment]
Thanks Giox for pointing that problem. I'll learn a bit about the apt policy and try to solve the problem myself. I don't mind closing the ticket, since it's probably not a remmina related issue. Your call.

**Comment by UrielSalomon** [comment]
I manually changed all of my ppa repos in ubunut's Software & Updates to xenial, and upgraded (again) to 16.04 (don't ask me why ubuntu offered me to upgrade after I already upgraded a week ago.)
Redid the steps above (including purging, verified with apt-cache), and now I have the Remmina 1.2.0-rcgit-18.

Yay.
