### ISSUE TITLE
RDP to Win10 makes ToolBar clear

### ISSUE THREAD

**Issue by rtn2** [FreeRDP/Remmina#1209]
Hi,

Hopefully this is right place to ask but if not I do apologize. Here is the information requested.

* Client (OS name and version):  Ubuntu
* Remmina version (remmina --version):  1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment (GNOME, Unity, KDE, ..):  LXDE
* Connecting to (OS and version):  Windows 10
* Connecting via (RDP, VNC, ...):  RDP

It seems that whenever I RDP to a Windows 10 machine the floating Toolbar becomes clear/transparent and it is hard to see. Is that an intended feature? If so is there a way to turn that off? I noticed the setting "invisble toolbar in fullscreen mode" and tried disabling that but it still doesn't have any affect. Please note the toolbar is regularly visible when RDPing into Windows 7

**Comment by antenore** [comment]
Weird, as far as I know there is no difference in the toolbar based on the remote OS.

Would you mind, just for testing, switch temporary to another DE, like gnome for example?

I'm afraid it's a theme or DE issue more than Remmina fault.

**Comment by giox069** [comment]
Just put the mouse cursor on the floating toolbar and use the mouse wheel: the toolbar will change its transparency level.

**Comment by rtn2** [comment]
thanks @giox069 that fixed my issue. man that makes me feel dumb.

**Comment by giox069** [comment]
Maybe a day we will find a better way to make this and other features more "visible" to the user. If we find some good ideas :)
