### ISSUE TITLE
RDP quality settings not saved

### ISSUE THREAD

**Issue by adocampo** [FreeRDP/Remmina#1216]
Client - Arch linux 64 bits
    remmina Version 1.2.0-rcgit-18 (git rcgit-18)
    Desktop environment - Plasma
    Connecting via RDP
    FreeRDP version 2.0.0-dev (git 6001cb710)

If I modify RDP quality settings and close, they are not saved. All other settings (keyboard layout, rotation, etc) are saved successfully.

**Comment by adocampo** [comment]
Nevermind, I've just saw the #521 issue...

**Comment by antenore** [comment]
Also #1247 is relevant and we are going to work around that issue. 
I'm closing this one.
