### ISSUE TITLE
Invalid (too large) file size in rdp shared folder

### ISSUE THREAD

**Issue by niconix-ua** [FreeRDP/Remmina#1220]
Details about the systems:
* Client (OS name and version): xUbuntu 14.04.5 i386 (Linux 4.4.0-83-generic)
* Remmina version (remmina --version): 1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment (GNOME, Unity, KDE, ..): XFCE
* Connecting to (OS and version): Win Server 2008 R2 x64
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): (not installed)

Files in shared folder via RDP session have invalid file size.
![screenshot - 21 07 2017 - 15 37 39](https://user-images.githubusercontent.com/30345226/28463792-f174f2d4-6e2a-11e7-829e-025bc77958a7.png)
![screenshot - 21 07 2017 - 15 36 58](https://user-images.githubusercontent.com/30345226/28463791-f0ec2bd4-6e2a-11e7-9d4a-1e5d0a0d7b06.png)

**Comment by antenore** [comment]
There was an issue like this some time ago in freerdp, but has been solved, so if you install remmina from our PPA it should work.

We need to know what version you have. How did you install remmina and the freerdp package?

**Comment by niconix-ua** [comment]
Remmina installed from "ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu"

remmina 1.2.0-rcgit-18-1.0ubuntu5~trusty
remmina-common 1.2.0-rcgit-18-1.0ubuntu5~trusty
remmina-plugin-rdp 1.2.0-rcgit-18-1.0ubuntu5~trusty
remmina-plugin-vnc 1.2.0-rcgit-18-1.0ubuntu5~trusty

libfreerdp-plugins-standard:i386 2.0.0~dev201703030839+dfsg201704111144-0ubuntu0~git59a8418+e33fbeb~ubuntu14.04.1
libfreerdp1:i386 2.0.0~dev201703030839+dfsg201704111144-0ubuntu0~git59a8418+e33fbeb~ubuntu14.04.1
remmina-plugin-rdp 1.2.0-rcgit-18-1.0ubuntu5~trusty

**Comment by giox069** [comment]
Packages on the [remmina-next PPA](https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next) are newer.
Please upgrade your system with the usual
`apt-get update && apt-get dist-upgrade`

**Comment by niconix-ua** [comment]
apt-get says that I have last version of remmina
![screenshot - 21 07 2017 - 16 27 56](https://user-images.githubusercontent.com/30345226/28465929-360f6b1a-6e33-11e7-8cfb-ca524dd79728.png)

**Comment by giox069** [comment]
did you run `apt-get **dist-upgrade**`?
Your remmina is updated, but not libfreerdp1... Your libfreedp1 is dated back 201704111144 (april).

**Comment by niconix-ua** [comment]
Thank you.
Solved
