### ISSUE TITLE
Missing icons after compiling latest Git release

### ISSUE THREAD

**Issue by der-eismann** [FreeRDP/Remmina#1221]
Hey everyone,

after downloading and compiling the latest FreeRDP and Remmina releases from Git there are a lot of icons missing in the program:

![remmina](https://user-images.githubusercontent.com/10406217/28501061-01d3dce4-6fd4-11e7-9746-8af2b11d435f.png)
![remmina2](https://user-images.githubusercontent.com/10406217/28501062-01ea9600-6fd4-11e7-90cd-21046e37da97.png)

How can I fix this? The rcgit.18 version worked perfectly before. I compiled with
```
cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DWITH_AVAHI=OFF \
        -DWITH_APPINDICATOR=OFF \
        .
```

* Client (OS name and version): Solus OS
* Remmina version (remmina --version): 1.2.0-rcgit-19
* Desktop environment (GNOME, Unity, KDE, ..): Budgie

**Comment by giox069** [comment]
I have no idea why. Try to check inside /usr/share/icons/hicolor/16x16/actions, or /usr/share/icons/hicolor/22x22/actions, you should find
```
remmina-scale.png
remmina-switch-page.png
remmina-fullscren.png
remmina-fit-window.png
```
You could also try to check where remmina is looking for icons like remmina-scale.png:

1. execute `strace -e trace=open -o tempfile.txt remmina`
2. open a connection, so remmina will need remmina-scale.png
3. close the connection, exit remmina
4. `fgrep remmina-scale tempfile.txt` to find where remmina is looking for the icon

**Comment by der-eismann** [comment]
```
> tree /usr/share/icons/hicolor/16x16/actions
/usr/share/icons/hicolor/16x16/actions
├── libpeas-plugin.png
├── remmina-fit-window.png
├── remmina-fullscreen.png
├── remmina-pin-down.png
├── remmina-pin-up.png
├── remmina-scale.png
└── remmina-switch-page.png
```

```
> tree /usr/share/icons/hicolor/22x22/actions
/usr/share/icons/hicolor/22x22/actions
├── libpeas-plugin.png
├── remmina-fit-window.png
├── remmina-fullscreen.png
├── remmina-scale.png
└── remmina-switch-page.png
```

https://hastebin.com/enebopozin.pl
Looks like it doesn't open any icons at all? Should I rebuild with `-DCMAKE_BUILD_TYPE=Debug` or is that useless?

**Comment by giox069** [comment]
Icon are there but GTK is not loading them. @antenore do you have any idea?

**Comment by antenore** [comment]
As we didn't change anything at the icon level, neither we didn't change the make files, It's not a Remmina issue.

I don't know how Budgie works, but I'd investigate around the icon cache mechanism and I'd check if they have changed the default icons placement.

In the last case let us know if you need we add additional prefix variables to selectively choose the icons folder.

**Comment by der-eismann** [comment]
Well... I still don't know the reason, but I compiled it again - this time against the stable and not unstable repository - and now I have all icons. Sorry for bothering you!

**Comment by antenore** [comment]
Cool, not bothering at all!! ;-)
