### ISSUE TITLE
Problems with some color schemes

### ISSUE THREAD

**Issue by rollopack** [FreeRDP/Remmina#1225]
Hi, using color schemes without explicit cursor_color (TANGO, LINUX, XTERM) cause the blinking cursor to be black like the background.

![immagine](https://user-images.githubusercontent.com/2045052/28614560-89d5ad38-71f6-11e7-8473-cfdd62a0fa33.png)

Highlighting the text the cursor is show
![immagine](https://user-images.githubusercontent.com/2045052/28614699-04443698-71f7-11e7-902d-84017658ddfa.png)

For more details: https://github.com/FreeRDP/Remmina/commit/ea58c62377109f0a60d7c82a48eef37a8cacf9b3
-
Client: Debian GNU/Linux testing 
Remmina version: 1.2.0-rcgit-19
Desktop environment: KDE
Connecting to: Any Linux
Connecting via: SSH

**Comment by antenore** [comment]
Thank you, I'll take a look in a couple of weeks.

**Comment by mark-orion** [comment]
I can confirm the ame problem with XUbuntu 16.04.

**Comment by antenore** [comment]
I'm testing and I'll merge in "next" ASAP.
