### ISSUE TITLE
Please don't change releases after you publish them

### ISSUE THREAD

**Issue by diogocp** [FreeRDP/Remmina#1231]
v1.2.0-rcgit.19 was 9d05738e557b9af83c028299ec70aee24f9888b6, then it changed to 0387ee0a916e64083972b45ee147c1e02b60ea90. The same thing happened a year ago with rcgit.15. This creates problems for distributions (see the Gentoo bugs below), so please avoid doing it. If you need to fix something, it's better to make a new release.

https://bugs.gentoo.org/626630
https://bugs.gentoo.org/591604

**Comment by mfvescovi** [comment]
+1, in general.

_Sent from my Google Galaxy Nexus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by antenore** [comment]
Sorry for this, I didn't know it could cause issues.
