### ISSUE TITLE
Feature Request: Create custom Terminal Color Schemes for SSH

### ISSUE THREAD

**Issue by mark-orion** [FreeRDP/Remmina#1235]
I would like to request a feature that allows to define custom terminal color schemes for the SSH terminal.

**Comment by antenore** [comment]
Yes, it's a good idea. As there are some urgent bugs to fix I'll work on this afterwards.

**Comment by digitalfiz** [comment]
Would be nice if this supported importing of formats like GNOME Terminal and others so people can use existing color schemes.

**Comment by antenore** [comment]
@digitalfiz it would be nice, but it's almost  impossible.

Most of the terminal servers have terminal themes hard-coded in their source code, except for those that use Xresources to stock color's configuration. But again, some people at (mainly) Red Hat they are putting all of their effort to erase Xorg from the planet.

As there are some applications that uses external files for the color schemes, I could probably try to implement the same mechanism. If you know any of these applications let me know.

**Comment by digitalfiz** [comment]
Here are a few

http://iterm2colorschemes.com/
https://github.com/baskerville/xresources-color-schemes
https://github.com/AlexAkulov/putty-color-themes

And this site has a neat export feature for tons of different terminals so it would probably be a good place to test out anything you write:

https://terminal.sexy/

**Comment by antenore** [comment]
Any brave humankind who is willing to help out testing [this PR](https://github.com/FreeRDP/Remmina/pull/1272)?

**Comment by antenore** [comment]
I've added a color scheme uploader and color scheme editor, both accessible frm the preferences widget.
