### ISSUE TITLE
Tray applet closing when last window gets closed

### ISSUE THREAD

**Issue by supremesyntax** [FreeRDP/Remmina#1236]
**Remmina version:** 1.2.0-rcgit-19 (git rcgit-19)
**OS:** Ubuntu Gnome 16.04 (GNOME Shell 3.18.5)
**Happens on:** all connections

**What happens:**
I have installed/updated remmina from the remmina-next  ppa.
Now when opening one or more connections (vnc, rdp etc.) the tray applet closes when the last window gets closed.

**What should happen:**
Applet should stay in tray when last window gets closed.

**Comment by giox069** [comment]
This has been fixed a couple of days ago. See issue #1229.
If you are using the remmina-next PPA or snap version of remmina, you will see the update in the next release (1.2.0-rcgit-20).
If you want to test it before the next release, you can switch to the remmina-next-daily PPA or the edge snap channel.
