### ISSUE TITLE
Color on SSH terminal window being applied

### ISSUE THREAD

**Issue by box293** [FreeRDP/Remmina#1238]
* Client: Linux Mint 18.1
* Remmina version: 1.2.0-rcgit-19 (git rcgit-19)
* Desktop environment: MATE
* Connecting to: Linux via SSH 
* Connecting via: SSH

I used Update Manager on Linux Mint to install all the latest updates. Since doing this my terminal window is no longer black with white font, there seems to be some sort of yellow/orange effect being applied.

![selection_002](https://user-images.githubusercontent.com/8356113/28949138-16d86db6-78fe-11e7-8a0f-2e08509f5f7b.png)

You can see that the black background isn't really black. I've highlighted some text and it's got a yellow/orange color to it.

![selection_003](https://user-images.githubusercontent.com/8356113/28949157-3b218b62-78fe-11e7-92ee-05819affc944.png)

It doesn't matter what I set the coilor to above, I tried a completely different background color and it wasn't applied, even after exiting Remmina and opening again.

**Comment by antenore** [comment]
This is because I've introduced the color themes, that you can choose for each connection profile.

![advanced_ssh_profile](https://user-images.githubusercontent.com/5975/29043292-d0d33e58-7bba-11e7-8234-c6a3409e68aa.png)

There are still some bugs unlucky...

Try to select a different theme and thick "Allow bold text", then let me know.

If you have other suggestion open one issue for each please.

**Comment by box293** [comment]
On the connection itself I can select Tango, Linux or XTerm and I get the original style I want. Like you said, just some bugs.

I'm sure that you'll be providing a way to edit the different scheme, define the global default, apply to all selected / existing SSH settings.

The color schemes is a nice feature to add, always good to see improvements added to the product :)

**Comment by antenore** [comment]
I've just merged a commit that fixes the palettes you are using. I'll think about the rest. 
I'll keep this opened anyway.

**Comment by WanWizard** [comment]
It would probably be a good idea to select `Linux` as the default for connection definitions that were made before this update. Now I have to edit all of them, changing them from `Gruvbox` to `Linux`.

**Comment by antenore** [comment]
yes true.

I'll do, in the meanwhile as workaround you can do quick sed command line to change all in one shot.
Do you know how to do it? do you need support? Do you know where to find the profiles?

**Comment by WanWizard** [comment]
yeah, already done, thanks.

**Comment by antenore** [comment]
It's done, it's in our HEAD (next) and it'll be released soon (some few weeks), so it'll be available for distros, hopefully, EOM

**Comment by antenore** [comment]
> edit: perhaps set de charset to UTF8 by default too? 

Didn't see this, I'll take a look on this later on.

Can you please open a new issue for this?
