### ISSUE TITLE

full screen window placement with multiple monitors

### ISSUE THREAD

**Issue by dkruyt** [FreeRDP/Remmina#124]
When opening fullscreen it opens always on the same monitor fullscreen with a multiple monitor setup and it doesnt matter where the mouse is.

The older version of remmina fullscreen (i belive in ubuntu 10.04 or 09.10) was opening on the monitor where the mouse pointer was.

Is this a bug or is there a different way to choose the monitor for fullscreen?
##

**Comment by Hubbitus** [comment]
I could reproduce problem on remmina-1.1.2, freerdp-1.2.0-0.6.beta.1.
I have 2 monitors - small (notebook) and big one. Big set main, there panels and tray with Remmina applet.
Reproduce:
1) Open RDP connection. Window in scaled mode opens on "big".
2) Switch to full mode work as expected. Exit from full-screen.
3) Move window to "small monitor". Switch to full-mode and window fill all "small" monitor and part of "big".

Another case (workaround):
1) Switch to full mode on "big" monitor as before.
2) Do not exit and move it to another monitor (with Alt pressed). It work as expected - fit into "small" monitor.

**Comment by ivansabik** [comment]
Really annoying, I'm using two monitors with different resolutions and this is always happening. As workaround I change the small monitor's resolution to be smaller in width than the one I want the full screen on.  Then make Remmina full screen after that setting back original width resolution.
I found somewhere in other bug report that Remmina always makes the full screen on the monitor with the highest width and for my case this is true.

**Comment by Jean-Dom** [comment]
Nearly 3 years to solve such a problem.
Maybe a bit long, doesn't it?

**Comment by Jean-Dom** [comment]
For "dkruyt commented on 21 Oct 2012": Yes, it was Remmina TABs.

**Comment by antenore** [comment]
We still have some problems with fullscreen support that we need to address. 
I'm going to link the last discussions .

**Comment by antenore** [comment]
For reference:

#864 #873 #241 #376

**Comment by ivansabik** [comment]
I would love to contribute to fixing this, but falls out of my expertise area by far sadly. Also stopped using Remmina since I switched from Mint to OSX for work. I loved it in general except for Copy/Paste capabilities and that full screen thing, great that it exists though and that it's open source 👍 👍

**Comment by 14karat** [comment]
Just an FYI - aside from this glitch, Remmina is great. 
My setup:
Lenovo T560 laptop with 2 external monitors.
Remmina 1.2.0-rcgit-14
Fedora 24 (4.7.4-200.fc24.x86_64 #1 SMP Thu Sep 15 18:42:09 UTC 2016)
gnome-shell-3.20.4-1.fc24.x86_64
Going full screen always goes to the same screen... and it's always the last screen (#3 in my case)
That said, I usually need 2 or 3 windows open at once. I can only have one in fullscreen though since if I set another to fullscreen it covers the one I have already open. So I run one window fullscreen and the rest are only maximized on the other screens.
Given some time I will try with other desktops and see what happens there...

**Comment by skewty** [comment]
Is there any word from the devs on this?  One would think such a basic feature would be a priority..
Paper cuts..  so many paper cuts.  This one needs stitches

**Comment by antenore** [comment]
I don't know yet how to fix it, even if it looks simple to everybody. Help is welcome.

**Comment by Jean-Dom** [comment]
The software works globally
          correctly and is faster than most I have seen.
    Even if the problem of full
          screen is sometimes awfull, thanks for the job already done.
          As we say in French language: À cheval donné, on ne regarde
          pas la bride (when somebody gives you a horse, do not look how
          it is dressed).
    With my version (Ubuntu
          16.04.1 64 bits, Kernel 4.4.0-38, Mate 1.12.1, Remmina 1.1.2)
          and 2 displays, the remaining problems are:
    
      Difficulty to predict on
            which display the full screen will occur. Expected behaviour
            = The full screen should be on the display where the windows
            is located when the command is initiated (so we can drag the
            window if opened on the wrong display) ; If the full screen
            is requested when starting (for instance via the Setup
            parameter "Remember last display mode"), the screen should
            open on the last display used for that connection (if it
            does not exist any more, the main screen).
      Sometimes disconnected
            without any reason = Sometimes need to kill Remmina + Always
            need to restart the programm.
      Unable to force the
            behaviour of <ALT><Tab>: On main screen (the one
            with Application menu) = Switch between programms on local
            PC ; In secondary screen = Switch applications on remote
            server. Need information / Setup parameter/... I do not
            know.
    
    Thanks and "Bon courage +
          Bon week-end".
    Jean-Dominique.
        
    
        
    
    Le 15/10/2016 à 09:34, Antenore Gatta a
      écrit :
    
    
      I don't know yet how to fix it, even if it looks simple to
        everybody. Help is welcome.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeRDP/Remmina","title":"FreeRDP/Remmina","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeRDP/Remmina"}},"updates":{"snippets":[{"icon":"PERSON","message":"@antenore in #124: I don't know yet how to fix it, even if it looks simple to everybody. Help is welcome."}],"action":{"name":"View Issue","url":"https://github.com/FreeRDP/Remmina/issues/124#issuecomment-253968603"}}}

**Comment by 14karat** [comment]
I switched from Gnome to LXDE and have been using the Openbox desktop for several days now. This is NOT an issue here. The screens stay where I put them. (Plus the added advantage of speed and stability that comes with the minimal desktop.)
So - whatever the reason, it must be something specific to Gnome or the associated processes...

**Comment by Enverex** [comment]
I've had the same issue with OpenBox and Marco (MATE) so it's not just Gnome.

**Comment by SolarBear** [comment]
I have the same problem but I have found a workaround (YMMV obviously but this is working for me on Linux Mint 17.3).

Just like you guys, when I press the FullSreen button, Remmina will go full screen on my laptop screen instead of my main monitor. However when that happens I can still move the window around using my keyboard shortcuts (on Mint its Windows key + Left or Right) and moving the full screen window to my monitor works _most of the time_ (which makes that bug even weirder). When it doesn't, I put Remmina back in windowed mode, move the window to my other screen, put it back into full screen mode and then move it to the right monitor using the shortcut described above; it usually works.

Hope it helps!

**Comment by snydox** [comment]
Thank you @SolarBear That made it.

**Comment by antenore** [comment]
#873 should have fixed this

**Comment by Enverex** [comment]
Negative. Still happens. Have to alt+enter to unfullscreen it then alt+enter to fullscreen it again, at which point it fullscreens on the correct monitor.

**Comment by antenore** [comment]
OK, gtk mysteries. I hope I'll find some time soon to look deeply at this. Please, all, provide as much details as possible, distribution, gtk, gdk versions, which remmina distribution are you using (aka, compiled, AUR, PPA, crop, etc)

**Comment by antenore** [comment]
It seems I've found the mistake and fixed it, anybody can test it?

**Comment by useralexey** [comment]
What about multi-monitor support (a key / multimon)?
Tested and main branch multihead Problem in the absence of borders between the two screens in Windows (it defines as one screen)

**Comment by cwilgo** [comment]
I'm currently having this issue with version 1.2.0
