### ISSUE TITLE
No cursor visible in SSH terminal

### ISSUE THREAD

**Issue by WanWizard** [FreeRDP/Remmina#1245]
After the connection is established, no cursor is visible, making editing impossible. This wasn't the case with the previous version (available in F26).

Please give us some details about the systems you are using:
* Client: Fedora 26
* Remmina version: 1.2.0-rcgit-19 (git rcgit-19)
* Desktop environment: Gnome 3 
* Connecting to: Ubuntu 16-04 
* Connecting via: SSH 

Same happens when connecting to other Linux environments, is it is not related to the target.

**Comment by antenore** [comment]
Duplicated of #1225

Already fixed and closed. Will be available in the next release in few weeks.

**Comment by WanWizard** [comment]
Sorry about that, couldn't find it but searched only in the open issues. Stupid me. :flushed:

**Comment by antenore** [comment]
No problem
