### ISSUE TITLE
"Remember last view mode for each connection" not respected in v1.2.0-rcgit.19

### ISSUE THREAD

**Issue by smilemak** [FreeRDP/Remmina#1247]
Hi

I am using ARCH (4.12.4-1-ARCH) with the latest remmina (1:1.2.0rcgit.19-1). This version does - contrary to 1:1.2.0rcgit.18-1) not respect the flag "Remember last view mode for each connection" anymore.

When changing the resolution for a one-timer session and clicking on "Connect" instead of "Save" it also saves the resolution although the flag in the preferences dialog is deactivated. Downgrade to 18-1 helped.

If anything (more infos / logs) is needed - just tell me.

**Comment by antenore** [comment]
When you click on connect Remmina save the connections parameters are set in the profile editor.

We will add an additional button "Save & Connect", Connect will not save the parameters and we are going to rename the Default button to something more clear, like "Save as default"

**Comment by antenore** [comment]
Closed by #1250
