### ISSUE TITLE
VNC plugin on Debian 9 (stretch) no longer available / working

### ISSUE THREAD

**Issue by Papaiso** [FreeRDP/Remmina#1248]
On  my last dist-update the VNC plugin was removed and it is no longer available in the repository.
I tried to manually install a binary for Ubuntu but it says that there are unmet dependencies. The problem seems to be caused by the fact that libvncclient0 is no longer available and it was replaced with libvncclient1. 
Would it be possible to get the vnc-pluggin to work with  libvncclient1?
Thanks

**Comment by giox069** [comment]
Unfortunately we do not have binary .deb pacakges for Debian 9, vnc plugin included. And Remmina has been totally removed from the distributions by the downstreaim maintainters.
So, you have three choiches, after totally uninstalling remmina and rebooting:

1. Use the snap version of Remmina, instructions on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). The snap version has some known problems, the most annoying are that remmina cannot access your ~/.ssh directory to find public/private keys and remmina cannot access system icon files and you will not see all the icons.
2. We have an AppImage version of remmina. But it's under testing. If you want to help in tesing, I will send you an URL for downloading it.
3. You can compile remmina (this is a bit more complex than 1. or 2.). Instructions are on the wiki [here](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Debian-9-Stretch)

**Comment by probonopd** [comment]
Let me know if you need additional testers for your AppImage @giox069

**Comment by giox069** [comment]
Thank you @probonopd for partecipating to this discussion.
We have not yet decided which one will be the better way to build appimage for remmina.
We need to produce AppImage both for x86_64 and for armhf RaspberryPI Raspbian.
I have been able to build it from the PPA for x86_64 via @probonopd Recipe script (my Remmina.yml is just a for of your Remmina.yml), you can see results [here](http://www.remmina.org/appimage-test/). I have not yet investigated on the armhf version. @Papaiso in the meanwhile you can test this version: download the executable, make it executable with chmod a+x and execute it. It will autoinstall.
I have also been able to build a x86_64 version with Travis, but Travis seems to be limiete to x86_64 (no armhf).
So, we are still looking for the simplest way for us to obtain all the needed images.
But not... I'm on holiday now, I will be back next week, so please, be patient :)

**Comment by probonopd** [comment]
To throw one more idea, the Open Build Service is a great option to build for 32-bit and 64-bit Intel and ARM architectures. It also helps you to keep the AppImage updated at all times.
https://git.io/obs-ai

**Comment by giox069** [comment]
@probonopd I'm trying with OBS and your guide. Is there a help/manual which explain the syntax of appimage.yml? I need to clone the branch "next" of remmina, but
```
  git:
    - https://github.com/FreeRDP/FreeRDP.git
    - https://github.com/FreeRDP/Remmina.git
```
seems only to clone the master branch of remmina, not "next" which is the default on github.com.

Thank you.

**Comment by probonopd** [comment]
That's an excellent question @giox069. I am not 100% sure whether pulling non-master branches is possible yet on OBS. Ping @adrianschroeter.

**Comment by giox069** [comment]
A Remmina AppImage for x86_64 systems is ready to test. It has been built with Debian 9 in mind.

HOW TO TEST
Download .AppImage file from http://www.remmina.org/appimage-test/, make it executable and execute it.

KNOWN PROBLEMS
– External Tools are not working

@probonopd: 2 more problems for you :)
1. When Remmina executes an external gnome-terminal via system(), gnome-terminal can't find dependencies. Should I unset LD_LIBRARY_PATH before exec/system()?
2. Are there some guidelines for package publishing which can simplify package updates from the user point of view?
Thank you

**Comment by probonopd** [comment]
> External Tools are not working

Please forgive me for being ignorant, but which "External Tools" and why do you think they are not working?

> When Remmina executes an external gnome-terminal via system(), gnome-terminal can't find dependencies. Should I unset LD_LIBRARY_PATH before exec/system()?

Depends: If you are using an `AppRun` that exports environment variables, then you might want to use something like `appimage-exec-wrapper` (see https://github.com/AppImage/AppImageKit/issues/396). Alternatively and perhaps more elegantly, you could try to do without an AppRun file at all, and just use a symlink to your payload application instead. This would require the application to search for libraries in the right (bundled) location, e.g., by using rpath. This is what `linuxdeployqt` does. No exported environment variables, less trouble with processes started by the payload application.

> Are there some guidelines for package publishing which can simplify package updates from the user point of view?

Yes - please embed update information inside the AppImage. This can be done by using the `-u` option of `appimagetool`. See https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases

**Comment by probonopd** [comment]
Btw, this is the AppImage running on Deepin Linux.

![deepinbildschirmfoto20170908180441](https://user-images.githubusercontent.com/2480569/30220570-35cd5ef6-94c0-11e7-92e6-8b215ea44636.png)

**Comment by giox069** [comment]
External Tools is a command which appears when you select a connection profile and right click the mouse. It lets you to launch an external shell script with the host ip address as parameter. I don't think most of users know/need it :)
To execute this shell script, a "gnome-terminal" is launched by remmina. I will check my AppRun.
Thank you for the on update and the screenshot.
I can see all icons are missing in deepin linux. A debian sid/unstable user reported me a similar problem. Are you running remmina under wayland?

**Comment by probonopd** [comment]
Are you trying to load the icons from a hardcoded absolute path in $PREFIX, such as `/usr/share`? That is not going to work, since the AppImage is not "installed" to `/usr`. Instead, all assets need to be loaded from a path relative to the main executable. Check http://listaller.tenstral.net/docs/chap-Listaller-App-Development.html#sect-Listaller-App-Development-Relocation for one way to achieve this.

**Comment by giox069** [comment]
I'm closing this issue. @Papaiso  if you are interested in AppImage developement, follow issue #1123. For native Debian 9 .deb support: maybe in the future there will be some backports. But not now. Currently it's not possible to build a .deb of Remmina under Debian 9 due to libssh not yet updated to use newer libssl.
