### ISSUE TITLE
ALT + F4 closes Remina remote Window

### ISSUE THREAD

**Issue by cavagnaro** [FreeRDP/Remmina#125]
Hi,
Ubuntu 12.04
Remina 0.9.99.1

Pressing ALT + F4 closes the remote windows as well as Host Key (CONTROL_R) + F4

Pressing ALT+F4
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0065 keycode=26 scancode=18 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=0065 keycode=26 scancode=18 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=FF09 keycode=23 scancode=15 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=FF09 keycode=23 scancode=15 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0041 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0023 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0033 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680
[RDP]keyval=0020 keycode=65 scancode=57 extended=-1077248680
[RDP]keyval=0020 keycode=65 scancode=57 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0041 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0023 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0033 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680
[RDP]keyval=FFE9 keycode=64 scancode=56 extended=-1077248680

Pressing CTRL_R + F4
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0065 keycode=26 scancode=18 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=006A keycode=44 scancode=36 extended=-1077248680
[RDP]keyval=0065 keycode=26 scancode=18 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=FF09 keycode=23 scancode=15 extended=-1077248680
[RDP]keyval=FF09 keycode=23 scancode=15 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0041 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006C keycode=46 scancode=38 extended=-1077248680
[RDP]keyval=0066 keycode=41 scancode=33 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0063 keycode=54 scancode=46 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=006E keycode=57 scancode=49 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0074 keycode=28 scancode=20 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0061 keycode=38 scancode=30 extended=-1077248680
[RDP]keyval=0075 keycode=30 scancode=22 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=0072 keycode=27 scancode=19 extended=-1077248680
[RDP]keyval=006F keycode=32 scancode=24 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0023 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=FFE2 keycode=62 scancode=54 extended=-1077248680
[RDP]keyval=0033 keycode=12 scancode=4 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680
[RDP]keyval=0031 keycode=10 scancode=2 extended=-1077248680
[RDP]keyval=FF0D keycode=36 scancode=28 extended=-1077248680

**Comment by ivoshm** [comment]
Still in 1.1.2 on ManjaroLinux (ArchLinux) ... it's possible include solution to 1.2.0 please?

**Comment by antenore** [comment]
I think this is not a Remmina issue, but your desktop manager that trap the Alt+F4 shortcut.
Check your DM settings and change ALT+F4 with something else and let me know.

**Comment by giox069** [comment]
Or... on the connection window toolbar, you have a keyboard icon. Just press it, and remmina will try to capture all keyboard events which are usually forwarded to the window manager. Let us know.

**Comment by ivoshm** [comment]
giox069: I overlooked this possibility (icon of keyboard was not enough intuitive for me). My problem is solved, thanks.

**Comment by giox069** [comment]
You're welcome :)

**Comment by lolmaus** [comment]
I'm running into this issue.

I want Alt+F4 to close windows, so I don't want to unmap it. But when Remmina is active, I want it to overtake Alt+F4 and execute it on the remote machine.

The very existence of the Host button in Remmina proves that Remmina is supposed to capture special key combinations.

Please reopen.

**Comment by antenore** [comment]
@lolmaus do you have the grab all keys activated?

**Comment by giox069** [comment]
@lolmaus you *must* enble the grab all keys option (press the keyboard icon on the toolbar), or the ALT key will not be captured by remmina and it will  be never sent to the remote desktop.
There could be some problems under older versions of wayland, but under Xorg it works perfectly.

**Comment by lolmaus** [comment]
Works! Thank you, @antenore and @giox069. :bow:
