### ISSUE TITLE
Can't Specify X :display for XDMCP. 

### ISSUE THREAD

**Issue by JulioLeonPhd** [FreeRDP/Remmina#1251]
Since switching to GDM and Gnome, remmina fails to connect to another server via XDMCP. I can connect via Xephyr and X directly. I discovered I can do that if I specify the X display to anything other than :0 or :1. Apparently, GDM uses :0 for the login manager and :1 for my user session. 

It appears that Remmina uses :1 as default for XDMCP. I have looked and can't figure out where I can change this; I believe that specifying :2 or any other X display would suffice to fix this issue.

--
* Client (OS name and version): Ubuntu 16.04
* Remmina version (remmina --version): 1.2.0-rcgit-19 (git rcgit-19)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME 3
* Connecting to (OS and version): CentOS 7
* Connecting via (RDP, VNC, ...): XDMCP
* RDP issues only, freerdp version (xfreerdp --version): N/A

**Comment by JulioLeonPhd** [comment]
I've downloaded the source and debugged it a bit: mainly **xdmcp_plugin.c**. It appears remmina is getting correctly the next free X display using **remmina_get_available_xdisplay()**. However, I still get an error and can't start the connection:

`Fatal server error:
(EE) X11 error
Error code: 8
Sequence number: 5
Major code: 1	Minor code: 0
Error value: 50333225
(EE) 
`
I appreciate any feedback.

**Comment by antenore** [comment]
Thank you for your analysis.
I'll take a look ASAP.

**Comment by antenore** [comment]
Yep, I think I've found it.

```C
#define MAX_X_DISPLAY_NUMBER 99
#define X_UNIX_SOCKET "/tmp/.X11-unix/X%d"

#define INCLUDE_GET_AVAILABLE_XDISPLAY static gint \
remmina_get_available_xdisplay (void) \
{ \
        gint i; \
        gint display = 0; \
        gchar fn[200]; \
        for (i = 1; i < MAX_X_DISPLAY_NUMBER; i++) \
        { \
                g_snprintf (fn, sizeof (fn), X_UNIX_SOCKET, i); \
                if (!g_file_test (fn, G_FILE_TEST_EXISTS)) \
                { \
                        display = i; \
                        break; \
                } \
        } \
        return display; \
}
```

If I'm not wrong, this function will return a display number as soon as it'll find a X_UNIX_SOCKET file, and in your case will be 0 (the GDM display). 

Anyway, I think the best is to add an option to specify the X server number by hand, and than I'll see if we can improve that function.

I'm quite busy lately (other bugs, life and job), so I don't know if I'll be able to implement it in the next days.

Are you up to it? It's easy as adding a line [here](https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/xdmcp/xdmcp_plugin.c#L403) and than using that value as the X server.

You can take a look also to other plugins to have some ideas. There are even some external ones that have a really good and simple structure:

https://github.com/muflone?utf8=%E2%9C%93&tab=repositories&q=remmina&type=&language= 

As you can see from the rest of the code, we are not that much academic, so don't be shy, we are very open.

If you cannot, want and/or don't have time, be patient, I'll do it ASAP.  Ping me from time to time so I won't procrastinate further.

**Comment by antenore** [comment]
> If I'm not wrong, this function will return a display number as soon as it'll find a X_UNIX_SOCKET file, and in your case will be 0 (the GDM display).

The functions seems to do the right thing, sorry, but still the rest of what I said still apply (implementing the option)

**Comment by JulioLeonPhd** [comment]
I did find that function on common/remmina_plugin.h and my debug was trying to test if it was working. It does work: remmina_get_available_xdisplay returns first free X display ID.

I'm not entirely sure why it still does not work. Apparently, I've found a few messages online that state Xephyr might be bugged. It is odd, as I can use Xephyr to connect (without remmina). 

I'm using Xephyr 1.18 btw. Let me know if I can help more.

**Comment by JulioLeonPhd** [comment]
So, I found out it is actually a conflict of Xephyr. If I comment the following lines in function remmina_plugin_xdmcp_start_xephyr (xdmcp_plugin.c), I can get the Xephyr window to actually open (however, resolution is 640 x 480 and I can't get it to change). 

`	argv[argc++] = g_strdup("-parent");  `
`	argv[argc++] = g_strdup_printf("%i", gpdata->socket_id); `

We're getting closer!

**Comment by JulioLeonPhd** [comment]
It appears it is indeed a Xephyr bug that doesn't allow Remmina to nest a Xephyr instance. Let's hope the next version of Xephyr addresses this issue.
