### ISSUE TITLE
SSH username ignored for Tunnels for RDP 

### ISSUE THREAD

**Issue by mkzero** [FreeRDP/Remmina#1254]
I've set an SSH tunnel for an RDP connection that uses a different username for the SSH proxy host than my local login. When connecting it tries to connect with my local name instead of the confugured name. When editing the connection and then opening it again it sets the username for the SSH connection to my local login instead of the one supplied. Rolling back to remmina-1:1.2.0rcgit.18 solved this and lets me connect correctly to that RDP server

* Client (OS name and version): Arch Linux, everything 
* Remmina version (remmina --version): remmina-1:1.2.0rcgit.19
* Desktop environment (GNOME, Unity, KDE, ..): XFCE
* Connecting to: Windows
* Connecting via: RDP
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 2.0.0-dev (git n/a)

**Comment by antenore** [comment]
Can you please test the latest version (rcgit-20)?

**Comment by mkzero** [comment]
Seems like it works again. Connection works and the jump host reports the correct login for SSH in the auth logs.

**Comment by antenore** [comment]
Cool! I'm closing this. Thanks
