### ISSUE TITLE
Changes user name ssh tunnel (vnc over ssh) do not save.

### ISSUE THREAD

**Issue by urobasa** [FreeRDP/Remmina#1255]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 16.04.3 LTS
* Remmina version (remmina --version): 1.2.0-rcgit-19 (git rcgit-19)
* Desktop environment (GNOME, Unity, KDE, ..): gnome
* Connecting to (OS and version): any vnc over ssh (windows, linux)
* Connecting via (RDP, VNC, ...): vnc over ssh
* RDP issues only, freerdp version (xfreerdp --version): 

vnc over ssh
ssh tunnel settings
Changes user name ssh tunnel do not save. Returned to logged user name on any option(agent, password, key, file)

**Comment by antenore** [comment]
Can you please test the latest version (rcgit-20).

**Comment by urobasa** [comment]
Tested. 
vnc over ssh
Create new connection.
set user name ssh toonel to root and option (password or any)
save
Edit settings again, and see user name ssh toonel - current logged user

**Comment by urobasa** [comment]
Rollback to a previous version Remmina 1.1.2 ubuntu 16

**Comment by antenore** [comment]
Fixed. You can test it in the next branch or in the next release rcgit-21
