### ISSUE TITLE
Autoreconnect function with same credentials

### ISSUE THREAD

**Issue by frankdrum** [FreeRDP/Remmina#1264]
Hi team,
Thanks for your work.
Autoreconnect function works, but ask users to re-insert credentials, though saved in the configuration file.
For example i'm loged on with user testts01 with password saved, but when i try to simulate a network failover for some seconds, autoreconnect works but ask me to re-insert my credentials.

![image](https://user-images.githubusercontent.com/31350825/29766703-ed0c6542-8bdf-11e7-80e4-15e17b629659.png)

How can i solve this problem ? any tips ?

Thank you in advance
Bye

**Comment by giox069** [comment]
In this case, when credentials are required inside the remote RDP session, Remmina has already sent the saved credentials to reconnect. But your server is asking them again.
In Remmina, edit the profile and check that under advanced settings, security is set to "Negotiate". Also NLA and TLS may work.
If you security is already in negotiate mode, then I can think there is a setting (maybe GPO ?) at the server side to force the user to reauthenticate after a disconnection?

**Comment by giox069** [comment]
@frankdrum can I close this issue? Did you checked the current authentication type of authentication?

**Comment by frankdrum** [comment]
Sorry,
Yes. Solved
Thank you

Il 06 Ott 2017 11:33, "Giovanni Panozzo" <notifications@github.com> ha
scritto:
