### ISSUE TITLE
Large file corruption over shared folder on RDP connection.

### ISSUE THREAD

**Issue by lachuzhnikov** [FreeRDP/Remmina#1266]
Hi, Team!

On attempt to transfer large files over 2GB (3+ GB images of OS, large archives, etc) with shared folder over RDP - transferred files corrupted. A checksum is mismatched after transfer. 

Small files are transferred correctly.

OS: Fedora 26 with all patches. 
APP: Remmina 1.2.0-rcgit-19
Desktop: Gnome 3.24.1-2.fc26
CONECTIONG TO: W2k8R2, W2k12.
CONNECTION: RDP
RDP: FreeRDP version 2.0.0-dev (git n/a)

Thanks.

**Comment by giox069** [comment]
It seems to be a libfreerdp problem https://github.com/FreeRDP/FreeRDP/issues/4075
The problem has been fixed few weeks ago by the FreeRDP team. Ping @hubbitus.
