### ISSUE TITLE
Remmina on Raspbian 9 Stretch and Remmina RemoteApp support

### ISSUE THREAD

**Issue by canefield** [FreeRDP/Remmina#1269]
Dear Remmina/Support/All,

#1 Remmina v1.2 on Raspbian 9 Stretch
Can you help me out here...I'm using Raspbian 9 Stretch with Desktop _(Release date: 2017-08-16 on a Raspberry Pi 3; 1GB RAM)_, but can't find a way to install the powerful Remmina v1.2. I tried adding the repository _(first had to install the package 'software-properties-common' to use the 'add-apt-repository' command)_ with using the command _'apt-add-repository ppa:remmina-ppa-team/remmina-next'_, but no luck. It couldn't find Remmina as this repository is most likely for Ubuntu, isn't it? Is their a repository out there for Raspbian 9 Stretch (Debian). If so, could someone help me out to get it installed?

Commands used with Ubuntu Mate: 
> apt-add-repository ppa:remmina-ppa-team/remmina-next
> apt-get update
> apt-get install remmina
While trying to simply install Remmina on Raspbian 9 Stretch, it installs Remmina 1.1 instead of 1.2. Perhaps there is some upgrade command? I'm sure the powerful Remmina 1.2 can be installed on Raspbian 9, right?

#2 Remmina RemoteApp support
Does Remmina supports RemoteApp? If yes, how can I configure this? Can I make some file/script attached to Raspbian's Desktop for quick launch? How do I manage/make that? If it doesn't support RemoteApp, will it be in the near future? If not, any alternative/recommendation?
If possible I want to configure RDP and/or RemoteApp with the very best performance using a Raspberry Pi 3 with Raspbian 9 installed. All ideas are most welcome.

Many thanks already,
Canefield

=== ===
Please give us some details about the systems you are using:

* Client (OS name and version): Raspbian 9 Stretch with Desktop (Release date: 2017-08-16, Kernel: 4.9.46-v7 ARMV71), Hardware: Raspberry Pi 3 (1GB RAM)
* Remmina version (remmina --version): 1.1.2-4
* Desktop environment (GNOME, Unity, KDE, ..): LXDE (ls /usr/bin/*session*)
* Connecting to (OS and version): Windows 10 or RemoteApp from Windows Server 2012
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): although Remmina is installed, xfreerdp isn't

**Comment by giox069** [comment]
1. Unfortunately there is no remmina in .deb format for Debian 9, see our [blog post](https://www.remmina.org/wp/remmina-1-2-will-be-available-on-debian-9-stretch/).
We are working on an AppImage version which will run on Debian 9, but currently there are only 2 ways to have remmina on a Debian 9: by compiling it following [the guide on the wiki](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Debian-9-Stretch) (works on Intel, must change some details for ARM) , or as a snap package (again, see [the wiki](https://github.com/FreeRDP/Remmina/wiki)). Please note that currently the snap package has three major problems: password not saved in keyring, missing icons, and inability to access to your ssh keys.
The PPA is for ubuntu, so if you install xubuntu or ubuntu mate on raspberry, you can use the PPA.
I hope we will be able to build an AppImage package for both intel and armhf as soon as possible, see issue #1248.
2. No, remmina does not support RemoteApp. You can use xfreerdp to have remoteapp support. You can find their .deb packages on their github project page.
