### ISSUE TITLE
[Feature Request] Add SPICE Native WebDAV shared folder support

### ISSUE THREAD

**Issue by aenertia** [FreeRDP/Remmina#1273]
Spice supports native remote folder sharing via webdav see 

https://www.spice-space.org/docs/manual/manual.chunked/ar01s10.html

Implement support for this feature in Remmina in a similar manner as is handled by the RDP client today.

**Comment by antenore** [comment]
Thanks @aenertia 
As soon as I'll finish [this](https://github.com/FreeRDP/Remmina/pull/1272) I'll take a look at the WebDAV support.

In the meanwhile do you know that you can already share files between a client and a spice server with Remmina (copy&paste files into the desktop, with the spice-vdagent installed)?

**Comment by larchunix** [comment]
Feature released in Remmina version `v1.2.0-rcgit.25`.
