### ISSUE TITLE
Problem with latest pthread cmake patch and address sanitizer

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#1276]
When compiling with cmake flags `-DWITH_GCC_SANITIZE_ADDRESS=on`, the link phase fails with
```
/usr/bin/ld: CMakeFiles/remmina.dir/src/remmina_sftp_plugin.c.o: undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
remmina/CMakeFiles/remmina.dir/build.make:1053: recipe for target 'remmina/remmina' failed
make[2]: *** [remmina/remmina] Error 1
CMakeFiles/Makefile2:131: recipe for target 'remmina/CMakeFiles/remmina.dir/all' failed
make[1]: *** [remmina/CMakeFiles/remmina.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
@jabl can you help? If not, I will take a look when possible.
Thank you

**Comment by jabl** [comment]
Ugh. Thanks for the heads-up. I'll try to find some time for this tomorrow.

**Comment by jabl** [comment]
I looked briefly at it on Friday, but didn't really make any substantial progress. It seems in remmina/CMakeFiles.txt the CMAKE_THREAD_LIBS_INIT is empty and thus it fails to add -lpthread to the link. It didn't even help to redo the find_library(Threads) stuff there. I'll look into it some more next week.

**Comment by giox069** [comment]
Ok, found it!

-DWITH_GCC_SANITIZE_ADDRESS=on adds "-fsanitize=address" to CMAKE_C_FLAGS and then gcc also adds libasan to the cc link library list.
cmake's FindThreads search for the symbol "pthread_create" in all current default libraries by trying to compila a small program that uses pthread_create. Cmake finds "pthread_create" symbol inside libasan, and FindThreads deduces that no extra "-lptreads" is needed during compilation, so it sets
CMAKE_THREAD_LIBS_INIT to empty.
But in libasan there is only pthread_create, no pthread_cancel symbol. So the link phase will fail due to the missing "-lpthread"

I think this is a cmake FindThreads problem: it should look not only for "pthread_create" do decide to set CMAKE_THREAD_LIBS_INIT to empty.
[I'm using cmake 3.5.1 of ubuntu 16.04]

In the meanwhile, the workaround I found for remmina, is to delay the addition of "-fsanitize=address" after pthread detection.
I'm doing a commit with this solution.

If you have better ideas, you are welcome.

**Comment by jabl** [comment]
I think this is the correct solution for existing cmake versions. I found a cmake issue where this was discussed at https://gitlab.kitware.com/cmake/cmake/issues/16609 and added a note there.

Thanks!
