### ISSUE TITLE
How about support XDG dir structure

### ISSUE THREAD

**Issue by jarryson** [FreeRDP/Remmina#129]
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Instead of useing ~/.remmina, put config files to
$XDG_CONFIG_HOME/signon, cache files to $XDG_CACHE_HOME/signon, data
files to $XDG_DATA_HOME, like the other applications do.

The default fallbacks are:
 $XDG_CACHE_HOME -> $HOME/.cache
 $XDG_CONFIG_HOME -> $HOME/.config
 $XDG_DATA_HOME -> $HOME/.local/share

example: glib contain functions like g_get_user_config_dir(),
g_get_user_cache_dir().

I really hope you can implement this change, it would make the home dir
cleaner, and user can delete all application's cache files or config
files or data files easily.

 Cheers!

**Comment by Hubbitus** [comment]
:+1:

**Comment by antenore** [comment]
I've done the migration

https://github.com/FreeRDP/Remmina/tree/xdg-folders

Some thoughts:

1) Code

The code can be improved, at the moment I used the original one just to avoid to break what it's working. Is it acceptable in your opinion? 

2) Data, config locations and migration

The .remmina files are saved in the $XDG_DATA_HOME, the remmina preferences in the XDG_CONFIG_HOME

Now, in my opinion remmina shouldn't do any data and config migration, this should be done by the user, but I was thinking that maybe it'd would be nice to provide an helper shell script.

One solution could be to provide a wrapper, remmina.sh, that check if there are files under ~/.remmina, does the migration and then execute the remmina binary.

The second one just a simple migremtoxdg.sh (or whatever)...

Any ideas? 

@jarryson @imraro @eheintzmann @Hubbitus @giox069

**Comment by giox069** [comment]
1.  Code: seems to be ok. Please also check the code for locating the external tools scripts in the user home dir. I can't remember how it works.
 2. Remmina is a GUI applications and some users are unable to migrate correctly the configuration files or executing scripts. I think we should do the migration in the GUID. But I'm a bit afraid of it. We should be very paranoid in doing many checks before migrating these files to the new XDG dir.

**Comment by antenore** [comment]
I've used a quite safe workflow:

1. If the XDG directories exist, use them.
2. If the old .remmina exists, use it.
3. If none exist, use/create the XDG ones.

**Comment by antenore** [comment]
Please review #590
