### ISSUE TITLE
Remmina VNC viewer window become freeze or unresponsive if remote Ubuntu pc  connection dropped or shutdown

### ISSUE THREAD

**Issue by vpmuhsin** [FreeRDP/Remmina#1296]
Ubuntu 14:- Remmina VNC viewer window become freeze or unresponsive if remote Ubuntu pc  connection dropped or shutdown.. then we have to Kill remmina process then only we can make new connection...Problem is already accessed other remote connections again need to reconnect....any solutions..!!??  thanks

**Comment by giox069** [comment]
Which version of remmina are you using?

**Comment by vpmuhsin** [comment]
its 0.9.99.1..coming as default one from Ubuntu 14.04.5 version

**Comment by giox069** [comment]
Please upgrade to the latest version, 1.2.0-rcgit.20.
Use our Ubuntu PPA as explained on our [wiki](https://github.com/FreeRDP/Remmina/wiki).

**Comment by vpmuhsin** [comment]
its worked now in 1.2 version..thanks alot
