### ISSUE TITLE
Tab size - SSH Sessions

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#1305]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Kubuntu 16.04.3
* Remmina version (remmina --version): Remmina - Version 1.2.0-rcgit-21 (git rcgit-21)
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): Windows (RDP) and Debian (SSH)
* Connecting via (RDP, VNC, ...): RDP / SSH
* RDP issues only, freerdp version (xfreerdp --version): 

Hi everyone,

when connecting to a SSH Session in Remmina with "grouping by tabs" enabled, I get two different sizes of tabs (one size for RDP, a different size for SSH). Since I use fixed resolution when RDP-ing to a Windows machine the tab, opening the SSH tab screws with the display of my RDP Session. For a workaround I use a sub-group "/customer/servers/ssh", but if it is possible I'd like to get rid of that subgroup.

Is there a way to fix this right away? If not, this is not a priority issue, but would be nice to have :)

Best Regards!
![20171009_consato_002](https://user-images.githubusercontent.com/17683794/31330687-aa4224d8-acdf-11e7-90c5-a8c855b4e3dc.png)
![20171009_consato_003](https://user-images.githubusercontent.com/17683794/31330686-aa3ce1c6-acdf-11e7-8c4d-72c35ff7c4e8.png)

**Comment by giox069** [comment]
The problem is with the default theme (breeze) for KDE. As a workaround, read my post on issue #1011.

**Comment by CS-JS** [comment]
Works perfectly, thanks :) The Icons even look better!
