### ISSUE TITLE
Shared file timestamp

### ISSUE THREAD

**Issue by joo0ne** [FreeRDP/Remmina#1310]
* Client (OS name and version): Debian GNU/Linux buster/sid
* Remmina version (remmina --version): Version 1.2.0-rcgit-20 (git rcgit-20)
* Desktop environment (GNOME, Unity, KDE, ..): xfce
* Connecting to (OS and version): Windows Server 2008 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 1.1.0-beta1 (git n/a)

Files and folders timestamps become older, when see from windows. For example local (linux) timestamp 9.10.2017 8:43:10, on windows 9.10.2017 8.39.39.

If copy file from windows, timestamp go back in time.

**Comment by giox069** [comment]
Confirmed, I can see files with 4-8 minutes of difference. I opened an issue to the freerdp team, see [FreeRDP issue #4173](https://github.com/FreeRDP/FreeRDP/issues/4173).

**Comment by giox069** [comment]
Issue has been fixed upstream by the FreeRDP team. Can you test with a newer FreeRDP?

**Comment by joo0ne** [comment]
fixed
