### ISSUE TITLE
libwinpr.so.2 dependcy missing

### ISSUE THREAD

**Issue by angerangel** [FreeRDP/Remmina#1312]
Hi,
libfreerdp package changed some names, so insert also to update the package **libfreerdp-plugins-standard** otherwise the last version of remmina will hang or crash immediately.

For example on my distribution I need to upgrade to **libfreerdp-plugins-standard**  to version   

     2.0.0~git201710051313-0+remmina201710051517.r73647ad.d0f49046~ubuntu14.04.1

**Comment by antenore** [comment]
Normally if you do an ```apt-get update``` everything should work out of the box, how do you update remmina/freerdp? By hand, for each package?

**Comment by giox069** [comment]
We have just released Remmina 1.2.0-rcgit.23, which should include a fix on the PPA dependencies. Can you test it and close this issue if it's solved?
Thank you.

**Comment by angerangel** [comment]
Yes, it works now.
