### ISSUE TITLE
Remmina removes the desktop application bar when placed in fullscreen mode (Linux Mint v18.2)

### ISSUE THREAD

**Issue by Andrew-Poloni** [FreeRDP/Remmina#1317]
My OS information:

RELEASE=18.2
CODENAME=sonya
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.2 Sonya"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sonya_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sonya_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.2 Cinnamon 64-bit

I've noticed that, when I connect to my RDP desktop and click on the `fullscreen` icon (with `Scaled Mode` *unselected*), it removes the Mint application toolbar.  If I then activate the `Scaled Mode` icon, the application toolbar is restored.  I'm running Remmina in a separate monitor from the monitor displaying the application toolbar in a 4-monitor configuration.  I'm using the NVidia v375.66 driver, X Server Version number 11.0, Server Vendor Version 1.18.4 (11804000), NV-CONTROL Version 1.29.  Let me know if there's any other information I can provide.

Thank you in advance!

**Comment by giox069** [comment]
Hi @Andrew-Poloni, thank you for reporting.
Can you please tell us which remmina version you are using?
If possilble, could you post a couple of screenshots, one with the toolbar missing and scaling disabled, and the other with scaling enabled and the toolbar visible?
Thank you.

**Comment by Andrew-Poloni** [comment]
My apologies: the Remmina version is v1.1.2.

I'm attaching two screenshots of my desktop environment that I captured with Shutter.  The first shows Remmina not in fullscreen mode in the display it's running in and you can see my application toolbar in another display.  The next screenshot shows Remmina in fullscreen mode with the application toolbar gone.

[Workspace1_Remmina_not_fullscreen.png.tar.gz](https://github.com/FreeRDP/Remmina/files/1388714/Workspace1_Remmina_not_fullscreen.png.tar.gz)

[Workspace1_Remmina_fullscreen.png.tar.gz](https://github.com/FreeRDP/Remmina/files/1388716/Workspace1_Remmina_fullscreen.png.tar.gz)

If, once I select the `fullscreen` icon in Remmina and then turn off the scaling, the application toolbar will reappear.

**Comment by giox069** [comment]
@Andrew-Poloni you should upgrade to remmina 1.2.0-rcgit.XX, the latest version. You can find the guide in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). With linux Mint I think you can use the "remmina-next" ubuntu's PPA, so I think the only lines you need to enter on a terminal window, one at time, are:
```
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
```

**Comment by Andrew-Poloni** [comment]
You are a gentleman and scholar ... fixed the issue nicely (and remembers login passwords to boot)! :+1:
