### ISSUE TITLE
SSH session log to file

### ISSUE THREAD

**Issue by kolszak** [FreeRDP/Remmina#1320]
Hi,

Is possible to log all ssh session to asci text file? Like putty, mobaterm or linux bash script

function _sshlog(){ /usr/bin/ssh $@ | tee -a ~/log/ssh_log_$1-`date +%d%m%Y`;}; _sshlog

**Comment by antenore** [comment]
Not yet. I'll work on it.

**Comment by antenore** [comment]
It shoudl quite easy to be implemented.

I've took a look at the well written vte terminal example from the Gnome team.

https://github.com/GNOME/vte/blob/master/src/app/app.cc#L1339 

Their strategy is, if a flag is set, to save the whole buffer at exit time.

As there is not (yet) a vte_terminal_write_contents_async function, I presume that it's not possible to keep a log file opened and save the buffer asynchronously, therefore what I propose is to save the buffer at exit if an optional flag is set and on demand from a context menu command.

I'll add an option like "Save session to file" in the SSH profile, another one to choose the file name and path and a new context menu command "Save session to file" (right click in the terminal window) with its keyboard shortcut.

What do you think?

**Comment by box293** [comment]
Just discovered the "Save session to file" ... great addition 🥇

**Comment by antenore** [comment]
>  Just discovered the "Save session to file" ... great addition 🥇

Thank you Sir!
