### ISSUE TITLE
vte no longer optional

### ISSUE THREAD

**Issue by benkohler** [FreeRDP/Remmina#1327]
With the change in commit dfb497f76439a35b6932cebac49cf187977d7800, vte is no longer optional.  I still pass -DWITH_LIBSSH=no but this change adds an unconditional include on vte.h.

Do I need to unconditionally depend on vte now, or should this new include & related code be wrapped in an "if"?

**Comment by benkohler** [comment]
/mnt/disk/var-tmp/portage/net-misc/remmina-1.2.0_rc22/work/Remmina-1.2.0-rcgit.22/remmina/src/remmina_pref_dialog.c:41:21: fatal error: vte/vte.h: No such file or directory
 #include <vte/vte.h>

**Comment by antenore** [comment]
Yes, you're right, I should have wrapped it, sorry.

If you want you can do a PR or I'll work on it ASAP.

**Comment by benkohler** [comment]
I don't think I'll be able to write the fix myself but I'd be happy to test any proposed patch

**Comment by giox069** [comment]
We have just released Remmina 1.2.0-rcgit.23, which contains a fix for the optional LIBSSH and VTE inclusion during compilation.
Can you test it ?
Thank you.

**Comment by benkohler** [comment]
Works great on my end, thanks!
