### ISSUE TITLE
Keyboard mapping for RDP wrong on up-to-date ubuntu, when accessed on local machine remotely through remmina.

### ISSUE THREAD

**Issue by jgyllinsky** [FreeRDP/Remmina#1328]
Issue
---
_**Breaks when:**_
- SSH+VNC tunneled into same remote machine running up-to-date Ubuntu. Then remmina is opened to use RDP for accessing headless VirtualBox VM of Win10. Keyboard mapping is now broken.

**_Works as expected when:_**
- Locally now, physically at previously remote machine's keyboard, remmina is opened to use RDP for same. Keyboard works as expected.
- At local machine, using remmina to access VNC works as expected. I *believe* accessing RDP from VNC with Remmina on local machine also works, but will have to check later (although this was only test with 1.1.2, and there could of course be a regression either way).

**_Confirmed with clients:_**
1. Chromebook (ARM) with crouton (ubuntu 16.04), running remmina to connect to SSH+VNC server.
2. Android (ARM) with ConnectBot and VNC Client apps, to connect to SSH+VNC server.

Extra data:
---
Issue was present in "1.1.2". PPA was installed following directions at https://github.com/FreeRDP/Remmina/wiki. Version "1.2.0-rcgit-22 (git rcgit-22)" does not resolve issue. Have tired US Keyboard, International English Keyboard, and use client (nothing gets typed). Ubuntu 16.04.3 LTS, running 64bit kernel 4.4.0-96-generic.

This is a show-stopper bug for this use-case. Very confused. Please help.

**Comment by antenore** [comment]
Sorry we were busy with other things.

Did you try to play with the keyboard remmina preferences?

**Comment by ic3d** [comment]
Hi @jgyllinsky we're reviewing old open issues. Do you still experience this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
