### ISSUE TITLE
New connection closes existing window

### ISSUE THREAD

**Issue by matthewsezeller** [FreeRDP/Remmina#1340]
It used to be that I could connect to multiple remote desktops simultaneously and have them open on different workspaces. However after the update opening a new connection closes all of the other windows although I think the old connections are staying open. Once the new window is closed the old one pops up again. Is this a bug, setting, expected behaviour? If you need any more info let me know. Thanks.

Please give us some details about the systems you are using:
* Client OS: Linux 4.13.8-1-ARCH
* Remmina version: After updating from 1.2.0rcgit.21-1 ---> 1.2.0rcgit.22-1
* Desktop environment: Xfce
* Connecting to: Windows 7 and Windows XP
* Connecting via: RDP
* RDP issues only, freerdp version: 2.0.0-dev (git n/a)

**Comment by antenore** [comment]
> You can install [KStatusNotifierItem/AppIndicator](https://extensions.gnome.org/extension/615/appindicator-support/) extension for Gnome Shell, and the remmina systray menu will appear on the top right corner of the screen. One of the last options at the bottom will allow you to reopen the main window. 
 
See #1337 

This is because in Gnome Shell they have removed the systray icon support

**Comment by matthewsezeller** [comment]
Thanks, it was actually a different issue. Not duplicate but also not really a bug. Hopefully this might be useful for someone in the future if this is a common problem. Again, thanks for the help, and sorry to bother.
