### ISSUE TITLE
Ubuntu 17.10 Alt not passed 

### ISSUE THREAD

**Issue by coolemza** [FreeRDP/Remmina#1342]
* Client (OS name and version): Ubuntu 17.10
* Remmina version (remmina --version): 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Xubuntu 17.04
* Connecting via (RDP, VNC, ...): RDP

"Alt" stopped passing after upgrading from 17.04 to 17.10, 1.1.2 version have same issue

**Comment by giox069** [comment]
Are you using Unity under Wayland/XWayland? This can be similar to issue #1086 if you are running under wayland.

**Comment by coolemza** [comment]
yes, you right, its the same

**Comment by julian-alarcon** [comment]
This should be closed and marked as duplicated of #1086

**Comment by antenore** [comment]
Good point @julian-alarcon 

Duplicate of #1086
