### ISSUE TITLE
remmina shows pop-up notification only for first screenshot

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#1347]
I use remmina (=net-misc/remmina-1.2.0_rc21) with ssh and rdp plugins on Gentoo GNU/Linux (amd64, up to date system, portage tree synced at Mon Oct 16 00:39:24 UTC 2017).

> $ remmina --version
> (remmina:6125): Gtk-WARNING **: Theme parsing error: gtk.css:9:22: The :focused pseudo-class is deprecated. Use :focus instead.
> StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed
> Remmina - Version 1.2.0-rcgit-21 (git rcgit-21)

Please note Gtk-Warning.

For now I try to connect to Windows Server via rdp.

remmina is built with support user notification.
Take screenshot button is very useful feature.

But remmina display's notification pop-up only for first screenshot in buffer.
I'm not shure it is a bug, but it is something strange to see notofication for first screenshot and to see nothing for second.

**Comment by antenore** [comment]
Very strange indeed, I've never had this problem, can you please check the notification settings on your side? Notifications uses DBus, how is your window manager configured to use DBus (which wm do you have?)?

**Comment by ssten** [comment]
I use XFce-4.12.

Could you explain what configuration error in notification settings correctly display first one and skips others?

**Comment by antenore** [comment]
For example, did you enable dbus?
```
rc-update add dbus default 
```
Or from your .xprofile, something like:

```
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
    ## if not found, launch a new one
    eval `dbus-launch --sh-syntax --exit-with-session`
    echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi
```

XFCE doesn't have notification support through DBus activated by default, so you should also verify that inside ```/usr/share/dbus-1/services``` (not sure on gentoo about the path) or $XDG_DATA_HOME/dbus-1/services you have something like:

```
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon-1.0/notification-daemon
```

Again sorry for the path if are wrong.

You must have ```xfce4-notifyd``` running and configure it with ```xfce4-notifyd-config```

To test try a script like the following (you need libnotify)

```
#!/bin/bash
notify-send 'Test Message 1!' 'test_notification_id' --icon=dialog-information
notify-send 'Test Message 2!' 'test_notification_id' --icon=dialog-information
notify-send 'Test Message 3!' 'test_notification_id' --icon=dialog-information
```

I really think it's a configuration issue, I've just tried a gentoo with Gnome and it works :-\

**Comment by ssten** [comment]
It is **not** a configuration issue, but a some kind of misexplanation.

Suggested test script works as expected, displaying sequence of **temporary** notification pop-ups (which disappears after a time without any user action).
*remmina* by default displays **static** notification pop-up, which is displayed until user push close icon on it.
After this notification window is closed, taking a screenshot provides no notification pop-up.

Maybe, such behavior was produced by compile-time settings.

**Comment by antenore** [comment]
Really strange... I'd like to reproduce this, but on my systems the notifications works whatever I do, so I don't know what else to do... PLease keep going the debug.

Would you mind uninstalling Remmina and trying to compile it? We have some different guides in our wiki.

**Comment by ssten** [comment]
I use Gentoo GNU/Linux.
So, I already use locally compilled from sources build. Or you mean the latest git snapshot?

My compiler is gcc-5.4.0-r3.
Possibly CFLAGS may matter. Not only in remmina, but also in dependencies.

As I see, for now notification support is a kind of poorly documented runtime dependency.
Maybe we can make in compile-time dependency? With at least interface selection of notification type.

**Comment by antenore** [comment]
@ssten regarding this issue I don't know how to help you. I've Remmina installed on different OS, distros and with different desktop environments and the notifications are working fine.

Also no other users/contributors have reported issues with the notifications. This doesn't mean you are wrong, but just that I really don't know how to replicate your problem and try to eventually fix it.

I'm closing this, but don't take it wrong, IMHO this is an issue with your notification subsystem, try to ask in the gentoo forum to see what they think about it.

Feel free to come back here if you have more details to share, I'll be happy to reopen the issue.
