### ISSUE TITLE
Mapping drives to Windows 2016 server 

### ISSUE THREAD

**Issue by kimdelta** [FreeRDP/Remmina#1354]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version):  Ubuntu 16.04 LTS 64 bit
* Remmina version (remmina --version): 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..):  Unity
* Connecting to (OS and version): Windows Server 2016
* Connecting via (RDP, VNC, ...):  RDP
* RDP issues only, freerdp version (xfreerdp --version): 

I'm having trouble mapping a drive/folder on the client, connecting to windows 2016 server.
I'm able to access the client folder in windows 2016 when loading, but not when saving.
The client folder gives everyone read & write permission.
The problem doesn't occur when connecting to Windows 2003 server.
The windows 2016 server seems to work ok when connecting with standard windows RDP client from e.g. a windows 7 pc, then the client local folder is accessable for saving files aswell as loading.

**Comment by antenore** [comment]
Can you try from the command line with xfreerdp?

Thanks

**Comment by ic3d** [comment]
Hi @kimdelta we are reviewing old open issues. Do you still experience this one? Thanks!

**Comment by ic3d** [comment]
I'm closing thi issue because it problably effects only an old version of Remmina. Feel free to open it again if needed.
