### ISSUE TITLE
clipboard synch not working for second RDP connection

### ISSUE THREAD

**Issue by ElPandaro** [FreeRDP/Remmina#1357]
Please give us some details about the systems you are using:
* Client (OS name and version):  Linux Mint 18.1  64 bit  Kernel Version 4.4.0-98-generic
* Remmina version (remmina --version):  1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..):  mate-desktop_1.16.2-1+serena
* Connecting to (OS and version): Windows Server 2008 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0

I have two RDP connections. Only difference between the two is the Host IP address. The later one has been created by copying from the first. Copy Paste works for the first, but not the second. No matter which i start first. Already deleted the second and recreated it - no work.

**Comment by crysman** [comment]
I've been experiencing the same issue for a longer time already. When more than one RDP connection is established, clipboard syncing starts to behave buggy...

**Comment by antenore** [comment]
I use different RDP connections every day and I don't have these kind of issues.
The only thing is a little delay, but that is normal/wanted.

Which is the clipboard manager you are using?

**Comment by ElPandaro** [comment]
I didn't use any Clipboard manager till i read your comment. I tried with "clipit" but still the same behaviour.

**Comment by ic3d** [comment]
Hi @ElPandaro we're reviewing old open issues. Do you still experience this one? Thanks!

**Comment by ElPandaro** [comment]
Working witz Remmina 1.2.0-rcgit-27 (git rcgit-27) atm and issue is not reproducable anymore.

**Comment by ic3d** [comment]
Thanks @ElPandaro I'm closing this issue, feel free to open it again if (ever) needed.
