### ISSUE TITLE
WARNING: the "resolution" setting in .pref files is deprecated

### ISSUE THREAD

**Issue by ekorneechev** [FreeRDP/Remmina#1358]
* Client (OS name and version): Linux Mint 17.2
* Remmina version (remmina --version): 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): MATE
* Connecting via (RDP, VNC, ...): NX

**WARNING: the "resolution" setting in .pref files is deprecated,
but some code in remmina or in a plugin is trying to read it.**

This warning appears every time you connect to any NX server. Even after: `rm -rf ~/.remmina`
How fix it?

**Comment by genepool99** [comment]
Client (OS name and version): Ubuntu 16.04
Remmina version (remmina --version): 1.2.0-rcgit-23 (git rcgit-23)
Desktop environment (GNOME, Unity, KDE, ..): Unity
Connecting via (RDP, VNC, ...): RDP

Same problem.

**Comment by giox069** [comment]
I just did a PR #1360 to fix it. But I can't test it, because I have no NX servers. @antenore can you test it? Should also be tested maximization/minimization and fullscreen.

**Comment by antenore** [comment]
I'll test ASAP

**Comment by ekorneechev** [comment]
Thank you, we are waiting for the release!

**Comment by antenore** [comment]
@ekorneechev I'm afraid it won't happen very soon as we must fix some other bugs before that.
Maybe you can use the daily build, but sometimes it's not enough safe.
