### ISSUE TITLE
Support for left-handed mouse

### ISSUE THREAD

**Issue by Marlind** [FreeRDP/Remmina#136]
Is there a way to tell Remmina to provide a left-handed mouse? Or add support for it in a future release?

**Comment by antenore** [comment]
This has been implemented in freerdp https://github.com/FreeRDP/FreeRDP/pull/2779/files 

Can you check if you still have the problem (surely yes...).

**Comment by coldserenity** [comment]
Looks like the problem is solved
 * Remmina 1.2.0-rcgit.7
 * Fedora 24 x64

2016-08-25 3:30 GMT+03:00 Antenore Gatta <notifications@github.com>:

**Comment by antenore** [comment]
Cool!
