### ISSUE TITLE
Option to run Pre Command before ANYTHING else

### ISSUE THREAD

**Issue by metafarion** [FreeRDP/Remmina#1363]
Currently, the Pre Command doesn't precede all connection operations.  I don't know everything that happens before it, but at least the destination hostname gets checked for resolvability first.  It would be nice if we could set it to truly run **first**.

In my particular scenario, I'm trying to use a Pre Command to issue wakeonlan before an RDP connection is attempted.  However, Remmina checks my destination name first, doesn't find it because the host is in standby and its DHCP lease and DNS entry have expired, and then gives up.  This does not occur when connecting using an IP address, because no DNS check needs to be made.

I can also see the utility of requiring Remmina to check the destination address before running the Pre Command, so I propose a checkbox to toggle this behavior.

**Comment by antenore** [comment]
Thanks for the report, I'll take a look at it ASAP.

In the meanwhile I don't have a workaround, I'm sorry.

**Comment by CS-JS** [comment]
If I can help in any way to track this down, I'd be glad. I have a similar scenario, where OpenVPN connections to my remote sites are only established, when the first packet is received for a particular destination network. Sometimes, when I connect to hosts via this mechanism, and the WAN connection on the other side is quite slow, the RDP connection times out, after a retry it works fine. So I tried to precede the connection with a "ping -c 3" command, that the VPN itself will be created before Remmina tries to connect to the RDP host, but that did not work. I sadly had no time to further investigate this issue, but as I said, I would be glad to help :-)

**Comment by antenore** [comment]
Yes, I'll work on this in the next days, because it'll allow also all those having ssh tunnel issues to workaround it, so for me this is high priority.

I want to profit to improve the prior and post commands, so if you have any advises and/or feasible requirements. If you can test while I'm working on it, I'll be very thankful.

**Comment by antenore** [comment]
EDIT: updated https://github.com/FreeRDP/Remmina/issues/1363#issuecomment-345634769

**Comment by antenore** [comment]
Do you have issues only with RDP?

**Comment by CS-JS** [comment]
As far as I can tell for now (as I have it tested), yes, only with RDP sessions - I will test with an SSH connection now.

SSH seems to ping beforehand, at least I get a circling "Please Wait" window from remmina.

**Comment by antenore** [comment]
This commit should fix the issue, but I'd like to improve the prior commands even further before to do a PR
