### ISSUE TITLE
Spacebar button bug with "use client mapping" RDP option enabled

### ISSUE THREAD

**Issue by kofbox** [FreeRDP/Remmina#1364]
* Client (OS name and version): KDEneon (User Edition), 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64
* Remmina version (remmina --version): 1.2.0-rcgit-20 (git rcgit-20)
* Desktop environment: KDE
* Connecting to: Windows Server 2008R2 SP1
* Connecting via: RDP
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0~dev

After upgrade Remmina from 1.2.0-rcgit-20 to 1.2.0-rcgit-21 (and higher, up to 1.2.0-rcgit-24) spacebar button not working in some specific way. In Windows I use Total Commander (version 6.5.3 and 8.52a), and I use spacebar button to select folders and files. And some how Remmina breaks working spacebar in Total Commander, but not breacking in notepad and other text-editors. Please, check this bug, because I want to use fresh Remmina and I need to use Total Commander.

**Comment by antenore** [comment]
In the Remmina preferences did you set any particular keyboard layout? Can you try with the "use client mapping"?

**Comment by kofbox** [comment]
@antenore You right! By defaul checkbox "use client mapping" is checked, and when I turn it off - all working fine! Thanks!

**Comment by giox069** [comment]
I think we should disable the mapping of space, and send it as hardware keycode even if "use client mapping" is enabled. I'm leaving this issue open to fix this.
