### ISSUE TITLE
remmina rdp session freeze or hide

### ISSUE THREAD

**Issue by jangar** [FreeRDP/Remmina#137]
on my OpenSuSe 12.2 x64, KDE 4 (noeffect) remmina rdp sessions after indeterminate time freeze or hide the session window.
And if i launch same session nothing appens.
The remmina process remains active and i must kill it for re-exec it.
##

**Comment by Hubbitus** [comment]
@weedy is there any progress? What freerdp/remmina versions are you use?

**Comment by ic3d** [comment]
@weedy is there any news about it? I've seen that OpenSUSE "Tumbleweed" has a recent version of Remmina, did you try to upgrade to Tumbleweed?

**Comment by ic3d** [comment]
@weberhofer I think this bug is related to a very old version of Remmina (and OpenSUSE), do you think we can close it?

**Comment by ic3d** [comment]
I'm closing this issue, because OpenSUSE uses Remmina 1.0 till Leap 42.1. OpenSUSE Leap 42.2 will use Remmina 1.2.0~rcgit.15 (release date: November 16th, 2016).
