### ISSUE TITLE
Remmina shows separate running icon in gnome shell activities overview favorite toolbar

### ISSUE THREAD

**Issue by shnplr** [FreeRDP/Remmina#1370]
Ubuntu 16.04.3 LTS
remmina 1.2.0-rcgit-24
Gnome-Shell 3.18.5
$ dconf read /org/gnome/shell/favorite-apps
[...'org.remmina.Remmina.desktop']
$ locate org.remmina.Remmina.desktop
/usr/share/applications/org.remmina.Remmina.desktop

After adding Remmina to favorites and then clicking to open I notice a new icon is created on favorites toolbar to display the running app - so now there are 2 remmina icons.  For all other favorites apps I have pinned this does not happen - the running app s/be grouped with the existing pinned remmina icon.

**Comment by airvb** [comment]
Ubuntu 17.10 
Last remmina installed
Same snag also !
![remmina](https://user-images.githubusercontent.com/18460569/32828173-a92ae612-c9ee-11e7-9743-e394212a1f21.png)

It's easier if there is only one icon in toolbar 
thks !

**Comment by antenore** [comment]
This is really weird and it doesn't happen on clean Remmina installation.

Are you sure you have only one version of remmina installed?

Would you mind trying a purge and reinstalling it? 

Thanks!!!

**Comment by giox069** [comment]
Try to close remmina, remove the icon from the launcher and then re-add it. Are you still having 2 icons?

**Comment by shnplr** [comment]
Removing/re-adding the icon does not solve the issue.
This problem does NOT occur on my base Ubuntu Gnome 16.04 VM
On closer inspection of my PPA's I find I've added remmina-next along the way...
To reproduce the issue:
```
sudo add-apt-repository ppa:remmina-ppa-team/remmina-next
sudo apt update
sudo apt install remmina
```
This will remove the current favourite from the dock -after re-adding the issue occurs
To resolve the issue:
```sudo ppa-purge ppa:remmina-ppa-team/remmina-next```

This will remove the current favourite from the dock -after re-adding the issue no longer occurs.

Cheers,
Paul
