### ISSUE TITLE
Remmina tray icon not visible anymore

### ISSUE THREAD

**Issue by SlimG** [FreeRDP/Remmina#1371]
* Client (OS name and version): Ubuntu 17.10
* Remmina version (remmina --version): 1.2.0-rcgit-24 (git rcgit-24) (From remmina-next PPA)PPA
* Desktop environment (GNOME, Unity, KDE, ..): Gnome Shell version 3.26.1

The problem:
Remmina tray icon used to work as expected after I upgraded to Ubuntu 17.10, but sometime ~last week the tray-icon disappeared.
Remmina works as expected in every other regard, it's just the lovely tray-icon missing.

I have set "Start Remmina in tray icon at user logon" in Remmina Preferences.
I have tried rebooting
I have tried the following:
```
slimg@bauta:~$ killall remmina 
slimg@bauta:~$ killall remmina 
remmina: no process found
slimg@bauta:~$ remmina --icon
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
Running under Gnome Shell version 3.26.1
```
But my top right corner tray still looks like this:
![selection_057](https://user-images.githubusercontent.com/50249/32831983-53f477e2-c9fa-11e7-9117-b79e49f1c0b2.png)

**Comment by giox069** [comment]
Please also check on remmina global preferences, under "Applet" the tho options:
- Disable tray icon (do not enable it)
- Dark tray icon (try with both dark and not)

**Comment by SlimG** [comment]
I have reassured myself that "Disable tray icon" is not enabled.
I have tried both with and without "Dark tray icon", I've killed the remmina process inbetween tests.

Still no visible remmina tray-icon

**Comment by antenore** [comment]
@SlimG do you have an extention like [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) ?

Without it, starting from Gnome 3.26, that system tray icons are not supported anymore (blame the Gnome team).

Please, let us know

**Comment by SlimG** [comment]
@antenore That did the trick! Superhappy! :smiley:
