### ISSUE TITLE
Please add hostbased mechanism support for ssh

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#1373]
Hostbased authentication is historically very useful feature.
Please add it's support.

If needed, I can consult about configuration and testing.

**Comment by antenore** [comment]
Remmina uses libssh and they don't support hostbased authentication (yet).

They are not against it, but it looks like nobody have started to work on it.

See this thread https://www.libssh.org/archive/libssh/2017-02/0000005.html 

Has we cannot put any effort on helping out our libssh friends (we are already short in resources in Remmina), we cannot support this request in Remmina, I'm sorry.

If you manage to help them or to urge them to implement it, I'll be very happy to reopen this issue.

libssh2 also support hostbased authentication, but someone should implemented the functions for Remmina to use libssh2 as fallback to libssh and again, unlicky, we don't have time (yet).

**Comment by ssten** [comment]
???
According to http://api.libssh.org/stable/ libssh supports hostbased Authentication.
And sometimes it is much more correct solution, than common alternatives.

I agree, it can require some custom and non-trivial setup. Not only on server side, but also on client side.
Somewhere I use hostbased Authentication and can consult about server setup and debugging (this use case looks to be a good example to suggested debug logs tab in connection window).

**Comment by antenore** [comment]
yep, sorry.

I'll find some time to look into it.

**Comment by ssten** [comment]
One more hostbased-related improvement:
For security reasons administrator may need te restrict hosts list, where ssh-connections are allowed.
This can be done by compile-time option, which forces usage system-wide configs (i.e */etc/ssh/ssh_known_hosts*) and ingoring user configs (*~/.ssh/known_hosts*).

**Comment by antenore** [comment]
Please update your main request above.

**Comment by antenore** [comment]
I've verified and the Host based mechanism is not completed in libssh and they are not even sure they will put an effort on it.

One thing you can do is to use an ssh agent or support the libssh team to implement this feature.
