### ISSUE TITLE
Feature request - Option to completely hide the floating toolbar when in fullscreen.

### ISSUE THREAD

**Issue by ZAJDAN** [FreeRDP/Remmina#1379]
This is not a bug!
I am sorry, but I do not know, where I could ask about such thing.
My question is if is possible somehow disable/lock dashboard.
Thank You

**Comment by antenore** [comment]
Do you mean the unity bar on the left on Ubuntu?

**Comment by ZAJDAN** [comment]
antenore:
not, I mean the Reminna dashboard which I see on the top of screen when I have full screen mode.
![remmina_dashboard](https://user-images.githubusercontent.com/11646994/33064191-2a4bdd90-cea5-11e7-9e16-1629e4f2b414.png)

**Comment by antenore** [comment]
Under the preferences (Appearance) you can choose the way the toolbar is shown.

You can also drag and drop it where you want.

**Comment by ZAJDAN** [comment]
please, where exactly is it?
![remmina_dashboard1](https://user-images.githubusercontent.com/11646994/33079510-10948632-ced6-11e7-93fe-c2162475f28b.png)

**Comment by ZAJDAN** [comment]
now I know....it will be hidden in Tabbed mode.

**Comment by antenore** [comment]
![image](https://user-images.githubusercontent.com/5975/33081834-8be9aaba-cedb-11e7-8618-7bf7661275a4.png)

**Comment by ZAJDAN** [comment]
Thank for reply antenore...
should the option 'Hidden' hide the toolbar permanently / hard-boiled? or will be displayed when 'mouse over' the area where is hidden?

**Comment by antenore** [comment]
You can try, right? ;-)

**Comment by ZAJDAN** [comment]
yes it hide the toolbar, but when mouse over the area where it is hidden, it will apper
I would like to hide it permanently, something like a 'children lock'

**Comment by antenore** [comment]
I think this is not possible at the moment, you need a "kiosk mode" like?
Interesting feature, I think we could implement it, what do you think @giox069 ?

If I've understood, can you please update the title and the text of your first comment?

**Comment by ZAJDAN** [comment]
yes "kiosk mode" we could call this feature

**Comment by giox069** [comment]
- The "Fullscreen toolbar visibility" global preference already has an option to completely hide the **floating toolbar**. No need to implement it. See this image:
![disabledfloatingtoolbar](https://user-images.githubusercontent.com/5477803/33096210-1cb0752a-cefe-11e7-8f54-ffc331f9fd9f.png)

- When not disabled, you can drag the floating toolbar  at the bottom of the screen, if you just need to move it away.

- About Koisk mode: kiosk mode usually means "connect to a single host and stay connected only to it". I think `xfreerdp` is a better choice. Remmina strength is on managing multiple connections to multiple hosts in multiple windows or inside the same window, giving the user a lot of simple control/switches to rapidly adapt to different multiple desktops. `xfreerdp` is more skilled to the single connection case.

**Comment by antenore** [comment]
Thanks @giox069 , I'm closing this.
