### ISSUE TITLE
compatibility of microsoft account

### ISSUE THREAD

**Issue by boistordu** [FreeRDP/Remmina#1382]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): debian 9
* Remmina version (remmina --version): 1.2-21

* Connecting to (OS and version): windows 10
* Connecting via (RDP, VNC, ...): RDP

Hi,
is It compatible with microsoft account? or only local and domain account? And should we put it in place?

**Comment by ic3d** [comment]
We do not own a Microsoft account, so we can't know it neither try. Sorry.

**Comment by akallabeth** [comment]
Did authenticate to ms accounts with xfreerdp in the past if that helps

**Comment by antenore** [comment]
Thanks @akallabeth

**Comment by ic3d** [comment]
Closing this issue since it's not a bug nor something we can do much about it.
