### ISSUE TITLE
Remmina 1.2 displays lots artifacts when scrolling/zooming in MS Access print preview, but latest xfreerdp and old Remmina 1.1.2 works correctly

### ISSUE THREAD

**Issue by Baltix** [FreeRDP/Remmina#1387]
Important regression exists in latest Remmina 1.2.0-rcgit-24 (and older 1.2.x) displays lots artifacts (text is unreadable, see attached screenshot) when scrolling (and sometime when zooming) in MS Access print preview window, but latest xfreerdp and older Remmina 1.1.2 works correctly in same configuration.
I've tested on several computers with Ubuntu 16.04 and 17.10 - same issue exist in all Remmina 1.2.0 2017 releases (I did not tried with older), even with latest daily 2017-11-25 build

I'm attaching screenshots of Remmina 1.2.0-rcgit-24 and xfreeRDP 2.0.0~git201710191115 (I use xfreerdp without any options, except /u: /w: /h: /v: ).

![remmina bug artifacts when scrolling or zooming ms access print preview 2017-11-28](https://user-images.githubusercontent.com/1792089/33328996-2ad32f88-d464-11e7-89c8-6466691e19ba.png)
![xfreerdp no artifacts when scrolling or zooming print preview 2017-11-28](https://user-images.githubusercontent.com/1792089/33328997-2aefeb32-d464-11e7-8433-4de841e93328.png)

Details about the systems we are using:
* Client: Ubuntu Linux 16.04.3 and 17.10
* Remmina version: 1.2.0-rcgit-24 and latest
* Desktop environment: GNOME and Unity
* Connecting to: Windows 7 Pro with ThinStuff Terminal Server (see http://thinstuff.com/products/xpvs-server/ )
* Connecting via: RDP
* freerdp version: 2.0.0~git201710191115-0+remmina201710192147.r86bb1e0.d29dd283

Remmina 1.2.0-rcgit-24 and freerdp 2.0.0~git installed from official Remmina Ubuntu repository ppa:remmina-ppa-team/remmina-next , older Remmina 1.1.2 (which works correctly) installed from official Ubuntu repositories.

**Comment by antenore** [comment]
Remmina 1.1.2 cannot works with the latest freerdp.
What do you mean with

> but latest xfreerdp and older Remmina 1.1.2 works correctly in same configuration 
 
We don't know this product you are using, so it's quite hard for us to investigate that unexpected graphical issue.
 
Do you have a server we can access and do some tests? If yes, contact me by email (it's in the Remmina About widget).

**Comment by Baltix** [comment]
Thanks for quick reply @antenore :)
I know, that Remmina 1.1.2 cannot work with latest freerdp, so, I've tested by downgrading both - Remmina to 1.1.2 and freerdp libraries to 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1
> Remmina 1.1.2 cannot works with the latest freerdp.
> What do you mean with
> >  but latest xfreerdp and older Remmina 1.1.2 works correctly in same configuration

I mean, that *latest* xfreerdp  2.0.0-git201710191115-0+remmina201710192147.r86bb1e0.d29dd283 works fine in the same situation where latest Remmina 1.2.0-rcgit-24 (with same libfreerdp 2.0.0-git201710191115-0+remmina201710192147.r86bb1e0.d29dd283 libraries) displays a lot of artifacts, see screenshot above, so, the problem is not in freerdp libraries (because xfreerdp uses same libraries), but in Remmina.
Also I mean, that old Remmina 1.1.2 with old freerdp libraries 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 also works fine in the same situation, so, this issue is regression.

**Comment by antenore** [comment]
@giox069 ? Do I try to refresh the FreeRDP lib (after the debian patch issue)

**Comment by giox069** [comment]
@Baltix Can you try xfreerdp with /gdi:sw ? Remmina does not use the standard acceleration of xfreerdp, but the software rendering of libfreerdp. /gdi:sw makes xfreerdp use the same software renderer that remmina uses.

**Comment by Baltix** [comment]
**Yes, problem is in /gdi:sw - when I run xfreerdp with /gdi:sw then the same artifacts appears in xfreerdp!** 
Thanks @giox069 , maybe you can tell me how to reconfigure Remmina to not use software rendering of libfreerdp ?
I think there should be the setting in RDP connection preferences for enabling/disabling software rendering of libfreerdp

**Comment by giox069** [comment]
Remmina does not have hardware rendering support: it's too complex to implement and maintain for us. The correct solution should be opening an issue with the FreeRDP team [here](https://github.com/FreeRDP/FreeRDP/issues), after testing it with the latest xfreerdp compiled from their source. To have it solved, you should also add
- The name/version of the OS you are connecting to
- The version of office you are using

I can help in opening the issue, but I have to reproduce the problem so I need to know the above two informations and maybe more.

**Comment by giox069** [comment]
Yes, you can. But it's 6 days old, because the build system is currently broken. I will retry to fix it in some hours.

**Comment by Baltix** [comment]
latest xfreerdp version 2.0.0~git201711291428-0+remmina201711301433.rd2cb79c.d29dd283 (from https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily ) still has the same issue when using /gdi:sw option.
I'm connecting to: Windows 7 Pro with ThinStuff Terminal Server (see http://thinstuff.com/products/xpvs-server/ )

It's interesting to say, that that old Remmina 1.1.2 with old freerdp libraries 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 works fine in the same configuratio (the same client computer and the same Windows 7 Pro with ThinStuff Terminal Server

**Comment by giox069** [comment]
I have just setup a test VM with win7+office 2003, without thinstuff. I'm able to reproduce the problem. I opened an issue to the FreeRDP team: https://github.com/FreeRDP/FreeRDP/issues/4299

**Comment by Baltix** [comment]
Thanks for fixing this important (for us) issue - no problems with freerdp libraries 2.0.0~git201712281853 and remmina 1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da
