### ISSUE TITLE
Allow external commands without protocols in create connection dialog

### ISSUE THREAD

**Issue by gh-user-7392** [FreeRDP/Remmina#1391]
Using the latest Remmina - Version 1.2.0-rcgit-24 (git 72acb10) I mostly utilize VPN connections before launching a RDP connection to a Windows server. I have a script that I use in the Pre-command area to check if the VPN is open or not for every connection. If it is not it automates the setup of the connection. If it is already open it silently terminates. However, when I eventually want to shutdown the VPN I have to manually do this as I don't want to shutdown the VPN connection (using a Post-command script) every time I log off a server because I generally want to leave the VPN open for long periods of time during administration periods. I fudged this in Remmina by creating a SSH connection with no password that executes the Pre-command with a stop option for the Bash script. However, as you can imagine, I have to click an OK through an error message about a password problem. It would be nice if Remmina had the option to simply create a connection that simply calls an external script without having a protocol tied to it in order to facilitate the automated one-click calling of a script. I realize there are other methods to do this but I thought to keep it all in one place would be convenient.

**Comment by antenore** [comment]
Why not!
I was thinking, previously, to write an exec (protocol) plugin, to just exec something and have the result (whenever possible) in a remmina window.

Writing a protocol plugin for Remmina, it's quite straight forward, but I don't have time now.

If you have a bit of time it could be worth taking a look at the hellp plugin in the remmina-plugins folder in the source tree.

Otherwise I'll add this to our long queue

**Comment by gh-user-7392** [comment]
After looking into developing a solution to this problem, I found that it had already been done. Fabio Castelli (Muflone) has already created "Remmina Plugin EXEC", and you can find a well documented website at: http://www.muflone.com/jekyll/remmina-plugin-exec/english/, in addition, you can get the latest master git src from: https://github.com/muflone/remmina-plugin-exec. All I had to do was update two CMakeLists.txt files to build with the latest master of Remmina as an example plugin.

For anyone interested here is a quick summary of how to get this compiled into the current Remmina plugins source tree.

- Following the Remmina Wiki I built Remmina for Ubuntu 16.04.3 and also added FreeRDP 2.0 RC1 for the RDP plugin capability.
- After doing this and making sure it all works; use git to clone the EXEC plugin to a temporary area using this command:
  cd /tmp; git clone https://github.com/muflone/remmina-plugin-exec.git
- Using my /usr/local/src/remmina_devel/Remmina source tree as an example; 
  mv the /tmp/remmina-plugin-exec/remmina-plugin-exec directory to /usr/local/src/remmina_devel/Remmina/remmina-plugins/
- cd /usr/local/src/remmina_devel/Remmina/remmina-plugins/ and apply the first patch below to the CMakeLists.txt
  patch -p0 CMakeLists.txt < CMakeLists.txt.patch1.txt
- cd /usr/local/src/remmina_devel/Remmina/remmina-plugins/remmina-plugin-exec and apply the second patch
  patch -p0 CMakeLists.txt < CMakeLists.txt.patch2.txt
- The EXEC plugin was added to the Remmina source build by enabling the examples cmake selector (-DWITH_EXAMPLES).
- Rebuild the Remmina source tree with the new plugin:
  cd /usr/local/src/remmina_devel/Remmina/
  rm CMakeCache.txt
  make clean
  cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/remmina -DCMAKE_PREFIX_PATH=/opt/remmina_devel/freerdp -DWITH_EXAMPLES=ON --build=build .
- During the cmake, make sure you see this line:
  -- Enabling examples and test plugins.
- Make and install Remmina
  make && make install
- Run Remmina and create a new connection using the Exec protocol. Add a script to the "Startup Program" area and test.

I put this together quickly just to share, sorry about the patch files. Thanks to Fabio for the code, there was no need to reinvent the wheel; at least for my requirements anyway.

HTH

//Patch Files
[CMakeLists.txt.patch1.txt](https://github.com/FreeRDP/Remmina/files/1523471/CMakeLists.txt.patch1.txt)
[CMakeLists.txt.patch2.txt](https://github.com/FreeRDP/Remmina/files/1523472/CMakeLists.txt.patch2.txt)

**Comment by antenore** [comment]
Yes, he was participating in the Remmina development as well.
We should just integrate it in the Remmina tree.
Are you up to it? Would you like to try and submit a PR? 

Just be careful to keep all the copyright information. 

Please and thank you!

**Comment by muflone** [comment]
> We should just integrate it in the Remmina tree.
> Are you up to it? Would you like to try and submit a PR?
> Just be careful to keep all the copyright information.

@Antenore please restore the copyright information you removed from the remmina-plugin-exec code.

**Comment by antenore** [comment]
Which copyright? I didn't use your code at all, I have developed my own plugin based on your idea. They are quite different. If you want I can, if it's not already the case, add a note.

**Comment by muflone** [comment]
You know what I'm refering to.
Please restore the original copyright notices as this plugin is based on my idea and my code, still shares parts of the code, the plugin name and arguments.

I really apprieciate the enhancements you've done to the plugin and I'm happy that you decided to include it into remmina but please restore what was in the head of the files before you applied your modifications.

P.S. bump the version number, this is not yet a 1.0 version.

**Comment by antenore** [comment]
I will add what has to be added at the very first occasion and for sure before the next release. Consider that I've intentionally avoided to use as much as possible any part of your code. Some of these part are impossible to be changed because in common with all plugins. For the rest the plugin is a complete rewrite, I've kept the name because, indeed, the idea it's based on your originalbone. For the versioning I don't see why I should change it, if needed we will discuss this separately
