### ISSUE TITLE
remmina fails to open sftp window, connected to ssh2 server with public key auth

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#1392]
Sometimes I need to work with old unix servers.
My settings are:

* Client (OS name and version): Gentoo GNU/Linux amd64 profile
* Remmina version (remmina --version): net-misc/remmina (12:23:26 01.12.2017)
* Remmina - Version 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): XFce 4.12
* Connecting to (OS and version): OSF1 unix.domain.tld P5.1 1644 alpha

I don't want to use *passwords*. The only sufficiently secure authentication mechanism is *public key*.
Shell connection works fine.
But when I try to open *sftp* for files transfer, operation fails (usually just tab closes immediately, but once *remmina* crashed).
Starting in terminal showed no additional info.

The same test after roll-back to password authentication succeed.

**Comment by antenore** [comment]
I'll take a look

**Comment by antenore** [comment]
Fixed, it'll be available in the main branch in some days, as soon as I'll merge it.
The sftp plugin suffers from the same issues as the ssh plugin you have reported.

**Comment by antenore** [comment]
I've just fixed the SSH tunnel for the sftp as well. It wan't working.
I'm closing this, but if you'll issue don't hesitate to contact me again.
