### ISSUE TITLE
Capture Keyboard events turns off when remmina auto-reconnects after system lock due to inactivity

### ISSUE THREAD

**Issue by rounaksingh** [FreeRDP/Remmina#1394]
Hi,
I am using 
Remmina version v1.2.0-rcgit.24 
on Arch (kernel: 4.13.12-1 LTS) with XFCE desktop 
connecting to Windows 7 (via RDP -- FreeRDP version 2.0.0-dev)
connecting via Cisco Anyconnect VPN

The issue is the capture keyboard events. When connecting Remmina to Win7 first time it works fine. However, after system locks itself after a duration of inactivity, and when I unlock the system and Remmina tries to autoconnect, everything but the keyboard works fine. The keyboard losses focus again and again, so I have to click on the capture keyboard event everytime to get the focus. It gets annoying if I am working like this for long time. 
Also, if I will disconnect this connection, and connect again from the first step it works well. But after getting computer lock itself and Remmina autoconnect, the issue comes back again.

Thanks

**Comment by ic3d** [comment]
Hi @rounaksingh we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing thi issue because it problably effects only an old version of Remmina. Feel free to open it again if needed.
