### ISSUE TITLE
Remmina lock screen when i use it to connect to Win10.

### ISSUE THREAD

**Issue by berillions** [FreeRDP/Remmina#1396]
Please give us some details about the systems you are using:
* Client (OS name and version): Debian Stretch
* Remmina version (remmina --version): Remmina - Version 1.2.0-rcgit-24
* Desktop environment (GNOME, Unity, KDE, ..): Mate
* Connecting to (OS and version): Windows 10 - Fall Creator Update
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 

Hello,

I'm French so i try to explain correctly my problem. 
Actually i use my Desktop PC like a console on my TV when my wife is not here and use my laptop (Debian) when she is at home to play at Windows games with the Streaming local from Steam.

To avoid to use a mouse/keyboard on my Desktop, i installed Remmina on the laptop and the connection from my Debian to Win10 works great. The only issue that i have is that when i launch the connection from Remmina, the "lock screen" is started (if i launch my TV, i have the lock screen during my use of Remmina)

The problem is when i disconnect Remmina, i still have the "lock screen" enabled and it's not possible to play at my Windows games with local streaming from Debian. I have an error message from Steam which say me : "The Screen is locked on the remote computer"

I have this problem even if i disable "lock screen" on Windows 10. It's possible to use Remmina and connect me to Win10 without to lock screen ?

Thanks

**Comment by antenore** [comment]
Ton niveau en anglais est très bon, on a tout bien compris. Je passe à l'anglais pour le reste du monde.

This is a Windows security setting that has nothing to do with Remmina and FreeRDP unlucky.

On Windows 7 there was a key in the registry "HKEY_CURRENT_USER\Control Panel\Desktop\ScreenSaveActive", check if you have on Windows 10 as well.

Check also this thread https://superuser.com/questions/1030942/disable-lock-screen-after-remote-desktop-session-in-windows-10#1030966 that I think it's your main issue.

and this https://www.tenforums.com/network-sharing/16159-disable-login-screen-after-remote-desktop-session.html

Let me know... Just in case in the Remmina About Widget there is my personal mail, you can write me a message (in French or English, as you wish)
