### ISSUE TITLE
Full Screen with multiple monitors always in the same monitor

### ISSUE THREAD

**Issue by xkill** [FreeRDP/Remmina#140]
I have two monitors, if I do a full screen connection, it always appear on the main monitor ... but I want to create the fullscreen on the monitor when I have the remmina window.

**Comment by Hubbitus** [comment]
Possible duplicate of fixed https://github.com/FreeRDP/Remmina/issues/154

**Comment by ic3d** [comment]
@xkill it seems the we've already fix it (see bug #154 ), can you confirm that this bug is now solved? 
Thanks!

**Comment by ic3d** [comment]
I close this issue because of (possible) duplicate and it affects an old version of Remmina.
