### ISSUE TITLE
The password in the connections is not saved after upgrading Remmina

### ISSUE THREAD

**Issue by kofbox** [FreeRDP/Remmina#1402]
* Client (OS name and version): KDEneon useredition, Linux 4.10.0-42-generic #46~16.04.1-Ubuntu
* Remmina version: 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment: KDE
* Connecting to (OS and version): Windows Server 2008R2 SP1
* Connecting via: RDP
* RDP issues only, freerdp version: 2.0.0~dev

After updating Remmina to the latest version, the password from the saved settings of all connections was lost. I tried to create a new connection and entered a password. Also does not save it. Help.

**Comment by kofbox** [comment]
Sorry, somthing go wrong... After restart computer all working again.

**Comment by giox069** [comment]
@kofbox I noticed that under very rare circumstances on Ubuntu 16.04 remmina cannot connect to the gnome keyring. Just exiting remmina and reopening it solves the problem. But it happens too rarely to understand why.
