### ISSUE TITLE
Remmina crashes when sharing local printers and connecting through gateway

### ISSUE THREAD

**Issue by kirreen** [FreeRDP/Remmina#1405]
Basically what the title says. I'm using FreeRDP. Printers work without a gateway. 
Any files you need that'll help you out?

**Comment by antenore** [comment]
Can you please provide the FreeRDP and Remmina versions?

Can you also test with xfreerdp?

Thanks

**Comment by ic3d** [comment]
Hi @kirreen we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by kirreen** [comment]
I'm not! The problem was that the printer was badly configured. This caused all remmina windows to close.
