### ISSUE TITLE
build fails with -DWITH_GETTEXT=OFF

### ISSUE THREAD

**Issue by benkohler** [FreeRDP/Remmina#142]
When -DWITH_GETTEXT=OFF is passed to disable NLS support, the build system still attempts to build translations and fails due to undeclared vars.

Here's a short snippet of the error, but a full build log is attached:

/usr/bin/cmake -E cmake_progress_report /var/tmp/portage/net-misc/remmina-1.0.0_p20121004/work/remmina-1.0.0_p20121004_build/CMakeFiles 69
[ 37%] Generating th.mo
cd /var/tmp/portage/net-misc/remmina-1.0.0_p20121004/work/remmina-1.0.0_p20121004_build/remmina/po && -o /var/tmp/portage/net-misc/remmina-1.0.0_p20121004/work/remmina-1.0.0_p20121004_build/remmina/po/th.mo /var/tmp/portage/net-misc/remmina-1.0.0_p20121004/work/remmina-1.0.0_p20121004/remmina/po/th.po
/bin/sh: -o: command not found
make[2]: *** [remmina/po/th.mo] Error 127

**Comment by Hubbitus** [comment]
Could it been then closed?

**Comment by benkohler** [comment]
It seems that "-DWITH_TRANSLATIONS=OFF -DWITH_GETTEXT=OFF" works, but plain "-DWITH_GETTEXT=OFF" still fails.  This could be cleaned up with some extra logic in the build system I suppose, but this isn't really affecting me or my distro anymore, so I won't be upset if this bug is closed.

**Comment by ic3d** [comment]
@antenore I've seen that there was a similar bug #23, closed back in 2015. So, can we close this one?

**Comment by antenore** [comment]
Yes, thanks Dario
