### ISSUE TITLE
XDMCP Protocol

### ISSUE THREAD

**Issue by FBobbioC** [FreeRDP/Remmina#1421]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Slackware-current
* Remmina version (remmina --version):  The Digger Edition (v1.2.0-rcgit.25 (2017-12-27))
* Desktop environment (GNOME, Unity, KDE, ..):  KDE
* Connecting to (OS and version):  CentOS 7
* Connecting via (RDP, VNC, ...):  XDMCP
* RDP issues only, freerdp version (xfreerdp --version):  N/A

What package does XDMCP use in Remmina? I can use Xnest -query thincentre -geometry 1280x1024 :1 and am able to connect. I can get around this by running that command, but would like to use Remmina, since it would centralize all connections in one place.

**Comment by antenore** [comment]
You should install Xephyr.

**Comment by FBobbioC** [comment]
Antenore,

`Xephyr :5 -query thinkcentre -resizeable &`

works for me, but when I try starting it from Remmina, the connection does not work at all.

bash-4.4$ gdb remmina
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from remmina...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffead3f700 (LWP 12289)]
[New Thread 0x7fffea53e700 (LWP 12290)]
StatusNotifier/Appindicator support: your desktop does support it, but you did not compile remmina with cmake's -DWITH_APPINDICATOR=on

(remmina:12285): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
[New Thread 0x7fffd8c58700 (LWP 12293)]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffd3a62700 (LWP 12304)]
[Thread 0x7fffd3a62700 (LWP 12304) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[Thread 0x7fffd8c58700 (LWP 12293) exited]


Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffd8c58700 (LWP 12366)]
[New Thread 0x7fffd29d4700 (LWP 12367)]
[Thread 0x7fffd8c58700 (LWP 12366) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[Thread 0x7fffd29d4700 (LWP 12367) exited]

and then I receive "SSH public key authentication failed: Access denied.  Authentication that can continue: publickey,password,keyboard-interactive." and the option to click on "OK"

I can ssh into that same host without any issues

**Comment by antenore** [comment]
I'll take a look when I'll be back con the vacation, in one week.
I think I've a clue

**Comment by larchunix** [comment]
I guess it is the same issue as #366 (Xephyr upstream issue is https://bugs.freedesktop.org/show_bug.cgi?id=91700 ).

You have to downgrade Xephyr to version 1.16.4 or build a Flatpak version of Remmina which bundles the old Xephyr version (see build instructions here: https://github.com/FreeRDP/Remmina/blob/next/flatpak/README.md).

**Comment by FBobbioC** [comment]
Thank you, sir, that worked fine.
