### ISSUE TITLE
Remmina 1.2.0-rcgit-25 segfault

### ISSUE THREAD

**Issue by DareDevil73** [FreeRDP/Remmina#1422]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Linux Mint 18.3 64 bit (Ubuntu 16.04)
* Remmina version (remmina --version): 1.2.0-rcgit-25 
* Desktop environment (GNOME, Unity, KDE, ..): Mate
* Connecting to (OS and version): Any
* Connecting via (RDP, VNC, ...): Any
* RDP issues only, freerdp version (xfreerdp --version): None

Each time I click on a connection Remmina crashes with a segfault. This happens after latest upgrade.

**Comment by antenore** [comment]
Are you sure with Any protocol? We have a bug related to SSH, that has been fixed, see #1418 on how to workaround it.
In the next day we will release a new patched version.

**Comment by antenore** [comment]
for info

If you don't have any SSH private keys under ``` $HOME/.ssh ``` do the following from the command line

```sh
ssh-keygen -b 4096
```

**Comment by antenore** [comment]
Closing as I'm releasing a new version

**Comment by DareDevil73** [comment]
I confirm: issue solved with next release, thank you!
