### ISSUE TITLE
Password not saving - encrypting *.remmina connection files

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#1423]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Kubuntu 16.04.03
* Remmina version (remmina --version): 1.2.0-rcgit-26 (git rcgit-26)
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): -
* Connecting via (RDP, VNC, ...): -
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 2.0.0-dev2 (n/a)

Hi everyone,

with rcgit 26 I realized, *.remmina files are not longer handled as text files in my Kubuntu environment but rather open a remmina connection with their respective settings (I don't know, if they should behave like this before, I just realised it with the current release).
That made me think of distributing *.remmina files (e.g. RDP-connections to  our customers) to my coworkers without needing them to know the actual credentials for the login, what would be a great thing concerning our customers security if someone decides to quit working for us (hope that won't happen, but you never know :-) ).

I've tested this with an internal RDP-connection to our RD-Server, but I am not able to save the password in remmina - as soon as I close the connection, it gets wiped from the connection settings. When I reopen the connection I get prompted for the password again (username and domain are saved). Here I can opt to save the password again, but it has no effect.

Since the password is never saved, I could not view the *.remmina file with a stored password in my favourite text editor, to see if it is encrypted. From what I know of the developers here, I would suggest it is encrypted, but I have to be sure on that one, so sorry for asking this maybe stupid question.

If only the password is encrypted, is there a way to encrypt the whole *.remmina file, so I can distribute it without giving away any credentials? Maybe as an enhancement there could be a flag saying "encrypted credentials", so the credentials are used to connect, but never displayed to the user, and somehow encrypted in the *.remmina-file?

Thanks so long, and a happy new year to everyone!

**Comment by CS-JS** [comment]
Hi @ic3d - I can confirm passwords are saved now for my test connections, but in the *.remmina-file all I can see is the entry "password=."
When I copy this file to another pc, I don't think, the other pc will connect without asking for a password again. I cannot test it right away, since I am not in the office until tomorrow, but if this works, the issue can be closed :-)

**Comment by antenore** [comment]
@CS-JS The point means that the password is saved "externally" in the password manager, so you should export not only the remmina profiles but also the password storage used by libsecret.

Hope it helps!

From our point of view the issue is closed.
