### ISSUE TITLE
dynamic-resolution regression in NX (rc24 -> rc26)

### ISSUE THREAD

**Issue by lrenaud** [FreeRDP/Remmina#1426]
Please give us some details about the systems you are using:
* Client: Ubuntu 17.10
* Remmina version: 1.2.0-rcgit-26 (git rcgit-26) (via remmina-next ppa)
* Desktop environment: Mate
* Connecting to: CentOS 6.9
* Connecting via: NX

In either rcgit-25 or rcgit-26 a regression was introduced that prevents resolution changes (as far as I can tell) of NX sessions. The only resolution I'm able to get for the remote session is my current display resolution.

When the session is opened, the buttons in the toolbar that would normally enable scaling or dynamic resolution behavior are both visible but disabled (i.e. "grayed out"). To ensure this isn't related to legacy code creating .remmina files in my home directory, I've both inspected an existing .remmina file to ensure no lines related to width, height, or resolution remain, as well as created a new connection via the GUI. In both cases the bug persists.

Enabling the debug log shows the following messages. I can provide the full log if desired.
```
[NX] NX> 148 Server capacity: not reached for user: lrenaud
[NX] NX> 105 
[NX] startsession --encryption="1" --session="<REMOVED>" --link="modem" --cache="16M" --type="unix-gnome" --backingstore="1" --clipboard="both" --client="linux" --geometry="1920x1080" --media="0" --agent_server="" --images="64M" agent_password="******"1" --screeninfo="0x0x24+render" --keyboard="apple/us" --agent_user="" 
[NX] 
[NX] NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
```

I'm not familiar with the details of the code base, but it looks like this regression is related to the changes in #1360. Possibly due to the incidental removal of the `remmina_plugin_nx_service->protocol_plugin_set_expand(gp, TRUE);` call.

**Comment by giox069** [comment]
Hi @lrenaud. Yes, I can add `remmina_plugin_nx_service->protocol_plugin_set_expand(gp, TRUE);` and the scaler icon should be enabled again (I hope). But I have no ways to test it.
How did you setup NX? Via nomachine.com packages?

**Comment by lrenaud** [comment]
If you push it to a branch somewhere I can build and give things a test in my local environment.

The machines I'm connecting to are indeed running a stock NoMachine NX server. It might be a slightly older release as a license though.

**Comment by giox069** [comment]
Ok, [branch issue_1426](https://github.com/FreeRDP/Remmina/tree/issue_1426) is ready.
I tried to install nomachine.com, but it does not work as server for remmina. I think the remmina plugin only works with opensource NX protocols up to version 3.0, and not 4.0. And unfortunately the FreeNX project is dead.
There are also other problems: the remmina NX plugin is strongly based on GtkSocket and other Xorg features which are missing from Wayland. I don't think it will never survive in wayland environment.

**Comment by lrenaud** [comment]
I know it's an older NoMachine's implementation.
`[NX] HELLO NXSERVER - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)`

Unfortunately the change did not correct the issue. I suspect more is at play here though, as the resolution is always my full display resolution rather than the window resolution as I would expect to be forced otherwise.

**Comment by giox069** [comment]
Have you set a custom resolution in the profile editor (see image)?
![immagine](https://user-images.githubusercontent.com/5477803/34581624-71b6bf6a-f191-11e7-8c5b-afaf37211848.png)
I suspect "Use window size" is not the correct meaning for that option...
In the meanwhile I will try to find a NX 3.x server if possible.

**Comment by lrenaud** [comment]
Forcing that resolution manually changes the behavior in a very strange way.

Firstly, the resolution specified as the custom resolution becomes the minimum allowable resolution, not the set resolution. The dynamic resizing behavior works if one connects with a custom resolution, but as indicated before the resolution will not resize either width or height to be smaller than the custom resolution. In spite of the resizing working, the options in the toolbar indicating it's presence remain disabled as they were before. Furthermore, minimizing the host display window will resize the workspace to this minimum resolution failing to restore the window resolution until the de-minimized window is manually resized.

Changing the setting back to "Use Window size" restores the previously undesired behavior of passing the current display resolution rather than the window size.

Ultimately this changes restores the core functionality I need, but it's clear that the behavior is unlikely to match user expectations in a few regards given the current GUI preference descriptions, and changed behavior.

**Comment by ic3d** [comment]
Hi @lrenaud we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by lrenaud** [comment]
Yes and no. The dynamic resizing works again, but it is most certainly not working as intended.

Dynamic resizing works, but the configuration dialog does not reflect the behavior users observe (rc29). When using the "Use Window Size" for "Resoltuion" as in the original test recommendation, the window size is always ignored, dynamic resizing is disabled, and the resolution is set to the current display resolution.

When a specific size is selected (e.g. "Custom: 1024x768") the dynamic resizing behavior is enabled, and the window size is used to select the resolution. In all settings the session menu button for "Toggle dynamic resolution update" is disabled.

**Comment by verfriemelt-dot-org** [comment]
with or without set custom resolution, the dynamic resolution feature is broken in the current version of debian sid

	easteregg@x250 ~ $ remmina -V
	StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
	Remmina - 1.2.0-rcgit-29 (git rcgit-29)
	NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
	RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev (git n/a)
	RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev (git n/a)
	RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev (git n/a)
	SFTP                Protocol        SFTP - Secure File Transfer                                     1.2.0-rcgit-29
	SSH                 Protocol        SSH - Secure Shell                                              1.2.0-rcgit-29
	VNC                 Protocol        VNC - Virtual Network Computing                                 1.2.0-rcgit-29
	glibsecret          Secret          GNOME libsecret                                                 1.2.0-rcgit-29

**Comment by verfriemelt-dot-org** [comment]
fixed in the rc30

```
$ apt-cache policy remmina
remmina:
  Installed: 1.2.30+dfsg-1
  Candidate: 1.2.30+dfsg-1
  Version table:
 *** 1.2.30+dfsg-1 200
        200 http://ftp.de.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @giox069 @ic3d @lrenaud @verfriemelt-dot-org
