### ISSUE TITLE
SSH password authentication failed Wrong state during pending SSH call

### ISSUE THREAD

**Issue by gecedwards** [FreeRDP/Remmina#1428]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 14.04.5 LTS
* Remmina version (remmina --version): 1.2.0-rcgit-26 (git v1.2.0-rcgit.26)
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Ubuntu 14.04.5 LTS
* Connecting via (RDP, VNC, ...): VNC SSH tunneling
* RDP issues only, freerdp version (xfreerdp --version): 

remmina was working perfectly until December 28th when my desktop pulled automatically the last update. since then im getting the following error:
SSH password authentication failed Wrong state during pending SSH call

that i happening with VNC-SSH tunneling and SSH on the same server, the rest of my servers (Ubuntu 14 & 16) runs fine
the logs are clean except for the target server which shows connexions attempts failures

[remmina]
keymap=
ssh_auth=0
quality=9
disableencryption=0
ssh_charset=
ssh_privatekey=
colordepth=8
hscale=0
group=
password=.
name=Downloads
ssh_loopback=0
viewonly=0
ssh_username=xxx
ssh_server=
disableclipboard=0
protocol=VNC
vscale=0
ssh_enabled=1
username=xxx
showcursor=0
disableserverinput=0
server=192.168.4.3:5901
aspectscale=0
viewmode=1
window_maximize=0
window_height=907
window_width=1098
scaler_expand=1
scale=1
keyboard_grab=0
proxy=
disablepasswordstoring=0
precommand=
postcommand=
ssh_password=.
dynamic_resolution_height=0
dynamic_resolution_width=0
resolution_height=1200
resolution_width=1600

Jan  2 17:23:43 localhost sshd[8459]: error: maximum authentication attempts exceeded for xxx from 192.168.1.10 port 41931 ssh2 [preauth]
Jan  2 17:23:43 localhost sshd[8459]: Disconnecting: Too many authentication failures for xxx [preauth]
Jan  2 17:29:58 localhost sshd[8495]: error: maximum authentication attempts exceeded for xxx from 192.168.1.10 port 42027 ssh2 [preauth]
Jan  2 17:29:58 localhost sshd[8495]: Disconnecting: Too many authentication failures for xxx [preauth]
Jan  2 17:30:27 localhost sshd[8543]: error: maximum authentication attempts exceeded for xxx from 192.168.1.10 port 42028 ssh2 [preauth]

**Comment by antenore** [comment]
Does it works with ssh from the command line?
I see your password it's saved in the gnome keyring, can you check with seahorse that the password is correct?
If you have root rights on the server, it would be a good idea to start sshd in debug more to see what happens.

**Comment by gecedwards** [comment]
yes, it works from the command line.
the passwords have been reseted several times 

following the ssh -d
debug1: sshd version OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: private host key: #0 type 1 RSA
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type DSA
debug1: private host key: #1 type 2 DSA
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type ECDSA
debug1: private host key: #2 type 3 ECDSA
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
socket: Address family not supported by protocol
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 4 out 4 newsock 4 pipe -1 sock 7
debug1: inetd sockets after dupping: 3, 3
Connection from 192.168.1.10 port 44392 on 192.168.2.4 port 22
debug1: Client protocol version 2.0; client software version libssh_0.7.5
debug1: no match: libssh_0.7.5
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1
debug1: permanently_set_uid: 104/65534 [preauth]
debug1: list_hostkey_types: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: client->server aes256-ctr hmac-sha2-256 none [preauth]
debug1: kex: server->client aes256-ctr hmac-sha2-256 none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user tonto service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: PAM: initializing for "tonto"
debug1: PAM: setting PAM_RHOST to "192.168.1.10"
debug1: PAM: setting PAM_TTY to "ssh"
debug1: userauth-request for user tonto service ssh-connection method keyboard-interactive [preauth]
debug1: attempt 1 failures 0 [preauth]
maximum authentication attempts exceeded for tonto from 192.168.1.10 port 44392 ssh2 [preauth]
Disconnecting: Too many authentication failures for tonto [preauth]
debug1: do_cleanup [preauth]
debug1: monitor_read_log: child log fd closed
debug1: do_cleanup
debug1: PAM: cleanup
debug1: Killing privsep child 16756
debug1: audit_event: unhandled event 12


thank you for your help

Regards

**Comment by gecedwards** [comment]
Antenore,

Did you forget my case? are you planning a patch in the future?

thank  you for all your help

Regards

**Comment by antenore** [comment]
No, sorry, I'm quite busy with my job, therefore I have a really limited time to work on Remmina.
As a workaround till I will work on this, could be to use the prior commands in Remmina to lunch the tunnel before to connect.
Would you mind trying? The pre and post command are just below the name and group fields.

**Comment by antenore** [comment]
I'm afraid is linked to the libssh version available on ubuntu 14 and the Algorithms used to connect the ssh server.

I'd also need the Remmina client logs. In the main preferences set the SSH log to the highest level (SSH_LOG_FUNCTIONS) and than open the Remmina Debug window before to connect to the server giving you troubles.

The modifications I've put in place at the end of December are all around the KEX and MAC algos.

If the pre command is an option for you, I think it's the best workaround you can use.

Otherwise a solution is to rollback the Remmina version.

Did you try it? Please let me know.

**Comment by gecedwards** [comment]
Thank you very much for your help.
Yes i tried but didn’t work and i didn’t want to annoying you with the issue as it looks like Im the only one. i rolled back the app before asking for your help . 
so I’ve been working the  SSH tunnel disabled.

thank you very much again, you can see the logs below and i will continue looking for the solution.

StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:24505): Gtk-WARNING **: /build/gtk+3.0-Poe67P/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(remmina:24505): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(remmina:24505): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed

(remmina:24505): GLib-GIO-CRITICAL **: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

[glibsecret] found password for file /home/momo/.remmina/1514995756856.remmina
[glibsecret] found password for file /home/momo/.remmina/1480368029522.remmina
[glibsecret] found password for file /home/momo/.remmina/1514995756856.remmina
[glibsecret] found password for file /home/momo/.remmina/1480368029522.remmina
[glibsecret] found password for file /home/momo/.remmina/1514995756856.remmina
[glibsecret] found password for file /home/momo/.remmina/1480368029522.remmina
[SSH] SSH_OPTIONS_IDENTITY has been set to: /home/momo/.ssh/id_rsa
[SSH] SSH_OPTIONS_KEY_EXCHANGE does not have a valid value: (null)
[SSH] SSH_OPTIONS_CIPHERS_C_S does not have a valid value: (null)
[SSH] SSH_OPTIONS_HOSTKEYS does not have a valid value: (null)
[SSH] SSH_OPTIONS_PROXYCOMMAND does not have a valid value: (null)
[SSH] SSH_OPTIONS_STRICTHOSTKEYCHECK has been set to: 0
[SSH] ssh_config_parse_file: Reading configuration data from /etc/ssh/ssh_config
[SSH] ssh_connect: libssh 0.7.5 (c) 2003-2014 Aris Adamantiadis, Andreas Schneider, and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[SSH] getai: host 192.168.2.4 matches an IP address
[SSH] ssh_socket_connect: Nonblocking connection socket: 19
[SSH] ssh_connect: Socket connecting, now waiting for the callbacks to work
[SSH] ssh_connect: Actual timeout : 10000
[SSH] ssh_socket_pollcallback: Received POLLOUT in connecting state
[SSH] socket_callback_connected: Socket connection callback: 1 (0)
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] callback_receive_banner: Received banner: SSH-2.0-OpenSSH_6.6.1p1
[SSH] ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_6.6.1p1
[SSH] ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_6.6.1p1
[SSH] ssh_analyze_banner: We are talking to an OpenSSH client version: 6.6 (60600)
[SSH] ssh_packet_socket_callback: packet: read type 20 [len=1628,padding=6,comp=1621,payload=1621]
[SSH] ssh_packet_process: Dispatching handler for packet type 20
[SSH] ssh_list_kex: kex algos: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SSH] ssh_list_kex: server host key algo: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256
[SSH] ssh_list_kex: encryption client->server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[SSH] ssh_list_kex: encryption server->client: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[SSH] ssh_list_kex: mac algo client->server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[SSH] ssh_list_kex: mac algo server->client: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[SSH] ssh_list_kex: compression algo client->server: none,zlib@openssh.com
[SSH] ssh_list_kex: compression algo server->client: none,zlib@openssh.com
[SSH] ssh_list_kex: languages client->server: 
[SSH] ssh_list_kex: languages server->client: 
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=1
[SSH] ssh_knownhosts_algorithms: server 192.168.2.4:22 has ecdsa-sha2-nistp256 in known_hosts
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] ssh_client_select_hostkeys: Changing host key method to "ecdsa-sha2-nistp256"
[SSH] ssh_list_kex: kex algos: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SSH] ssh_list_kex: server host key algo: ecdsa-sha2-nistp256
[SSH] ssh_list_kex: encryption client->server: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc
[SSH] ssh_list_kex: encryption server->client: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc
[SSH] ssh_list_kex: mac algo client->server: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: mac algo server->client: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: compression algo client->server: none
[SSH] ssh_list_kex: compression algo server->client: none
[SSH] ssh_list_kex: languages client->server: 
[SSH] ssh_list_kex: languages server->client: 
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=444,padding=4,comp=439,payload=439]
[SSH] packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] ssh_packet_socket_callback: packet: read type 31 [len=260,padding=11,comp=248,payload=248]
[SSH] ssh_packet_process: Dispatching handler for packet type 31
[SSH] ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
[SSH] ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
[SSH] ssh_packet_socket_callback: Processing 16 bytes left in socket buffer
[SSH] ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
[SSH] ssh_packet_process: Dispatching handler for packet type 21
[SSH] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
[SSH] crypt_set_algorithms2: Set output algorithm to aes256-ctr
[SSH] crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
[SSH] crypt_set_algorithms2: Set input algorithm to aes256-ctr
[SSH] crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
[SSH] ssh_pki_signature_verify_blob: Going to verify a ecdsa-sha2-nistp256 type signature
[SSH] ssh_packet_newkeys: Signature verified and valid
[SSH] ssh_connect: current state : 7
[SSH] packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
[SSH] ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
[SSH] ssh_packet_process: Dispatching handler for packet type 6
[SSH] ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=60,padding=18,comp=41,payload=41]
[SSH] ssh_packet_socket_callback: packet: read type 51 [len=44,padding=19,comp=24,payload=24]
[SSH] ssh_packet_process: Dispatching handler for packet type 51
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=1
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=0
[SSH] match_hashed_host: Matching a hashed host: [192.168.2.4]:22 match=0
[SSH] match_hashed_host: Matching a hashed host: 192.168.2.4 match=1
[SSH] ssh_userauth_kbdint_init: Sending keyboard-interactive init request
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=76,padding=10,comp=65,payload=65]
[SSH] ssh_packet_socket_callback: packet: read type 1 [len=76,padding=15,comp=60,payload=60]
[SSH] ssh_packet_process: Dispatching handler for packet type 1
[SSH] ssh_packet_disconnect_callback: Received SSH_MSG_DISCONNECT 2:Too many authentication failures for adminloads
[SSH] ssh_packet_disconnect_callback: Received SSH_MSG_DISCONNECT: 2:Too many authentication failures for adminloads
[SSH] ssh_userauth_password: Wrong state during pending SSH call

**Comment by cmadera** [comment]
Hi, I have the same issue on Ubuntu 17.10, you can reproduce the problem using the live version.

**Comment by antenore** [comment]
Can you share your Remmina profile please?

**Comment by antenore** [comment]
Can you share your Remmina profile please?

**Comment by gecedwards** [comment]
Could it be the Ubuntu bits version? mine is 32 bits and it is giving me problems with others software as well.

**Comment by antenore** [comment]
It's hard to say @gecedwards , I cannot reproduce this, that's why I've asked to have a sample remmina profile file so that I can try to put in place a testing environment.

What I need:

1. A remmina profile file that cause issues (found under ```~/.local/share/remmina``` ).
2. VNC server name and version.
3. How your ssh is configured (any ssh running agent, using provyte/public keys, simple password auth, etc).
4. Client and server OS version and arch (32/64 bit).
4. Whatever additional information you may provide, even if you think it's not useful. 

Regarding the point 1, be sure it won't contain any sensible data (users, IP, etc, make it anonymous). 

Thanks

**Comment by cmadera** [comment]
Hello, no specific configuration, just downloaded the ubuntu 17.10 64bit version which already have the Remmina installed and I used it in the live version and in VM. When I try to connect to any ssh server I can`t do it.

1) no remmina profile created on this path
2) I`m not having problem with VNC, it is working.
3) ssh connection with simple password auth.
4) Ubuntu 17.10 64


best regard

**Comment by antenore** [comment]
@cmadera you have a different issue than the one reported here. Please, upgrade to Remmina last version from the PPA following the wiki and let me know.

**Comment by cmadera** [comment]
Thank you! I installed the Ubuntu 17.10 64bit then upgrade to Remmina last version from PPA following the wiki then everything is working perfect. The conclusion is the Remmina in the live version is not working.

Great job!

Best regards

**Comment by gecedwards** [comment]
After Carlos comments I wiresharked my both systems, I noticed that Openssh keeps using GSSAPI authentication even if it is disable.

so....

disable "GSSAPIAuthentication no" on both server and client "ssh_config & sshd_config"
increase to 6 the number of attemps on sshd_config "MaxAuthTries 6"
create a config file under .ssh and add "GSSAPIAuthentication no" under Host xxxx

You are done the tunnel is up and running again

thank you antenore for all your help

Regards.
