### ISSUE TITLE
display off-center upon connection to RDP hosts

### ISSUE THREAD

**Issue by benkohler** [FreeRDP/Remmina#143]
Upon connecting to an RDP host, the display is off-center.  For me it basically displays the bottom-right quadrant of the remote host's screen, placed in the upper left quadrant of the remmina window. 

Resizing the window will make things snap back to normal, but this is required at EVERY reconnection.

This is described in an issue at the old bug tracker:
https://sourceforge.net/tracker/?func=detail&aid=3527523&group_id=278330&atid=1181674

**Comment by muflone** [comment]
Does this issue still exist? It should be fixed some months ago.
If the issue still exists please reopen it.
