### ISSUE TITLE
Remmina does not save password

### ISSUE THREAD

**Issue by markreg** [FreeRDP/Remmina#1440]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Raspbian 9.1
* Remmina version (remmina --version): Remmina - Version 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): PIXEL
* Connecting to (OS and version): Windows 10 x64
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 

Remmina does not save the password. It opens the username/password prompt every time when connecting to an RDP session.

Previously, it did save the username/password and I was able to script automatic connection to the RDP session after login, however now it gets stuck at the username/password prompt.

**Comment by antenore** [comment]
Did you install gnome-keyring?

**Comment by giox069** [comment]
As suggested by antenore, install the package gnome-keyring to store encrypted password. At the 1st use of the keyring, you will be asked to create your keyring password. Unfortunately the desktop pixel by default does not unlock the keyring at autologon, so you will be asked for the password every time you use remmina for the first time on a desktop session (i.e: after every reboot).
As a less secure alternative, you can remove the "remmina-plugin-secret" plugin (formerly called remmina-plugin-gnome): without the remmina secret plugin, remmina will store is passwords in an obfuscated way (not encrypted) inside the profile files. No password to unlock keyring will be asked.

**Comment by giox069** [comment]
Can I close this issue? Is this solved?

**Comment by monomon** [comment]
I am still experiencing this in Ubuntu 17.04
Remmina is installed through Snap - version 1.2.0-rcgit-26 (git 08984ca)

**Comment by antenore** [comment]
@monomon 

With snap you have to enable the keyring
```
sudo snap connect remmina:password-manager-service :password-manager-service # gnome-keyring
```

**Comment by monomon** [comment]
oh snap! thanks :) first-time snap user

**Comment by markreg** [comment]
I ended up removing `remmina-plugin-gnome` since both the target and host machines are in the same private network and the target machines are set to auto-lock after a couple mins of inactivity.

Automatic login with remmina works well now.
