### ISSUE TITLE
[enhancement]SSH: Copy on select

### ISSUE THREAD

**Issue by Honghe** [FreeRDP/Remmina#1448]
Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 16.04.3
* Remmina version (remmina --version):  1.2.0-rcgit-26
* Desktop environment (GNOME, Unity, KDE, ..):  GNOME
* Connecting to (OS and version):  Linux
* Connecting via (RDP, VNC, ...): SSH
* RDP issues only, freerdp version (xfreerdp --version):  none

Request an enhancement: SSH connection Copy on Select, like SecureCRT.
Thanks.

**Comment by antenore** [comment]
I don't use securecrt, can you please explain how does it works?

In Linux there are 3 clipboard, one is the selection. If you select some text you can paste it elsewhere pushing the third button

**Comment by Honghe** [comment]
@antenore I'm sorry to have ignored the selection clipboard. And in SecureCRT, If you select some text you can paste it elsewhere via CTRL+C, can we implement it in Linux?

**Comment by antenore** [comment]
Yes we could but it may lead to several issues, even if we set it as a global option, than for sure we will have some users  that will have problems with some particular applications.

I prefer to be standard and follow the specifications as much as possible.

If you want you can change the behaviour of the clipboard at a system level , but this is "linux administration" domain and not the Remmina land, so you have to research how to change the clipboard configuration in your specific environment (Xorg, wayland, Gnome, etc).

Sorry for this but we won't change it till it won't be a must have in the Remmina community.

**Comment by Honghe** [comment]
Thanks!

> I prefer to be standard and follow the specifications as much as possible.
Can you forward the link of the standard specification, I have to read it :D

**Comment by antenore** [comment]
freedesktop.org/wiki/Specifications/ClipboardsWiki/

developer.gnome.org/gtk3/stable/gtk3-Clipboards.html
