### ISSUE TITLE
Support for AVC 444 mode

### ISSUE THREAD

**Issue by lavor777** [FreeRDP/Remmina#1449]
* Connecting to Windows 10
* Connecting via RDP
* RDP issues only

**Comment by lavor777** [comment]
With a new Windows 10 update, it is impossible to connect to it with Remmina(ERRINFO_GRAPHICS_MODE_NOT_SUPPORTED (0x0000112D):
The graphics mode requested by the client is not supported by the server.)

**Comment by antenore** [comment]
Which version of Remmina and FreeRDP do you have?

**Comment by lavor777** [comment]
Remmina: 1.1.2-3ubuntu1
freerdpx11: 1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2
RDP to: Windows 10 Insider Preview Build 17074

**Comment by giox069** [comment]
You are using a very old version of remmina. Please upgrade it to a newer version, instructions are on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). If you are using Ubuntu, the preferred method to get remmina, as explained on our Wiki, is to use the remmina-next PPA.

**Comment by giox069** [comment]
Same as issue #1456 whe should add AVC444 support to remmina.

**Comment by giox069** [comment]
I just added support for AVC444 in the next branch. It will be available to the public with the next release (1.2.0-rcgit.27). Read issue #1456 for further comments.
I'm closing this issue. If you find problems, just open another one.
