### ISSUE TITLE
Artifacts and Glitches with PeopleSoft App Designer

### ISSUE THREAD

**Issue by digitaleagle** [FreeRDP/Remmina#1452]
Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 17.10
* Remmina version (remmina --version): 1.2.0-rcgit-26 (git rcgit-26)
* Desktop environment (GNOME, Unity, KDE, ..): Gnome
* Connecting to (OS and version): Windows Server 2008 R2 Standard
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 1.1.0-beta1 (git n/a)

I get artifacts and trouble drawing child windows when running PeopleSoft Application Designer on the remote desktop.  It seems like it just started happening not too long along ago.

For some reason, it is only this application that I know of.  SQL Server Studio, File Exporer all work as expected.

I did try through xfreerdp.  I had to install it first (sudo apt-get install  xfreerdp-x11).  Using xfreerdp, App Designer works fine.  I don't know what the difference, and I'm not sure what else to try to troubleshoot.

I posted a screenshot of what it looks like on my blog because I didn't see a way to do it here.
[Blog Post](https://linuxsagas.digitaleagle.net/2018/01/22/remmina-issues-with-peoplesoft-application-designer/)

**Comment by giox069** [comment]
If you are using our remmina-next PPA, can you just try to upgrade your system and get newer freerdp packags? We have just upgrade freerdp library packages, and I think your problem was libfreerdp related. Thank you.
