### ISSUE TITLE
'remmina -c' accepting only configs with .remmina extension.

### ISSUE THREAD

**Issue by TJokiel** [FreeRDP/Remmina#1454]
Please give us some details about the systems you are using:
* Client (OS name and version): Gentoo stable
* Remmina version (remmina --version): Remmina - Version 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): Openbox
* Connecting to (OS and version): any
* Connecting via (RDP, VNC, ...): any
* RDP issues only, freerdp version (xfreerdp --version): 

Hi Team,

Any chance 'remmina -c' would accept configs no matter of its extension? Currently it displays 'File not found' message if i run 'remmina -c file.txt'.
It accepts only: 'remmina -c file.remmina'.

Reason i'm asking is that some users need to host their configs on various http servers (they are downloaded later on a local disk) and due to restrictions some servers needs to be reconfigured to be able to host files with .remmina extension.

I was hoping remmina application could accept .txt files as the configs.

Thank you for your consideration.

**Comment by antenore** [comment]
I think it's easily feasible.
I'll take a look as soon as I'll time. In the meantime why don't you write a shell wrapper or an alias that rename that file before to call remmina ?

**Comment by TJokiel** [comment]
Thank you for quick response.

Yes - i'm going to instruct them to use 'wget http://domain.com/files/config.txt -O config.remmina; remmina -c config.remmina' for now.

Whenever it would be implemented would be perfect for us.

Thank you.

**Comment by antenore** [comment]
Writing down some thoughts about this...

1. Remmina write the profiles in the XDG_USER_DATA/remmina directory.
1.1. We should add an option to allow the user to specify a different folder.
1.2. What happens to the profiles in the previous folder (migrate/leave there)? 
2. As per #1293 the full path to a remmina profile should be optional.
3. We should add as well an option to specify the profile name instead of the file path.

**Comment by antenore** [comment]
I've successfully added the support for any file extensions, remmina will only validate the file contents.
I've other enhancement to put in place and then I'll merge into 'next'.
You'll have it in the next release

**Comment by TJokiel** [comment]
Thanks a ton!
