### ISSUE TITLE
Remmina: black flash and connection closed (cannot connect to Windows 10 17074.1002 with Remmina 1.2.0-rcgit-26 (git rcgit-26))

### ISSUE THREAD

**Issue by ZaneCEO** [FreeRDP/Remmina#1456]
I'm long-time user of Remmina on a Ubuntu 16.04 PC. I use Remmina to connect via RDP to a Win10 PC. It used to work very well.

Since the last upgrade to [Windows 10 17074.1002](https://blogs.windows.com/windowsexperience/2018/01/11/announcing-windows-10-insider-preview-build-17074-pc/) (slow ring insider preview), I cannot connect anymore. As soon as I establish the connection (I open the connection and insert the password when asked), the Remmina window flashes "black" for an instant and then closes.

The client PC is a standard configuration with Ubuntu 16.04 and Unity. I'm using Remmina own PPA.

I just updated via `sudo apt-get install remmina freerdp -y` (I cannot update the whole PC at the moment). This are the relevant versions:

```
remmina is already the newest version (1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da~ubuntu16.04.1).
freerdp-x11 is already the newest version (2.0.0~git201801222200-0+remmina201801230403.rbdcb1a3.d9be5820~ubuntu16.04.1).
```
Can I see a connection log somehow? I tried `tail -f /var/log/syslog` but I got nothing there.

**Comment by giox069** [comment]
@ZaneCEO thank you for reporting. Currently we do not test on not-yet released windows :(
Some suggestions:

1. After every libfreerdp upgrade, reboot the PC.
2. Execute remmina from a terminal. You will get interesting output from libfreerdp when connecting.
3. Also try to connect to the same host with xfreerdp: `xfreerdp /v:hostname /u:username /d:domain` and let us know.

**Comment by giox069** [comment]
Could it be related to this issue on GFX https://github.com/FreeRDP/FreeRDP/issues/4341 ?

**Comment by ZaneCEO** [comment]
@giox069 IThanks for your reply! I can totally understand you guys not testing on pre-releases! Just keep an eye out on it: when we are this far in a new Win 10 branch development, the change could very much end up in the next RTM.

I rebooted the PC (both client and host, just to be sure).

I tired to connect via terminal and I got some output:

```
[10:22:57:713] [8566:8567] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[10:23:06:161] [8566:8567] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[10:23:06:161] [8566:8567] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[10:23:06:176] [8566:8567] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[10:23:06:185] [8566:8567] [INFO][com.freerdp.core] - ERRINFO_GRAPHICS_MODE_NOT_SUPPORTED (0x0000112D):The graphics mode requested by the client is not supported by the server.
```
The last line seems very relevant to me! I then Googled it and found this: https://github.com/FreeRDP/FreeRDP/issues/4326#issuecomment-353563501 : I added the `/gfx:avc444` and booom, it works once again! So you're right, it's related to #4341

**One last question before I close the issue: how can i set `/gfx:avc444` via the Remmina GUI?**

**Comment by giox069** [comment]
I don't think it's possible now to set /gfx:avc444 now in remmina. Please leave this issue open, and we will investigate in the next days.

**Comment by giox069** [comment]
... and thank you for helping in discovering this.

**Comment by Jasin2069** [comment]
Have same issue and can get it to work with freerdp directly. When you look at adding /gfx:avc444 please also look at adding /gfx-h264:AVC444 which supports the latest.

**Comment by giox069** [comment]
I'm adding some GFX support to remmina. The code is currently in a separate branch (rdp_gfx_plus_fixes). If anyone can compile remmina from this branch and then let us known, we will be happy.

To enable GFX support (with avc444 or avc240), a libfreerdp2 compiled with h264 support is needed. And in a typical ubuntu environment, freerdp automatically enables its flag "WITH_FFMPEG" when it finds libavcodec-dev and libavutil-dev packages installed. So it's important to compile freerdp2 with libavcodec/libavutil installed in the system.

Then, after building freerdp and remmina, you can choose one of the new options on the **Color depth** dropdown:

![schermata da 2018-02-01 10-25-30](https://user-images.githubusercontent.com/5477803/35671897-014aa16c-073d-11e8-8c40-da40570d7703.png)

I did some tests playing a video from a remote windows 10 server: bandwidth in "32bpp" mode was 50 to 100Mbps. Bandwidth with avc444 drops to 2-4Mbps.

But there is a a drawback: remmina only uses CPU for decoding, currently we do not have GPU support. So you need a good CPU to playback a compressed video, and your CPU will be quite busy to decode an h264 video. On my quadcore AMD FX(tm)-4300 I can see one fully used core (100%).

If someone want/can develop GTK+ hardware acceleration code for our RDP plugin and maintain it, I will be happy to help him :)

@Jasin2069 it seems to me, reading the libfreerdp code, that /gfx:AVC444 and /gfx-h264:AVC444 does exactly the same thing, see [here](https://github.com/FreeRDP/FreeRDP/blob/master/client/common/cmdline.c#L2264). But I may be wrong...

**Comment by ZaneCEO** [comment]
Grazie Giovanni,
I'll try and have a look at it during the weekend

**Comment by ZaneCEO** [comment]
I needed it for work, so I tried it now.... and with the new `GFX AVC440` it works like a charm!!! It also "feels" **very fast**, even better than the old 256 colors I was using before to obtain max performance!!

I'll report back if I ever find additional bugs, but so far is a "go-merge-it!" for me! Thanks again!

**Comment by akallabeth** [comment]
@giox069 Just a hint, the modes are `AVC420` and `AVC444` (from the corresponding YUV formats) don't know where you got he  `AVC440` and `AVC240` from (or is it just a typo?)

**Comment by giox069** [comment]
@akallabeth thank you very much! It's a typo, a double typo :( I will fix it shortly (and merge the rdp_gfx_plus_fixes branch too).
Thank you again.

**Comment by lavor777** [comment]
Guys, you are incredible supermans. It works flawless now!) Thank you.
