### ISSUE TITLE
drive-client not copied/loaded properly

### ISSUE THREAD

**Issue by PhilippHomann** [FreeRDP/Remmina#147]
Hi,

I've build FreeRDP and Remmina from newest git on Debian Wheezy.
FreeRDP:
$ cmake .
$ make
$ sudo make install
Remmina (with patches https://github.com/FreeRDP/Remmina/pull/145#issuecomment-12875528 & https://github.com/zeha/Remmina/commit/728d4372960757045dea32d23fa51e698bb1eb65)
$ cmake . -DCMAKE_INSTALL_PREFIX=/usr -DWITH_APPINDICATOR=OFF
$ make
$ sudo make install

I started remmina, enabled drive redirection for / and connected to the server.
The drive does not show up in windows and shell shows:
Loading device service drive (static)
LoadLibraryA: /usr/local/lib/x86_64-linux-gnu/freerdp/drive-client.so: cannot open shared object file: No such file or directory

Unfortunately there is no drive-client.so in FreeRDP. There is only a static library of drive-client (channels/drive/client/drive-client.a).

With xfreerdp /a:drive,root, /v:host it works without any problems!

Thanks for help

**Comment by antenore** [comment]
Do you still have the issue with the last Remmina version?

**Comment by PhilippHomann** [comment]
I guess this one could be closed.

2015-06-25 23:30 GMT+02:00 Antenore Gatta <notifications@github.com>:

**Comment by antenore** [comment]
Thanks @PhilippHomann
