### ISSUE TITLE
Can't build version 1.2.0-rcgit27 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/Remmina#1476]
Thanks for providing a new version of remmina! 
Unfortunately 1.2.0-rcgit27 can not be built on Tumbleweed. I guess it's related to a missing -I/usr/include/wayland when building the new remmina_stats_sender.c. 
The wayland-devel package is installed. -I/usr/include/wayland is set for "remmina-plugin-spice", which builds nicely.

This is the build log. You can see a full log via the web-interface on https://build.opensuse.org/package/show/home:weberho:branches:X11:RemoteDesktop/remmina

[   11s] [ 98%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_stats_sender.c.o
[   11s] cd /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/build/remmina && /usr/bin/cc -DHAVE_LIBAPPINDICATOR -DHAVE_LIBAVAHI_CLIENT -DHAVE_LIBAVAHI_UI -DHAVE_LIBGCRYPT -DHAVE_LIBSSH -DHAVE_LIBVTE -DWITH_MANPAGES -I/home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/. -I/home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/include -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/vte-2.91 -I/usr/include/libappindicator3-0.1/libappindicator -I/usr/include/json-glib-1.0 -I/usr/include/libsoup-2.4  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -O2 -g -DNDEBUG   -o CMakeFiles/remmina.dir/src/remmina_stats_sender.c.o   -c /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/src/remmina_stats_sender.c
[   11s] /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/src/remmina_connection_window.c: In function 'remmina_connection_window_go_fullscreen':
[   11s] /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/src/remmina_connection_window.c:3126:5: warning: 'gdk_screen_get_monitor_at_window' is deprecated: Use 'gdk_display_get_monitor_at_window' instead [-Wdeprecated-declarations]
[   11s]      (gdk_screen_get_default(), gtk_widget_get_window(GTK_WIDGET(cnnhld->cnnwin))
[   11s]      ^
[   11s] In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31:0,
[   11s]                  from /usr/include/gtk-3.0/gdk/gdk.h:32,
[   11s]                  from /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/src/remmina_connection_window.c:40:
[   11s] /usr/include/gtk-3.0/gdk/gdkscreen.h:91:15: note: declared here
[   11s]  gint          gdk_screen_get_monitor_at_window (GdkScreen *screen,
[   11s]                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   11s] In file included from /usr/include/gtk-3.0/gdk/gdkwayland.h:32:0,
[   11s]                  from /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/remmina/src/remmina_stats.c:143:
[   11s] /usr/include/gtk-3.0/gdk/wayland/gdkwaylanddevice.h:27:10: fatal error: wayland-client.h: No such file or directory
[   11s]  #include <wayland-client.h>
[   11s]           ^~~~~~~~~~~~~~~~~~
[   11s] compilation terminated.
[   11s] make[2]: *** [remmina/CMakeFiles/remmina.dir/build.make:978: remmina/CMakeFiles/remmina.dir/src/remmina_stats.c.o] Error 1
[   11s] make[2]: *** Waiting for unfinished jobs....
[   11s] [ 99%] Linking C shared module remmina-plugin-rdp.so
[   11s] cd /home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/build/remmina-plugins/rdp && /usr/bin/cmake -E cmake_link_script CMakeFiles/remmina-plugin-rdp.dir/link.txt --verbose=1
[   12s] /usr/bin/cc -fPIC -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -O2 -g -DNDEBUG -Wl,--as-needed -shared  -o remmina-plugin-rdp.so CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_event.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_file.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_settings.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_graphics.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_cliprdr.c.o CMakeFiles/remmina-plugin-rdp.dir/rdp_channels.c.o -lgtk-3 -lgdk-3 -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lpango-1.0 -lcairo -lgdk_pixbuf-2.0 -latk-1.0 -lpthread -lfreerdp2 -lfreerdp-client2 -lwinpr2 -lX11 -lXext 
[   12s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/build'
[   12s] [ 99%] Built target remmina-plugin-rdp
[   12s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/build'
[   12s] make[1]: *** [CMakeFiles/Makefile2:135: remmina/CMakeFiles/remmina.dir/all] Error 2
[   12s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/Remmina-1.2.0-rcgit.27/build'

**Comment by giox069** [comment]
Hi @weberhofer 
I did some improvements to FindGTK3, the commit is on the "next" branch. Can you compile with the latest next branch?

**Comment by weberhofer** [comment]
Thanks, @giox069! Commit 644cd140a387c7b5d3805b8af9554e241d5d2954 solves that issue. I have included the patch into my package for rcgit27.
