### ISSUE TITLE
Enabling "Minimize To Tray" blocks "open main window"

### ISSUE THREAD

**Issue by emrecio** [FreeRDP/Remmina#148]
I enable "Minimize To Tray" in the preferences.
I minimize the Window in KDE.
I right click on the system tray icon, and select "Open Main Window"
Nothing happens. The program, however is still running. 

The only change I did in my configuration to get it working was in my remmina.pref file and set it to this:
minimize_to_tray=false

**Comment by Hubbitus** [comment]
What versions of freerdp and remmina are you use? Is it actual now?

**Comment by NginUS** [comment]
I have this same issue running Remmina v. 0.9.99.1 in Linux Mint 17.3 KDE, with current updates as of 2016-4-17.

**Comment by antenore** [comment]
We don't support that version, it's really too old, follow our wiki on how to use the official PPA.

**Comment by ic3d** [comment]
I close this bug, because that Remmina version is out of date.
