### ISSUE TITLE
Dependency Error installing v1.2 on Debian Stretch

### ISSUE THREAD

**Issue by sai-mike** [FreeRDP/Remmina#1481]
Please give us some details about the systems you are using:
* Client (OS name and version): Debian GNU/Linux 9
* Remmina version (remmina --version): 1.2
* Desktop environment (GNOME, Unity, KDE, ..): Cinnamon

Installing using:
apt install -t stretch-backports remmina remmina-plugin-rdp remmina-plugin-gnome libfreerdp-plugins-standard

Error:
The following packages have unmet dependencies:
 remmina-plugin-gnome : Depends: remmina (= 1.2.0-rcgit.24-2~bpo9+1) but 1.2.0-rcgit.26+dfsg-1~bpo9+1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by giox069** [comment]
@sai-mike see issue #1473
Let us known if the solution reported in issue #1473 works.

**Comment by sai-mike** [comment]
Yes - replacing gnome with secret worked. Thanks.

**Comment by giox069** [comment]
Thank you @sai-mike. I updated the wiki too.
