### ISSUE TITLE
Enhancement - Variables for pre- and post-commands

### ISSUE THREAD

**Issue by AlexGluck** [FreeRDP/Remmina#1485]
Can you add "profile name" and "group name" as variables for commands. This can be use for us for find region of servers where we need connect vpn, before opened rdp.

**Comment by antenore** [comment]
Sure. I'm quite busy lately, but it'll be available for the next release and ASAP in the main branch (named next).

**Comment by AlexGluck** [comment]
Thanks, remmina the best rdp client for linux.

**Comment by AlexGluck** [comment]
Can you reopen issue?

**Comment by antenore** [comment]
I think you didn't close Remmina after the upgrade. Can you execute the following? 

```pkill remmina && remmina --version```
