### ISSUE TITLE
VNCI connection not working!

### ISSUE THREAD

**Issue by GFdevelop** [FreeRDP/Remmina#1502]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): ArchLinux lastest
* Remmina version (remmina --version): 1.2.0-rcgit-27 (git rcgit-27)
* Desktop environment (GNOME, Unity, KDE, ..): Budgie Desktop (GNOME based)
* Connecting to (OS and version): localhost
* Connecting via (RDP, VNC, ...): VNC
* RDP issues only, freerdp version (xfreerdp --version): 

I can't use plugin VNCI (Incoming connection), I have tried to connect from various software (vinagre, virt-manager, android VNC client...and Remmina) but I can't connect to Remmina VNCI, don't working with and without ssh tunnel, why?

I'm speak italian, I can explain better if you known italian...

**Comment by antenore** [comment]
Ciao,

You can contact me and Giovanni by email (see the about widget in Remmina).

**Comment by giox069** [comment]
@GFdevelop I'm closing this issue. We recently discovered that VNCI plugin is *NOT* a VNC server, but a VNC viewer in TCP listen mode (like `vncviewer -listen`) which allow TCP reverse connections.
So I think it's out of scope.
