### ISSUE TITLE
Remmina fails to connect to SSH server without compression since 1.2.0-rcgit-27 (git rcgit-27)

### ISSUE THREAD

**Issue by e-alfred** [FreeRDP/Remmina#1505]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

I upgraded and now I get the following error with Remmina 1.2.0-rcgit-27 (git rcgit-27):

```
[SSH] ssh_client_select_hostkeys: Changing host key method to "ssh-rsa"
[SSH] ssh_kex_select_methods: kex error : no match for method compression algo client->server: server [none], client [zlib@openssh.com,zlib]
```

Please give us some details about the systems you are using:
* Client (OS name and version): Debian 9
* Remmina version (remmina --version):  1.2.0-rcgit-27 (git rcgit-27)
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): LEDE 17.01 with Dropbear 2017
* Connecting via (RDP, VNC, ...): SSH

**Comment by antenore** [comment]
Can you please execute ```ssh -Q kex``` on both the client and the server?

**Comment by antenore** [comment]
Also, is that the hisghest level of debug available i Remmina?

**Comment by antenore** [comment]
The key is to find the kex supported by both client and server, maybe you can run an openssh session with ```-vvv``` and see what openssh will pick up. Than you can try selecting the same in the profile advanced tab. With an ssh tunnel it won't work, but you can still set a proxy command using openssh, again in the advanced tab.

**Comment by e-alfred** [comment]
These systems aren't running OpenSSH. They run the more lightweight Dropbear SSH server. It worked with all versions before 1.2.0-rcgit-27. It seems like Dropbear does not support ZLib compression, but Remmina now demands exactly that.

**Comment by antenore** [comment]
I don't have control on that part, it's something related with libssh.

Did you upgrade it?
I'll check also if I can do anything but I doubt.

**Comment by e-alfred** [comment]
Well, libssh is version 0.7.3-2:

```
dpkg -l|grep libssh
ii  libssh-4:amd64                                                   0.7.3-2                                     amd64        tiny C SSH library (OpenSSL flavor)
ii  libssh-gcrypt-4:amd64                                            0.7.3-2                                     amd64        tiny C SSH library (gcrypt flavor)
ii  libssh2-1:amd64                                                  1.7.0-1                                     amd64        SSH2 client-side library
```

**Comment by e-alfred** [comment]
I would say this change here is to blame: https://github.com/FreeRDP/Remmina/commit/5dc0358a0cdc733493e7c61df13fc3a925593722

` +	ssh_options_set(ssh->session, SSH_OPTIONS_COMPRESSION, "yes"); `

**Comment by antenore** [comment]
Ouch! You've got me! I've forgot about it! This is an option that must be set as optional...

I don't know if it will work, but it's worth trying.
In your ~/.ssh/config file you can try to set it to false. Libssh honour this file as openssh does, but not all the options are parsed. 
I cannot check the man page of ssh right now

**Comment by antenore** [comment]
>  Compression Specifies whether to use compression. The argument must be ``yes'' or ``no''. The default is ``no''.

**Comment by antenore** [comment]
Yes! It should work!

https://vovkos.github.io/doxyrest/samples/libssh/group_libssh_session.html#doxid-group-libssh-session-1ga82371e723260c7572ea061edecc2e9f1

**Comment by antenore** [comment]
Sorry...

**Comment by antenore** [comment]
I've added an optional setting in the remmina profile editor for the SSH protocol.
