### ISSUE TITLE
Copy and Paste stopped working in 1.2.0-rcgit-27

### ISSUE THREAD

**Issue by MarcoDotNet** [FreeRDP/Remmina#1518]
My Clipboard is broken since I updated to the latest version. Every time I copy something **in** the RDP session, it breaks. It breaks means I can copy things to the clipboard but not from the RDP session to my local host. And it's impossible to copy things from the local host clipboard to the RDP session. When I restart the Session it works again until I copy something in the RDP session.

My colleagues (3 ppl) have the same problem.

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 17.10
* Remmina version (remmina --version): 1.2.0-rcgit-27 (git rcgit-27)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): Windows Server 2016, Windows Server 2008 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): -

sudo apt list | grep remmina | grep installed
```
libfreerdp-client2/artful,now 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1 amd64 [installed,automatic]
libfreerdp2/artful,now 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1 amd64 [installed,automatic]
libwinpr2/artful,now 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1 amd64 [installed,automatic]
remmina/artful,now 1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 amd64 [installed]
remmina-common/artful,artful,now 1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 all [installed,automatic]
remmina-plugin-rdp/artful,now 1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 amd64 [installed]
remmina-plugin-secret/artful,now 1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 amd64 [installed]
remmina-plugin-vnc/artful,now 1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 amd64 [installed,automatic]

```

**Comment by havanahjoe** [comment]
I am having the same issue, but my problems started before the update to 1.2.0-rcgit-27 which just installed last week.

Please give us some details about the systems you are using:

Client (OS name and version): Fedora 27
Remmina version (remmina --version): 1.2.0-rcgit-27 (git rcgit-27)
Desktop environment (GNOME, Unity, KDE, ..): GNOME
Connecting to (OS and version): Windows Server 2008 R2
Connecting via (RDP, VNC, ...): RDP
RDP issues only, freerdp version (xfreerdp --version): FreeRDP version 2.0.0-dev (git 425942d)

**Comment by MarcoDotNet** [comment]
If you need more information to find the problem please let me know. That's a very annoying problem and it costs a lot of time to reconnect the sessions "hundred" times a day.

**Comment by giox069** [comment]
I will investigate it next week. In the meanwhile, next time it happens, can you check the windows server event viewer (both System and Application) if you can find something related?

**Comment by MarcoDotNet** [comment]
Thanks! I checked the event log but there is nothing related to my issue.

**Comment by MarcoDotNet** [comment]
I just found out if the clipboard is broken to locally the copying between two open RDP connections still works.

**Comment by antenore** [comment]
@MarcoDotNet what about xfreerdp from the command line? Does it works or do you have the same behaviour?

**Comment by MarcoDotNet** [comment]
My other colleagues works now with xfreerdp without any issues.

**Comment by MarcoDotNet** [comment]
I tried to follow the instructions (https://github.com/FreeRDP/Remmina/wiki/Testing-under-Ubuntu-with-the-remmina-next-daily-PPA) to switch to the daily build but I got an error:

> The following packages have unmet dependencies:
>  remmina-plugin-gnome : Depends: remmina (= 1.2.0-rcgit-24-0~remmina201710260247.rd9156ca.ddd444db~ubuntu17.10.1) but 1.2.0-rcgit-28-0~remmina201804042311.r19bbe44.d41791e1~ubuntu17.10.1 is to be installed
> E: Unable to correct problems, you have held broken packages.

Any ideas? I also tried it without the gnome plugin but my ssh tunnels are not working.

**Comment by antenore** [comment]
@MarcoDotNet did you purge the old remmina packages?

```
sudo apt-get install ppa-purge
sudo ppa-purge ppa:remmina-ppa-team/remmina-next
```

**Comment by antenore** [comment]
You missed at least one step, because it's still taking old packages

```sh
sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next-daily
sudo apt-get update # This is required
sudo apt-get install remmina \
   remmina-plugin-rdp remmina-plugin-gnome \
   libfreerdp-plugins-standard
```

**Comment by MarcoDotNet** [comment]
Still the same message:

The following packages have unmet dependencies:
 remmina-plugin-gnome : Depends: remmina (= 1.2.0-rcgit-24-0~remmina201710260247.rd9156ca.ddd444db~ubuntu17.10.1) but 1.2.0-rcgit-28-0~remmina201804042311.r19bbe44.d41791e1~ubuntu17.10.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by antenore** [comment]
@giox069 can you help please?

**Comment by giox069** [comment]
Also ckeck `/etc/apt/sources.list.d`
You should have only one file for the remmina-next-daily PPA there.

**Comment by MarcoDotNet** [comment]
I did a complete cleanup but I can't connect after the switch to daily builds:

`StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.2

(remmina:11212): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[21:52:21:441] [11212:11227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[21:52:21:441] [11212:11227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[21:52:21:441] [11212:11227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[21:52:21:441] [11212:11227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[21:52:22:666] [11212:11227] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
[21:52:22:666] [11212:11227] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
0002000F 00000003
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`
It seems the issue from here: https://github.com/FreeRDP/Remmina/issues/1513

My FreeRDP Version:
libfreerdp-plugins-standard/artful,now 2.0.0~git201802151002-0+remmina201802151136.r5d1ff02.d9be5820~ubuntu17.10.1 amd64 [installed]
libfreerdp1/artful,now 2.0.0~git201802151002-0+remmina201802151136.r5d1ff02.d9be5820~ubuntu17.10.1 amd64 [installed,automatic]

**Comment by antenore** [comment]
@MarcoDotNet sorry, my bad, we had some old packages still available in the PPA.

I've just cleaned everathing, sorry :-\ 

Can you upgrade one more time?

As a side note, the clipboard issue comes from a problem with Wayland, so upgrading Remmina won't fix this problem.

Can you test to execute Remmina (must NOT be running before to do this) from a terminal with:

```sh
GDK_BACKEND=x11 remmina
```

Thanks!

**Comment by MarcoDotNet** [comment]
@antenore bad news. I switched again to the daily build but during the installation appeared the following message:
remmina-plugin-rdp : Depends: libfreerdp1 (>= 2.0.0~git201802151002) but it is not installable

libfreerdp-common1.1.0/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed,automatic]
libfreerdp-plugins-standard/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed]
libfreerdp-utils1.1/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed,automatic]

remmina/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed]
remmina-common/artful,artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 all [installed,automatic]
remmina-plugin-secret/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]
remmina-plugin-vnc/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]

**Comment by antenore** [comment]
No worries, this should be easy to fix, erase everything (the above purges we discussed).

We will have the had of this bug! ;-)

**Comment by MarcoDotNet** [comment]
**I purged everything again:**
ppa-purge ppa:remmina-ppa-team/remmina-next
apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"
Delete all remmina entries in /etc/apt/sources.list.d/

**Then I tried to install the package:**
apt install remmina remmina-plugin-rdp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
remmina is already the newest version (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-rdp : Depends: libfreerdp1 (>= 2.0.0~git201802151002) but it is not installable
E: Unable to correct problems, you have held broken packages.

**My installed packages:**
remmina/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed]
remmina-common/artful,artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 all [installed,automatic]
remmina-plugin-secret/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]
remmina-plugin-vnc/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]

**Comment by antenore** [comment]
Nope, it's note purged

> remmina is already the newest version. 

After the purge there should be not any remmina, freerdp and winpr packages at all on the system.

When you do the purge what happens? Do you have any messages?

**Comment by MarcoDotNet** [comment]
> remmina is already the newest version.
This appeared because I tried several times to install after the purge with the wohle command.

**Ok, again. Now step by step:**

**Step 1**
sudo killall remmina

**Step 2**
sudo ppa-purge ppa:remmina-ppa-team/remmina-next

**Step 3**
sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"

**Step 4**
Delete sources if they still exists: /etc/apt/sources.list.d
sudo rm /etc/apt/sources.list.d/remmina-ppa-team-ubuntu-remmina-next-*

**Step 5**
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next-daily

_Daily build of Remmina (next branch) and FreeRDP packages.
 More info: https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next-daily
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmp5vmcyizg/pubring.gpg' created
gpg: /tmp/tmp5vmcyizg/trustdb.gpg: trustdb created
gpg: key 8A993C2521C5F0BA: public key "Launchpad PPA for Remmina PPA Team" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK_

**Step 6**
sudo apt update

_Get:12 http://ppa.launchpad.net/remmina-ppa-team/remmina-next-daily/ubuntu artful/main i386 Packages [5.120 B]                                    
Get:13 http://ppa.launchpad.net/remmina-ppa-team/remmina-next-daily/ubuntu artful/main Translation-en [2.072 B]_   

**Step 7**
sudo apt install remmina remmina-plugin-rdp libfreerdp-plugins-standard

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-rdp : Depends: libfreerdp1 (>= 2.0.0~git201802151002) but it is not installable
E: Unable to correct problems, you have held broken packages._

**Step 8**
apt list | grep freerdp | grep installed
<NO OUTPUT>

apt list | grep remmina | grep installed
<NO OUTPUT>

**Step 9**
sudo apt install remmina

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  remmina-common remmina-plugin-secret remmina-plugin-vnc
Recommended packages:
  remmina-plugin-rdp
The following NEW packages will be installed:
  remmina remmina-common remmina-plugin-secret remmina-plugin-vnc
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/442 kB of archives.
After this operation, 1.965 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package remmina-common.
(Reading database ... 269790 files and directories currently installed.)
Preparing to unpack .../remmina-common_1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1_all.deb ...
Unpacking remmina-common (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Selecting previously unselected package remmina.
Preparing to unpack .../remmina_1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1_amd64.deb ...
Unpacking remmina (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Selecting previously unselected package remmina-plugin-secret.
Preparing to unpack .../remmina-plugin-secret_1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1_amd64.deb ...
Unpacking remmina-plugin-secret (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Selecting previously unselected package remmina-plugin-vnc.
Preparing to unpack .../remmina-plugin-vnc_1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1_amd64.deb ...
Unpacking remmina-plugin-vnc (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Setting up remmina-common (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for shared-mime-info (1.8-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
Setting up remmina (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Setting up remmina-plugin-vnc (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ...
Setting up remmina-plugin-secret (1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1) ..._

**Step 10**
apt list | grep remmina | grep installed

_remmina/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed]
remmina-common/artful,artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 all [installed,automatic]
remmina-plugin-secret/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]
remmina-plugin-vnc/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]_

apt list | grep freerdp | grep installed
<NO OUTPUT>

**Step 11**
sudo apt install remmina-plugin-rdp

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-rdp : Depends: libfreerdp1 (>= 2.0.0~git201802151002) but it is not installable
E: Unable to correct problems, you have held broken packages._

**Step 12**
sudo apt install libfreerdp-plugins-standard

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libfreerdp-common1.1.0 libfreerdp-utils1.1 libwinpr-crt0.1 libwinpr-environment0.1 libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1 libwinpr-interlocked0.1 libwinpr-library0.1 libwinpr-path0.1
  libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-utils0.1
Suggested packages:
  freerdp-x11
The following NEW packages will be installed:
  libfreerdp-common1.1.0 libfreerdp-plugins-standard libfreerdp-utils1.1 libwinpr-crt0.1 libwinpr-environment0.1 libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1 libwinpr-interlocked0.1 libwinpr-library0.1
  libwinpr-path0.1 libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-utils0.1
0 upgraded, 15 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/380 kB of archives.
After this operation, 3.979 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package libwinpr-crt0.1:amd64.
(Reading database ... 269943 files and directories currently installed.)
Preparing to unpack .../00-libwinpr-crt0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-crt0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-library0.1:amd64.
Preparing to unpack .../01-libwinpr-library0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-library0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-environment0.1:amd64.
Preparing to unpack .../02-libwinpr-environment0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-environment0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-heap0.1:amd64.
Preparing to unpack .../03-libwinpr-heap0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-heap0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-path0.1:amd64.
Preparing to unpack .../04-libwinpr-path0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-path0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-handle0.1:amd64.
Preparing to unpack .../05-libwinpr-handle0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-handle0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-interlocked0.1:amd64.
Preparing to unpack .../06-libwinpr-interlocked0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-interlocked0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-thread0.1:amd64.
Preparing to unpack .../07-libwinpr-thread0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-thread0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-synch0.1:amd64.
Preparing to unpack .../08-libwinpr-synch0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-synch0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-sysinfo0.1:amd64.
Preparing to unpack .../09-libwinpr-sysinfo0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-sysinfo0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-utils0.1:amd64.
Preparing to unpack .../10-libwinpr-utils0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-utils0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libfreerdp-common1.1.0:amd64.
Preparing to unpack .../11-libfreerdp-common1.1.0_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libfreerdp-common1.1.0:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libfreerdp-utils1.1:amd64.
Preparing to unpack .../12-libfreerdp-utils1.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libfreerdp-utils1.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libwinpr-file0.1:amd64.
Preparing to unpack .../13-libwinpr-file0.1_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libwinpr-file0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Selecting previously unselected package libfreerdp-plugins-standard:amd64.
Preparing to unpack .../14-libfreerdp-plugins-standard_1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1_amd64.deb ...
Unpacking libfreerdp-plugins-standard:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-interlocked0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-handle0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-thread0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-heap0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-sysinfo0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-environment0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-library0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-crt0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-file0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Processing triggers for libc-bin (2.26-0ubuntu2.1) ...
Setting up libwinpr-path0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-synch0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libwinpr-utils0.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libfreerdp-utils1.1:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libfreerdp-common1.1.0:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Setting up libfreerdp-plugins-standard:amd64 (1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1) ...
Processing triggers for libc-bin (2.26-0ubuntu2.1) ..._

**Step 13**
sudo apt install remmina-plugin-rdp

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-rdp : Depends: libfreerdp1 (>= 2.0.0~git201802151002) but it is not installable
E: Unable to correct problems, you have held broken packages._

**Step 14**
apt list | grep remmina | grep installed

_remmina/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed]
remmina-common/artful,artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 all [installed,automatic]
remmina-plugin-secret/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]
remmina-plugin-vnc/artful,now 1.2.0-rcgit-28-0~remmina201804061816.r7c07949.da238709~ubuntu17.10.1 amd64 [installed,automatic]_

apt list | grep freerdp | grep installed

_libfreerdp-common1.1.0/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed,automatic]
libfreerdp-plugins-standard/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed]
libfreerdp-utils1.1/artful,now 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 amd64 [installed,automatic]_

I hope this helps.

**Comment by antenore** [comment]
Your Ubuntu installation has something really wrong

As per our PPA

https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next-daily?field.series_filter=artful 

Remmina needs freerdp2, but your ubuntu try to install freerdp1 and I really don't understand why.

Installing a fresh Ubuntu 17.10.1 works properly, yesterday @giox069 has done a test and was installing the right version.

I don't get it.

I'm gong to check some more stuff on our side but I'm afraid I can't do anything without putting my hands on your computer.

**Comment by giox069** [comment]
@antenore: I tested on 16.04 yesterday, not on 17.10.
Testing on 17.10 now. And yes, it fails in step 7 as @MarcoDotNet reported:
```
giovanni@pgt470s:~$ sudo apt install remmina remmina-plugin-rdp libfreerdp-plugins-standard
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Alcuni pacchetti non possono essere installati. Questo può voler dire
che è stata richiesta una situazione impossibile oppure, se si sta
usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
non sono ancora stati creati o sono stati rimossi da Incoming.
Le seguenti informazioni possono aiutare a risolvere la situazione:

I seguenti pacchetti hanno dipendenze non soddisfatte:
 remmina-plugin-rdp : Dipende: libfreerdp1 (>= 2.0.0~git201802151002) ma non è installabile
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

```

**Comment by giox069** [comment]
Also please note: we are going a bit off-topic for this thread. @MarcoDotNet can you reach us by another way, like telegram here https://t.me/Remmina ?
So, for @havanahjoe the clipboard problem should be Wayland. Can you try to start remmina from a terminal with ```GDK_BACKEND=x11 remmina`` .

**Comment by giox069** [comment]
The PPA remmina-next-daily for ubuntu 17.10 seems to be fixed now,@MarcoDotNet.
The clipboard problem on wayland is still not fixed.

**Comment by MarcoDotNet** [comment]
Indeed, the daily ppa is fixed and the workaround "GDK_BACKEND=x11 remmina" works fine.

**Comment by natrius** [comment]
Not possible to Copy and Paste text. Using KDE Neon 5.12 and Ubuntu Server 18.04. I can connect via VNC but no matter what i'm trying, i cannot c&p. Reminna 1.2.0-rcgit-29
Tried 
`GDK_BACKEND=x11 remmina`
did not work.

**Comment by craig** [comment]
Same issue here with Debian 9. Copy & Pasting does not work in either direction.

**Comment by giox069** [comment]
@craig let us know your setup: are you using Wayland? Is XWayland available? Which desktop environment (GNOME/XFCE)? Which protocol are you using (RDP, VNC..?) Which server do you connect to? What kind of data are you copiyng? Please reopen a new issue with all those parameter, or we are totally unable to investigate.

**Comment by craig** [comment]
- awesome window manager (https://awesomewm.org/).
- Protocol RDP (with credssp, latest patchlevel)
- Windows 2016 Standard

 I'm trying to copy from a urxvt terminal into notepad or the other way around.
