### ISSUE TITLE
Remmina Application - unable to find when searching or pin to launcher

### ISSUE THREAD

**Issue by cprofitt** [FreeRDP/Remmina#1521]
Fedora 27
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
Running under Gnome Shell version 3.26.2
Remmina - 1.2.0-rcgit-27 (git rcgit-27)
-----
Remmina disappeared from my launcher and no longer shows up as an application when searching. Can launch it from command line only. The org.remmina.Remmina.desktop contains the following:

[Desktop Entry]
Version=1.0
Name=Remmina
Name[ca]=Remmina
Name[cs]=Remmina
Name[de]=Remmina
Name[el]=Remmina
Name[es]=Remmina
Name[eu]=Remmina
Name[fr]=Remmina
Name[hu]=Remmina
Name[it]=Remmina
Name[lt]=Remmina
Name[nl]=Remmina
Name[pl]=Remmina
Name[pt_BR]=Remmina
Name[pt_PT]=Remmina
Name[ru]=Remmina
Name[tr]=Remmina
Name[uk]=Remmina
Name[zh_CN]=Remmina
GenericName=Remote Desktop Client
GenericName[ca]=Client d'escriptori remot
GenericName[cs]=Klient vzdálené pracovní plochy
GenericName[de]=Verbindung zu Fremdrechnern
GenericName[el]=Πελάτης απομακρυσμένης επιφάνειας εργασίας
GenericName[es]=Cliente de escritorio remoto
GenericName[eu]=Urruneko mahaigainaren bezeroa
GenericName[fr]=Afficheur de bureau distant
GenericName[hu]=Távoli asztal kliens
GenericName[it]=Client per connessione a desktop remoto
GenericName[lt]=Nutolusio darbastalio klientas
GenericName[nl]=Client voor verbinding met extern bureaublad
GenericName[pl]=Klient zdalnego pulpitu
GenericName[pt_BR]=Cliente de área de trabalho remota
GenericName[pt_PT]=Cliente de ambiente de trabalho remoto
GenericName[ru]=Клиент удалённого доступа к рабочему столу
GenericName[tr]=Uzak Masaüstü İstemcisi
GenericName[uk]=Клієнт з'єднання з віддаленою стільницею
GenericName[zh_CN]=远程桌面客户端
X-GNOME-FullName=Remmina Remote Desktop Client
Comment=Connect to remote desktops
Comment[bg]=Свързване към отдалечени компютри
Comment[ca]=Connecteu-vos a escriptoris remots
Comment[cs]=Připojení ke vzdáleným plochám
Comment[da]=Tilslut fjernskriveborde
Comment[de]=Zu entfernten Arbeitsflächen verbinden
Comment[el]=Συνδεθείτε σε απομακρυσμένους υπολογιστές
Comment[es]=Conectarse a escritorios remotos
Comment[eu]=Konektatu urruneko mahaigainekin
Comment[fr]=Connectez-vous à des bureaux distants
Comment[hu]=Kapcsolódás távoli asztalhoz
Comment[id]=Mengakses remote desktop
Comment[it]=Connessione a desktop remoti
Comment[kk]=Қашықтаған жұмыс үстелдерге қосылу
Comment[lt]=Jungtis prie nutolusių kompiuterių
Comment[nl]=Verbinding maken met bureaubladen op afstand
Comment[pl]=Łączy ze zdalnymi pulpitami
Comment[pt_BR]=Conecte-se a áreas de trabalho remotas
Comment[pt_PT]=Estabelecer ligação com computadores remotos
Comment[ru]=Подключение к удалённым рабочим столам
Comment[sk]=Pripojenie k vzdialeným pracovným plochám
Comment[sv]=Anslut till fjärrskrivbord
Comment[th]=เชื่อมต่อไปยังพื้นโต๊ะระยะไกล
Comment[tr]=Uzak masaüstlerine bağlan
Comment[uk]=Приєднатися до віддаленого комп’ютера
Comment[zh_CN]=连接到远程桌面
TryExec=/usr/bin/remmina %u
Exec=/usr/bin/remmina %u
Icon=remmina
Terminal=false
Type=Application
Categories=GTK;GNOME;X-GNOME-NetworkSettings;Network;
Actions=Profile;Tray;Quit;
MimeType=application/x-remmina;
Keywords=remote desktop;rdp;vnc;nx;ssh;spice;xdmcp;
StartupWMClass=remmina

[Desktop Action Profile]
Name=Create a New Connection Profile
Name[ca]=Crea un perfil de connexió nou
Name[cs]=Vytvořit nový profil připojení
Name[de]=Ein neues Verbindungsprofil erstellen
Name[el]=Δημιουργία νέου προφίλ σύνδεσης
Name[es]=Crear un perfil de conexión nuevo
Name[eu]=Sortu konexio profil berri bat
Name[fr]=Créer un nouveau profil de connexion
Name[hu]=Új kapcsolatprofil létrehozása
Name[it]=Crea un nuovo profilo di connessione
Name[lt]=Sukurti naują prisijungimo profilį
Name[nl]=Een nieuw verbindingsprofiel aanmaken
Name[pt_BR]=Criar um novo perfil de conexão
Name[pt_PT]=Criar um Novo Perfil de Ligação
Name[ru]=Создать профиль нового соединения
Name[sk]=Vytvoriť nový profil pripojenia
Name[sv]=Skapa en ny anslutningsprofil
Name[tr]=Yeni Bir Bağlantı Profili Oluştur
Name[uk]=Створити новий профіль з’єднання
Name[zh_CN]=新建连接配置
Exec=/usr/bin/remmina --new

[Desktop Action Tray]
Name=Start Remmina Minimized
Name[ca]=Inicia el Remmina minimitzat
Name[cs]=Spustit Remmina minimalizované
Name[de]=Reminna minimiert starten
Name[el]=Έναρξη του Remmina ελαχιστοποιημένου
Name[es]=Iniciar Remmina minimizado
Name[eu]=Abiatu Remmina minimizatuta
Name[fr]=Démarrer Remmina en mode réduit
Name[hu]=Remmina indítása minimalizálva
Name[it]=Avvia Remmina minimizzato
Name[lt]=Paleisti Remmina suskleistą
Name[nl]=Remmina geminimaliseerd starten
Name[pt_BR]=Iniciar Remmina minimizado
Name[pt_PT]=Iniciar o Remmina Minimizado
Name[ru]=Сворачивать Remmina после запуска
Name[sk]=Spustiť program Remmina minimalizovaný
Name[sv]=Starta Remmina minimerat
Name[tr]=Remmina'yı Küçültülmüş Başlat
Name[uk]=Запустити Rammina у системному лотку
Name[zh_CN]=启动后自动最小化
Exec=/usr/bin/remmina --icon

[Desktop Action Quit]
Name=Quit
Exec=/usr/bin/remmina --quit

**Comment by cprofitt** [comment]
I removed remmina-1.2.0-0.48.20180314.git.04e4a99.fc27.x86_64 and then reinstalled remmina-1.2.0-0.42.20170908git205df66.fc27.x86_64.

Expected functionality is back. This may be a Fedora packaging issue.

**Comment by cprofitt** [comment]
Filed a bug with Fedora
https://bugzilla.redhat.com/show_bug.cgi?id=1557572

**Comment by scaronni** [comment]
@antenore I reverted this:

https://github.com/FreeRDP/Remmina/commit/3f027730910292df1de9d30d112bc33c2c1cd073#diff-0dbceb3abda946f48c85504e4e6ead56

And the icon is back. Again, pretty useless that `desktop-file-validate` does not print any error about it.

**Comment by antenore** [comment]
Should be fixed via 09cfc03670cfd76baac6b59e0671e98f1a73ed10

**Comment by antenore** [comment]
The %u is needed to pass a .remmina file

**Comment by antenore** [comment]
I'm testing stay tuned

**Comment by scaronni** [comment]
Thanks!

**Comment by cprofitt** [comment]
Awesome work everyone!

**Comment by scaronni** [comment]
@antenore, sorry to bother you again, can you please revert this commit?

https://github.com/FreeRDP/Remmina/commit/380bab10c959c7ee9b333410aafaed0aa50d91f6

Please read this comment and the one after.

https://bugzilla.redhat.com/show_bug.cgi?id=1553098#c33

Thanks!

**Comment by antenore** [comment]
Sure, no problem @scaronni

**Comment by antenore** [comment]
Done
