### ISSUE TITLE
window has no focus when open ssh sessions

### ISSUE THREAD

**Issue by zagr0** [FreeRDP/Remmina#1530]
* Client (OS name and version): fedora27 
* Remmina version (remmina --version): 1.2.0-rcgit-27 (git 3a6cde40)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): -
* Connecting via (RDP, VNC, ...): ssh
* RDP issues only, freerdp version (xfreerdp --version): -

When you open the first ssh session it opens and the window with tabs get focus, but if you open any next ssh connection the window with terminal opens with no focus.   

Could you please fix that

**Comment by antenore** [comment]
Thanks for reporting this. I'll take a look.

**Comment by giox069** [comment]
When you open the second ssh connection, does the connection window stays under the remmina main window? Or the connection window is raised but the new tab is not selected? Can you provide a video/screencast?

**Comment by zagr0** [comment]
no, the console window comes to foreground but with no focus.
please find screencast attached.
[Screencast.zip](https://github.com/FreeRDP/Remmina/files/1837722/Screencast.zip)

**Comment by giox069** [comment]
Many thanks for the screencast! Are you running GNOME under Wayland or Xorg? Under Wayland (ubuntu 17.10) I have an extra problem: the connection window is not raised when you connect the 2nd time. But in your screencast I can't see the same problem.

**Comment by zagr0** [comment]
Its on Xorg, there is no issue you describe

**Comment by giox069** [comment]
I think I have fixed it. The fix is in the "next" branch. If you are using a fedora binary package, you will receive it with the next release.

**Comment by zagr0** [comment]
Thnx a lot, its fine now!
