### ISSUE TITLE
Icon missing in Gnome Activities on Fedora 27

### ISSUE THREAD

**Issue by term1n4l** [FreeRDP/Remmina#1534]
I cannot find the icon for remmina in GNOME activities on Fedora 27 it also doesn't show up in search.

When launching from command line, I get:

StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed

running a journalctl -xe shows:

gnome-software[2016]: failed to call gs_plugin_launch on packagekit: no such desktop file: org.remmina.Remmina.desktop
gnome-software[2016]: not handling error not-supported for action launch: no such desktop file: org.remmina.Remmina.desktop

This was after trying to launch from the gnome-software centre.

Please give us some details about the systems you are using:
* Client (OS name and version): Fedora 27
* Remmina version (remmina --version): Remmina - 1.2.0-rcgit27
* Desktop environment (GNOME, Unity, KDE, ..): GNOME 3.26.2 (x86_64)
* Connecting to (OS and version): none
* Connecting via (RDP, VNC, ...): RDP

**Comment by antenore** [comment]
This is something we've recently fixed, strange...

@scaronni any ideas? Thanks

**Comment by scaronni** [comment]
@term1n4l The update fixing this is batched for the official updates:

https://bodhi.fedoraproject.org/updates/?packages=remmina

If you don't want to wait for it to happen, you can do the following:

```
dnf update --enablerepo=updates-testing update remmina* freerdp* libwinpr*
```
@antenore I guess you can close the issue.

**Comment by antenore** [comment]
Thank you master @scaronni

**Comment by term1n4l** [comment]
Thanks, the updates resolved this issue
