### ISSUE TITLE
Is it possible to install to SailfishOS ?

### ISSUE THREAD

**Issue by PizzaProgram** [FreeRDP/Remmina#1540]
I don't know how much work would it be, but this is a GREAT program, and it would be cool to get it working under Sailfish.  
There is no need to put it directly to the offical Jolla-store, enough would be to make it accessible from [repo](https://openrepos.net/search/node/rdp). There are currently only .deb packages, and no .rpm :(   
So THIS would be the one and only possible choice. :1st_place_medal: 
  
Sadly I'm only a simple Delphi programmer on Windows enviroments, but I think it's getting more and more important to keep our (and out customer's data safe).  
So I'm switching to SailfishOS now, which is a debian based secure OS.

**Comment by antenore** [comment]
Out of curiosity, why do you use SFOS? It's an OS mainly targeted to mobile devices, like smartphones and tablets.

Unlucky we don't have resources and time to dedicate on it, better asks to the SFOS community. Consider that Remmina is in the debian backports, so it'd be possible to use it in SFOS.

**Comment by antenore** [comment]
One more thing @PizzaProgram if snap and flatpak are supported on SFOF, you can install Remmina through those systems. Flatpak is not yet published on flathub, but it's in progress.
See in our wiki how to use snap.
If you don't mind I'm closing this, but feel free to contact us through G+, reddit or telegram if you need further assistance

**Comment by PizzaProgram** [comment]
.. I've just lost everything I wrote after pressed Comment... Ahhhhg :(

Short answer:
- Jolla ppl can not do it.
- little interest to Flatpak from them too.
THANKS for your respond.

**Comment by antenore** [comment]
Well you can use freerdp, they have an android client

https://play.google.com/store/apps/details?id=com.freerdp.afreerdp

**Comment by PizzaProgram** [comment]
Sailfish is NOT Android!
I have not an "Official Jolla phone" for 1000+ Eur, but installed to a simple Redmi Note 4  (bought for 100 Eur). So I can not install or run any android .apk
SailfishOS has been ported to many phone types, but none of them has "Darvik" support because of [licensing problems](https://forum.xda-developers.com/jolla-sailfish/general/alien-dalvik-licensing-issue-t2694127).
_(But even if I could, adds other security concerns... do they log my logins/credentials?)_

**Comment by PizzaProgram** [comment]
##< OFF >
_... so you were my last hope to be able to RDP / VNC into my client's machine from my phone._
But I can **fully understand**, if you guys have not enough resources to support SailfishOS.
As a programmer myself I know how difficult and time consuming can be to do it.
