### ISSUE TITLE
Minor graphical issue on Ubuntu 18.04 with communitheme

### ISSUE THREAD

**Issue by cialu** [FreeRDP/Remmina#1546]
Hi all,

I'm testing **Ubuntu 18.04 LTS** with the communitheme and using GTK+ software like **Remmina**, I found a minor graphical issue on the main window. It's about a round corner under the title tab, where it's not supposed to be. I don't know if this is an issue related specifically to the theme or to the application. I post a picture to explain better the issue.

![commtheme](https://user-images.githubusercontent.com/1382127/37329151-dc3aab86-269c-11e8-8919-af1131333409.jpg)

I already reported it to the **ubuntu/gtk-communitheme** repo, this is the relative issue: 
[ Minor graphical issue on GTK+ window #311](https://github.com/ubuntu/gtk-communitheme/issues/311#issuecomment-378389686)

* Client (OS name and version): Ubuntu 18.04 Development Branch
* Remmina version (remmina --version): Remmina 1.2.0-rcgit-27
* Desktop environment (GNOME, Unity, KDE, ..): GNOME with communitheme
* Connecting to (OS and version): Win10
* Connecting via (RDP, VNC, ...): RDP

**Comment by antenore** [comment]
Thanks for reporting this.
IMHO it's a theme issue, as I never saw this issue, let's see what  the Ubuntu community will answer.

**Comment by clobrano** [comment]
@antenore I suggested to open a ticket also here, because I was surprised to see a headerbar inside a box

![image](https://user-images.githubusercontent.com/2883614/39625825-9629e0ea-4f9f-11e8-9bff-84dbf35e454e.png)

**Comment by antenore** [comment]
@clobrano Thanks! This make thing clear now. I should be able to fix this asap.

**Comment by antenore** [comment]
I've just committed an updated UI that should fix the problem.
Anybody available to test it?

Without compiling, it's enough to replace your remmina_main.glade with  this https://github.com/FreeRDP/Remmina/blob/c17c2d636193a98dd9b849dc0a484964b27b3b2f/data/ui/remmina_main.glade

@clobrano @cialu

**Comment by clobrano** [comment]
If this is the expected result, very well done :+1: 
![image](https://user-images.githubusercontent.com/2883614/39695082-a7a7e474-51e9-11e8-9e5c-da6fc8891d10.png)

**Comment by antenore** [comment]
I've just pushed an additional commit to add the windows controls

**Comment by clobrano** [comment]
This is using the patched file

**Comment by antenore** [comment]
Cool! Looks good :-) 
I'll leave the PR opened a while and then merge it if anything bad comes up again

**Comment by cialu** [comment]
Really great work. Thanks!

**Comment by antenore** [comment]
Thanks, I've merged the PR, it'll be available in the next release, hopefully very soon.

Buon appetito!
:-)
