### ISSUE TITLE
Connection window disappears when minimized 

### ISSUE THREAD

**Issue by JaggedJax** [FreeRDP/Remmina#155]
Using Cinnamon window manager (on Linux Mint), if the setting "Minimize windows to tray" is enabled and a connection window is minimized, the window disappears with no way to bring it back.

Starting a new session, loads the new connection, but the main window still stays hidden.

**Comment by Hubbitus** [comment]
Possibly duplicate of https://github.com/FreeRDP/Remmina/issues/148.

**Comment by ic3d** [comment]
@JaggedJax What versions of freerdp and remmina are you use? Is it actual now?

**Comment by ic3d** [comment]
I close this issue because it was opened a long ago and probably it's a duplicate of a already-closed bug.
