### ISSUE TITLE
Remmina is laggy on Ubuntu Mate for RPi

### ISSUE THREAD

**Issue by Bottson** [FreeRDP/Remmina#1552]
Because of problems installing Remmina on Raspbian(https://github.com/FreeRDP/Remmina/issues/1532), we tried Ubuntu Mate (16.04.2 Xenial) for Raspberry.

Following the wiki "For Ubuntu users we have an official PPA with Remmina 1.2" we installed the latest version of Remmina on our Raspberry.

While beeing connected to Windows Server 2016 (also tested on Win Server 2012 and Win 10 - so probably every Windows Version) we noticed that moving the Explorer Window is laggy. Also switching from one to another program does not work as good as it has on raspbian, sometimes there are graphic issues like the program remains frozen or you can see the content from the old window in the one which I switched to. 

Network issues are not recognized. 
Quality is set to poor in remmina options. 

As i did not find such problems on the web, is there something I am missing to increase video performance on raspberry, or am I doing something wrong? 

----
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu Mate 16.04.2
* Remmina version (remmina --version): 1.2.0-rcgit-27
* Desktop environment (GNOME, Unity, KDE, ..):  
* Connecting to (OS and version): Win Server 2016 - 2012 - Windows 10
* Connecting via (RDP, VNC, ...): rdp
* RDP issues only, freerdp version (xfreerdp --version): I have run xfreerdp --version and it told me there is no xfreerdp installed. So I installed it via sudo apt-get freerdp. Now it shows me version 2.0.0 dev2.
When trying with xfreerdp ip.ip.ip.ip it looks like there are no graphic issues. So what rdp does my remmina use if its not freerdp?

**Comment by Bottson** [comment]
Its a Raspberry Pi 3 Model B. Connect via Ethernet to our Network. 
I tried to downgrade to 16 and 24 bpp. It is indeed better with these settings but not as good as if I use the command: xfreerdp /V: ip.ip.ip.ip /rfx /f and as good as I remember it was with raspbian. 
I tried also with other various settings in remmina. 
Thanks for your help and quick answer regardless :)

**Comment by Bottson** [comment]
Ok, thank you. If I can help somewhere or if I can test something just let me know :)

**Comment by giox069** [comment]
Yes, it seems that remmina and xfreerdp on ubuntu mate are a bit laggier than xfreerdp on raspbian. Perhaps recent raspbian is more optimized than ubuntu mate.
We are now trying to produce some .deb packages for Raspbian. I hope we could have something to test in a week. Thank you @mfvescovi for this.

**Comment by Bottson** [comment]
That sounds really great. 👍 :)

**Comment by giox069** [comment]
@Bottson we have a repository to test for current **raspbian** stretch. I don't know if we can afford to update and maintain it for the future, but remmina 1.2.0-rcgit.29 is there.

### SETUP:
```
sudo apt-key adv --fetch-keys http://www.remmina.org/raspbian/remmina_raspbian.asc
sudo bash -c 'echo "deb http://www.remmina.org/raspbian/ stretch main" > /etc/apt/sources.list.d/remmina_raspbian.list'
```
### Install
```
sudo apt update
sudo apt install remmina 
```
Also please note that having a gnome keyring is strongly advised, otherwise remmina will save passwords unencrypted:
```
sudo apt install gnome-keyring
```
Let me know. If it works, I will update the Wiki.
Many thans again to @mfvescovi.

**Comment by Bottson** [comment]
Hi @giox069,

First Test was good. I was able to install remmina on the latest Raspbian.
Also connecting to a full patched Windows Server was possible. I will make some more tests later on, but the first look is good.

Thank you in the meantime. 

PS: How do mean "I don't know if we can afford to update and maintain it for the future"?

**Comment by giox069** [comment]
Maintaining a binary package takes a lot of time. Not only the initial setup. For every release there is a certain quantity of work to do: try to compile with the same setup as the previous release, if it does not work, change compilation setup (add new dependencies, remove old, change paths) and retry, check logs. Then, when you have a binary package, install it and do minimal testing. And then, publish. And during this process, it's very likely you will find bugs specific to your build or distribution that you should handle with upstream programmers.
Currently we directly maintain the ubuntu's PPA, and the SNAP package. Then we help upstream maintainers of Debian, Fedora, OpenSUSE in compiling remmina to bring it into the official distributions. And now we have Flatpack too. I think the transition from rcgit.27 to rcgit.29 was the most time consuming transition for binary packaging. I can't really say how long it has taken, but I think we suspended core remmina development for three weeks to follow binary packaging, investing more than 80 hours of work for creating/fixing binary packages and collaborating with package maintainers.
You can understand that it's a bit difficult to find time for another (Raspbian) binary release and release it with the same frequency as the other packaging systems. If someone else wants to learn debian packaging and wants to help, he/she is welcome to help.
In the meanwhile: thank you for testing ;), I will update the wiki as soon as possible.

**Comment by giox069** [comment]
Wiki is updated. I'm closing this issue now. If you find other problems, feel free to open a new one. Thank you for helping and testing. :+1:

**Comment by Bottson** [comment]
After some more testing I can confirm everything works as aspected. 
Thank you for the quick support and solution. 

PS: Maybe you could add to the Wiki that its also necessary to install the dirmngr package. 
"sudo apt-get install dirmngr".
