### ISSUE TITLE
Graphical glitch with Total Commander and Remmina

### ISSUE THREAD

**Issue by jmredfern** [FreeRDP/Remmina#157]
I see a graphical glitch when using Remmina  to connect to Windows XP.

The glitch is in the icons of Total Commander, they are nearly white.

I run Remmina from Xubuntu x86_64 Ubuntu 12.10, with kernal 3.5.0-25-generic.

Windows XP is Professional Version 2002 SP3.

Remmina version 1.0.0, was installed by package (not self-compiled):

I've tried connecting with different colour bitdepths (Remote FX32, True color 32, True color 24) and the same result.

I've attached a screenshot & ppa info below.

Thanks!

dpkg -l remm*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-=========================================================
ii  remmina                    1.0.0-4~441+19~qua amd64              remote desktop client for GNOME desktop environment
ii  remmina-common             1.0.0-4~441+19~qua all                common files for remmina remote desktop client
un  remmina-gnome              <none>                                (no description available)
un  remmina-plugin-data        <none>                                (no description available)
ii  remmina-plugin-rdp         1.0.0-4~441+19~qua amd64              RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc         1.0.0-4~441+19~qua amd64              VNC plugin for remmina remote desktop client
un  remmina-xfce               <none>                                (no description available)

![totalcommander](https://f.cloud.github.com/assets/3799803/232823/ed6ed36e-8741-11e2-953c-e7a85411e124.png)

**Comment by muflone** [comment]
The remmina version 1.0.0 is quite old.
Please refer to our wiki page how to get instructions to upgrade to the latest version of remmina.
