### ISSUE TITLE
Typo in snap pop up "passowrd" instead of "password"

### ISSUE THREAD

**Issue by 8none1** [FreeRDP/Remmina#1579]
I'm using the snap of Remmina (nice work!) and was prompted to set some additional permissions.
I spotted a type in that message that says "passowrd" instead of "password"

This is version 1.2.0-rcgit-29.

**Comment by antenore** [comment]
Thank you @8none1 ! 

I'm going to fix it, it will be available in few weeks in the next release (on snap probably few days).
