### ISSUE TITLE
Alt-tab in Windows XP while keyboard capture active doesn't switch windows in remote desktop

### ISSUE THREAD

**Issue by jmredfern** [FreeRDP/Remmina#158]
The issue I see is that alt-tab in Windows XP while keyboard capture is active doesn't switch windows in the remote desktop. Other alt combos work, such as alt+f opens the file menu.

I run Remmina from Xubuntu x86_64 Ubuntu 12.10, with kernal 3.5.0-25-generic.

Windows XP is Professional Version 2002 SP3.

Remmina version 1.0.0, was installed by package (not self-compiled):

I've attached ppa info info below.

Thanks!

dpkg -l remm*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-=========================================================
ii  remmina                    1.0.0-4~441+19~qua amd64              remote desktop client for GNOME desktop environment
ii  remmina-common             1.0.0-4~441+19~qua all                common files for remmina remote desktop client
un  remmina-gnome              <none>                                (no description available)
un  remmina-plugin-data        <none>                                (no description available)
ii  remmina-plugin-rdp         1.0.0-4~441+19~qua amd64              RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc         1.0.0-4~441+19~qua amd64              VNC plugin for remmina remote desktop client
un  remmina-xfce               <none>                                (no description available)

**Comment by ic3d** [comment]
Sorry for this very late answer, but we don't support that version, it's really too old, follow our wiki on how to use the official PPA.
