### ISSUE TITLE
Remmina snap fonts are ... gone.

### ISSUE THREAD

**Issue by bladernr** [FreeRDP/Remmina#1587]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): NA
* Remmina version (remmina --version): 1.2.0-rcgit-29  rev 766
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Ubuntu 16.04.4
* Connecting via (RDP, VNC, ...): NA
* RDP issues only, freerdp version (xfreerdp --version): NA

See attached screen shot.  Trying to load the remmina snap and I can't do anything with it because all the text appears as the annoying rectangular char you get when a font isn't installed.  

![remmina-snap](https://user-images.githubusercontent.com/4295496/39210902-13325e8e-47d8-11e8-9eb8-e659958255dd.png)

**Comment by antenore** [comment]
I've tested it on 3 different systems and I cannot reproduce it. It's likely an issue with your snap setup, but I really don't know how to help you.

Try to remove the Remmina snap and reinstall it as is described in our wiki.
If it doesn't help chase for help in the snap community, unlucky we cannot help more  as we cannot reproduce it. I'd ask as well in the Ubuntu community.

**Comment by amtlib-dot-dll** [comment]
@bladernr https://www.v2ex.com/t/450475 Same issue as yours. Probably an issue of snap itself
