### ISSUE TITLE
undefined symbol: vte_terminal_copy_clipboard_format

### ISSUE THREAD

**Issue by webian** [FreeRDP/Remmina#1591]
Today I updated to Ubuntu 18.04 from 17.10 and when I run remmina I always get this error:
`remmina: symbol lookup error: remmina: undefined symbol: vte_terminal_copy_clipboard_format`
also with a simple `remmina --version`

* Client (OS name and version): Ubuntu 18.04
* Remmina version (remmina --version): remmina/bionic,now 1.2.0-rcgit.29+dfsg-1ubuntu1 amd64
* Desktop environment (GNOME, Unity, KDE, ..): i3

**Comment by debelan** [comment]
I"ve endup using the snap package as I needed RDP @webian, can give it a try till this is fixed.

**Comment by debelan** [comment]
@giox069, I'm using: 
deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu bionic main

Did purge all remmina  and install again from the ppa, no luck

**Comment by giox069** [comment]
@debelan can you execute
```ldd /usr/bin/remmina | fgrep vte```
```apt-cache policy remmina```
and paste the output here?

**Comment by debelan** [comment]
libvte-2.91.so.0 => /usr/local/lib/libvte-2.91.so.0 (0x00007fee20a9b000)
And that's the remmina package
remmina:
  Installed: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Candidate: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Version table:
 *** 1.2.0-rcgit.29+dfsg-1ubuntu1 500
        500 http://gb.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu bionic/main amd64 Packages

**Comment by antenore** [comment]
@vabada Why you have a libvte installed under /usr/local, from where it comes? If you install the vte packages from Ubuntu you should probably not have this problem.

Can you please investigate in this direction?

**Comment by giox069** [comment]
Yes, for both @vabada and @debelan you both have a strange libvte installation into /usr/local/lib. Thank you Antenore for discovering this.
I can suggest to check if that file come from a specific package:
```
dpkg --search /usr/local/lib/libvte-2.91.so.0
```
and then uninstall the package.

**Comment by webian** [comment]
Same here:

```
$ ldd /usr/bin/remmina | fgrep vte
libvte-2.91.so.0 => /usr/local/lib/libvte-2.91.so.0 (0x00007fcb78e34000)
```

```
$ apt-cache policy remmina
remmina:
  Installed: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Candidate: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Version table:
 *** 1.2.0-rcgit.29+dfsg-1ubuntu1 500
        500 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu bionic/main amd64 Packages
```

```
$ dpkg --search /usr/local/lib/libvte-2.91.so.0
dpkg-query: no path found matching pattern /usr/local/lib/libvte-2.91.so.0
```
So I deleted `/usr/local/lib/libvte-2.91.so.0` and now Remmina works again!
