### ISSUE TITLE
RDP - Implement xfreerdp like  --no-fastpath option

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#1596]
On IRC it has been reported that connecting to a win2k3 server (remmina and freerdp from the PPA), often crashes, with both Remmina and xfreerdp.

With xfreerdp , using the --no-fastpath option, solves the issue.

Can we implement this? It may be useful, probably, with other windows versions when there are connections issues not correctly managed by the RDP server.

**Comment by giox069** [comment]
I had a lot of disconnection when connecting to windows2003 servers. But never had ha crash. Now with fast-path disabled, I'm still connected after 1 hour of work on a win2003 server. Wonderful!
Thank you for finding a solution (or workaround, in this case).

**Comment by antenore** [comment]
Thanks to you @giox069 I don't know how to get in touch with the user (Aro74) that has reported this on IRC. If he will jump in I'll tell him.
