### ISSUE TITLE
Flatpak - Add ffmpeg dependency (libavutil/libavcodec) to the Remmina flatpak for FreeRDP

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#1598]
Without compiling FreeRDP with ffmpeg, the GFX support added by @giox069 won't work.

Can you please add this as patch to the flatpak on flathub?

cc @larchunix @amtlib-dot-dll

**Comment by amtlib-dot-dll** [comment]
> the GFX support added by @giox069 won't work

Sorry, but where can I find the relevant code? I'd like to understand it before patching

**Comment by giox069** [comment]
When you "cmake" FreeRDP and you don't define -DWITH_FFMPEG=off, cmake it will try to look for libavcodec and libavutil (see cmake script [here](https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindFFmpeg.cmake)). If it can find it, it will link to libavcodec, libavutil and libx264, and it will enable "GFX AVC support for RDP". A description of what is it can be found [here](https://cloudblogs.microsoft.com/enterprisemobility/2016/01/11/remote-desktop-protocol-rdp-10-avch-264-improvements-in-windows-10-and-windows-server-2016-technical-preview/).
Remmia supports newer GFX AVC modes by default.

See this PR:https://github.com/FreeRDP/Remmina/pull/1468
And this screenshot: https://user-images.githubusercontent.com/5477803/35671897-014aa16c-073d-11e8-8c40-da40570d7703.png

When a remmina user create a new profile, it defaults to GFX AVC 444, and when he tries to connect to the remote server, if freerdp is not linked witht libavcodec/avutils/x264, remmina will complain for bad color depth.

**Comment by amtlib-dot-dll** [comment]
There is an existing `ffmpeg` library that can be used, but I don't know whether the required demuxers/decoders are enabled @giox069 

https://github.com/flathub/org.freedesktop.Platform.ffmpeg/blob/master/org.freedesktop.Platform.ffmpeg.json

**Comment by larchunix** [comment]
@amtlib-dot-dll is right, you have to run `flatpak --user install flathub org.freedesktop.Platform.ffmpeg` for H264 to be working.

There is nothing to do for the flatpak manifest.

**Comment by antenore** [comment]
Ah! Nice, I will update the documentation. Thanks!

**Comment by amtlib-dot-dll** [comment]
I didn't manually install `org.freedesktop.Platform.ffmpeg` and it seems to be automatically installed. Probably @antenore you were using the deprecated GNOME repo rather than Flathub
