### ISSUE TITLE
make sessions in the NX session dialog double-clickable

### ISSUE THREAD

**Issue by calestyo** [FreeRDP/Remmina#16]
This is from: https://sourceforge.net/tracker/?func=detail&aid=3486871&group_id=278330&atid=1181677

Hi.

In the NX plugin, when the session dialog comes up where one can create new, terminate old or restore sessions it would be nice, if the session is restored, if on double clicks it in the list of sessions.

Cheers,
Chris.

**Comment by muflone** [comment]
Fixed in the branch next
