### ISSUE TITLE
cmake install prefix bug

### ISSUE THREAD

**Issue by Shumen** [FreeRDP/Remmina#160]
CMake Error at remmina/icons/cmake_install.cmake:44 (FILE):
  file INSTALL cannot set permissions on
  "/icons/hicolor/16x16/actions/remmina-fit-window.png"
Call Stack (most recent call first):
  remmina/cmake_install.cmake:58 (INCLUDE)
  cmake_install.cmake:41 (INCLUDE)

It seems that the script install some resource to root / directory, when I execute make install.

**Comment by muflone** [comment]
You have to specify the install prefix in the cmake command line.
Closing this issue, invalid.
