### ISSUE TITLE
Remmina refactoring - Merge 'next' in 'master' and switch back to master

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#1602]
In the next days I'll switch back the main branch to use the master branch.

This could have some impacts on those distributions that are still providing an old Remmina package, but it will be in charge to them to point to the right commit or tag and not pointing directly to master.

I'll update/write the documentation of the workflow to follow when developing on Remmina, in then meanwhile let me know your thoughts if any.

## Workflow/rules proposal

1. Never ever rebase or rewrite the history if you can.
We are having too many troubles because of the many times we have rewritten the history.
2. Master is the main branch to be used for new releases/tags.
Any changes you need to do, create a feature-branch or an issue-branch, and than open a pull request or merge directly in "master".
3. 'Next' will be set in read only and we will delete it ASAP.

@giox069 @larchunix @amtlib-dot-dll 
cc @3v1n0 @mfvescovi 

EDIT: Rewritten as per comments.

**Comment by larchunix** [comment]
I don't understand the added value to keep the next branch.

Why don't use the more classic workflow of development being done on master and creating maintenance branches from tags if needed?

**Comment by antenore** [comment]
@larchunix yes it may be viable as well and easier. The only reason I was thinking to keep next is because some distributions were using the master branch (directhly), so everytime were doing a commit, some "remote" maintainer was jumping in and complaining because the master was not stable enough. We had a bad discussion with a Debian maintainer for instance, but at the end today, these kind of issues should have been fixed, most are using tags or traballs from specific tag or commit.

So yes, why not, I would just avoid direct commits in master and follow the fork/merge schema.

I'll update the text later.

**Comment by giox069** [comment]
The master branch was kept alive with its own developement to keep Remmina 1.1, the version compatible with freerdp 1.1, from 2014 to 2017. The branch was not abandoned: it had its own updates, different commits from the "next" branch for version 1.2.
Now most linux distributions switched to freerdp2, so we can destroy it.

**Comment by antenore** [comment]
@giox069 we don't destroy the master branch, but we merge 'next' into 'master' and we get rid of next.

This way we don't lose the history and we use 'master' as the main branch as it's more "standard" and logic.

**Comment by antenore** [comment]
Updated.

So we are almost ready for the v1.2.1 :-)

**Comment by mfvescovi** [comment]
@antenore why don't you simply rename branches? master becomes v1.1, next becomes master and create a new "develop" for next release. Just my .02

**Comment by antenore** [comment]
@mfvescovi Thanks, branch renaming it's very tricky and basically it even does not exists. More over with new versions of git it's not allowed to rename a remote master branch, so ys, it's an idea, I've done some tests that miserably failed one way or the other and than I've deleted everything as I was quite p...ed off :-) 

I'll definitively look at this again, but I'm still convinced that the merge is the way to go, at least it's the cleanest (or it should).

**Comment by antenore** [comment]
I've created a new branch "oldmaster" that is a copy of the current master.

https://github.com/FreeRDP/Remmina/tree/oldmaster

Before the end of this week I'll reset master to next, therefore the new master will be a copy of next.

Till that moment you can continue to commit in next, but as soon as I'll do the reset, you will have to start from a fresh checkout from master and start to work on it (not anymore on next).
I will set next readonly some days and than delete as soon as all the maintainers will be notified.

If this week is too early and you need more time let me know.

Hopefully, before Wednesday of the next week, we will tag a new version v1.2.30 that will be an official, stable, release. I'd like as well to release a new snap stable and a new flatpak.

For any disagreement and or doubts contact me and/or Giovanni.

**Comment by antenore** [comment]
I'm resetting master to next right now.

It means that master will be "refreshed" to the code we have currently in the next branch.
I'll set next to read only, few days, just the time to organize the communication with all the package maintainers we know and prepare for the release.

@amtlib-dot-dll @larchunix @giox069 @mfvescovi @3v1n0

**Comment by antenore** [comment]
DONE. Next is read only and oldmaster as well.
Please use a fresh copy of master for all new PRs
