### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by TerkiKerel** [FreeRDP/Remmina#1605]
Can you please provide official nix packages?

Thank you

**Comment by antenore** [comment]
What do you mean? Did you read the README and the wiki? What do you miss exactly?

**Comment by giox069** [comment]
We (upstream programmers) usually does not provide packages. We can't: a lot of time is needed to create, maintain and update a package. Packages are usually provided by someone else. For example, Debian packages are provided by Debian maintainers, Fedora packages by Fedora maintainers, Arch Linux packages by Arch Linux maintainers. There is an exception: we only maintain an Ubuntu PPA (and a generic SNAP package), but we still rely on other's people help also for these kinds of packages too.
So, if someone needs another packaging system, he/she is welcome to create and provide it. We will be happy to add it to the list of available packages.

**Comment by TerkiKerel** [comment]
I understand. Thank you :1st_place_medal:
