### ISSUE TITLE
No shared folder when connecting to console

### ISSUE THREAD

**Issue by Forage** [FreeRDP/Remmina#161]
I'm trying to access a shared (local) folder when connecting to Windows Server 2003 in console mode. It does show up when connecting to the server normally, but not in console mode. It does work when I connect to the server from Windows 7.

Local:
- Ubuntu 12.10 (x64)
- Remmina 1.0.0-1ubuntu8 (0.9.99.1 in About dialog)
- FreeRDP 1.0.0-1ubuntu7

Remote:
- Windows Server 2003 R2 Standard Edition, SP2

Let me know if you need any more information.

**Comment by Hubbitus** [comment]
What versions of freerdp and remmina do you use? Most shared folder issues has been fixed in https://github.com/FreeRDP/Remmina/issues/243. Could you please confirm?

**Comment by antenore** [comment]
Please open a new issue if you still have problems with the last (branch next) remmina version
