### ISSUE TITLE
Feature request - Improve UI

### ISSUE THREAD

**Issue by pieton** [FreeRDP/Remmina#1638]
**We support Remmina 1.2+ versions only.** 
*Do not report bugs related to older Remmina versions!* 
 
## Local System Description

* Client (OS name and version):
* Remmina version ( ```remmina --version``` ):
* Installation mean:
  - [X] Distribution package.
  - [ ] PPA.
  - [ ] Snap.
  - [ ] Flatpak.
  - [ ] Compiled from sources.
  - [ ] Other - detail:
* Desktop environment (GNOME, Unity, KDE, ..):
Kubuntu 18.04

* Plugin:
  - [X] RDP - freerdp version ( ```xfreerdp --version``` ):
  - [ X] VNC
  - [X ] SSH
  - [ ] SFTP
  - [ ] SPICE
  - [ ] EXEC
  - [ ] Other (Please specify):
![remina-kubuntu-default](https://user-images.githubusercontent.com/8570370/40273068-329c4ec8-5bb1-11e8-84ad-65cdc930ffcf.jpeg)

## Problem Description

Hi,

Can you make the + Tab more clear and it's functionality more clear ?

It is not easy to see that this is where you edit a profile or configure the defaults.

See attached for how difficult it is to see on default Kubuntu 18.04.

Changing the colour/contrast of the + would help as would including a link under the burger menu.

thanks

**Comment by antenore** [comment]
@pieton That is a theme issue and not a Remmina problem :-\ 
The problem that is visible in your screenshot and it's "Remmina" fault is the headerbar placement (I've fixed this few days ago).
But the fact that the plus sign is not visible it's a Kde theme problem, I really don't know how to help you.

Just as a demonstration, choose the default vanilla KDE theme and you will see the plus sign.

**Comment by antenore** [comment]
#1546
![image](https://user-images.githubusercontent.com/5975/40273217-accbb818-5bbc-11e8-9f90-ac4fd169832a.png)

**Comment by antenore** [comment]
Closing. If you need more support feel free to join us on G+, or reddit
