### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by hafizahmmed** [FreeRDP/Remmina#1644]
Hi, 
Good day, sir, my name is MD Hafiz Ahmmed. I am a Graphic designer. I saw one of your posts that you need a logo for this project. If you allow me I will make the logo for you.

![logo](https://user-images.githubusercontent.com/38810169/40440133-fc258888-5ede-11e8-84f3-c292a933d318.jpg)

Thank you

**Comment by antenore** [comment]
Sorry @hafizahmmed I have to delete this post as the github issues is not intended for this kind of discussions. The logo and icon redesign is already in progress.
