### ISSUE TITLE
Remmina will not load RDP plugins 

### ISSUE THREAD

**Issue by lowwalker** [FreeRDP/Remmina#165]
Fedora 18.x86_64 

With all the plugins loaded, still can't get remmina to show RDP sessions.

**Comment by kuchaguangjie** [comment]
Cool, and if u are on gnome desktop, don't forget to install `remmina-plugin-gnome`

**Comment by benabrahamson** [comment]
@kuchaguangjie actually ```remmina-plugins-gnome```

**Comment by kuchaguangjie** [comment]
@benabrahamson I am using linux mint mate 17.1 (`Linux 3.16.0-38-generic #52~14.04.1-Ubuntu x86_64 GNU/Linux`), which is base on ubuntu 14.04, and it is `remmina-plugin-gnome`, without the `s`.

**Comment by haythamdouaihy** [comment]
@quasarj thanks, i tried your solution and it works

**Comment by CVAS7** [comment]
For Fedora , Add the pulgin by using bleow command
sudo yum install remmina remmina-plugins-common remmina-plugins-gnome remmina-plugins-rdp remmina-plugins-vnc

**Comment by AlinGabriel** [comment]
this issue still persisting, worked after @quasarj explanation. Thank you!
