### ISSUE TITLE
feature request: credentials management

### ISSUE THREAD

**Issue by mmiat** [FreeRDP/Remmina#1651]
it'd be very useful to have a credentials management: many servers are in the same environment, with one AD server, and the user is all the same, when you change password you have to update all saved connections/profiles. same for ssh. please add the option to create users and use them in multiple connections.
thanks

**Comment by antenore** [comment]
If you have Remmina 1.2, this feature exists already, there is password changer under the menu

**Comment by mmiat** [comment]
ok thanks
a clarification: it requires gnome-keyring and doesnt work by default in kde
