### ISSUE TITLE
clipboard not working

### ISSUE THREAD

**Issue by thiagobucca** [FreeRDP/Remmina#1652]
**We support Remmina 1.2+ versions only.** 
*Do not report bugs related to older Remmina versions!* 
 
## Local System Description

* Client (Ubuntu 18.04):
* Remmina version ( ```1.2.0-rcgit-29 (git rcgit-29)``` ):
* Installation mean:
  - [X] Distribution package.
  - [ ] PPA.
  - [ ] Snap.
  - [ ] Flatpak.
  - [ ] Compiled from sources.
  - [ ] Other - detail:
* Desktop environment (GNOME 3.):
* Plugin:
  - [X] RDP - freerdp version ( ```xfreerdp --version``` ):
  - [ ] VNC
  - [ ] SSH
  - [ ] SFTP
  - [ ] SPICE
  - [ ] EXEC
  - [ ] Other (Please specify):
* Gtk Backend (Wayland, Xorg, ??):
* Optional: include the output of the following commands at the end of this text:
  - `remmina --full-version`
  - `  *-display                 
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:48 memory:a0000000-a03fffff memory:90000000-9fffffff ioport:2000(size=64) memory:c0000-dffff
`
  - `4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

## Remote System Description

* Server (WIndows Server 2012): 

## Problem Description

Hi, clipboard is not working between Host (Ubuntu 18.04) and Guest (Windows Server 2012)
i installed via apt-get remmina in terminal.

**Comment by thiagobucca** [comment]
I Solved it using ¨Share Folder¨ option.

**Comment by antenore** [comment]
Strange anyway, thanks for reporting

**Comment by giox069** [comment]
What did you tried to copy&paste? Files or text/images? Copy&paste of files is not currently implemented in remmina.

**Comment by thiagobucca** [comment]
@giox069 Yes, i misunderstood the current remmina clipboard support and thought it was supposed to work when copying and pasting files. Text copy&paste always worked for me. Now i´ḿ transferring files with the Share Folder option and i´ḿ very happy with it. Thanks.
