### ISSUE TITLE
The mouse pointer theme is not respected

### ISSUE THREAD

**Issue by herrenP** [FreeRDP/Remmina#1668]
## Local System Description

* Client (OS name and version): **Ubuntu 18.04 LTS (Bionic Beaver)**
* Remmina version ( ```remmina --version``` ): **1.2.30.1 (git cf309b0)**
* Installation mean:
  - [ ] Distribution package.
  - [ ] PPA.
  - [X] Snap.
  - [ ] Flatpak.
  - [ ] Compiled from sources.
  - [ ] Other - detail:
* Desktop environment (GNOME, Unity, KDE, ..): **GNOME**
* Plugin:
  - [ ] RDP - freerdp version ( ```xfreerdp --version``` ):
  - [X] VNC
  - [ ] SSH
  - [ ] SFTP
  - [ ] SPICE
  - [ ] EXEC
  - [ ] Other (Please specify):
* Gtk Backend (Wayland, Xorg, ??): **Xorg**
* Optional: include the output of the following commands at the end of this text:
  - `remmina --full-version`
```
(remmina:32550): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
Remmina - SNAP Build - 1.2.30.1 (git cf309b0)
NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
EXEC                Protocol        Execute a command                                               1.0       
NX                  Protocol        NX - NX Technology                                              1.2.30.1  
RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.2.30.1 (git cf309b0), Compiled with FreeRDP lib: 2.0.0-dev3 (dad6b7a), Running with FreeRDP lib: 2.0.0-dev3 (rev dad6b7a), H264: Yes
RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.2.30.1 (git cf309b0), Compiled with FreeRDP lib: 2.0.0-dev3 (dad6b7a), Running with FreeRDP lib: 2.0.0-dev3 (rev dad6b7a), H264: Yes
RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.2.30.1 (git cf309b0), Compiled with FreeRDP lib: 2.0.0-dev3 (dad6b7a), Running with FreeRDP lib: 2.0.0-dev3 (rev dad6b7a), H264: Yes
SFTP                Protocol        SFTP - Secure File Transfer                                     1.2.30.1  
SPICE               Protocol        SPICE - Simple Protocol for Independent Computing Environments  1.2.30.1  
SSH                 Protocol        SSH - Secure Shell                                              1.2.30.1  
VNC                 Protocol        VNC - VNC viewer                                                1.2.30.1  
VNCI                Protocol        VNCI - VNC viewer listen mode                                   1.2.30.1  
XDMCP               Protocol        XDMCP - X Remote Session                                        1.2.30.1  
glibsecret          Secret          GNOME libsecret                                                 1.2.30.1  
```
  - `sudo lshw -C video`
```
  *-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:129 memory:eb000000-ebffffff memory:a0000000-afffffff ioport:f000(size=64) memory:c0000-dffff
```
  - `uname -a`
```
Linux --- 4.15.0-18-generic #19-Ubuntu SMP Thu Apr 19 22:36:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
## Remote System Description

* Server (OS name and version): **Windows 10 Pro**
* Special notes regarding the remote system (i.e. gateways, tunnel, etc):  **None**

## Problem Description

- I have this mouse pointer theme enabled on the remote machine: https://randomacronym.deviantart.com/art/Cursor-Sans-Family-v1-5-1-468397737
- I have this mouse pointer theme enabled on my local machine: https://github.com/keeferrourke/capitaine-cursors

When I connect to the remote machine my local theme is used to show where the mouse pointer is instead of the remote machine's theme. I have selected "Best" as my quality for this remote session. The only way I know to get the mouse pointer theme to be respected is to change the remote machine's theme to something random and then back to the one I want while in the current remote session.

**Comment by herrenP** [comment]
I have not tested if this is a VNC only issue.

**Comment by herrenP** [comment]
Actually, it's possible that this was fixed by activating "Enable mouse pointer shadow" in Windows on the remote machine.

I will close when I know more. Probably tonight or tomorrow.

**Comment by herrenP** [comment]
No, the shadow option did not help. This still occur for me. I now believe it happens either after the local machine has rebooted, or when remote machine has rebooted.

Working around like I mentioned in the "Problem Description" and then restarting Remmina does not make this occur.

**Comment by antenore** [comment]
Do you have another vnc client just to validate that it's a remmina/libvnc issue?

Thanks

**Comment by herrenP** [comment]
I do actually. None that should be running as far as I know though.

My local machine:
```
➜ dpkg --list "*vnc*" 
...
un  libgtk-vnc-1.0-0               <none>               <none>               (no description available)
ii  libgtk-vnc-2.0-0:amd64         0.7.2-1              amd64                VNC viewer widget for GTK+3 (runtime libraries)
ii  libgvnc-1.0-0:amd64            0.7.2-1              amd64                VNC GObject wrapper (runtime libraries)
ii  libvncclient1:amd64            0.9.11+dfsg-1ubuntu1 amd64                API to write one's own VNC server - client library
un  libvncserver0                  <none>               <none>               (no description available)
un  tigervnc-common                <none>               <none>               (no description available)
ii  tigervnc-viewer                1.7.0+dfsg-8ubuntu2  amd64                Virtual network computing client for X
un  vnc-viewer                     <none>               <none>               (no description available)
un  vncviewer                      <none>               <none>               (no description available)
un  xtightvncviewer                <none>               <none>               (no description available)
```

```
➜ ps aux | grep vnc    
---       2951  0.0  0.0  15972  1104 pts/0    S+   16:55   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn vnc
```

Remote machine:
```
TightVNC 2.7.10.0
```

**Comment by herrenP** [comment]
I wonder if the issue is really the OS of the remote machine. Maybe the chosen themes isn't even active even though the mouse option dialog tell me that it is.

**Comment by herrenP** [comment]
Yeah, it sounds like that on https://answers.microsoft.com/en-us/windows/forum/windows_7-desktop/custom-mouse-cursors-reset-on-restart/e80690de-314e-e011-8dfc-68b599b31bf5. I am currenly trying the work around found in "Jonpwn's" comment posted April 11, 2011 on page 1.

**Comment by antenore** [comment]
I really don't know how to help you. I use x11vnc on the remote server and even if it's a bit more limited than tiger vnc, I don't have such behaviour.

Remmina misses a VNC maintainer at the moment, we just keep fixing obvious bugs till someone will jump in helping out.

We use [libvnc](https://libvnc.github.io/), it's quite well documented, so it should not so hard...

If you know anybody who would help we will be more than happy to support her/him

**Comment by herrenP** [comment]
Thank for the reply @antenore. I hope the work around in my comment above will fix this. I will probably know more tomorrow and close this ticket if it worked.

**Comment by herrenP** [comment]
Issue was fixed with the work around I linked to in [my comment above](https://github.com/FreeRDP/Remmina/issues/1668#issuecomment-396557580).
