### ISSUE TITLE
net-misc/remmina-1.0.0_p20121004 fails rsa-key auth on X11Forwarding-enabled OpenSSH server

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#168]
Working under migration on net-misc/remmina (using Gentoo GNU/linux build on amd64-system) as ssh-client just today I've find that it fails to connect with some of typical servers (FreeBSD 7.3-RELEASE-p2 #0: Mon Jul 12 19:23:19 UTC 2010     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64).
The servers' logs showed no, errors, but remmina fails to open remote terminal, showing two different errors for two issued servers:
The first one is:
Аутентификация по публичному ключу SSH не удалась: Parsing private key /home/user/.ssh/id_rsa: error:0906A065:lib(9):func(106):reason(101)
The seconf one:
Аутентификация по публичному ключу SSH не удалась: Access denied. Authentication that can continue: publickey,keyboard-interactive

Further analyse showed, that the only difference between servers was:
X11Forwarding yes

The issue also was reproduced on my wokstation (everywhere I've used user-selected key file).
Password-base authetication works correctly in both cases (X11Forwarding enabled and disabled).

**Comment by Hubbitus** [comment]
It some sort of duplication of https://github.com/FreeRDP/Remmina/issues/83, #223 and #235 (or in different order). If ~/.ssh/config will be properly handled all ControlMaster, tunnels, agent forwardings and proxy commands may be defined there.

What versions of freerdp and remmina are you use? Is it actual now?

**Comment by giox069** [comment]
Bug too old. In remmina 1.2 ssh support has been completly renewed. Please reopen issue with updated informations.
