### ISSUE TITLE
remmina incorrectly handles saved terminal size for ssh-connection

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#169]
I use remmina on primarely stable branch of amd64 Gentoo GNU/Linux.
As asked dowstream (https://bugs.gentoo.org/show_bug.cgi?id=461484), issue's reproducibility was approved by git-version (yesterday's build).

If ssh-terminal window size was changed, re-opening ssh-terminal for stored connection showes blank black window, and only resizing window in current session displays ssh session data.
Opening newer ssh-connections (tabs in this terminal) starts correctly, doesn't requireing terminal window resize.

Opening new connection resets terminal window size to default.
But opening stored (with remembered non-default terminal window size) connection in such (terminal-size, resetted on default) case showed same issue (blank black window, requireing resize to display ssh session data).

The easiest workaround I see is to add an option like "Reset terminal size to default", but it is not a solution.

What additional data could be useful in work under this issue?

**Comment by ssten** [comment]
Fixed in 1.1.2.

**Comment by giox069** [comment]
Thank you for reporting.
