### ISSUE TITLE
Cannot connect to VNC servers using IPv6

### ISSUE THREAD

**Issue by robled** [FreeRDP/Remmina#170]
I'm running Ubuntu 12.10 and I'm using Remmina 1.0.0-4~441+19~quantal1 from this PPA:

https://launchpad.net/~freerdp-team/+archive/freerdp

I've got a VNC server accessible via IPv6, but Remmina is unable to connect to it.  In the GUI I get this error message:

"Couldn't convert 'myhost.example.dom' to host address."

![remmina-ipv6](https://f.cloud.github.com/assets/3211560/277636/39d8d904-90cd-11e2-92df-feb23e290992.png)

I tried running Remmina from the command line to get more information, but none was presented in the terminal.  Steps to reproduce:

1.  Connect to a VNC server using IPv6 (DNS hostname or IPv6 address using bracket notation)
2.  Wait 10 seconds or more
3.  See error message described above.

Supplemental info:

* Server is running x11vnc and is listening on IPv6
* I can connect to the same x11vnc server using the xvnc4viewer client via IPv6

**Comment by Hubbitus** [comment]
Hello.
It seams long outstanding bug with regression: https://bugzilla.redhat.com/show_bug.cgi?id=1176406

**Comment by ic3d** [comment]
@robled Sorry for this _very_ late answer, do you still experience this problem with the latest release of Remmina?
Thanks.

**Comment by giox069** [comment]
VNC connection is delegated to [libvncclient](http://libvnc.github.io/).
I did some testing:

- connecting to an IPv6 host using a numeric IPv6 address should work, but you must enclose it within brackets, i.e: **[fd10:XX9e:XXXX:9df:eea8:6bff:fef4:b99]:5901**
- if you connect to an IPv6 which contains a "%" sign (for local scope ID), libvncclient will fail telling you that hostname could not be resolved. This seems to be a bug of libvncclient.
- I did no testing using an hostname which resolves into IPv6.

In any case, please note that remmina can do nothing to fix it: you should open a bug in [libvncclient](http://libvnc.github.io/) project.
