### ISSUE TITLE
LIBVNCSERVER_WITH_CLIENT_TLS is never defined

### ISSUE THREAD

**Issue by gber** [FreeRDP/Remmina#173]
Since the removal of the inline libvncserver copy the LIBVNCSERVER_WITH_CLIENT_TLS macro is not defined any more and TLS support code is always disabled in the VNC plugin.
##

**Comment by ic3d** [comment]
@gber can you explain better what's the problem? Do you still get it using the last version of Remmina?

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina that is now out of date.
