### ISSUE TITLE
Cant see the Windows login screen while RDPing to a machine

### ISSUE THREAD

**Issue by Mynom** [FreeRDP/Remmina#174]
In version 1.0.0 (on Fedroa 18) I cannot see the login Screen Windows offers. So I have to know the User and Domain I want to use, instead of just clicking it on the login screen.

It is nice to save the credentials in Remmina, but please give me the option to skip it, and see the Window login screen, like it was in the older Version.

**Comment by antenore** [comment]
Do you still have the issue with the last Remmina version?

**Comment by antenore** [comment]
Too old, closing
