### ISSUE TITLE
SSH: missed check availability of PubkicKey Auth on remote host before asking passphrase

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#176]
Using remmina-1.0.0_p20121004 on amd64 Gentoo GNU/Linux I've find the following issue:
1. New connection with custom-file client key auth;
2. No user's public key file on remote server (so, pasword-base auth used);
3. But remmina asks _passphrase_.
4. After typing it reports error.

I expect reporting result of public key auth availability (in both cases^ auto-select and user set private key file) before asking passphrase.
So, on step 3 see error message something like:
"Selected auth mechanism is unavailable".
##

**Comment by antenore** [comment]
We have to review the SSH plugin

**Comment by antenore** [comment]
Closed by #1196
