### ISSUE TITLE
Can't attach to Windows console

### ISSUE THREAD

**Issue by mikioma** [FreeRDP/Remmina#177]
Hi!

I'm using Remmina under ArchLinux and I cannot attach to a Windows Console screen, even though I do check the setting intended to do so (It's under the "Advanced" settings tab).

I've tried it under Fedora 17 and it does work fine.

Also tried launching the connection via "rdesktop -0 ..." command line, and it also works.

The only difference I notice is that Fedora 17 uses "freerdp-1.0.1" whereas Arch uses "freerdp-1.0.2".

Hope it helps.

Please, if I should report this as a bug to Archlinux, tell me so and I'll do.

Thanks so much!

**Comment by antenore** [comment]
Do you still have the issue with the last Remmina version?

Can you also please try with the xfreerdp command line?

**Comment by mikioma** [comment]
Hi!!

xfreerdp worked when remmina didn't (by the time I issued this problem).

Now, I've just tried it with Remmina's latest version... and it works!!!!

Should I mark this issue as "solved"

Thanks so much. Kind regards,

2015-06-25 23:33 GMT+02:00 Antenore Gatta <notifications@github.com>:

**Comment by antenore** [comment]
@mikioma this is a really good news :-)
