### ISSUE TITLE
Remmina Hangs/Stucks at second login to RD Server

### ISSUE THREAD

**Issue by luponec** [FreeRDP/Remmina#179]
Package: remmina
Version: 1.0.0-4+deb7u1
Architecture: armhf
Hardware : rasperry PI rev. 2  512MB RAM

This is very strange and not so easy to explain for a not native english language ..but I will try.

Client (Raspbian “wheezy”.) and server (Win7 Ultimate on Intel Quad-core 8GB RAM)  are connected via a cross cable at 100Mb Full Duplex so that no switch,  FW and router could create issue in the middle. 
In server machine  antivirus, FW, and all security tools are all disabled.

 I open remmina and create a new session. I connect to RD server using session I just created and all is fine:  Video / Audio OK, client folders on server OK, printer OK.
Nice job by the way ...this program is awesome.  
BUT
I close session with a regular disconnect  and  I try to re-open same session to same server from same client.  Windows machine prompt via RDP  for username and password  and after I login  all is freezed. 
Only way to quit remmina is to  kill it by command line or task manager.
I tried again and again and only solution I found was  to delete the current connection  restart the program and create a new connection  which will work first time then stucks again at second login to RD.  Not a simple way to use it. 
I thought it was a server related issue so I tried  to open same server from another RDP client on a win machine and all was  fine. Server warned me about  user was already logged in and it will kick him if I login again hmm .   So tried again from rasp and after error with remmina I opened  same server from same client rasperry machine with command line rdesktop and  xfreerdp  and it worked  with them. 
After 100 tests I decided (just to be faster) to save username and password in remmina client,  and here the surprise. All was ok and I can use and reuse the saved session.
I tried to save only user and issue was back again.
I tried to create 3 different sessions with 3 different users and everything was fine for all of them but the fact it worked just if I saved username and password in remmina.
Now this could not be an issue in a test environment but I'd like to use remmina on a server that forces password change  monthly and I wouldn't like to give users instructions to change password in the client,  infact my goal is to launch remmina at boot time with no user interaction but to put user and password on the RD Server.
I tried to launch remmina from terminal to check if I could see any error message but I saw no log after the lines of  connection to remote server is logged as successfully and prn1 too.
I tried to strace it but was too long and complex for me to read.  If you need it I can send it.

Now what ? 
I can reproduce the issue
I can give you output if you suggest me what/how  to log

Tnx in advance for the attention and your help.
Regards

Lupone C@tiivo 
##

**Comment by ic3d** [comment]
@luponec @makinux-git do you still get this problem using the latest version of Remmina?

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
