### ISSUE TITLE
do ssh server host key check with the NX plugin

### ISSUE THREAD

**Issue by calestyo** [FreeRDP/Remmina#18]
This is from: https://sourceforge.net/tracker/?func=detail&aid=3402157&group_id=278330&atid=1181677

Hi.

With the NX plugin (and any other plugins using SSH) it would be great if the plugin would verify the SSH server host keys, when connecting (and before sending any sensitive stuff).

I'd suggest to let people either specify a pub-key file in the GUI itself (just as they can specify a client secret key now) or it should fall back to use the normal ssh known hosts locations (/etc/ssh/ssh_known/hosts, ~/.ssh/known_hosts.. at least those are the default location,.. perhaps some ssh config parsing might become necessary).

If no key is found, it should fail (not just with a warning) or allow to take the key over (but then of course only with displaying the fingerprints/etc. and not into the ssh keyrings but as separate key file, e.g. in ~/.remmina/

Cheers,
Chris.

**Comment by antenore** [comment]
This should be implemented and working correctly. Don't hesitate to reopen i needed (with more details).
