### ISSUE TITLE
remmina remote desktop -- erratic partial display issue

### ISSUE THREAD

**Issue by kamaleshpatil** [FreeRDP/Remmina#181]
When I RDP to my work desktop, every once in a while, a certain square (or maybe rectangular) area of screen starts displaying duplicate image of area around my cursor. Please see attached screenshots.
The area where duplicate rendering happens, seems to be mostly in middle of screen although that may be mostly because thats where my mouse is most of the time when I come out of "full screen" mode; and when I enable full screen mode again it becomes the spot for duplicate rendering.

The issue happens to be mostly when I am in full screen mode, although that may be because I use full screen mode almost all the time when using RDP.

I am running Ubuntu 12.10 Desktop x64.

Sorry for the rather verbose and less technical description of this bug.

Thanks for your time, effort and dedication.

**Comment by maxvodo** [comment]
Huh, old issue...
I think I have similar issue. In my case, when mouse pointer inside of guest area, cursor sometimes disappeared or cursor becomes virtually invisible:
![screenshot from 2015-03-04 13 32 43](https://cloud.githubusercontent.com/assets/5998258/6482001/32939fb0-c273-11e4-9dcf-84677fdec5fe.png)
And this is normal cursor in host mode (over host window):
![screenshot from 2015-03-04 13 32 57](https://cloud.githubusercontent.com/assets/5998258/6482002/329414fe-c273-11e4-91d7-35069755dead.png)

Also, in remmina package from official repo and I wasn't seen something like that.
Host OS: Ubuntu 12.04 LTS, x64, Elementary OS Luna. 
Guest OS: Windows 2003.
Build: Remmina was build from sources (working dir state @0ac7a833c890b275e19e750ccce208d1ac5c7d83)

**Comment by giox069** [comment]
Please check to have Remmina 1.2 (or 1.1) installed. Read the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for info on upgrading.

**Comment by maxvodo** [comment]
Checkout branch v1.2.0-rcgit.2 (@93bf25e8ec2e69ca9d807e351675d333a5a3ddfc), clean make, remmina version 1.2.0-rcgit.2 (about dialog) still has issue. 
Trying compile "next" branch of remmina (with "master" branch of freerdp) do follow compilation errors (gtk version: 3.4.2-0ubuntu0.8).

**Comment by giox069** [comment]
This issue is a bit confusing: the original author opened an issue talking about "replication of small rectangular area". @maxvodo: do you see replication of small rectangular area ? If not, please open another issue for mouse disappearing in RDP connection (o something similar), and I will close this old one.

**Comment by maxvodo** [comment]
@giox069: Nope, i don't see anything like this issue. You are right. #514

**Comment by giox069** [comment]
Thank you @maxvodo. Closing this one because the RDP problems refers to oldev version of remmina and Freerdp, they have changed too much in the meanwhile. @kamaleshpatil: please reopen it if you still see strange squares in newest remmina (1.2).
