### ISSUE TITLE
Crash in BitBlt_SRCAND_32bpp, BitBlt_32bpp

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#186]
Could anyone look on it?
It initially reported into Fedora (RedHat) bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=843025 but have not any movement long time.
Provided report contains full backtrace, list of opened files and many other information which may be relevant.

According to our automatic problem tracker ( https://retrace.fedoraproject.org/faf/problems/hot/*/*/remmina/ ) those errors happened frequently for our users.

With best wishes, Pavel Alexeev.

**Comment by antenore** [comment]
I think this should be fixed. Please ask for confirmation and let's close it if we don't have answers,

**Comment by Hubbitus** [comment]
Thank you. It is very old bug and reported against Fedora 17 which does not supported long time. I think it may be closed.

**Comment by antenore** [comment]
Thanks Pavel
