### ISSUE TITLE
Remmina in Fullscreen does hide Panels on other unused monitors in gnome

### ISSUE THREAD

**Issue by Hibbelharry** [FreeRDP/Remmina#188]
I have a pc with two monitors. When I open up a remote Session in Remmina on any screen the Panel(s) are hidden on all monitors as long as the session is in fullscreen, I would expect to be able to use the panel on the unused monitor. Other fullscreen apps like google chrome, firefox, gedit don't trigger the same behaviour, the panel is still usable, so i expect this to be a remmina bug.

I currently use Remmin 0.9.99.1 on Ubuntu 13.04 with Gnome 3.80 as Desktop Environment.

**Comment by ic3d** [comment]
@lyman @Hibbelharry we are now reviewing old issues, do you still get this problem with the latest version of Remmina? Thanks!

**Comment by Hibbelharry** [comment]
Haven't had that problem in a while. I think this bug is solved.

**Comment by ic3d** [comment]
Thanks @Hibbelharry, I close this issue.
