### ISSUE TITLE
Segfault after login by rdp

### ISSUE THREAD

**Issue by Anrock** [FreeRDP/Remmina#200]
Gentoo x86, remmina-1.0.0_p20121004
1. connect to windows 2003 server (tested on multiple servers)
2. enter credentials and press ok
3. remmina crashes with 
(remmina:4529): Gtk-CRITICAL **: gtk_distribute_natural_allocation: a
ssertion `extra_space >= 0' failed

Bug isn't persistent - works fine until first crash and then crashes on every login to the same server

**Comment by ic3d** [comment]
@Anrock do you still get this problem using the latest version of Remmina? Thanks.

**Comment by Anrock** [comment]
@ic3d, dunno. I've stopped using remmina and changed place of work long time ago.

**Comment by ic3d** [comment]
@Anrock thanks for the answer. I'll close this issue.
