### ISSUE TITLE
can't connect to 2008r2 when set "negotiation" security mode

### ISSUE THREAD

**Issue by emoxam** [FreeRDP/Remmina#202]
In my ubuntu 13.04 and remmina 1.0.0-4ubuntu2
when i try to connect windows 2008 r2 server i get an error "can't connect to RDP server" (in Russian)
so i learned it's setted up in "negotiation" security mode by default, if i choose RDP ot TLS i can connect.
##

**Comment by ic3d** [comment]
@emoxam @toote do you still get this problem using the latest version of Remmina?

**Comment by toote** [comment]
@ic3d I have stopped using remmina since 2013 so I wouldn't be able to confirm this is still an issue. Sorry.

**Comment by howlingc** [comment]
Currently using rcgit.11 and having this issue. Choosing Ignore certificate also fixes this in addition to changing the default security mode from negotiation to either RPD or TLS. It's the NLA method that doesn't work with some certificates.

The 2008r2 servers that I'm having this issue with have a custom certificate with some additional fields such as Subject Alternative Name. The servers using a default self-signed certificate work just fine.

**Comment by howlingc** [comment]
Just to update I updated to rcgit.15 and don't have this issue anymore. The NLA method connects just fine with all 2008r2 and 2012r2 servers that I've tried.

**Comment by ic3d** [comment]
@howlingc thank you so much! I'll close this issue.
