### ISSUE TITLE
Resolution of Client Viewport not functioning correct

### ISSUE THREAD

**Issue by andersks** [FreeRDP/Remmina#205]
Originally, when Remmina was installed, setting the resolution at "Use Client Resolution" worked great, completely filling the screen. Recently, the window opens in full screen, but with borders. Clicking the toolbar to display full-screen does not function correctly. Instead it shifts the display down and to the right. Only option is to not use the "Use Client Resolution" option.
##

**Comment by ic3d** [comment]
@andersks do you still get this problem using the latest version of Remmina?

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina. We only support the Remmina 1.2.* branch.
