### ISSUE TITLE
Copy paste clipboard does not work

### ISSUE THREAD

**Issue by acvt007** [FreeRDP/Remmina#207]
I use Remmina 1.0.0-4 with ubuntu 12.04 LTS 64. It seem can not use clipboard sync to windows 8 x64.

**Comment by Hubbitus** [comment]
I think it was already fixed in https://github.com/FreeRDP/Remmina/issues/280

**Comment by giox069** [comment]
@Hubbitus you are right: this issue has already been fixed in Remmina 1.1 and 1.2. I'm closing it now.

**Comment by naisanza** [comment]
I'm using version 1.1.0 and it the clipboard does not sync for me. It did, once, unidirectionally, but then, not again.
