### ISSUE TITLE
clipboard sync is enabled per default

### ISSUE THREAD

**Issue by calestyo** [FreeRDP/Remmina#209]
From: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714590

It seems that remmina activates clipboard sync per default

As clipboard sync is very security critical (any sensitive content
from the root password to your private key might be in the clip
boad) this should NEVER be done automatically...

Actually, one should even warn users from the consequences of
activating it.

Cheers,
Chris.

btw: I'd even consider the enabling of sound forwarding per default as a security hole... and it should likewise be disabled and users be warned.

**Comment by meoso** [comment]
if the authors change this, it is *critical* to have the option available.  my work requires multitudes of copy/pastes between client and host.

**Comment by Hubbitus** [comment]
I disagree. Its not secure at all leave password authentication for root or copy in clipboard private key.

Enable by default future used in everyday basis in desktop GUI client is must have.

**Comment by antenore** [comment]
Security is a must and it's something we always keep an eye on, but the Remmina project doesn't have enough resources yet to fix these kind of issues.
I'm going to close this bug report, but we will consider, in the future, to improve farther the Remmina security and we will surely take into account your precious input.

**Comment by calestyo** [comment]
You don't have the resources to change a boolean value that swaps the default? ...what the f***?

**Comment by antenore** [comment]
I understand partly your frustration and, again, this may be an important fix, but:

1. Changing the default behavior it's not just a matter of swapping a boolean value.
2. The default behavior is what the normal users wants and need.
3. Your request, as is, it would brake the user experience.
4.  Security it's not just a matter of switching on/off the clipboard.

So, **for now**, we wont implement this, but we will do it in the future with other security fixes I'm thinking about.

In the meanwhile some workaround are:

* Run remmina with a different user 
* Run Remmina in a secondary X server
* Run Remmina in a dedicated VM or better on a thin client used only for this purpose.

With the above, not only your clipboard will be safe but also the rest of the system.

Now, regarding your polite reply, I'll reply to you with the same politeness, we can then come back to a more civil way to discuss if you want.

As it's so simple for you, and indeed it is, to implement this feature, do it yourself and propose us a pull request. 

If you don't know how to do it, shut the f*** up! Alternatively you can find and pay, with real money, not with some peanuts, a developer and ask him/her to do it (roughly 3 man-hours of job, knowing the code).
 
This is a FLOSS project, managed in the free time by people that don't put any money in their pockets, as we couldn't live with donations, we prefer to keep the few donations to pay administration fees.

So yes, it happens that we have a job and a family between one commit and another. 

If you come here just pretending, you won't get anything, so please, change behavior.

**Comment by calestyo** [comment]
As for 2: Well what users want isn't necessarily the best for their own interests and proper software should take this into account.
This is why e.g. firefox doesn't just unconditionally install 3rd party plugins, even though this may be just what the user wants.

As for 1: Since changing the value in the connection setup seems to just fix the issue, I still don't understand why switching the default wouldn't easily fix this (at least for any newly created connections).

As for 3: It's not that this would be an extremely drastic change (especially as already existing connections wouldn't be affected). I highly doubt that any user who experiences new connections not having clip board sync enabled per default would fall into agony, but simply check the single option.

As for 4: Sure, there are many other parts to it. But if people keep using this as an argument for not changing anything, than bad security is just self-sustaining.


For the workarounds, only using a separate Xserver would likely help, as this would be the only certain way of getting a new clipboard context. But since a user would need to change between one X where he does his whole main work (potentially copying sensitive data like passwords) and the other where he's then doing remmina alone... this doesn't really seem feasible.

Neither different user (within the same X server) nor VM (when it's "video" is shown in the same X server) really change anything. In the former case, the clipboard would be still shared between the X server and the remmina X client (even when it runs under another user).. and in the later, many display agents for VMs just suffer form the same problematic default of having clipboard sharing enabled.
So you see already that the assumption you're making yourself, namely that "jailing" things in a VM, breaks by the very same thing remmina is doing.


Anyway... happy Christmas and that like =)
