### ISSUE TITLE
Last keys get repeated when leaving window with rdp connection

### ISSUE THREAD

**Issue by gevatter** [FreeRDP/Remmina#210]
I run an xrdp server and connect to it with remmina (0.9.99.1).

when I type something and leave the window (by mouse or alt-tab) the last keystroges get repeated. It only affects remmina, when I use rdesktop or frreerdp this doesnt happens.

I have clearly no idea how to debug this.
##

**Comment by ic3d** [comment]
@gevatter do you still get this error with the latest version of Remmina?

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
