### ISSUE TITLE
Security Bug: Keystrokes for Password Leaking through to RDP Session as Plain Text

### ISSUE THREAD

**Issue by xhococat** [FreeRDP/Remmina#218]
This is a fairly serious error.  Microsoft's RDP clients (including the one for Mac) sometimes leak a "3" or a "5" or a "3"/"5" surrounded by tab characters when logging in to an existing Windows session.  What I am seeing here is that Remmina leaks the plain text password through to the client during sign-in.  If focus in the Windows session is on the desktop, this is unseen.  But if focus is in, say, a UNIX window from an Exceed session on the PC, then the plain text password is actually passed into the UNIX window, and will likely enter the command history if a Return key follows.  I am using Ubuntu 13.04 and Reminna 0.9.99.1 as the built-in package, as a regular user.
##

**Comment by ic3d** [comment]
Hi @xhococat, do you still get this issue with the latest version of Remmina? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
