### ISSUE TITLE
remmina 200% load cpu

### ISSUE THREAD

**Issue by sineokg** [FreeRDP/Remmina#219]
when user copy paste text with remmina to windows 2008r2 terminal - remmina load cpu to 200%, please help
##

**Comment by Hubbitus** [comment]
Its time to update and try new versions of Remmina.

**Comment by ic3d** [comment]
Hi @sineokg, do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
