### ISSUE TITLE
Connecting to a VNC server with toggle scaled mode on

### ISSUE THREAD

**Issue by dbass81** [FreeRDP/Remmina#221]
Connecting to a VNC server with toggle scaled mode on doesn't display correctly for me.  After I connect I can toggle scaled mode on and off to fix it, but it doesn't display correctly with scaled mode on.

![screenshot from 2013-08-14 15 40 38](https://f.cloud.github.com/assets/5233000/965451/f8da8a88-052a-11e3-9f3f-19cb3dcd141f.png)
##

**Comment by Hubbitus** [comment]
What version of freerdp and remmina are you using?

**Comment by ic3d** [comment]
Hi @dbass81 @cbluth , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
