### ISSUE TITLE
Segfault: FreeRDP

### ISSUE THREAD

**Issue by Tavda** [FreeRDP/Remmina#222]
When you connect to RDP from the list of drop is remmina and drop all open session. Quick connect by IP works.

remmina[9732]: segfault at 0 ip 00007f39f17615f4 sp 00007f39afffed38 error 4 in libc-2.15.so[7f39f16ce000+19e000]

remmina-1.0.0_p20130723
freerdp-1.1.0_beta1_p20130710
gentoo AMD64
##

**Comment by Hubbitus** [comment]
remmina-1.0.0_p20130723
freerdp-1.1.0_beta1_p20130710
Why you have so different versions? In nay case it time to update. New versions of Remmina became mature.

**Comment by ic3d** [comment]
Hi @Tavda @garrettskj , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
