### ISSUE TITLE
Cannot connect to RDP over SSH to multiple hosts

### ISSUE THREAD

**Issue by ringe** [FreeRDP/Remmina#223]
I have several RDP over SSH connections defined in Remmina. When I connect to one, the fingerprint is stored in .freerdp/known_hosts - but for the "host" 127.0.0.1, due to the SSH tunnel.

When I try to connect to the next RDP over SSH connection, this fails with "Unable to connect to RDP server 127.0.0.1", due to the record in known_hosts.

![skjermdump fra 2013-08-22 14 25 55](https://f.cloud.github.com/assets/778570/1008491/06b13200-0b26-11e3-9b9a-fcc3a0d45658.png)

Seems like Remmina should allow several RDP to localhost to avoid this.

Workaround: Remove ~/.freerdp/known_hosts between each connection.

Permanent workardound:
```$ rm .freerdp/known_host && ln -s /dev/null .freerdp/known_hosts```

**Comment by giox069** [comment]
Is this fixed ? (see issue #373)

**Comment by QuezoQ** [comment]
Good morning.
I am new to Ubuntu.
I have an RDP connection from my pc to Wondows7, and today I threw a mistake for which the solution is to remove ~ / .freerdp / known_hosts.
How I can delete that entry?
Beforehand thank you very much.

**Comment by giox069** [comment]
Please **DO NOT** reuse closed issues. This issue is closed, and not related to your problem.

You should delete the following two files:
~/.freerdp/known_hosts
~/.config/freerdp/known_hosts

~ is your home directory (i.e: /home/myname). Search with google how to delete a file.

**Comment by ringe** [comment]
@giox069 I just **have** to comment now: Awesome response to a new user! Thank you.

**Comment by QuezoQ** [comment]
@giox069 
in fact I searched google and one of the first link was this conversation thread... but thank for commentary (Y).

@ringe thank you anyway. I found how to eliminate from the graphical application.
