### ISSUE TITLE
LinuxMint 14, cannot compile Remmina 1.0

### ISSUE THREAD

**Issue by tapin13** [FreeRDP/Remmina#224]
tapin13@tapin13-pc ~/Downloads/FreeRDP-Remmina-356c033 $ sudo apt-get install cmake intltool   libgtk-3-dev libssh-dev libavahi-ui-gtk3-dev libvte-2.90-dev libxkbfile-dev   libtelepathy-glib-dev libgnome-keyring-dev   libappindicator3-dev libgcrypt11-dev libgnutls-dev   libfreerdp-dev libjpeg-dev
Reading package lists... Done
Building dependency tree  
Reading state information... Done
cmake is already the newest version.
intltool is already the newest version.
libappindicator3-dev is already the newest version.
libavahi-ui-gtk3-dev is already the newest version.
libfreerdp-dev is already the newest version.
libgnome-keyring-dev is already the newest version.
libjpeg-dev is already the newest version.
libtelepathy-glib-dev is already the newest version.
libvte-2.90-dev is already the newest version.
libxkbfile-dev is already the newest version.
libgcrypt11-dev is already the newest version.
libgnutls-dev is already the newest version.
libgtk-3-dev is already the newest version.
libssh-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

make dir build

tapin13@tapin13-pc ~/Downloads/FreeRDP-Remmina-356c033 $ cmake --build=build .
-- Finding suggested package PTHREAD.
--   Disable this using "-DWITH_PTHREAD=OFF".
-- checking for module 'pthread'
--   package 'pthread' not found
-- Finding suggested package GCRYPT.
--   Disable this using "-DWITH_GCRYPT=OFF".
-- Finding suggested package LIBSSH.
--   Disable this using "-DWITH_LIBSSH=OFF".
-- Finding suggested package VTE.
--   Disable this using "-DWITH_VTE=OFF".
-- Finding suggested package APPINDICATOR.
--   Disable this using "-DWITH_APPINDICATOR=OFF".
-- Finding suggested package Gettext.
--   Disable this using "-DWITH_GETTEXT=OFF".
-- Finding suggested package LIBSSH.
--   Disable this using "-DWITH_LIBSSH=OFF".
-- Finding suggested package FREERDP.
--   Disable this using "-DWITH_FREERDP=OFF".
-- Finding suggested package TELEPATHY.
--   Disable this using "-DWITH_TELEPATHY=OFF".
-- Finding suggested package ZLIB.
--   Disable this using "-DWITH_ZLIB=OFF".
-- Found libgcrypt: /lib/i386-linux-gnu/libgcrypt.so
-- Finding suggested package Gettext.
--   Disable this using "-DWITH_GETTEXT=OFF".
-- Finding suggested package AVAHI.
--   Disable this using "-DWITH_AVAHI=OFF".
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tapin13/Downloads/FreeRDP-Remmina-356c033

make

[ 32%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_string_list.c.o
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c: In function ‘remmina_string_list_init’:
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c:183:2: warning: ‘gtk_table_resize’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtktable.h:105): Use 'GtkGrid' instead [-Wdeprecated-declarations]
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c:188:2: warning: ‘gtk_table_attach_defaults’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtktable.h:120): Use 'GtkGrid' instead [-Wdeprecated-declarations]
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c:209:2: warning: ‘gtk_vbox_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkvbox.h:60): Use 'gtk_box_new' instead [-Wdeprecated-declarations]
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c:211:2: warning: ‘gtk_table_attach’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtktable.h:109): Use 'GtkGrid' instead [-Wdeprecated-declarations]
/home/tapin13/Downloads/FreeRDP-Remmina-356c033/remmina/src/remmina_string_list.c:251:2: warning: ‘gtk_table_attach’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtktable.h:109): Use 'GtkGrid' instead [-Wdeprecated-declarations]
[ 33%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_widget_pool.c.o
Linking C executable remmina
CMakeFiles/remmina.dir/src/remmina.c.o: In function `main':
remmina.c:(.text.startup+0x50): undefined reference to`g_thread_init'
collect2: error: ld returned 1 exit status
make[2]: **\* [remmina/remmina] Error 1
make[1]: **\* [remmina/CMakeFiles/remmina.dir/all] Error 2
make: **\* [all] Error 2
##

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina. We only support Remmina 1.2.* branch.
