### ISSUE TITLE
Provide a different icon for the tray icon

### ISSUE THREAD

**Issue by elvisd** [FreeRDP/Remmina#225]
This would open the possibility for theme designer to perfectly theme the tray icon too.
At the moment if I apply an icon theme, the same icon as the application icon is used in the tray, causing an unpleasant result.
I attach an example of Ubuntu themed with Moka icon theme.
![selection_002](https://f.cloud.github.com/assets/307127/1089076/a4fe1154-163d-11e3-9fe9-ce549f2fbf69.png)
##

**Comment by ic3d** [comment]
@elvisd do you still get this issue with the latest version of Remmina? Thanks.

**Comment by giox069** [comment]
I think PR https://github.com/FreeRDP/Remmina/pull/894 exactly fixes this issue, so please @ic3d, close it if there is no answer in a couple of days.
Also see:
PR https://github.com/FreeRDP/Remmina/pull/907
PR https://github.com/FreeRDP/Remmina/pull/901
PR https://github.com/FreeRDP/Remmina/pull/894
PR https://github.com/FreeRDP/Remmina/pull/608

**Comment by elvisd** [comment]
For me it's ok now. I see a mono icon, with the ability to set a dark variant in the preferences.
Cool

**Comment by ic3d** [comment]
Thanks, @elvisd! Now closing it.
