### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by claytonraymond2004** [FreeRDP/Remmina#227]
Is it possible to implements more complex command line arguments? I'm working on a project for University that heavily relies on Remmina but I have had to resort to extremely hacky measures to connect to some dynamically changing hosts and full screen the connection.

Need command lines arguments to:
Specify protocol (VNC, RDP, etc.)
Specify Host
Specify Port
Specify Username
Specify Password
Specify scaling
Enter full screen automatically upon connecting

**Comment by muflone** [comment]
Many command line options are already present and they will be showed in the help text (remmina --help) if you use the branch next

**Comment by muflone** [comment]
I don't think we want to implement this feature, it requires a lot of redundant code and the connection arguments would depends on the chosen protocol.

This is already accomplishing by creating a .remmina file and then to ask to remmina to connect using the -c filename.remmina.
