### ISSUE TITLE
VNC to OSX 10.8: Unknown authentication scheme from VNC server: 30, 35

### ISSUE THREAD

**Issue by colindean** [FreeRDP/Remmina#230]
Using Remmina 0.9.99.1 on Ubuntu 12.10, connecting to OSX 10.8.4:

```
Unknown authentication scheme from VNC server: 30, 35
```

Related to #75?
##

**Comment by ic3d** [comment]
This issue affects a old version of Remmina, and we support only Remmina 1.2.* branch. 
@colindean @ashleysommer @KylePDavis @chreekat do you still get this issue? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
