### ISSUE TITLE
Numlock status

### ISSUE THREAD

**Issue by kinazarov** [FreeRDP/Remmina#233]
Numlock status should be taken from current xsession, it should not be "off" at start. Or, if so, remmina should switch system numlock state to "off".
##

**Comment by ic3d** [comment]
@kinazarov do you still get this issue with the latest version of Remmina?

**Comment by kinazarov** [comment]
No but thank you for asking.
3 years passed, Remmina growed up as well as Gnome. Now Remmina is much
better than it was. And you guys doing great job.

В Чт, 03/11/2016 в 08:20 -0700, Dario пишет:

**Comment by ic3d** [comment]
Thanks @kinazarov, I'll close this issue.
