### ISSUE TITLE
Remmina crash when running towards server with xrdp 0.7.0

### ISSUE THREAD

**Issue by stenis999** [FreeRDP/Remmina#234]
I've set up a Ubuntu 12.04.3 LTS with xrdp 0.7.0 built from source, using the script found at:
http://scarygliders.net/2013/07/25/x11rdp-o-matic-version-3-now-released/

It works fine from Windows, Mac and other Linux (with Ubuntu) computers using rdesktop or xfreerdp. If I try with Remmina, it works for a while, but remmina crashes quickly with "segmentation fault" if I start up eclipse on the remote computer.

I'm running the ubuntu-packaged version of remmina for 12.04.3 LTS, i.e. the packages says version 1.0, but the version reported in the "about" dialog is 0.9.99.1.

I have not been able to find any logs from remmina, so there's not much more information I can give you at this point. It's easy to reproduce though, so I'm more than willing to help tracking down why this happens.
##

**Comment by ic3d** [comment]
@stenis999 do you still get this issue with the latest version of Remmina?

**Comment by metalefty** [comment]
Now the latest version of xrdp can accept connections from new RDP client for Mac.

**Comment by metalefty** [comment]
I'm using f5ff6e1 and it doesn't get the issue.

**Comment by ic3d** [comment]
I'm closing this issue because it only affects an old version of Remmina. If needed, a new issue can be opened.
