### ISSUE TITLE
Lost toolbar in keyboard captured mode

### ISSUE THREAD

**Issue by craigs100** [FreeRDP/Remmina#242]
Using Remmina 0.9.99.1 on Linux MInt 16 Cinnamon x64 with nVidia-319 driver.

Connected with RDP to a Windows 2012 server. Put it into full screen, all was ok. Then  , to enable me to use the Windows key, I selected the icon to have the session grab all mouse and keyboard events. From that point on, I have not been able to see the floating toolbar to minimise the window or do anything else. Even if I shutdown the session and restart it, it is in the same condition. So I'm stuck.

**Comment by muflone** [comment]
Remmina was upgraded recently.
Please test this issue with the latest available version. You can find instruction how to install the latest available version on the wiki page.

If this issue persists please reopen.
