### ISSUE TITLE
Remmina has stopped showing shared folders

### ISSUE THREAD

**Issue by jmahoney127** [FreeRDP/Remmina#243]
Initially Reminna connected fine and allowed me to share my local drive as a shared folder. Now, despite adding the drive as a shared folder, I cannot access it from the remote desktop.

**Comment by paalfe** [comment]
enable sound redirection made shared folder work :D

**Comment by giox069** [comment]
Please ensure you have a recent version of remmina (1.2.X or 1.1.X). Folder sharing has totally been reworked both by FreeRDP and Remmina. See [the remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for info on how to get remmina.

**Comment by akawaka** [comment]
Thanks Giovanni.  The issue has been resolved after installing the latest version of Remmina and FreeRDP.

**Comment by giox069** [comment]
:+1:

**Comment by nickjer** [comment]
Was working for me on Windows 2008 R2 a few days ago, but then stopped working after latest update through the Ubuntu PPA a day ago.

**Comment by nicStuff** [comment]
Enabling sound redirection works for me too, great

**Comment by nickjer** [comment]
Just got a Remmina update today through the Ubunta PPA. Folder sharing is working again.

**Comment by Hubbitus** [comment]
@nickjer, it will be much more helpfull if you will provide actual remmina version isntead of some date of update in particular distro.

**Comment by nickjer** [comment]
@Hubbitus, I did provide a version of Remmina when it was failing (please see my first post in this issue on Jan 21). I then followed up with my comment quite a few updates in that it was fixed and still remains fixed.

**Comment by michaelkuty** [comment]
this is realy piece of :hankey: enable sound fixed this issue !
:+1:

**Comment by bmaupin** [comment]
For anyone using the remmina-next PPA, I also had to manually upgrade the libfreerdp-plugins-standard package; for some reason the dependencies weren't properly set and the drive sharing wasn't working due to a missing library:

    [10:00:37:014] [18886:2095822592] [ERROR][com.winpr.library] - LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/libdrive-client.so: cannot open shared object file: No such file or directory

To fix, make sure you upgrade the libfreerdp-plugins-standard package as well:

    sudo apt-get install libfreerdp-plugins-standard

The full instructions:

    sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
    sudo apt-get update
    sudo apt-get install libfreerdp-plugins-standard remmina remmina-plugin-rdp

**Comment by dvlierop** [comment]
Thanks bmaupin, this was exactly what I needed to know!

**Comment by erm3nda** [comment]
I dont know if that helps much, but in my case the only way i found to make it work was to not "save", and press "connect" instead, otherwise the "share folder" checkbox will not be saved. Later i did save and still works :-)

**Comment by llucenic** [comment]
This issue appeared on my Windows 2012 connections a few days ago. The remote sound setting does not help a least bit. I had to connect **without shared folder at first**, after reconnecting with shared folder set to originally set folder, its contents started to appear again in Explorer on the remote machine.
The classical "get-out, get-in" solution works here apparently.

**Comment by nabice** [comment]
I found I can't share '/tmp/', but '/tmp/xxx' works.

**Comment by chrisv2** [comment]
It seems sharing `/` is also not possible (though it is offered by the dialog), while sharing a folder in my home works fine.

 Using Remmina 1.2.0-rcgit-18 (1d744f6) installed with snap on Ubuntu 16.04.

**Comment by runderwo** [comment]
This is frustrating, but the solutions posted here by @bmaupin and @llucenic still work FWIW.
