### ISSUE TITLE
Remmina-plugins-rdp fails to compile correctly with the latest version of gcc & freerdp

### ISSUE THREAD

**Issue by garrettskj** [FreeRDP/Remmina#244]
Latest version of GCC development libraries in Fedora Core 21 prevent the rdp plugin from fucntioning correctly.

gtk3-devel-3.11.2-1.fc21.x86_64
gcc-4.8.2-6.fc21.x86_64

Error Examples:
/home/garretts/gitinstalls/Remmina/remmina-plugins/rdp/rdp_cliprdr.c:115:13: note: expected ‘int *’ but argument is of type ‘size_t *’
 static void crlf2lf(UINT8* data, int* size)

/home/garretts/gitinstalls/Remmina/remmina-plugins/rdp/rdp_settings.c:158:3: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 2 has type ‘DWORD’ [-Wformat=]
   s = g_strdup_printf("%08X - %s", layouts[i].code, layouts[i].name);

/home/garretts/gitinstalls/Remmina/remmina-plugins/rdp/rdp_settings.c:258:2: warning: ‘gtk_table_get_type’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtktable.h:100) [-Wdeprecated-declarations]

After compilation occurs: Remmina segaults whenever connecting via RDP:
traps: remmina[3963] general protection ip:3e4cc8a8ca sp:7f6bd27fbb08 error:0 in libc-2.18.90.so[3e4cc00000+1be000]

Compiled with the latest git release of FreeRDP & Remmina

**Comment by Hubbitus** [comment]
It should be closed now. Thank you very much.
