### ISSUE TITLE
Double-clicking a column header to sort list of saved connections actually attempts connection

### ISSUE THREAD

**Issue by bostrt** [FreeRDP/Remmina#250]
I have a long list of saved connections. I sorted the list, clicking twice quickly to get ascending sort, and remmina tried to connect to my last selected item in the list.

I'm running version 0.9.99.1.

**Comment by muflone** [comment]
Please test the PR #438 https://github.com/FreeRDP/Remmina/pull/438
as it changed the default action (generally the open connection action) on a connection

**Comment by muflone** [comment]
Fixed in the branch 'next'
