### ISSUE TITLE
RDP: No caret on explorer address bar and white squares instead of small icons

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#251]
I'm using the last git version of FreeRDP and Remmina. When I connect to my 2008 servers, I can see some white squares instead of some small icons, and I have no caret/cursor in the Explorer address bar.

Possible fix:
After checking on the code, I modified function remmina_rdp_pre_connect() of rdp_plugin.c and put to False all NEG_ values in OrderSupport array.
Now it seems to be working.

**Comment by antenore** [comment]
@giox069 
Seems fixed now, I don't see this issue since a long time now. :-)

**Comment by giox069** [comment]
This is my first patched issue :) I'm closing it now.
