### ISSUE TITLE
Wrong "es" keyboard mapping of one key

### ISSUE THREAD

**Issue by Yajo** [FreeRDP/Remmina#254]
When using remmina or xfreerdp to a RDP session with "es" keyboard layout, the character `/` from the numeric keypad writes `-` instead.

It's quite annoying because in Spain the common short date format is 30/03/2014, so it's one of the most used keys when your work involves writing dates.

Thanks.
##

**Comment by ic3d** [comment]
Hi @Yajo , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by Yajo** [comment]
Not sure, long time I don't use Remmina... :confused:

**Comment by ic3d** [comment]
OK. 
@jgjimenez do you get this issue (assuming you're using "es" keyboard layout)?

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects an old version of Remmina.
