### ISSUE TITLE
Checkboxes and radio buttons don't display (4D software accessed through rdp)

### ISSUE THREAD

**Issue by e-ch** [FreeRDP/Remmina#255]
The trouble :
4Dv12 checkboxes do not display in Remmina with rdp. You can toggle them on and off, the event will be fired, but the display will stay the same. Needless to say that when in a local Windows session, the checkbox state displays correctly. The matter appears only when using Remmina (with 2X rdp client (e.g.) the display is correct). It's the same with radio buttons.

To check the issue you can download 4Dv12 eval version here :
http://www.4d.com/downloads/products.html (4Dv12 tab is to be selected, "full installer"). The download may take quite a long time (20 minutes).

There is a checkbox app demo here :
http://www.4d.com/support/resources/exampleapplications.html (4Dv12 tab is to be selected) .
Choose the "contact listbox" demo, unzip the whole archive and open the "4D ContactListBox.4DB" file. (you must have installed the eval version in order to open the file).
##

**Comment by ic3d** [comment]
Hi @e-ch , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
