### ISSUE TITLE
Auto-fit stucks the window

### ISSUE THREAD

**Issue by mail6543210** [FreeRDP/Remmina#257]
When connect to RDP-WindowsXP, clicking the button resize("remmina-fit-window"),
the view window stucks(the view part becomes the same color as the toolbars), and the remmina main window keeps working.

This happens on lubuntu 12.04 32/64-bit version, but works well on Ubuntu 12.04 32bit.

So, how to fix it?

**Comment by muflone** [comment]
This issue was fixed a lot of time ago.
Please update your version of remmina. Follow the wiki page to get instructions how to install the latest available version for Ubuntu.

If the issue persists with the latest available version please reopen.
