### ISSUE TITLE
RDP - Conection breaks when I run'Shadow.exe 0'

### ISSUE THREAD

**Issue by Djamana** [FreeRDP/Remmina#260]
Well Remmina seem to be great - just installed and run it.

However it break when I try to shadow active user by running this shell command
'Shadow.exe 0'

Error on remmina console
-> rdp_client_connect_demand_active failed

( well with rdesktop that'll work)

However if I just run
'tscon.exe 0 /password:blah'
it's working.
And well just connecting is sufficient for now.

However plz check shadowing - to make remmina perfect.
Maybe you just didn't test / thought of this case that someone us it for shadowing... 

Ah yes and 'Target' is a WinXP Sp3 with a patched TS for removing some stupid Windows version and suite depending restrictions...
remmina Version is 0.9.99.1 (from Linux Mint 16 )
##

**Comment by ic3d** [comment]
Hi @Djamana , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.

**Comment by Djamana** [comment]
Wow thanks for caring.
...and nice to hear that it's fixed.

I'll close this issue now.
