### ISSUE TITLE
Cannot install Remmina - Could NOT find LIBSSH

### ISSUE THREAD

**Issue by ancesar** [FreeRDP/Remmina#265]
I am getting this message error:
--   package 'libssh>=0.4' not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:57 (MESSAGE):
  Could NOT find LIBSSH (missing: LIBSSH_LIBRARY LIBSSH_INCLUDE_DIR)
Call Stack (most recent call first):
  cmake/FindLIBSSH.cmake:32 (find_package_handle_standard_args)
  cmake/FindOptionalPackage.cmake:37 (find_package)
  remmina/CMakeLists.txt:96 (find_suggested_package)

but the libssh is installed in my environment:
-bash-4.1# rpm -qa | grep libssh
libssh-0.5.4-5.el6.x86_64
libssh2-docs-1.4.2-1.el6.x86_64
libssh2-devel-1.4.2-1.el6.x86_64
libssh2-1.4.2-1.el6.x86_64
libssh2-1.4.2-1.el6.i686

What is missing here?

Regards,
Antonio Cesar

**Comment by muflone** [comment]
The build process depends on your distribution.
On Fedora the ssh package for development is called libssh-devel.

**Comment by giox069** [comment]
Also please read the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for build instructions.
