### ISSUE TITLE
(Windows) Certificates mismatch due to case sensitivity of certificates

### ISSUE THREAD

**Issue by RubenBosch** [FreeRDP/Remmina#268]
Being new to Remmina, I noticed the following while connecting to a Windows (2008R2) Server: 

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@           WARNING: CERTIFICATE NAME MISMATCH!           @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The hostname used for this connection (mgt001.domain.local) 
does not match the name given in the certificate:
MGT001.domain.local
A valid certificate for the wrong name should NOT be trusted!
SSL_read: Failure in SSL library (protocol error?)
```

I would like Remmina to ignore cases when connecting to RDP servers. 
##

**Comment by ic3d** [comment]
Hi @RubenBosch , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
