### ISSUE TITLE
ssh key selection overwritten on edit

### ISSUE THREAD

**Issue by Shaav** [FreeRDP/Remmina#271]
When I create a configuration with a key-based ssh tunnel that does not use .ssh/id_rsa, it works fine the first time but when I subsequently edit the configuration, the key reverts back to the default .ssh/id_rsa.

Steps to recreate:
1. Create a new configuration
2. Select a non-default location/filename  for an ssh key
3. Save the configuration
4. Edit the configuration

Perhaps this is related to:
Issue #256

**Comment by antenore** [comment]
Closed as no feedback given, please reopen if you still have the issue.
