### ISSUE TITLE
Remmina freeze after system boots from suspend

### ISSUE THREAD

**Issue by kendzi** [FreeRDP/Remmina#284]
I'm using Remmina 0.9.99.1 to connect vnc remote desktop. I connect to that desktop and then suspend Ubuntu 14.04. After computer boot from suspend all programs are working correctly except Remmina. Window with remote connection is still open but it freeze after I click on it. It is not possible to close that window and I'm force to kill it.

**Comment by muflone** [comment]
Hi @kendzi 
does this issue still persist?
Remmina has been upgraded recently, please refer to the wiki page how to download the latest available version.
If the issue still persists please reopen.
