### ISSUE TITLE
Remmina install /usr/include/remmina/ empty

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#292]
I've hack it in speck in next fasion:
```
sed -i 's#install(DIRECTORY include/remmina DESTINATION include/remmina #install(DIRECTORY remmina/include/remmina DESTINATION include/ #' CMakeLists.txt
```

Also, for convenient build plugins against remmina outside source tree I would suggest include also config.h.in here.

**Comment by muflone** [comment]
This issue was fixed by the PR #428
