### ISSUE TITLE
Remmina blocks and I have to disconnect every 20 minutes

### ISSUE THREAD

**Issue by clipboard** [FreeRDP/Remmina#332]
I don't know if anyone happen this but I have two computers who are connecting to a windows 7 using RDP and every 20 or 30 minutes they have to disconnect it because remmina blocks and they can't do anything. And I compiled remmina in both computers in a recent installed ubuntu 14.04
##

**Comment by ic3d** [comment]
Hi @clipboard , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by clipboard** [comment]
No problem with the latest version
