### ISSUE TITLE
XDMCP plugin broken

### ISSUE THREAD

**Issue by muflone** [FreeRDP/Remmina#366]
Hi

The XDMCP plugin doesn't work at all, neither in local usage nor with LAN access.
The same applies to the master and to the next branches.

Steps to reproduce:
1- enable XDMCP in your display manager
2- create a new connection in remmina using the XDMCP plugin
3- specify the host argument and an optional startup command (like xterm)
4- save and start the connection with double click

What happens:
A black window appears with no login at all.
A really tiny little Xephyr window appears. By maximizing it no login window is shown.
The command line which is executed is:
```
Xephyr :2  -parent <RANDOM_WINDOW_ID> -query <HOSTNAME>
```

What should happen:
A login (from the XDMCP server) should appear in the remmina window.

**Comment by muflone** [comment]
The current branch 'next' still suffer from this issue.
The same defect afflicts every remmina plugin that use the GtkSockets (NX, XDMCP, X2Go).

The terminal window shows always the same message:
(EE) 
Fatal server error:
(EE) X11 error
Error code: 8
Sequence number: 5
Major code: 1	Minor code: 0
Error value: 37752837
(EE) 

This seems again related to the GtkSocket unrealization.

**Comment by giox069** [comment]
It should have been fixed 1 week ago (there was an implicit reparenting with the usual socket destruction). Tested on Debian 8, because most distributions currently have a bugged Xephyr which is unable to work via GtkSocket. See here:
https://bugs.freedesktop.org/show_bug.cgi?id=91700

**Comment by muflone** [comment]
oh damn, issue confirmed here (Arch Linux with xorg-server-xephyr 1.18.0-3)
Reverting to the version 1.16 fixes the issue.
Thank you @giox069

**Comment by antenore** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=91700 
Things are moving on, so maybe soon we will have a working Xephyr.

In the meanwhile @larchunix has created a [remmina flatpak](https://github.com/FreeRDP/Remmina/blob/next/flatpak/README.md) that comes with Xephyr 1.16.
