### ISSUE TITLE
fatal_handler - SIGSEGV in CommandLineParseArgumentsA

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#383]
```
#1 fatal_handler at /usr/src/debug/FreeRDP-1.2.0-beta1-android7/libfreerdp/utils/signal.c:66
 #3 strlen at ../sysdeps/x86_64/strlen.S:106
 #4 CommandLineParseArgumentsA at /usr/src/debug/FreeRDP-1.2.0-beta1-android7/winpr/libwinpr/utils/cmdline.c:118
 #5 rdpsnd_process_addin_args at /usr/src/debug/FreeRDP-1.2.0-beta1-android7/channels/rdpsnd/client/rdpsnd_main.c:654
 #6 rdpsnd_process_connect at /usr/src/debug/FreeRDP-1.2.0-beta1-android7/channels/rdpsnd/client/rdpsnd_main.c:730
 #7 rdpsnd_virtual_channel_client_thread at /usr/src/debug/FreeRDP-1.2.0-beta1-android7/channels/rdpsnd/client/rdpsnd_main.c:955
```

Please look at full report https://bugzilla.redhat.com/show_bug.cgi?id=1161083

I could not exactly say how reproduce it, but it happened from time to time.
##

**Comment by Hubbitus** [comment]
Many peoples in Fedora experience it: https://bugzilla.redhat.com/show_bug.cgi?id=1196838 Backtraces present along with env.
Could you please look on it?

**Comment by Hubbitus** [comment]
Reproduced also in 1.2.0: https://bugzilla.redhat.com/show_bug.cgi?id=1232598

**Comment by Hubbitus** [comment]
https://bugzilla.redhat.com/process_bug.cgi

**Comment by ic3d** [comment]
Hi @Hubbitus is this issue still open, or we've only forget closing it? :-)

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects older version of Remmina.
