### ISSUE TITLE
Num lock off

### ISSUE THREAD

**Issue by zuza07** [FreeRDP/Remmina#389]
Why the num lock works unlike ubumtu, has an option for me to change it?
I love the Remmina but actually hinders it.

Thank you

**Comment by mahescho** [comment]
For me for all versions up to 1.1.2-ppa1+850 num lock state is not propagated to Windows 2012 servers in RDP sessions. I've num lock always on. when I type, numbers get typed. When I open a RDP session num lock is off in this session but outside (any other Linux application) it is still on. I've to press num lock one time in the RDP session to make it work there but then it is disabled outside of the RDP session for all the other Linux applications. When I use "rdesktop" this problem does not exist.

**Comment by zuza07** [comment]
Version 1.2.0 does not have this problem
https://github.com/FreeRDP/Remmina/wiki
