### ISSUE TITLE
Passwords not properly escaped

### ISSUE THREAD

**Issue by sean-abbott** [FreeRDP/Remmina#390]
If a password has a space at the beginning, it will not be properly passed to a windows rdp server.
##

**Comment by muflone** [comment]
Please test this issue with the latest available version of Remmina.
See the wiki page to get instructions how to get a more recent version of Remmina.
https://github.com/FreeRDP/Remmina/wiki

**Comment by ic3d** [comment]
Hi @Tavda @sean-abbott  , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects an old version of Remmina.
