### ISSUE TITLE
[feature request] agent forwarding with ssh!

### ISSUE THREAD

**Issue by coolbombom** [FreeRDP/Remmina#395]
Hi

brilliant program, use it often. I was wondering if agent forwarding is a feature to come, if not i would like to suggest it!

cheers
c_bb

**Comment by bartanxas** [comment]
+1

**Comment by eovolkov** [comment]
+1

**Comment by antenore** [comment]
Please test the last commit on next, you have to configure it on the ~/.ssh/config file.
