### ISSUE TITLE
Screen lockups During RDP session

### ISSUE THREAD

**Issue by alitvak69** [FreeRDP/Remmina#400]
When switching in to full screen mode, task bar is no longer responding to clicks (programs, start button etc) regardless of windows server version (2003R2 or 2008R) on the remote machine.

Remmina is running on dual screen desktop, kde 4.14 on opensuse 13.2.  It happens usually on the screen that has kde task bar as well, left monitor in my case, and 100% reproducible.

I am running git (next)  now  but issue persists since remmina 0.9.9.

Also some times (less often) remote desktop becomes unresponsive across the view port and the only way to make it work is to close and open session again..  This happens regardless of the monitor location or size / mode  of the remmina viewport. 

I have not tried VNC or other plugins.

snow-leopard:~> remmina
Remmina plugin GKEYRING (type=Secret) registered.
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin XDMCP (type=Protocol) registered.
Remmina plugin telepathy (type=Entry) registered.
NX: detected keyboard type logiik/us
Remmina plugin NX (type=Protocol) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.

(remmina:11327): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[20:41:23:165] [11327:638678784] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkAlignment': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkAlignment': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaScrolledViewport': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkAlignment': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaScrolledViewport': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:11327): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)
##

**Comment by holooloo** [comment]
The same issue...

**Comment by giox069** [comment]
@holooloo does it happens under kde also to you ? Opensuse ? With the latest freeedp from master branch ?
I could try to setup a machine with the same config as your and try to reproduce. But I need more data.

**Comment by holooloo** [comment]
Debian 8.1 (Jessie) 64 bit 
Lenovo X1 Cardbon 2nd
GNOME Shell 3.14.4
Freerdp 1.1.0 from disrtib sources
Remmina 1.1.0

**Comment by giox069** [comment]
I think we are speaking of many different things here.
1. The KDE taskbar not responding, as written on the 1st lines of the 1st post, when switching to fullscreen mode the KDE taskbar on the other monitor stops responding (did I get it right ?). Does the same happens under remmina 1.2 ? Or under Gnome shell ?
2. Screen lockups (as written in the title): this is unfortunately too vague. It can be a network connectivity issue or hundred of different things. Currently remmina is not able to do a normal reconnect as the miscrosoft RDP client does. So, when you loose the TCP connection without regular disconnection, remmina will not retry to reconnect and your remote screen will freeze. And yes, you have to disconnect reconnect manually.

Also please note: for remmina 1.1 we are only able to patch security and critical issues (i.e.: data corruption or 100% reproducible crashes). Please upgrade to remmina 1.2. Instructions for upgrading are on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). For Debian it requires recompilation.

**Comment by ic3d** [comment]
Hi @alitvak69 @holooloo , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects an old version of Remmina.
