### ISSUE TITLE
Full screen viewport siezes monitor foreground when the window with focus is on another monitor

### ISSUE THREAD

**Issue by ShroudedNight** [FreeRDP/Remmina#403]
Remmina's full screen viewport will jump to a monitor's foreground when window focus switches to another monitor.  Furthermore, with fairly high probability, attempting to interact with the viewport with the mouse will instead bring up a context menu. Alternatively, though less often, attempted interactions will cause the last active window on the monitor to pop back to the foreground and re-acquire focus.

Example:
Monitor 0 has a (maximized) gedit window and a Remmina RDP session running in full-screen mode.
Monitor 1 has a firefox window.
With the gedit window having focus and in the foreground of monitor 0, alt-tab or click such that the firefox window has focus on monitor 1.  The Remmina RDP session view will jump to the foreground of monitor 0, covering up gedit, and possibly exhibiting the context menu interaction behaviour.

The behaviour I expected instead was that gedit would remain in the foreground of the monitor, and in such a mannter that it can interacted with normally with the mouse.

This is on Arch 64bit with remmina 1.1.1-4 (shown as 1.1.0 in Help->About) and gnome 3.14.2
##

**Comment by ShroudedNight** [comment]
Late update: I can confirm I'm using Gnome Shell.

**Comment by weberhofer** [comment]
When I do not switch via Alt-Tab to the Remmina Window displaying a freerdp session all the mouse-events are going to the (invisible) windows in the background which could be a gnome shell or any other wnome window. I'm using the latest master versions of both remmina and freerdp.

**Comment by ic3d** [comment]
Hi @ShroudedNight , do you still get this issue with the latest version of Remmina? Indeed, now we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects an old version of Remmina.
