### ISSUE TITLE
Problems after conneting to Windows Server 2012

### ISSUE THREAD

**Issue by McRob** [FreeRDP/Remmina#410]
I am trying to use Remmina for remote desktop applications. The server is a Windows Server 2012 and the connection to the server works fine, but after the login with correct data remmina crashes without a report. For a better understanding watch the video: http://youtu.be/eSCLtuxyfg4  Do someone knows a solution for this? When I am emulating windows7 in vmplayer i can easily connect and use the windows server...
##

**Comment by McRob** [comment]
the problem is still there...

my version:
FreeRDP version 1.2.0-dev (git 65214b4)
remmina 1.2.0-rcgit.2

Connections to Windows Server 2003 R2 and Windows 7 are working fine, the problem persist just with Windows Server 2012...

**Comment by ic3d** [comment]
Hi @McRob  , do you still get this issue with the latest version of Remmina? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects older version of Remmina.
