### ISSUE TITLE
Remmina crashes copying from remoted computer and pasting into remoting one

### ISSUE THREAD

**Issue by penalvch** [FreeRDP/Remmina#411]
1) lsb_release -rd
Description:    Ubuntu Vivid Vervet (development branch)
Release:    15.04

2) apt-cache policy remmina
remmina:
  Installed: 1.1.1-1ubuntu1
  Candidate: 1.1.1-1ubuntu1
  Version table:
 **\* 1.1.1-1ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status

3) What is expected to happen remoted into a scratch build of Microsoft Windows Vista Business x86 6.0.6002 Service Pack 2 Build 6002 (only using built-in Microsoft Security Essentials/Windows Defender as anti-virus) is remote into it via Remmina > Remote Desktop Preferences > tab Basic > Protocol RDP > Username USERNAME > Password PASSWORD > blank field for Domain > Resolution Custom 800x600 > Color depth High color (15 bpp) > unchecked Share folder > tab Advanced > Quality Poor > Sound Off > Security RDP > all other fields/checkboxes blank/unchecked > remote into Vista and open Paint > File > Open > Pictures > Sample Pictures -> Autumn Leaves.png > select the entire picture and copy > click into Ubuntu and attempt to paste and it doesn't crash.

4) What happens is it does. This has been reproducible since Quantal (remmina 1.0.0-1ubuntu8).
##

**Comment by giox069** [comment]
I think I can close the issue, but some patches should be ported to Vivid ? (what are the plans for Remmina on Ubuntu 15.10 @dktrkranz ?)

**Comment by giox069** [comment]
oops... 15.04, vivid. I apologize for the typo.

**Comment by dktrkranz** [comment]
There's still time to push patches to both Ubuntu and Debian. I'll try to have this sorted ASAP.

**Comment by Hubbitus** [comment]
Doesn't it fixed and need to be closed?

**Comment by ic3d** [comment]
Hi @penalvch  , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by penalvch** [comment]
Vista is EOL, so this issue is considered closed for the originally scoped issue and supported branch:
apt policy remmina
remmina:
  Installed: 1.1.2-3ubuntu1
  Candidate: 1.1.2-3ubuntu1
  Version table:
 *** 1.1.2-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
