### ISSUE TITLE
Allow the user to hide the toolbar inside a remmina connection window

### ISSUE THREAD

**Issue by jiajunhuang** [FreeRDP/Remmina#413]
because it looks like this in Xmonad.

or, just add an option to turn off it.
##

**Comment by muflone** [comment]
Hi

could you please elaborate? What do you mean with status bar?
In the upper screenshot I cannot see any status bar (which is generally placed on the bottom of the window).

**Comment by gansteed** [comment]
I'm sorry, what I mean is the icons below Xmobar(in the top of the window, blank one), you know, I don't need the icons  all the time, so I wonder can you add an option to hide it?

**Comment by muflone** [comment]
Ok, that's the top toolbar.
Marking as new feature, maybe someday we'll add a setting to hide the toolbar

**Comment by nikoudel** [comment]
This would be a great enhancement, I wonder why didn't it get much attention...
The toolbar is constantly getting on my way. I often work all day in a full-screen remote desktop and the toolbar pops up every time I move the mouse to the top area. I also use several nested RDP sessions which have that small blue Remote Desktop Connection (MS Windows) toolbar too. It gets hidden by the Remmina toolbar all the time. Sometimes I try to click some button on the top (e.g. minimize a browser window) but Remmina pops up just before my finger lands on the mouse button and I end up clicking the Disconnect button on Remmina toolbar which is definitely not what I was trying to do. Very frustrating.

Windows RDP client has that awesome feature "Display the connection bar when I use the full screen". When unselected, you need to press Ctrl+Alt+Break to exit the full screen mode. It would be great to have a similar option in Remmina.

**Comment by giox069** [comment]
If you are using Remmina 1.2.X, in fullscreen the toolbar is draggable to the bottom of the screen. Just drag and drop it.
Other two notes:

1. In windowed mode, you cannot hide or move the toolbar. This is why this issue exists, and implementing it it's a "newfeature".
2. In Remmina Preference-> Appearance there is an option called "invisible toolbar in fullscreen mode". It should be used to hide the toolbar in fullscreen mode, but currently it does not work.

**Comment by bj0** [comment]
There is an option to disable the toolbar, but it doesn't affect the top bar (that shows connection tabs).  This wastes just enough vertical space that I am constantly having to scroll the window up and down.  Is there a way to hide this (especially since I only ever have a single connection)?

**Comment by nikoudel** [comment]
That's how you fix it:
`xfreerdp /v:192.168.1.144 /d:some.domain /u:jsmith /f +compression +fonts -wallpaper -glyph-cache`
Press Ctrl+Alt+Enter to exit full screen.

**Comment by giox069** [comment]
@bj0 @jiajunhuang:
**IN FULLSCREEN MODE**
there is a global option to disable the "floating toolbar", the toolbar appearing in fullscreen mode, which already is quite short when hidden.
Starting from Remmina **1.2.0-rcgit.3**, you can also drag and drop the floating toolbar at the bottom of the screen.

**IN WINDOWED MODE**
In windowed mode, starting from Remmina **1.2.0-rcgit.7**, you can drag and drop the toolbar in any of the four edges of the screen, for example to the left or to the right. So you can save vertical space.

If you need to upgrade remmina, see our [wiki](https://github.com/FreeRDP/Remmina/wiki).

We leave this issue marked as **newfeature**, because currently there is no way to hide the windowed mode toolbar.

**Comment by transistor1** [comment]
@giox069:

For me (on Debian Jessie), in fullscreen mode, the "invisible toolbar" option shrinks the size of the floating toolbar from showing a very small handle to not showing at all, but when you move your cursor to the top of the screen it still appears.  I did not see an option to completely disable it in fullscreen mode, so I created PR #1135.

My use case is similar to @nikoudel's.

**Comment by antenore** [comment]
Thanks @transistor1 
closed by #1135
