### ISSUE TITLE
Hide quick connect bar by default

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#421]
The "Quick connect" bar confuses new users: they usually push Connect! button to connect to a profile in the list. And many advanced users do not use that bar at all.

@muflone added a "View menu" item which allows you to hide the bar: https://github.com/FreeRDP/Remmina/commit/2300bf892e5b27ad6fb518311514f8185a71e646

My proposal is to hide the quick connect toolbar by default on all new remmina install, leaving the user the ability to reenable it via the View menu.

**Comment by hoyang** [comment]
yes, very useless and ugly.

**Comment by larchunix** [comment]
@giox069 @antenore  I guess this issue can be closed with the new design from #875.

**Comment by antenore** [comment]
Yes! Thanks @larchunix
