### ISSUE TITLE
After clicking the 'WIN' key, the key mapping is disorder

### ISSUE THREAD

**Issue by xiaoaiwhc** [FreeRDP/Remmina#426]
I am using the Remmina v0.9.99.1 installed on Ubuntu 14.04 to connect a windows PC which version is windows 64bit via RDP. But I found after properly connected the windows PC, and then I click the 'WIN/HOME' key, the key mapping has started to get a  disorder, the behaivor of keyboard is like I have pushed a combination keys. To solve this problem, I have to click the 'WIN/HOME' key again.
##

**Comment by ic3d** [comment]
Hi @xiaoaiwhc  , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, assuming it only affects older version of Remmina.
