### ISSUE TITLE
Connection closes right away when trying to connect to Mac

### ISSUE THREAD

**Issue by cesarramirez** [FreeRDP/Remmina#427]
I am trying to VNC into a mac pro with dual screen but the connection closes instantly. I get asked for my password, I enter it correctly and it seems like a connection is created and then closed right away. Is there any way I can get more information about what is going on? I have not seen any -d or -v flags for remmina.

When I try to connect to other computers via RPD they work fine.

**Comment by muflone** [comment]
Hi

what version of Remmina are you using?

What version of OS X are you using?
The VNC server does use the OS X authentication or the VNC password (in the shared desktop settings)?

**Comment by muflone** [comment]
Please provide the required information, without that we cannot help you in any way.
