### ISSUE TITLE
Regression: "Unknown authentication scheme from VNC server: 18"

### ISSUE THREAD

**Issue by arty-name** [FreeRDP/Remmina#433]
I was using Remmina 0.9.99.1 from standard Ubuntu 14.10 repo to connect to standard Ubuntu 14.10 vino server. Then I upgraded to the Remmina 1.1.1-1+561+next+201412311019~ubuntu14.10.1 from PPA http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/ . When I tried to connect to the same host I got following error message: 

    Unknown authentication scheme from VNC server: 18

After downgrade to Remmina 0.9.99.1 everything started working again.

**Comment by giox069** [comment]
I cannot reproduce. I'm using the latest remmina-next PPA on ubuntu 14.10 (client side) and connecting to another ubuntu 14.10 box without problems.
On the "server" side these are my settings for integrated "Desktop Sharing" (which uses vino-server):
![desktop sharing preferences_094](https://cloud.githubusercontent.com/assets/5477803/5612245/0d254d2e-94d2-11e4-838e-5edc82a93f0e.png)
Maybe you installed a newer version of VINO ? I'm trying to understand what kind of authentication scheme is number 18...

**Comment by arty-name** [comment]
I have a different configuration:
![vino](https://cloud.githubusercontent.com/assets/133055/5612395/74cb3e96-94d4-11e4-8e3e-0df50b1bad15.png)

no password is required, and I configured it to only accept connections from loopback addresses

**Comment by arty-name** [comment]
vino's version is 3.8.1-0ubuntu2

**Comment by giox069** [comment]
Server site: I tried your settings (just removed the password), but it works. Vino is the same version.

Client side: please check that you did not enable "Disable encryption" settings. I **can** reproduce the problem with encryption disabiled.

**Comment by arty-name** [comment]
Indeed I have "Disable encryption" checked. Why would I need extra encryption when I already have SSH? :)

**Comment by giox069** [comment]
When you check "Disable encryption", remmina restricts the authentication modes it can accept from the server to rfbNoAuth, rfbVncAuth, rfbMSLogon.

Unfortunately vino, for security reasons, only sends type 18 (rfbTLS). So server and client cannot match. A workaround can be found [here](http://www.bonusbits.com/main/KB:Fix_VNC_Desktop_Sharing_on_Ubuntu_Desktop_14.04), but you must change the configuration server side.

But wait... that's only authentication ! Not really. rfbTLS not only protects authentication, but seems to force all VNC sockets traffic to be TLS encrypted. I haven't fonund a doc saying that, but sniffing with wireshark and [libvncserver client.c around line 155](https://github.com/LibVNC/libvncserver/blob/master/libvncclient/sockets.c) shows that when TLS is in effect, also RFB traffic outside authentication is encrypted by TLS.

So, at the end, if you also enabled SSH tunnel on this remmina profile, you will come out with a twice encrypted channel.

What can we do ? I cant't see the double encryption a big problem with current cpu/machines. And it can be disabled by syssadmin on the vino side as explained above. From the client side we can't do anything useful to avoid double encryption.

But we can improve the UX (User Experience) to provide a better message when the user disabled encription in the remmina profile and vino only offers rfbTLS.

**Comment by arty-name** [comment]
Hmm, I don't how why it works with Remmina 0.9.99.1 then, but it's okay. 

It would be nice to have two things: 

1) a tooltip for the "Disable encryption" checkbox which tells you it might not work with Vino anymore
2) when getting this kind of error, Remmina can show a different message instead. Something like "This server requires encryption, enable it in this connection's settings"

**Comment by giox069** [comment]
I did a small test with Remmina 0.9.99.1, looking at the Remmina debug window (Help->Debug Window) and having the "Disable encryption" option enabled.
It seems that remmina 0.9.99.1 silently agrees to use rfbTLS, and looking at its code [here](http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/utopic/remmina/utopic/view/head:/remmina-plugins/vnc/vnc_plugin.c) in line 1243, it seems just a wrong #ifdef that prevents the "Disable encryption" checkbox to work. So, it's a bug in the old remmina 0.9.99.1: encryption will be enabled forever.

I agree on 2) but I'm not sure for 1): people don't connect to vino only. 2) will be enough :)

There is also a major problem for 2): the message "Unknown authentication scheme from VNC server: %s" is not generated by remmina, but from the libvnc library. And is a bit tricky to change it in the callback function remmina_plugin_vnc_rfb_output().

I'll leave this issue open for future thoughts.

**Comment by arty-name** [comment]
Thanks for your help in figuring it out!

**Comment by giox069** [comment]
Message added. The updated PPA should be available tomorrow after 19:30 GMT.

Two new strings now need to be translated:
1. "Unknown authentication scheme from VNC server: %s"
2. "Please retry after enabling encryption on this profile."
If you can post here a possible german translation, I will include it in a future commit :)

Thank you.

**Comment by arty-name** [comment]
The funny thing is I only study German :) Here are Russian translations though:
1) Сервер VNC использует неизвестную схему аутентификации: %s
2) Включите шифрование в настройках этого подключения и повторите попытку.

**Comment by giox069** [comment]
I just was visiting your blog, just after my last post... I can't read a word! :)
Many thanks for the russian translation, every translation is welcome :)

**Comment by arty-name** [comment]
I really should make my English blogposts more visible :)
