### ISSUE TITLE
Issues with viewport fullscreen

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#44]
This is reproducible while connecting to a system with an higher resolution.
Steps to reproduce the issue:
* Connect to a system with an higher resolution
* Activate viewport fullscreen mode
* Scrollbars do not work, and image is distorted

Switching to scrolled fullscreen is fine, though.

**Comment by muflone** [comment]
Do this issue still persist?
In the case please reopen this issue. For now I'm closing this 2 years old issue.
