### ISSUE TITLE
Does (or will) Remmina support multi monitor RDP?

### ISSUE THREAD

**Issue by radman0x** [FreeRDP/Remmina#442]
Hi,

I have just discovered Remmina and it seems to be the best RDP option for linux systems. My question is: Does (or will) Remmina support multi monitor RDP?

From my reading Remmina uses Freerdp as its backend and this supports multi monitor RDP. I have compiled Freerdp and have this working. I have also compiled Remmina from source today and I can't find any option to enable multi monitor support, so it seems like its not there. Posting this to confirm and also to see if there are any plans for adding this to a future version.

**Comment by giox069** [comment]
Already marked in #376 as new feature to add.
Which commandline switch did you use for freerdp ?

**Comment by radman0x** [comment]
Thanks for letting me know. The flag that controls it is /multimon. Just for completeness, I'm running on Kubuntu 14.04 with two screens.

**Comment by Higuitar99** [comment]
+1 for this feature, like microsoft's mstsc.
