### ISSUE TITLE
Segfault in sspi_CopyAuthIdentity

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#443]
[ Forwarded from https://bugs.debian.org/775513 ]

remmina segfaults trying to connect to a rdp server (Windows 8.1)

 % remmina 
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
loading channel cliprdr
connected to 10.1.51.41:3389
zsh: segmentation fault  remmina

 % gdb /usr/bin/remmina 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/remmina...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecc16700 (LWP 14316)]
loading channel cliprdre=Protocol) registered.
connected to 10.1.51.41:3389

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe0a11700 (LWP 14759)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33  ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt full
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33

No locals.
#1  0x00007fffe6447dee in sspi_CopyAuthIdentity () from /usr/lib/x86_64-linux-gnu/libwinpr-sspi.so.0.1

No symbol table info available.
#2  0x00007fffe6445f0b in ntlm_InitializeSecurityContextW () from /usr/lib/x86_64-linux-gnu/libwinpr-sspi.so.0.1

No symbol table info available.
#3  0x00007fffe6446091 in ntlm_InitializeSecurityContextA () from /usr/lib/x86_64-linux-gnu/libwinpr-sspi.so.0.1

No symbol table info available.
#4  0x00007fffe7daeb0f in credssp_client_authenticate () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#5  0x00007fffe7dd1da1 in transport_connect_nla () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#6  0x00007fffe7daf419 in nego_security_connect () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#7  0x00007fffe7db009d in nego_connect () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#8  0x00007fffe7dcc233 in rdp_client_connect () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#9  0x00007fffe7dc2c38 in freerdp_connect () from /usr/lib/x86_64-linux-gnu/libfreerdp-core.so.1.1

No symbol table info available.
#10 0x00007fffec20be85 in ?? () from /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so

No symbol table info available.
#11 0x00007fffec20c57a in ?? () from /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so

No symbol table info available.
#12 0x00007ffff5bc20a4 in start_thread (arg=0x7fffe0a11700) at pthread_create.c:309

```
    __res = <optimized out>
    pd = 0x7fffe0a11700
    now = <optimized out>
    unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736962041600, 8434445067145717223, 1, 140737354125408, 0, 140736962041600, -8434421472301931033, -8434467626715044377}, mask_was_saved = 0}}, priv = {
        pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
    not_first_call = <optimized out>
    pagesize_m1 = <optimized out>
    sp = <optimized out>
    freesize = <optimized out>
    __PRETTY_FUNCTION__ = "start_thread"
```
#13 0x00007ffff4d43ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

No locals.
(gdb)
##

**Comment by ic3d** [comment]
This issue affects Remmina 1.1.2, that is out of maintenance, we only support Remmina 1.2.*. I'll close this issue in the next days.
