### ISSUE TITLE
Host Name checking is erroneously case sensitive for RDP fingerprint

### ISSUE THREAD

**Issue by jtmoree-kahalamgmt-com** [FreeRDP/Remmina#462]
I'm using the ppa so my version is fairly recent? 1.2.0-rcgit.2 on (K)Ubuntu 14.04

Connecting with RDP to Windows Server:
freerdp wont connect and asks for confirmation due to case sensitive checking of the host name.  For example, the host name in the cert on windows server uses a capital letter but I use all lowercase for freerdp/remmina parameters
  e.g. MyServer.Mydomain.com vs myserver.mydomain.com 
The error from freerdp is that the hostname does not match the certificate but by definition DNS names are case insensitive.  The check should be case insensitive.

With remmina the error is pretty useless.  It just says it couldn't connect but not the reason why.

**Comment by giox069** [comment]
The PPA is updated daily for remmina, and manually when needed for freerdp. Last update for freerdp is less than a week ago.

Can you executed remmina from a terminal window, connect to the server, and paste the the thext output you get on the terminal windows ?

Remmina does not check server certificate vs typed hostname, it just prompt the user the CN of the server certificate the first time and every time it connects.

**Comment by jtmoree-kahalamgmt-com** [comment]
Ah, yes.  xfreerdp complains about the hostname when case does not match but remmina works either way.  Apologies for not testing thoroughly.
