### ISSUE TITLE
Latest changes causes compilation errors

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/Remmina#464]
FYI, I'm building development versions of remmina and freerdp on a regualry basis at https://build.opensuse.org/package/show/home:weberho:UNSTABLE:RemoteDesktop/remmina

The changes between Feb.10th and Feb.13th breaks the compilation as you can see:

[  103s] cd /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/build/remmina && /usr/bin/cc  -DHAVE_LIBAVAHI_CLIENT -DHAVE_LIBAVAHI_UI -DHAVE_LIBGCRYPT -DHAVE_LIBSSH -DHAVE_LIBVTE -DREMMINA_EXTERNAL_TOOLS_DIR=\"/usr/share/remmina/external_tools\" -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DLIBVNCSERVER_WITH_CLIENT_TLS=1  -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -O3 -DNDEBUG -I/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/. -I/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/include -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/vte-2.91    -o CMakeFiles/remmina.dir/src/remmina_file.c.o   -c /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_file.c
[  104s] /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_connection_window.c: In function 'remmina_connection_holder_create_toolbar':
[  104s] /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_connection_window.c:1128:2: warning: 'gtk_arrow_new' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkarrow.h:73) [-Wdeprecated-declarations]
[  104s]   arrow = gtk_arrow_new(GTK_ARROW_DOWN, GTK_SHADOW_NONE);
[  104s]   ^
[  104s] /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_exec.c: In function 'remmina_exec_command':
[  104s] /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_exec.c:71:5: warning: implicit declaration of function 'remmina_main_new' [-Wimplicit-function-declaration]
[  104s]      widget = remmina_main_new();
[  104s]      ^
[  104s] /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_exec.c:71:12: warning: assignment makes pointer from integer without a cast [enabled by default]
[  104s]      widget = remmina_main_new();
[  104s]             ^

**Comment by muflone** [comment]
We cannot guarantee anything about not breaking things in the development branch, that's what the development branch is for.

First of all retry to build from the source again.
If the issue still persist please provide the whole log, in the log that you described here I cannot see any error message, just a couple of warning messages.

**Comment by weberhofer** [comment]
I know it will be broken some times; packaging stops thru the error in /src/remmina_exec.c:71; this results in a "remmina 64bit-portability-issue /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20150212/remmina/src/remmina_exec.c:71" message.

You can see the full changelog via OSB interface at https://build.opensuse.org/project/show/home:weberho:UNSTABLE:RemoteDesktop opening the remmina project and the red "failed" link on the differnet distributions;

In case you are interested in it, I could set up automatic checkout/build, too.

**Comment by muflone** [comment]
The offending line results to be remmina_exec.c at line 71
widget = remmina_main_new();
The widget variable is a GtkWidget, the returned value from remmina_main_new is a GtkWidget, I cannot see any issue with this line.

I've just sent a commit that removes an unused void parameter from the definition.
Please try again with the sources committed today.

**Comment by weberhofer** [comment]
Thanks! Build status is "succeeded" again and is running here on my desktop with the lates freerdp library.

**Comment by muflone** [comment]
Ok, thank you @weberhofer
