### ISSUE TITLE
Support opening rdp files

### ISSUE THREAD

**Issue by freechelmi** [FreeRDP/Remmina#47]
Rdp files are used a lot on Windows environement, it's simple txt files that contains the adress of the RDP server : 

full address:s:servername:3392
compression:i:1
displayconnectionbar:i:1

I don't know if there is a formal spec for this...

**Comment by antenore** [comment]
https://github.com/FreeRDP/FreeRDP/blob/ca274b6b49583c203afebba50d48303dc103110c/client/common/file.c

This is the parser under FreeRDP and we can even use the API:

https://github.com/FreeRDP/FreeRDP/blob/ca274b6b49583c203afebba50d48303dc103110c/include/freerdp/client/file.h

**Comment by mikevdg** [comment]
If I may add my vote, it would be really useful to be able to open a .rdp file from the command line.

Once common use case is that a web browser fetches a .rdp file, which I'd like remmina to automatically open because it has a file association with .rdp files.

**Comment by antenore** [comment]
We will address this issue as soon as possible, but if anybody wants to try to implement it, we will be happy to test and merge it.

**Comment by greenlighttec** [comment]
Idk if theres any progress on this, but i noticed if you Drag and Drop the RDP file into Remmina it loads all the settings and you can then connect. Convenient, but would still prefer to have Remmina associated so you can just click on the RDP file and it connects.

**Comment by antenore** [comment]
Here we are  ``` \(^o^)/  ``` 

I'll merge this and release a new remmina version ASAP. In the mean while you want to test it, after compiling the remmina_main_fixes branch, just drag&drop rdp or remmina files inside the remmina main window.

FYI: @giox069 @larchunix
