### ISSUE TITLE
segfault after closing RDP window

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#479]
[ forwarded from https://bugs.debian.org/777130 ]

In 8 out of 10 cases after/while closing a RDP connection window, remmina
segfaults. This happens with both 1.1.1 and 1.1.2 versions:

(gdb) run
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecf0e700 (LWP 12045)]
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
[New Thread 0x7fffe0b7a700 (LWP 12046)]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffdbfff700 (LWP 12049)]
loading channel rdpdr (static)
loading channel rdpdr
loading channel rdpsnd
loading channel cliprdr
connected to vic2.some.server:3389
Unable to detect time zone
[New Thread 0x7fffdad3a700 (LWP 12050)]
[New Thread 0x7fffda539700 (LWP 12051)]
[New Thread 0x7fffd9d38700 (LWP 12052)]
[New Thread 0x7fffd9537700 (LWP 12053)]
[New Thread 0x7fffd8d36700 (LWP 12054)]
[New Thread 0x7fffd3fff700 (LWP 12055)]
[New Thread 0x7fffd37fe700 (LWP 12056)]
[New Thread 0x7fffd2ffd700 (LWP 12057)]
[New Thread 0x7fffd27fc700 (LWP 12058)]
Loading device service drive (static)
[New Thread 0x7fffd1ffb700 (LWP 12059)]
[New Thread 0x7fffd0ff9700 (LWP 12061)]
[New Thread 0x7fffd17fa700 (LWP 12060)]
[New Thread 0x7fffcbfff700 (LWP 12062)]
registered device #1: downloads (type=8 id=1)
[Thread 0x7fffdbfff700 (LWP 12049) exited]
[Thread 0x7fffd27fc700 (LWP 12058) exited]
[Thread 0x7fffcbfff700 (LWP 12062) exited]
[Thread 0x7fffd1ffb700 (LWP 12059) exited]
[Thread 0x7fffd0ff9700 (LWP 12061) exited]
[Thread 0x7fffd17fa700 (LWP 12060) exited]

Program received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff5001620 <main_arena>) at malloc.c:4151
4151    malloc.c: No such file or directory.
(gdb) bt full
#0  malloc_consolidate (av=av@entry=0x7ffff5001620 <main_arena>) at malloc.c:4151

```
    fb = <optimized out>
    maxfb = 0x7ffff5001670 <main_arena+80>
    p = 0x7ffff5001678 <main_arena+88>
    nextp = 0xbedd10
    unsorted_bin = 0x7ffff5001678 <main_arena+88>
    first_unsorted = <optimized out>
    nextchunk = 0x7ffff5c6ca68
    size = 13022192
    nextsize = <optimized out>
    prevsize = <optimized out>
    nextinuse = <optimized out>
    bck = <optimized out>
    fwd = <optimized out>
    __func__ = "malloc_consolidate"
```
#1  0x00007ffff4cd7d28 in _int_malloc (av=av@entry=0x7ffff5001620 <main_arena>, bytes=bytes@entry=1760) at malloc.c:3423

```
    nb = 1776
    idx = 75
    bin = <optimized out>
    victim = <optimized out>
    size = <optimized out>
    victim_index = <optimized out>
    remainder = <optimized out>
    remainder_size = <optimized out>
    block = <optimized out>
    bit = <optimized out>
    map = <optimized out>
    fwd = <optimized out>
    bck = <optimized out>
    errstr = 0x0
    __func__ = "_int_malloc"
```
#2  0x00007ffff4cda86c in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3219

```
    av = 0x7ffff5001620 <main_arena>
    oldtop = 0xd9c880
    p = <optimized out>
    bytes = 1760
    sz = 1760
    csz = <optimized out>
    oldtopsize = 132992
    mem = <optimized out>
    clearsize = <optimized out>
    nclears = <optimized out>
    d = <optimized out>
    hook = <optimized out>
    __func__ = "__libc_calloc"
```
#3  0x00007ffff6fa9822 in g_malloc0 (n_bytes=n_bytes@entry=1760) at /tmp/buildd/glib2.0-2.42.1/./glib/gmem.c:127

```
    mem = <optimized out>
```
#4  0x00007ffff7673f42 in _gtk_css_lookup_new (relevant=relevant@entry=0x0) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkcsslookup.c:33

```
    lookup = <optimized out>
    n = 72
```
#5  0x00007ffff77a3579 in build_properties (context=context@entry=0xb02b00, values=values@entry=0x864800, info=info@entry=0xb10580, relevant_changes=relevant_changes@entry=0x0) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:767

```
    priv = 0xb02a80
    matcher = {klass = 0x864800, path = {klass = 0x864800, path = 0xf77a33c4, index = 11601280, sibling_index = 0}, superset = {klass = 0x864800, subset = 0xf77a33c4, relevant = 11601280}}
    path = 0x9988a0
    lookup = <optimized out>
```
#6  0x00007ffff77a34fc in style_values_lookup (context=context@entry=0xb02b00) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:813

```
    priv = 0xb02a80
    values = 0x864800
    info = 0xb10580
    __FUNCTION__ = "style_values_lookup"
```
#7  0x00007ffff77a5be3 in _gtk_style_context_validate (context=0xb02b00, timestamp=timestamp@entry=2068012874551, change=GTK_CSS_CHANGE_STATE, change@entry=0, parent_changes=parent_changes@entry=0x1) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:3060

```
    values = <optimized out>
    priv = 0xb02a80
    info = 0xb10580
    current = <optimized out>
    changes = <optimized out>
    list = <optimized out>
    __FUNCTION__ = "_gtk_style_context_validate"
```
#8  0x00007ffff77a5b52 in _gtk_style_context_validate (context=<optimized out>, timestamp=timestamp@entry=2068012874551, change=change@entry=0, parent_changes=parent_changes@entry=0x1) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:3115

```
    priv = 0xb02940
    info = <optimized out>
    current = <optimized out>
    changes = 0x1
    list = 0x8ee160
    __FUNCTION__ = "_gtk_style_context_validate"
```
#9  0x00007ffff77a5b52 in _gtk_style_context_validate (context=<optimized out>, timestamp=timestamp@entry=2068012874551, change=change@entry=0, parent_changes=parent_changes@entry=0x1) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:3115

```
    priv = 0x7fffe8006da0
    info = <optimized out>
    current = <optimized out>
    changes = 0x1
    list = 0x984250
    __FUNCTION__ = "_gtk_style_context_validate"
```
#10 0x00007ffff77a5b52 in _gtk_style_context_validate (context=<optimized out>, timestamp=timestamp@entry=2068012874551, change=change@entry=0, parent_changes=parent_changes@entry=0x1) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkstylecontext.c:3115

```
    priv = 0x7fffe8006d00
    info = <optimized out>
    current = <optimized out>
    changes = 0x1
    list = 0x76fd40
    __FUNCTION__ = "_gtk_style_context_validate"
```
#11 0x00007ffff766420a in gtk_container_idle_sizer (clock=0x6d13a0, container=0x950240) at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkcontainer.c:1738

```
    current_time = 2068012874551
```
#12 0x00007ffff699f474 in _g_closure_invoke_va (closure=0xc6b990, closure@entry=0xc6a6a0, return_value=0xc127f0, return_value@entry=0x0, instance=0xb1, instance@entry=0x6d13a0, args=0x7ffff5001678 <main_arena+88>, args@entry=0x7fffffffdc88, n_params=-184543704, param_types=0x7ffff5001670 <main_arena+80>) at /tmp/buildd/glib2.0-2.42.1/./gobject/gclosure.c:831

```
    marshal = 0xc6b3f0
    marshal_data = 0x7ffff5001628 <main_arena+8>
    __FUNCTION__ = "_g_closure_invoke_va"
```
#13 0x00007ffff69b9087 in g_signal_emit_valist (instance=0x6d13a0, signal_id=<optimized out>, detail=0, var_args=0x7fffffffdc88) at /tmp/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3218

```
    return_accu = <optimized out>
    accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
    accumulator = 0x0
    emission = {next = 0x0, instance = 0x6d13a0, ihint = {signal_id = 140, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 7122720}
    signal_id = 140
    instance_type = <optimized out>
    emission_return = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
    rtype = 4
    static_scope = 0
    fastpath_handler = <optimized out>
    closure = 0xc6a6a0
    run_type = <optimized out>
    l = <optimized out>
    fastpath = <optimized out>
    instance_and_params = <optimized out>
    signal_return_type = <optimized out>
    param_values = <optimized out>
    i = <optimized out>
    n_params = <optimized out>
    __FUNCTION__ = "g_signal_emit_valist"
```
#14 0x00007ffff69b9f2a in g_signal_emit_by_name (instance=0xc6b990, instance@entry=0x6d13a0, detailed_signal=0xc127f0 "\033", detailed_signal@entry=0x7ffff72fd6b6 "layout") at /tmp/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3405

```
    var_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffddc0, reg_save_area = 0x7fffffffdcd0}}
    detail = 0
    signal_id = 140
    __FUNCTION__ = "g_signal_emit_by_name"
```
#15 0x00007ffff7297954 in gdk_frame_clock_paint_idle (data=0x6d13a0) at /tmp/buildd/gtk+3.0-3.14.5/./gdk/gdkframeclockidle.c:408

```
    iter = 1
    clock = 0x6d13a0
    clock_idle = 0x6d13a0
    priv = 0x6d12c0
    skip_to_resume_events = 0
    timings = 0xc54b00
```
#16 0x00007ffff7289e78 in gdk_threads_dispatch (data=0x82dd60, data@entry=<error reading variable: value has been optimized out>) at /tmp/buildd/gtk+3.0-3.14.5/./gdk/gdk.c:654

```
    dispatch = 0x82dd60
    ret = 0
```
#17 0x00007ffff6fa4613 in g_timeout_dispatch (source=0xc505c0, callback=<optimized out>, user_data=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:4520

```
    timeout_source = 0xc505c0
    again = <optimized out>
```
#18 0x00007ffff6fa3b6d in g_main_dispatch (context=0x68cc20) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3111

```
    dispatch = 0x7ffff6fa4600 <g_timeout_dispatch>
    prev_source = 0x0
    was_in_call = 0
    user_data = 0x82dd60
    callback = 0x7ffff7289e50 <gdk_threads_dispatch>
    cb_funcs = <optimized out>
    cb_data = 0xc63ca0
    need_destroy = <optimized out>
    source = 0xc505c0
    current = 0x6dee00
    i = 0
```
#19 g_main_context_dispatch (context=context@entry=0x68cc20) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3710

No locals.
#20 0x00007ffff6fa3f48 in g_main_context_iterate (context=0x68cc20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3781

```
    max_priority = 120
    timeout = 0
    some_ready = 1
    nfds = <optimized out>
    allocated_nfds = 3
    fds = 0x675ca0
```
#21 0x00007ffff6fa4272 in g_main_loop_run (loop=0x675070) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3975

```
    __FUNCTION__ = "g_main_loop_run"
```
#22 0x00007ffff770fbf5 in gtk_main () at /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkmain.c:1207

```
    loop = 0x675070
```
#23 0x0000000000415778 in main ()

No symbol table info available.
##

**Comment by ic3d** [comment]
This issue affects Remmina 1.1.1 and 1.1.2, that is out of maintenance, we only support Remmina 1.2.*. I'll close this issue in the next days.
