### ISSUE TITLE
Tab key changes windows

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#482]
[ forwarded from https://bugs.debian.org/726048 ]

When using Remmina to connect to xrdp on debian-7.1.0-i386, the Tab key causes the focus to change Windows rather than advancing to the next widget in the current window.
##

**Comment by ic3d** [comment]
This issue affects an old version of Remmina, that is out of maintenance, we only support Remmina 1.2.*. I'm closing this issue.
