### ISSUE TITLE
Keyboard grab broken for 'super' key

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#483]
[ forwarded from https://bugs.debian.org/763723 ]

Keyborad grab does not work correctly for 'super' key. It does not send super+[some key] to remote side, only sends super key itself.
##

**Comment by ic3d** [comment]
A comment form Debian Bug Tracker: _"After some testing I found this: for VNC connections unset Keymap to empty ('Keymap=' in connection file instead of 'Keymap=Map Meta Keys'. Super key will work fine."_

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina.
