### ISSUE TITLE
RDP Window has blue tint on PPC32 system

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#484]
[ forwarded from https://bugs.debian.org/777498] 

RDP Window has blue tint on PPC32 system. Appears to be an endianess problem.
##

**Comment by giox069** [comment]
This seems to be remmina 1.0.0 related, not maintained now. Do you know if the bug is still there in Debian 8 (remmina 1.1.X) PPC ?

**Comment by ic3d** [comment]
Debian Bug Tracker: _"I just checked this using the latest version of Remmina 1.1.2-3 available in Stretch
and the bug is still present."_

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina, now we support only version 1.2.*.
