### ISSUE TITLE
Remarks to some setting's labels

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/Remmina#489]
I'm reviewing the (german) translation and foud some questions/remarks

* VNC setting "Disable server input" what is here disabled?

* RDP-Setting "Client name" - what is this?

* On remmina's settings dialog there is a String "Configure resolutions" which is so far not in PO files.

* On the enhanced page there are a few negative formulated settings; from the usability point of view it would be better to mark them by default and formulate them positive

**Comment by muflone** [comment]
Disable server input disables the control from the client and makes the connection read-only from the client side.

RDP Client name is the name of the client which will be shown to the server. Tipically this is shown in the task manager

Configure resolutions is a new button introduced recently and the .po files are not yet updated, we'll take care of that later.

The options are not easily changed as the existing connections would lose their settings.

If you need further information feel free to open the issue again.
