### ISSUE TITLE
Interface bug: edit window

### ISSUE THREAD

**Issue by Tavda** [FreeRDP/Remmina#491]
![- 20 02 2015 - 10 23 56](https://cloud.githubusercontent.com/assets/1696211/6281877/be412f28-b8eb-11e4-934d-291bdebc500e.png)
Difficult to edit the connection. See the attachment.

uname -a
Linux fsa-k75 3.17.8-gentoo-r1 #1 SMP Sat Jan 31 22:06:26 YEKT 2015 x86_64 AMD A8-4500M APU with Radeon(tm) HD Graphics AuthenticAMD GNU/Linux
[ebuild   R   ~] net-misc/remmina-1.1.1  USE="crypt freerdp nls ssh -avahi (-ayatana) -debug -gnome-keyring -telepathy -vte" 0 KiB

**Comment by muflone** [comment]
We cannot read the Russian language, could you please restart remmina using the command line
LANG=C remmina
and post the same image again with the english language?

**Comment by Tavda** [comment]
1.2.0-rcgit.3 - fixed
