### ISSUE TITLE
Invisible toolbar in fullscreen mode grayed out

### ISSUE THREAD

**Issue by emanuelmocean** [FreeRDP/Remmina#492]
Invisible toolbar in fullscreen mode is grayed out and using keyboard shortcuts to turn it off doesn't work either. 
 I am using Ubuntu 14 with LXDE .

**Comment by giox069** [comment]
1. Which version of remmina are you using ?
2. What do you mean with "grayed" ? Maybe "transparent" ? Can you post a screenshot here ?
3. The fullscreen mode toolbar (internally called "floating toolbar") currently has no shortuct to turn it off. It *must* stay on the screen, but it will usually hide so you see only 2 or 3 pixels of it on the top of your screen.

**Comment by emanuelmocean** [comment]
1. Remmina 0.9.99.1
2. The option can't be selected (the text has gray background and clicking doesn't check it)
3. That is a little dissapointing because I use this daily for a data entry job and a lot of times I try to change broser tabs and end up bringing the "floating toolbar" up . Sometimes I even close it accidentally. It would be really nice if it could be at least moved to a side.

**Comment by giox069** [comment]
1. You can try to upgrade to a newew Remmina version using our Ubuntu PPA. Read [the Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for more info.
2. Now I understand: "Invisible toolbar in fullscreen mode" is an option in the remmina global preferences window. Yes, in version 0.99 it's grayed out, and I don't know why. Try to use the newest remmina as suggested in the previous step. But... read point 3
3. In current development version of Remmina ("next" branch), you can hide the floating toolbar via the option "Invisible toolbar in fullscreen mode". But when you move the mouse on the top of the screen, the floating toolbar will be shown again. So, I don't think "Invisible toolbar in fullscreen mode" is the feature you are looking for, and I currently can't see any simple solution.
For the future, if you want, I can open a new issue/"feature request" requesting to put the floating toolbar on the other sides of the screen (left, right, bottom).

**Comment by emanuelmocean** [comment]
Thank you very much for taking the time to answer . Yes , I think such an option would be really usefull for users who use it to browse the web daily like I do . For now I just adjusted the browser window's vertical size so the toolbar doesn't get in the way anymore.
