### ISSUE TITLE
Show or hide the icons near the menu

### ISSUE THREAD

**Issue by muflone** [FreeRDP/Remmina#504]
Latest GTK+ releases by default hide the icons near the menu.
Add a preference to restore the old behavior and show the menu icons.

**Comment by muflone** [comment]
Please test and comment the PR #505

**Comment by muflone** [comment]
Fixed by the PR #505

**Comment by ozbek** [comment]
This feature is not working on Ubuntu (1.1.1-1+745+next+201504260616~ubuntu14.04.1):

Regardless of the user setting, button icons are always shown, menu icons are never shown.
