### ISSUE TITLE
Remmina can no longer recognize RDP authentication failure

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#507]
With the latest FreeRDP library version, remmina can no longer detect when NLA user authentication fails. This poses two problems:
1. The user receives a generic connection warning, not an "authentication failed"
2. Saved user credentials are not blanked as expected
##

**Comment by ic3d** [comment]
@giox069 FreeRDP bug is now closed, do you think we can close this one too?

**Comment by giox069** [comment]
Yes! Thank you :)
