### ISSUE TITLE
Remmina doesn't work with Windows Azure HDInsights remote connection

### ISSUE THREAD

**Issue by rathboma** [FreeRDP/Remmina#513]
I realize this is a bit vague, but when running a HDInsights cluster in Windows Azure and enabling remote desktop (Windows Server 2012), Remmina is unable to connect (it just says 'unable to connect').

Connecting works fine from my windows 7 vm, so I know the server is accepting connections. Is there a way for me to debug this?

In windows I had to accept a certificate before connecting, could it be something like that screwing things up?

**Comment by muflone** [comment]
Hi

Remmina branch next has an option to ignore the certificates, try to check that option.
If you execute remmina from the command line you can see various message, useful to debug issues.

Furthermore, you should try to connect to your server using xfreerdp command line, that will help you to properly understand how to configure the Remmina connection.

**Comment by antenore** [comment]
@rathboma 

Do you still need support?

Did you try to test the connection from the command line with xfreerdp?

    xfreerdp +clipboard /v:hostname /u:username

Can you also provide more details about your setup ( distro/OS, remmina ad freerdp version, desktop environment, etc)

**Comment by antenore** [comment]
@rathboma 
I close this. Just reopen it if you need support.
