### ISSUE TITLE
Cursor mouse disappearing in RDP connection

### ISSUE THREAD

**Issue by maxvodo** [FreeRDP/Remmina#514]
When mouse pointer inside of guest area, cursor sometimes disappeared or cursor becomes virtually invisible:
![screenshot from 2015-03-04 13 32 43](https://cloud.githubusercontent.com/assets/5998258/6482001/32939fb0-c273-11e4-9dcf-84677fdec5fe.png)

And this is normal cursor in host mode (over host window):
![screenshot from 2015-03-04 13 32 57](https://cloud.githubusercontent.com/assets/5998258/6482002/329414fe-c273-11e4-91d7-35069755dead.png)

Host OS: Ubuntu 12.04 LTS, x64, Elementary OS Luna. 
Guest OS: Windows 2003.
FreeRDP build: branch master FreeRDP/FreeRDP@b33bba04288648e94039c6de724474f01fbd0d73
Remmina build: branch v1.2.0-rcgit.2 @93bf25e8ec2e69ca9d807e351675d333a5a3ddfc, clean make, remmina version 1.2.0-rcgit.2 (about dialog). 

Also, in remmina package from ubuntu repo I wasn't seen something like that.

**Comment by antenore** [comment]
@maxvodo 

First of all note that Ubuntu 12.04 provides a really old GTK3 version, if you can upgrade your OS it would surely help.

Coming back to your problem.
Do you have "Option SWCursor ON" set in your Xorg? Can you please test with that option?

If you don't, can you please post your "lspci -vvv" "xrandr --query" and any relevant xorg.conf sections?

Thanks.

**Comment by maxvodo** [comment]
@antenore, sorry for awaiting. Now I using remmina and do you know, what? 
It's working fine, no more problem with mouse cursor in RDP session. :blush:

No, I didn't find "Option SWCursor ON" on any form (remmina preferences or RDP connection settings). But I using for my RDP session "Quality" option "Best".

**Comment by maxvodo** [comment]
@antenore, is "lspci -vvv" "xrandr --query" request still actual?

**Comment by antenore** [comment]
I'm closing this. Open a new one if you still have an issue.
