### ISSUE TITLE
NX connection to freenx-server with public key not working

### ISSUE THREAD

**Issue by fansari** [FreeRDP/Remmina#515]
A connection to freenx-server with public key is not possible.

I put my public key in /var/lib/nxserver/home/.ssh/authorized_keys readable for user nx.

In order to test I put selinux to permissive and disabled firewalld.

I get these errors from the nxserver:

-- NX SERVER START: -c /usr/libexec/nx/nxserver - ORIG_COMMAND=
-- NX SERVER START:  - ORIG_COMMAND=
Info: Using fds #4 and #3 for communication with nxnode.
HELLO NXSERVER - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
NX> 105 HELLO NXCLIENT - Version 3.2.0
NX> 134 Accepted protocol: 3.2.0
NX> 105 SET SHELL_MODE SHELL
NX> 105 SET AUTH_MODE PASSWORD
NX> 105 login
NX> 101 User: fansari
NX> 102 Password:
Info: Auth method: ssh Permission denied (publickey,gssapi-keyex,gssapi-with-mic).^M
FREENX> 716 Slave mode failed to start.
Info: Closing connection to slave with pid 13663.

NX> 404 ERROR: wrong password or login
NX> 999 Bye

From sshd it seems that in the beginning the communication is succesful. Also I can clearly see 
A connection to freenx-server with public key is not possible.

I put my public key in /var/lib/nxserver/home/.ssh/authorized_keys readable for user nx.

In order to test I put selinux to permissive and disabled firewalld.

I get these errors from the nxserver:

-- NX SERVER START: -c /usr/libexec/nx/nxserver - ORIG_COMMAND=
-- NX SERVER START:  - ORIG_COMMAND=
Info: Using fds #4 and #3 for communication with nxnode.
HELLO NXSERVER - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
NX> 105 HELLO NXCLIENT - Version 3.2.0
NX> 134 Accepted protocol: 3.2.0
NX> 105 SET SHELL_MODE SHELL
NX> 105 SET AUTH_MODE PASSWORD
NX> 105 login
NX> 101 User: fansari
NX> 102 Password:
Info: Auth method: ssh Permission denied (publickey,gssapi-keyex,gssapi-with-mic).^M
FREENX> 716 Slave mode failed to start.
Info: Closing connection to slave with pid 13663.

NX> 404 ERROR: wrong password or login
NX> 999 Bye

From sshd it seems that in the beginning the communication is succesful. 

Also I can clearly see that it behaves differently when I don't have my key in the authorized_keys. 

With the authorized_key file there is some successful communication in the beginning. The strange thing is that I am asked for a password (it does not even come up to this point when I don't have the entry in the authorized_keys file).

ar 06 12:44:52 intel.localdomain sshd[13501]: debug1: attempt 0 failures 0 [preauth]
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: PAM: initializing for "fansari"
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: PAM: setting PAM_RHOST to "localhost"
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: PAM: setting PAM_TTY to "ssh"
Mar 06 12:44:52 intel.localdomain sshd[13501]: Connection closed by 127.0.0.1 [preauth]
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: do_cleanup [preauth]
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: monitor_read_log: child log fd closed
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: do_cleanup
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: PAM: cleanup
Mar 06 12:44:52 intel.localdomain sshd[13501]: debug1: Killing privsep child 13502
Mar 06 12:45:33 intel.localdomain sshd[12566]: debug1: Forked child 13513.
Mar 06 12:45:33 intel.localdomain sshd[13513]: Set /proc/self/oom_score_adj to 0
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: inetd sockets after dupping: 3, 3
Mar 06 12:45:33 intel.localdomain sshd[13513]: Connection from 2001:4dd0:ff00:8e7f:5246:5dff:fe9e:7b30 port 45675 on 2001:4dd0:ff00:8e7f:c23f:d5ff:fe64:c7ff port 222
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: Client protocol version 2.0; client software version libssh-0.6.4
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: no match: libssh-0.6.4
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: Enabling compatibility mode for protocol 2.0
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: Local version string SSH-2.0-OpenSSH_6.6.1
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SELinux support enabled [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: ssh_selinux_change_context: setting context from 'system_u:system_r:sshd_t:s0-s0:c0.c1023' to 'system_u:system_r:sshd_net_t:s0-s0:c0.c1023' [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: permanently_set_uid: 74/74 [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256 [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SSH2_MSG_KEXINIT received [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: kex: client->server aes256-ctr hmac-sha1 none [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: kex: server->client aes256-ctr hmac-sha1 none [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: KEX done [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: userauth-request for user nx service ssh-connection method publickey [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: attempt 0 failures 0 [preauth]
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: PAM: initializing for "nx"
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: PAM: setting PAM_RHOST to "bat"
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: PAM: setting PAM_TTY to "ssh"
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: temporarily_use_uid: 985/980 (e=0/0)
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: trying public key file /var/lib/nxserver/home/.ssh/authorized_keys
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: fd 4 clearing O_NONBLOCK
Mar 06 12:45:33 intel.localdomain sshd[13513]: Found matching RSA key: 9a:c5:84:98:f8:c9:93:31:75:e7:c2:67:b3:1c:d6:31
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: restore_uid: 0/0
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: ssh_rsa_verify: signature correct
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: do_pam_account: called
Mar 06 12:45:33 intel.localdomain sshd[13513]: Accepted publickey for nx from 2001:4dd0:ff00:8e7f:5246:5dff:fe9e:7b30 port 45675 ssh2: RSA 9a:c5:84:98:f8:c9:93:31:75:e7:c2:67:b3:1c:d6:31
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: monitor_child_preauth: nx has been authenticated by privileged process
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: monitor_read_log: child log fd closed
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: temporarily_use_uid: 985/980 (e=0/0)
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: ssh_gssapi_storecreds: Not a GSSAPI mechanism
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: restore_uid: 0/0
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: SELinux support enabled
Mar 06 12:45:33 intel.localdomain sshd[13513]: debug1: PAM: establishing credentials
Mar 06 12:45:35 intel.localdomain sshd[13672]: Set /proc/self/oom_score_adj to 0
Mar 06 12:45:35 intel.localdomain sshd[12566]: debug1: Forked child 13672.
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: inetd sockets after dupping: 3, 3
Mar 06 12:45:35 intel.localdomain sshd[13672]: Connection from 127.0.0.1 port 34138 on 127.0.0.1 port 222
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1\* compat 0x04000000
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: Enabling compatibility mode for protocol 2.0
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: Local version string SSH-2.0-OpenSSH_6.6.1
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: SELinux support enabled [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: ssh_selinux_change_context: setting context from 'system_u:system_r:sshd_t:s0-s0:c0.c1023' to 'system_u:system_r:sshd_net_t:s0-s0:c0.c1023' [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: permanently_set_uid: 74/74 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: SSH2_MSG_KEXINIT received [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: kex: curve25519-sha256@libssh.org need=16 dh_need=16 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: kex: curve25519-sha256@libssh.org need=16 dh_need=16 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: KEX done [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: userauth-request for user fansari service ssh-connection method none [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: attempt 0 failures 0 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: PAM: initializing for "fansari"
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: PAM: setting PAM_RHOST to "localhost"
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: PAM: setting PAM_TTY to "ssh"
Mar 06 12:45:35 intel.localdomain sshd[13672]: Connection closed by 127.0.0.1 [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: do_cleanup [preauth]
Mar 06 12:45:35 intel.localdomain sshd[13672]: debug1: monitor_read_log: child log fd closed
##

**Comment by fansari** [comment]
It seems that the public key authentication only apples to the SSH protocol communication but that the login to the machine is a different thing. The NoMachine client behaves the same way.

**Comment by antenore** [comment]
@fansari 

I don't have an NX server available at the moment.

Did you try an ssh connection by hand? THis is th first very important test you should do.

It looks like the nx user (the one that run the nx server) does not have access to the key.

Change to that user and try to cat the file, just to be sure everything is set up correctly.

**Comment by ic3d** [comment]
Hello @fansari ! We are reviewing old issues, so: do you still get this problem with the latest Remmina version? Thanks!

**Comment by fansari** [comment]
Sorry, no idea. I haven't used this software for a long time.

**Comment by ic3d** [comment]
Closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.
