### ISSUE TITLE
NX connection to freenx-server not possible

### ISSUE THREAD

**Issue by fansari** [FreeRDP/Remmina#516]
After I found theat the public key method does not work Ifor NX  tried to setup a connection with password.

Alll I get is a blank black screen. After some second there appears an error message: "Oh no. Something has gone wrong:" together with a "Logout" button.

What I don't know is whether this is a problem of Remmina or a problem of the freenx-server or some wrong configuration.

-- NX SERVER START: -c /usr/libexec/nx/nxserver - ORIG_COMMAND=
-- NX SERVER START:  - ORIG_COMMAND=
Info: Using fds #4 and #3 for communication with nxnode.
HELLO NXSERVER - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
NX> 105 HELLO NXCLIENT - Version 3.2.0
NX> 134 Accepted protocol: 3.2.0
NX> 105 SET SHELL_MODE SHELL
NX> 105 SET AUTH_MODE PASSWORD
NX> 105 login
NX> 101 User: fansari
NX> 102 Password: 
Info: Auth method: ssh fansari@127.0.0.1's password:
NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
NX> 716 Slave mode started successfully.
nxnode_reader: NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
nxnode_reader: NX> 716 finished
nxnode_reader: NX> 1001 Bye.

NX> 103 Welcome to: intel.localdomain user: fansari
NX> 105 listsession --user="fansari" --status="suspended,running" --type="unix-gnome"
NX> 127 Sessions list of user 'fansari' for reconnect:

Display Type             Session ID                       Options  Depth Screen         Status      Session Name
------- ---------------- -------------------------------- -------- ----- -------------- ----------- ------------------------------

NX> 148 Server capacity: not reached for user: fansari
NX> 105 startsession --encryption="1" --session="intel" --link="modem" --cache="16M" --type="unix-gnome" --backingstore="1" --clipboard="both" --client="linux" --geometry="1920x1080" --media="0" --agent_server="" --images="64M" agent_password="******"1" --screeninfo="1920x1080x24+render" --keyboard="pc104/de" --agent_user="" 

&encryption=1&session=intel&link=modem&cache=16M&type=unix-gnome&backingstore=1&clipboard=both&client=linux&geometry=1920x1080&media=0&agent_server=&images=64M&agent_password=******&screeninfo=1920x1080x24+render&keyboard=pc104/de&agent_user=&clientproto=3.2.0&login_method=SSH&user=fansari&userip=2001:4dd0:ff00:8e7f:5246:5dff:fe9e:7b30&uniqueid=A3DCAC0DF0EF50F4BF5758E85B0ADC7E&display=2015&host=127.0.0.1 
nxnode_reader: NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
server_nxnode_echo: NX> 1000 NXNODE - Version 3.2.0-74-SVN OS (GPL, using backend: not detected)
nxnode_reader: ping: icmp open socket: Operation not permitted
ping: icmp open socket: Operation not permitted
nxnode_reader: NX> 700 Session id: intel.localdomain-2015-A3DCAC0DF0EF50F4BF5758E85B0ADC7E
nxnode_reader: NX> 705 Session display: 2015
nxnode_reader: NX> 703 Session type: unix-gnome
nxnode_reader: NX> 701 Proxy cookie: 4689d7fc061f49d6344abc9fa6671650
nxnode_reader: NX> 702 Proxy IP: 127.0.0.1
nxnode_reader: NX> 706 Agent cookie: 4689d7fc061f49d6344abc9fa6671650
nxnode_reader: NX> 704 Session cache: unix-gnome
nxnode_reader: NX> 707 SSL tunneling: 1
server_nxnode_echo: NX> 700 Session id: intel.localdomain-2015-A3DCAC0DF0EF50F4BF5758E85B0ADC7E
server_nxnode_echo: NX> 705 Session display: 2015
NX> 700 Session id: intel.localdomain-2015-A3DCAC0DF0EF50F4BF5758E85B0ADC7E
NX> 705 Session display: 2015
NX> 703 Session type: unix-gnome
NX> 701 Proxy cookie: 4689d7fc061f49d6344abc9fa6671650
NX> 702 Proxy IP: 127.0.0.1
NX> 706 Agent cookie: 4689d7fc061f49d6344abc9fa6671650
NX> 704 Session cache: unix-gnome
NX> 707 SSL tunneling: 1
server_nxnode_echo: NX> 703 Session type: unix-gnome
server_nxnode_echo: NX> 701 Proxy cookie: 4689d7fc061f49d6344abc9fa6671650
server_nxnode_echo: NX> 702 Proxy IP: 127.0.0.1
server_nxnode_echo: NX> 706 Agent cookie: 4689d7fc061f49d6344abc9fa6671650
server_nxnode_echo: NX> 704 Session cache: unix-gnome
server_nxnode_echo: NX> 707 SSL tunneling: 1
nxnode_reader: NX> 1009 Session status: starting
NX> 1009 Session status: starting
server_nxnode_echo: NX> 1009 Session status: starting
nxnode_reader: NX> 710 Session status: running
NX> 710 Session status: running
nxnode_reader: NX> 1002 Commit
NX> 1002 Commit
server_nxnode_echo: NX> 710 Session status: running
nxnode_reader: NX> 1006 Session status: running
NX> 1006 Session status: running
server_nxnode_echo: NX> 1002 Commit
session_status A3DCAC0DF0EF50F4BF5758E85B0ADC7E Running
NX> 105 server_nxnode_echo: NX> 1006 Session status: running
bye
Bye
NX> 999 Bye
Info: Closing connection to slave with pid 17480.
nxnode_reader: 1001 Bye.
1001 Bye.
nxnode_reader: NX> 1009 Session status: suspending
session_status A3DCAC0DF0EF50F4BF5758E85B0ADC7E Suspending
NX> 1009 Session status: suspending
nxnode_reader: NX> 1005 Session status: suspended
NX> 1005 Session status: suspended
server_nxnode_echo: NX> 1009 Session status: suspending
session_suspend A3DCAC0DF0EF50F4BF5758E85B0ADC7E
server_nxnode_echo: NX> 1005 Session status: suspended

**Comment by fansari** [comment]
The issue is ralated to GNOME3. The same thing appears with the NoMachine client when I choose an SSH session. With port 4000 it works - but I cannot find a way to make freenx-server work in the same way.

https://bugzilla.redhat.com/show_bug.cgi?id=958259
https://www.centos.org/forums/viewtopic.php?t=47386&p=201363

Testing with xfce4 works out of the box.

**Comment by antenore** [comment]
@fansari 

Thanks for your report, let us know if you still need support.
