### ISSUE TITLE
Remmina crashes attempting VNC connection to Mac OS X Yosemite

### ISSUE THREAD

**Issue by penalvch** [FreeRDP/Remmina#517]
1)  lsb_release -rd
Description:    Ubuntu 14.10
Release:    14.10

2) Remmina versions:
https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next?field.series_filter=utopic
1.1.1-1+724+next+201503042231~ubuntu14.10.1
https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-master?field.series_filter=utopic
1.1.1-1+483+201502131916~ubuntu14.10.1

3) What is expected to happen is when I attempt a VNC connection to Mac OS X Yosemite via OS X built-in VNC with Remmina settings:
Basic tab
Color Depth (15-bit)
Quality Poor (fastest)
All other checkboxes unchecked

it connects like it did with the version of Remmina found in Vivid 1.1.1-1ubuntu1.

4) What happens instead is it crashes consistently. Hence, would appear to be a regression from the VIvid version to later versions of Remmina.

Crash reports:
https://errors.ubuntu.com/oops/ba55d20a-c391-11e4-bb92-fa163e4ccdf2
https://errors.ubuntu.com/oops/f1df87ba-c388-11e4-9185-fa163e4aaad4
##

**Comment by giox069** [comment]
@penvalch: unfortunately I'm unable to access the crash reports, because Canonical requires me to sign a quite complex contract and it's a bit off topic now. Can you extract only the stack trace part and post here ?
Please also check if the last commit/merge of today remmina next will fix the problem (the PPA will update automatically with the last commit in 1 day, I hope).

**Comment by penalvch** [comment]
glox069, thanks for the quick response.

>"@penvalch: unfortunately I'm unable to access the crash reports, because Canonical requires me to sign a quite complex contract and it's a bit off topic now."

the privacy policy is not complex at all (one page, a few paragraphs) -> https://forms.canonical.com/reports/ .

>"Can you extract only the stack trace part and post here ?"

Please see below.

Master:

StacktraceAddressSignature 	

/usr/bin/remmina:6:/lib/x86_64-linux-gnu/libpthread-2.19.so+fb5b:/usr/lib/x86_64-linux-gnu/libfreerdp-utils.so.1.1.0+4555:/lib/x86_64-linux-gnu/libc-2.19.so+36e37:/lib/x86_64-linux-gnu/libc-2.19.so+38528:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+118f4:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+11c01:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+120b8:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+aefa:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+b274:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9c665:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9d2e1:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9ac80:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+a53d7:/usr/lib/x86_64-linux-gnu/libvncclient.so.0.0.0+1425c:/usr/lib/x86_64-linux-gnu/libvncclient.so.0.0.0+16064

StacktraceTop 	

__GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
__GI_abort () at abort.c:89
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20

Next:

StacktraceAddressSignature

/usr/bin/remmina:6:/lib/x86_64-linux-gnu/libc-2.19.so+36e37:/lib/x86_64-linux-gnu/libc-2.19.so+38528:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+118f4:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+11c01:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+120b8:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+aefa:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+b274:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9c665:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9d2e1:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+9ac80:/lib/x86_64-linux-gnu/libgcrypt.so.20.0.1+a53d7:/usr/lib/x86_64-linux-gnu/libvncclient.so.0.0.0+1425c:/usr/lib/x86_64-linux-gnu/libvncclient.so.0.0.0+16064:/usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-vnc.so+67f1:/usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-vnc.so+6cb6

StacktraceTop 	

?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20

>"Please also check if the last commit/merge of today remmina next will fix the problem (the PPA will update automatically with the last commit in 1 day, I hope)."

Unfortunately, I won't be able to do that as I've already purged the PPA, and returned to the original version in Utopic. As well, the PPA had a nasty side effect of borking RDP connections until I completely uninstalled, and reinstalled the original packages.

**Comment by antenore** [comment]
@penalvch 
 Can you please clarify if you still have the issue or not?

Thanks in advance

**Comment by penalvch** [comment]
antenore, while I won't be testing the PPA again, this is not reproducible in the version available in Vivid:
apt-cache policy remmina
remmina:
  Installed: 1.1.1-1ubuntu1
  Candidate: 1.1.1-1ubuntu1
  Version table:
 *** 1.1.1-1ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by ic3d** [comment]
Hi @penalvch, to do you still get this issue with our latest version of Remmina (1.2.*)? Thanks!

**Comment by penalvch** [comment]
ic3d, thanks for the follow up.

I don't remote into a Mac anymore, and wouldn't remote into Mac OS X Yosemite if I did.

Also, I only use Remmina from Ubuntu's supported repositories as per below.

Hence, I'll close this report, and open a new one if reproducible in latest Mac OS.

apt policy remmina
remmina:
  Installed: 1.1.2-3ubuntu1
  Candidate: 1.1.2-3ubuntu1
  Version table:
 *** 1.1.2-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
