### ISSUE TITLE
Can't share a folder in KDE, due to Gtk issue

### ISSUE THREAD

**Issue by mmardegan** [FreeRDP/Remmina#518]
Fedora 20 64bit, KDE 4.14.4, remmina 1.2.0-rcgit.2

I installed the program using this guide: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20.
I can finally share also the smart card: thanks to all the developers!!!
But there is still a problem: when I try to share a folder in the configuration tab of a connection, the program crashes, with this error messages:

(remmina:10841): Gtk-CRITICAL *: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
(remmina:10841): GLib-GObject-WARNING *: gtype.c:4215: type id '0' is invalid
(remmina:10841): GLib-GObject-WARNING **: can't peek value table for type '' which is not currently referenced
Errore di segmentazione

The problem was present also in the previous versions of remmina and kde.
Is there a way to resolve this issue?
Thank you very much.

**Comment by antenore** [comment]
@mmardegan 

Can do a back trace with gdb? (gdb remmina --> run---> bt as soon as you have the segmentation fault)

**Comment by mmardegan** [comment]
This is the output. Ty.
---
(gdb) run
Starting program: /usr/local/bin/remmina 
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3800.2-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3800.2-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libgraphite2.so.3
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/90/82e46860379c3dff9004eb8c9834e50afbb528.debug
[New Thread 0x7ffff0baf700 (LWP 11155)]
Remmina plugin XDMCP (type=Protocollo) registered.
NX: detected keyboard type evdev/it
Remmina plugin NX (type=Protocollo) registered.
Remmina plugin GKEYRING (type=Segreto) registered.
Remmina plugin telepathy (type=Voce) registered.
Remmina plugin VNC (type=Protocollo) registered.
Remmina plugin VNCI (type=Protocollo) registered.
Remmina plugin RDP (type=Protocollo) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preferenza) registered.
Remmina plugin SFTP (type=Protocollo) registered.
Remmina plugin SSH (type=Protocollo) registered.
[New Thread 0x7fffe7805700 (LWP 11156)]
Detaching after fork from child process 11157.
Detaching after fork from child process 11158.
[New Thread 0x7fffe63fe700 (LWP 11159)]

(remmina:11151): Gtk-WARNING **: Unknown property: GtkStatusbar.margin-start

(remmina:11151): Gtk-WARNING **: Unknown property: GtkStatusbar.margin-end
[Thread 0x7fffe7805700 (LWP 11156) exited]
[New Thread 0x7fffe7805700 (LWP 11161)]
[New Thread 0x7fffe587d700 (LWP 11162)]
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[Thread 0x7fffe587d700 (LWP 11162) exited]
[New Thread 0x7fffe587d700 (LWP 11163)]
[Thread 0x7fffe587d700 (LWP 11163) exited]

(remmina:11151): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(remmina:11151): GLib-GObject-WARNING **: gtype.c:4215: type id '0' is invalid

(remmina:11151): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

Program received signal SIGSEGV, Segmentation fault.
0x00000036568a4add in gtk_tree_model_get_valist () from /lib64/libgtk-3.so.0
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-7.fc20.x86_64 alsa-lib-1.0.27.2-2.fc20.x86_64 at-spi2-atk-2.10.2-1.fc20.x86_64 at-spi2-core-2.10.2-1.fc20.x86_64 atk-2.10.0-1.fc20.x86_64 avahi-glib-0.6.31-21.fc20.x86_64 avahi-libs-0.6.31-21.fc20.x86_64 avahi-ui-gtk3-0.6.31-21.fc20.x86_64 cairo-1.14.0-2.fc20.x86_64 cairo-gobject-1.14.0-2.fc20.x86_64 celt-0.11.3-1.fc20.x86_64 cups-libs-1.7.5-13.fc20.x86_64 dbus-glib-0.100.2-2.fc20.x86_64 dbus-libs-1.6.30-1.fc20.x86_64 expat-2.1.0-7.fc20.x86_64 ffmpeg-libs-2.1.7-1.fc20.x86_64 flac-libs-1.3.1-1.fc20.x86_64 fontconfig-2.11.0-2.fc20.x86_64 freetype-2.5.0-10.fc20.x86_64 gdbm-1.10-8.fc20.x86_64 gdk-pixbuf2-2.30.3-1.fc20.x86_64 glib2-2.38.2-2.fc20.x86_64 glibc-2.18-19.fc20.x86_64 gmp-5.1.2-2.fc20.x86_64 gnutls-3.1.28-2.fc20.x86_64 gsm-1.0.13-10.fc20.x86_64 gstreamer1-1.2.4-1.fc20.x86_64 gstreamer1-plugins-base-1.2.4-1.fc20.x86_64 gtk3-3.10.9-2.fc20.x86_64 gvfs-1.18.4-1.fc20.x86_64 harfbuzz-0.9.27-1.fc20.x86_64 json-c-0.11-6.fc20.x86_64 keyutils-libs-1.5.9-1.fc20.x86_64 krb5-libs-1.11.5-18.fc20.x86_64 lame-libs-3.99.5-2.fc19.x86_64 libICE-1.0.8-6.fc20.x86_64 libSM-1.2.1-6.fc20.x86_64 libX11-1.6.1-1.fc20.x86_64 libXau-1.0.8-2.fc20.x86_64 libXcomposite-0.4.4-4.fc20.x86_64 libXcursor-1.1.14-2.fc20.x86_64 libXdamage-1.1.4-4.fc20.x86_64 libXext-1.3.2-2.fc20.x86_64 libXfixes-5.0.1-2.fc20.x86_64 libXi-1.7.4-1.fc20.x86_64 libXinerama-1.1.3-2.fc20.x86_64 libXrandr-1.4.1-2.fc20.x86_64 libXrender-0.9.8-2.fc20.x86_64 libXtst-1.2.2-2.fc20.x86_64 libappindicator-gtk3-12.10.0-3.fc20.x86_64 libasyncns-0.8-6.fc20.x86_64 libattr-2.4.47-3.fc20.x86_64 libbluray-0.7.0-1.fc20.x86_64 libcap-2.22-7.fc20.x86_64 libcom_err-1.42.12-3.fc20.x86_64 libdbusmenu-12.10.2-5.fc20.x86_64 libdbusmenu-gtk3-12.10.2-5.fc20.x86_64 libdrm-2.4.58-1.fc20.x86_64 libffi-3.0.13-5.fc20.x86_64 libgcc-4.8.3-7.fc20.x86_64 libgcrypt-1.5.3-2.fc20.x86_64 libgnome-keyring-3.10.1-1.fc20.x86_64 libgpg-error-1.12-1.fc20.x86_64 libindicator-gtk3-12.10.1-2.fc20.x86_64 libjpeg-turbo-1.3.1-3.fc20.x86_64 libogg-1.3.0-6.fc20.x86_64 libpng-1.6.6-3.fc20.x86_64 libselinux-2.2.1-6.fc20.x86_64 libsndfile-1.0.25-9.fc20.x86_64 libssh-0.6.4-1.fc20.x86_64 libstdc++-4.8.3-7.fc20.x86_64 libtasn1-3.8-2.fc20.x86_64 libtheora-1.1.1-9.fc20.x86_64 libuuid-2.24.2-2.fc20.x86_64 libva-1.2.1-3.fc20.x86_64 libvncserver-0.9.10-0.6.20140718git9453be42.fc20.x86_64 libvorbis-1.3.4-1.fc20.x86_64 libvpx-1.3.0-100.git8f850d6.fc20.x86_64 libwayland-client-1.2.0-3.fc20.x86_64 libwayland-cursor-1.2.0-3.fc20.x86_64 libwayland-server-1.2.0-3.fc20.x86_64 libxcb-1.9.1-3.fc20.x86_64 libxkbcommon-0.4.3-2.fc20.x86_64 libxkbfile-1.0.8-4.fc20.x86_64 libxml2-2.9.1-3.fc20.x86_64 lzo-minilzo-2.08-1.fc20.x86_64 mesa-libEGL-10.3.3-1.20141110.fc20.x86_64 mesa-libgbm-10.3.3-1.20141110.fc20.x86_64 mesa-libglapi-10.3.3-1.20141110.fc20.x86_64 ncurses-libs-5.9-12.20130511.fc20.x86_64 nettle-2.7.1-3.fc20.x86_64 nss-softokn-freebl-3.17.4-1.fc20.x86_64 openjpeg-libs-1.5.1-13.fc20.x86_64 openssl-libs-1.0.1e-41.fc20.x86_64 opus-1.1-1.fc20.x86_64 orc-0.4.22-2.fc20.x86_64 oxygen-gtk3-1.3.5-1.fc20.x86_64 p11-kit-0.20.7-1.fc20.x86_64 pango-1.36.1-3.fc20.x86_64 pcre-8.33-8.fc20.x86_64 pixman-0.30.0-5.fc20.x86_64 pulseaudio-libs-5.0-25.fc20.x86_64 schroedinger-1.0.11-5.fc20.x86_64 speex-1.2-0.18.rc1.fc20.x86_64 systemd-libs-208-30.fc20.x86_64 tcp_wrappers-libs-7.6-76.fc20.x86_64 telepathy-glib-0.22.0-1.fc20.x86_64 trousers-0.3.13-1.fc20.x86_64 vte3-0.34.9-3.fc20.x86_64 x264-libs-0.138-2.20131030gitc628e3b.fc20.x86_64 xvidcore-1.3.2-5.fc20.x86_64 xz-libs-5.1.2-12alpha.fc20.x86_64 zlib-1.2.8-3.fc20.x86_64
(gdb)

**Comment by antenore** [comment]
Thanks for the stack.

Which gtk and qt themes/engines do you have? Can you test with a default theme? Maybe you can try with a new user, that way you won't loose your settings.

**Comment by mmardegan** [comment]
I use Oxygen theme, style, ecc... 
I tried to create a new user and launch the program via new user.
The problem persists: I open remmina (also  via gdb), I create a new profile (or a  new connection), I select RDP protocol, server IP, credentials, etc, than I select the "share folder" radio button and finaly the program crashes (with the same messages) when I try to select the folder to share.

**Comment by antenore** [comment]
Unlucky I really cannot reproduce the issue so far.

It seems an issue around GTK and KDE inter operability and I should be able to patch Remmina to workaround this issue setting a default folder.

If you are willing to help, can you kindly tests different themes, or even test a pure Gnome installation (if you have any)? It would help me to exclude (or not) KDE.

Thanks in advance.

**Comment by antenore** [comment]
@mmardegan One more thing.

Does it change anything modifying the following property inside /usr/share/themes/oxygen-gtk/gtk-3.0/gtk.css from

    GtkComboBox-appears-as-list: 1; 

to 
    
    GtkComboBox-appears-as-list: 0;

Or same thing inside /usr/share/themes/oxygen-gtk/gtk-2.0/gtkrc if you are using (you should not) GTK2 version.

You could have the same property in your home.

**Comment by mmardegan** [comment]
@antenore 
Does it change anything modifying the following property inside /usr/share/themes/oxygen-gtk/gtk-3.0/gtk.css from
GtkComboBox-appears-as-list: 1; 

I modify that property and now remmina don't crashes.
Thank you!
Shall I close the issue?

**Comment by antenore** [comment]
Just for reference. This is related to well known gtk bug.
