### ISSUE TITLE
RDP Quality is not being stored

### ISSUE THREAD

**Issue by michaelhofer** [FreeRDP/Remmina#521]
When I change the RDP quality option (which is set to "poor" by default) in the Remmina preferences, the new value is never being stored. Setting the quality option for stored RDP sessions works as expected. 
I'm running Ubuntu 14.10, Remmina version in apt-cache is shown as 1.1.1-1+725+next+201503102231~ubuntu14.10.1

**Comment by giox069** [comment]
The "Quality settings" in Remmina preferences -> RDP is not the "default" quality. Is a tool which can be used to edit the four quality profiles. Call it a "quality profile editor".

**Comment by michaelhofer** [comment]
Thanks, I'm really sorry about this, looks like I misunderstood this one. I'll close the issue since it's not relevant.

**Comment by giox069** [comment]
No problems @michaelhofer. Your question will be useful for a FAQ list or for a UI improvement :)
