### ISSUE TITLE
Problem with shared  folder on Windows Server 2012

### ISSUE THREAD

**Issue by dulaman** [FreeRDP/Remmina#523]
Everythink works perfect except that I cannot find shared folder in "This PC" (replacement of "My Computer") and tsclient workgroup.

**Comment by giox069** [comment]
Please post also the version of remmina you are using and which client OS too.

**Comment by dulaman** [comment]
Remmina: 0.9.99.1
OS: Xubuntu 14.04

**Comment by giox069** [comment]
Please upgrade remmina to the latest version we are developing now (1.2.rcgit-something). See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) and use the Ubuntu remmina-next PPA as explained at the beginning of the wiki homepage.

**Comment by dulaman** [comment]
I just update to 1.2.0-rcgit.2 and I have still the same problem.

**Comment by giox069** [comment]
Please try the following: close remmina, open a terminal window, and type
```
killall remmina
remmina
```
connect to your windows 2012 server.
You should see libfreerdp complaining that it cannot find libdrive-client.so. If you see it, we have a problem in the PPA and should fix it :)

**Comment by dulaman** [comment]
Still doesn't work.

**Comment by giox069** [comment]
Can you paste here the text you see on the terminal when you connect to the 2012 server? I need to know if libdrive-client.so is missing in your system or not.

**Comment by dulaman** [comment]
[11:22:40:452] [12979:1606375168] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[11:22:40:452] [12979:1606375168] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[11:22:40:452] [12979:1606375168] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[11:22:40:571] [12979:1590925056] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)
[11:22:40:571] [12979:1590925056] [ERROR][com.winpr.library] - LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/libdrive-client.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu

Part of this log is in polish, but as you write libdrive-clinet.so is missing in my system.

**Comment by giox069** [comment]
Ok, it's a bug on the PPA, we will try to solve it. Thank you for reporting.

**Comment by giox069** [comment]
@dulaman: we found a missing dependency on the PPA. Can you try to install libfreerdp-plugins-standard
```
sudo apt-get install libfreerdp-plugins-standard
```
and then re-test folder sharing ?
Thank you
Giovanni

**Comment by dktrkranz** [comment]
A fixed freerdp package has been provided for both trusty and utopic.

**Comment by giox069** [comment]
@dktrkranz: many thanks for updating the PPA.
@dulaman: you can just upgrade your system and libfreerdp-plugins-standard will be installed automatically now. Let us know if folder sharing works.

**Comment by dulaman** [comment]
Works perfect! Thanks for update!

**Comment by giox069** [comment]
Thank you @dulaman and @dktrkranz.
