### ISSUE TITLE
remmina: _XAllocID(): remmina killed by SIGABRT

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#527]
Could you please look at: https://bugzilla.redhat.com/show_bug.cgi?id=1180888 ?
Short quote:

```
I connected on a machine on the local network via VNC, and a server, also on the local network, via RDP. Requested that the machine was restarted (via VNC), and the Remmina caught.

This situation was repeated more than 2 times.
```
##

**Comment by antenore** [comment]
Hi Pavel, I cannot replicate this issue with the last Remmina version, I'm afraid we can't do anything.

I keep the issue opened because it's a potential bug.

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina, now we support only version 1.2.*.
