### ISSUE TITLE
Regression in RDP plugin - no ipv6 support

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#528]
Please look at our Fedora user bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1176406
Unfortunately I have no ipv6 setup to test.

**Comment by antenore** [comment]
Thanks for this report and sorry for the late answer.

This is more likely an issue with FreeRDP, but to confirm it I need as well an IPV6 setup.

@giox069  can you help out on this? And you Pavel can you ask to have reported the issue to obtain a back trace?

Thanks in advance

**Comment by antenore** [comment]
also...
https://github.com/FreeRDP/FreeRDP/issues/1949

So the user should test as well with xfreerdp /v:[ipv6_adress] or /v:dnsnamethatresolvestov6 

If it works it's our issue, otherwise a FreeRDP problem

Thanks!

**Comment by Hubbitus** [comment]
User asked.

**Comment by giox069** [comment]
I have just tested IPv6 RDP connections in Remmina 1.2 and FreeRDP 2.0. It's working. So I'm closing this issue.
