### ISSUE TITLE
Remmina does not report Host key Changed.

### ISSUE THREAD

**Issue by Damme** [FreeRDP/Remmina#532]
Then upgrading a windows 10 machine, Remmina only sais 
```Unable to connect to RDP server 192.168.168.1```

but as root:

```
damme@Five-Of-Nine:~ > sudo remmina 
[sudo] password for damme: 

Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
connected to 192.168.0.102:3389
The host key for 192.168.0.102 has changed
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the host key sent by the remote host is
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Please contact your system administrator.
Add correct host key in ~/.freerdp/known_hosts to get rid of this message.
Host key for 192.168.0.102 has changed and you have requested strict checking.
Host key verification failed.
SSL_write: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
```

I think this is a lack of error message and no easy option to correct.

I have fixed the issue by updating known_hosts but It took a while before I figured out what was going on.

Thanks!

**Comment by Damme** [comment]
(I have fixed the issue by updating known_hosts but It took a while before I figured out what was going on)

**Comment by giox069** [comment]
Which version of remmina are you using ? On which operating system ?
Please check to be running remmina 1.2.X, as explained in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki).
Also please see issue #407: the problem should be already been fixed some times ago in Remmina.

**Comment by Damme** [comment]
Ah thanks, I did a quick search but clearly wasn't paying attention. My remmina version is 0.99 also so sorry yet again not running latest.

You may remove this issue!

**Comment by giox069** [comment]
:smile:
