### ISSUE TITLE
Copy and Paste between local and remote desktops failing in Ubuntu 15.04

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#533]
In Ubuntu 15.04, copying and pasting between local and remote desktop has ceased working.

Launchpad bug:
https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/1439478

Workaround request:
http://askubuntu.com/questions/604258/remmina-cant-copy-and-paste-between-desktops-in-ubuntu-15-04

Please advise.

**Comment by Lonniebiz** [comment]
Thanks for getting this repo to vivid!

So far it seems to have fixed the copy and paste issue. I'm very thankful for that.

It seems I will have to file another bug addressing the fact that this repo version is incapable of scaling disproportionately like older versions could and like I prefer.

I wish I could save my preferences, which are always:
1) A Maximize Scroll Window
2) Launched remote desktops into tabs that fill the entire tab-container (even if it is disproportionate-looking).

Each time I launch Remmina, I always have to maximize the window first thing (manually). Then for each remote desktop I launch, I always have to hit the scale button to get it to fill the window completely. I do these steps so many time per day.

Remmina is so close to being the best thing ever. So close!

**Comment by giox069** [comment]
@Lonniebiz: I'm closing this issue now.
Yes you are right. The new scaler code does not support scaling with distorted aspect ratio. For scaling without respecting the remote destkop aspect ratio, please open a new issue and I will mark it as "newfeature".
For the other problems... I'm not sure I have understood. If possible, please reopen another issue and post also a video :)

**Comment by Lonniebiz** [comment]
Thanks a lot!

I posted the other bug here and provided screen-shots:
https://github.com/FreeRDP/Remmina/issues/537
