### ISSUE TITLE
=net-misc/remmina-1.1.2 ssh quick connect always ask password, even if server don't support it

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#539]
I use Remmina as second client. Primarily for ssh.
Now I use 1.1.2 stable version. 1.2.0 RC not tested yet.

On most of used servers sshd is configured to accept only public key authentication.
When using standard connection, previously configured and stored, everything is OK.
But when I try to use Quick connection scenario, I sudenly get… PASSWORD (!) type form.

To my mind Remmina should first check availability of expected authentication method and only after that display password type form.
Even in Quick-Connect scenario.

**Comment by antenore** [comment]
@ssten 
I've tested the last version and it seems to work as expected.

Just in case... You can insert user@hostname in the quick connect box.

We don't have the time and the resources to backport most of the SSH improvements on 1.1.2.

I'm closing this, but don't hesitate to contact me if you need more support or if you think this should still be kept opened.
