### ISSUE TITLE
=net-misc/remmina-1.1.2 Quick Connect should filter supported protocols similiarly with profile manager

### ISSUE THREAD

**Issue by ssten** [FreeRDP/Remmina#540]
I use Gentoo build of =net-misc/remmina-1.1.2.
Trying to use Quick Connect scenario to establish RDP-connection I've got a pop-up window with error message:

> Protocol plugin RDP is not installed.

Connection profile manager don't show RDP protocol in the list of available ones.
To my mind, Quick Connect protocol list should provide the same filtering and display only supported (by used build) protocols.

**Comment by giox069** [comment]
This is a installation problem on your PC or packaging problem of Gentoo. Usually in other distributions all remmina plugins are installed as extra packages, and RDP is a remmina plugin. Check on Gentoo help/forum.

**Comment by ssten** [comment]
It is not my installation issue.
In Gentoo available plugins are handled with Use-flags,
Particularly freerdp requires net-misc/freerdp package.

This bug is about tha in connection's profile I see available (in particular installation) protocols list.
But in Quick Connect I see ALL potentially compatible protocols. Including ones not available in current installation.
The last "feature" looks not downstream-handleable.

I know how to build Remmina with RDP support, the question is not to show RDP in Quick Connection list when it's not available. Like it as already done in" Add connection" window.

**Comment by giox069** [comment]
I have just pushed a fix for Remmina 1.2.0-rcgit.3 ("next" branch).
