### ISSUE TITLE
Remmina doesn't copy cells from libreoffice to WS2003R2

### ISSUE THREAD

**Issue by ncarvalho08** [FreeRDP/Remmina#541]
Hello, 
I'm using ubuntu and xubuntu 14.04 LTS and Remmina 0.9.99.1 to access to a Windows Server 2003 R2 and I need to copy-paste cell content from libreoffice to an app in ws2003. Doesn't work. If I copy from a PDF or gedit it works. If I use libreoffice on W8.1 with windows RDP client it works. Can you help? This is a remmina's bug or libbreoffice bug?

**Comment by giox069** [comment]
Please upgrade to Remmina 1.2 following the instuction on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). Re-test and let us know.

**Comment by antenore** [comment]
Closed because not supported version.
