### ISSUE TITLE
Auto-Highlight Quick Search Text Upon Each Remote Session Launch

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#544]
I use the filter-search box to locate and launch remote-session-profiles numerous times per day.

Each time I do this, I have to erase my previous search-query before I can type my current query. Therefore, I propose that each time a user launches a remote session, the search-query-filter-text, they just typed, should be "auto-highlighted" so that when they return to the main window later (to launch another remote session) all they have to do is start typing and it will erase their previous search-filter-query.

This could likely be achieved by putting some code into the event that gets fire when a user launches a remote session; it could highlight their search-filter-query right before the session is launched.

Ultimately, I just want to start typing anytime I switch over to the main window of Remmina. So that's the goal I'm proposing here. Might seem petty, but when you really use Remmina a lot, these little steps being eliminated mean a lot.

**Comment by antenore** [comment]
@Lonniebiz 
I'll take  a look as soon as I have free time. 
Thanks for the report

**Comment by Lonniebiz** [comment]
Previously, Remmina would at least auto-focus to the search box after launch. Version 1.2.0-rcgit.13 (git n/a) doesn't do this anymore.

Can you take a look at this, and please consider my auto-highlighted request above. This enhancement saves a lot of steps for heavy Remmina users.

**Comment by antenore** [comment]
> Previously, Remmina would at least auto-focus to the search box after launch.

Indeed it does! Since commit https://github.com/FreeRDP/Remmina/commit/e105d15199314fe3efb1e468ffd28811a991dd23#diff-2cf953142f31bdda4aed5ca8e0cba1bbR286 

It's duplicated of #887 and it's already solved.

Can you update and test? 

> and please consider my auto-highlighted request above.

There is not an easy way to do this without messing up the code. I keep a note of this and as soon as will be feasible I will do it.

**Comment by Lonniebiz** [comment]
Thanks for #887. Please continue to keep #544 in mind. 

What programming language is the UI written in? In some languages is wouldn't be too hard to change the focus to a textbox and highlight its contents each time the user launches a remote session. You could do this before or after the remote session is launched; the user wouldn't notice or care about the order of events, just as long as it is ready for them to type the next time that go to the launch-window.

**Comment by antenore** [comment]
If you have time maybe you can take a look at the code and propose a patch?

**Comment by Lonniebiz** [comment]
My main programming language is JavaScript and node.js. My desktop programming experience is in c#, windows forms, and WPF. I've always wanted to contribute to linux and open source, but I'd probably need a little help getting the development environment  set up. Believe it or not, I don't know git and I've rarely used **make** other than building stuff that's outdated in the repos (via a tutorial).

If this project has clear instructions on how to build the source code and suggestions on setting up the development environment, I can find that.

**Comment by antenore** [comment]
@Lonniebiz sorry for the late, I've been quite busy lately.

It's done, but keep in mind that the text entry will be selected only when you move around with the keyboard (i.e with TAB or S-TAB), if you click with the mouse it's a signal that I cannot handle without really messing up things.

I'm going to request a PR, we will test it (you can as well), than, in some days, we will merge and release a new Remmina version, that will be available to the Ubuntu PPA just after.
