### ISSUE TITLE
Need to Adjust ClearType Fonts Each time I connect

### ISSUE THREAD

**Issue by Faraclas** [FreeRDP/Remmina#545]
Everytime I connect to the given remote system (RDP into Windows7 from linux), the fonts look terrible.  Each time I connect, in the remote windows, I goto start --> Fonts --> Adjust ClearType Fonts.  It is always unchecked, so I hit the checkbox to enable it and then next, next, next through the wizzard and then the fonts look fine.  Is there a way to get this to be persistent?

As far as I can tell I have all the settings at highest quality.
- Color Depth: RemoteFX (32 bpp)
- Quality: Best (slowest)
- Sound: Local - high quality
##

**Comment by giox069** [comment]
Which version of remmina are you using (find it on Help->About) ? On which operating system ?

**Comment by Faraclas** [comment]
I am using version 1.1.1 on Gentoo Linux, Gnome 3.14 desktop [if that matters].

**Comment by giox069** [comment]
Is it possible on gentoo to upgrade to Remmina 1.2 ? Remmina 1.1 is based on freerdp 1.1 and currently we can only spend a very small amount of development time on it. See on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for manual compilation instructions of remmina 1.2.0-rcgit.3.

**Comment by repzilon** [comment]
Time to file a Gentoo bug so that the live ebuild track the "next" branch instead of the "master" branch.

**Comment by antenore** [comment]
@Faraclas can we close this or is still a Remmina issue?
@repzilon thanks for your help

**Comment by Faraclas** [comment]
Well, if it is a Gentoo bug, the bug has been filed with Gentoo.  There was
an update to Remmina in the Gentoo repositories, but it failed during
compile.  So while the issue is not closed for me, it may or may not be
closable for your criteria.  Thanks for you help.

**Comment by nahuel** [comment]
I had the same problem using Ubuntu and upgrading to Remmina 1.2 using the remmina-next ppa solved it.

**Comment by antenore** [comment]
@repzilon can you kindly check why the gentoo team is not taking care of this issue?

**Comment by repzilon** [comment]
I sent a bump in Gentoo Bugzilla. I confirm the issue with Remimina 1.1.x , but cannot acknowledge the fix right now.

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina, now we support only version 1.2.*.
