### ISSUE TITLE
Quick Search Textbox is Only 8 Characters Wide

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#547]
Using the Remmina-Next PPA, on Ubuntu 14.04 and Ubuntu 15.04, the Quick Search textbox is now only 8 characters wide:
http://neartalk.com/ss/2015-04-10_008_1110x338.png

Since there is plenty of Horizontal Space available, this text box's width should be expanded so that it can hold and display even the longest queries a user might type into it.

Ideally, this text-box's width should scale to take up the remaining horizontal space before and during window resizing. But even you you make it a fixed width, it should be wider than it is. Displaying 8 characters max is very narrow indeed.

**Comment by antenore** [comment]
@Lonniebiz 
Making the search box "expandable" doesn't look nice, in the future I'll move it somewhere else.

In the meanwhile I've made it bigger, I'm going to commit, let me know what do you think.

**Comment by Lonniebiz** [comment]
Yes, that looks much better. Now there's plenty of room. Thank you.
