### ISSUE TITLE
Tab all connections

### ISSUE THREAD

**Issue by mihaig11** [FreeRDP/Remmina#548]
Tab interface -> "Tab all connections" does not work, the connections open all in different windows.
Tab interface -> "Tab by protocol" works just fine.

I am using remmina 1.2.0-rcgit.2 (compiled on fedora 20 64 according to instructions found on remmina wiki).

PS: In the remmina rpm from fedora 20 repo (I think version 0.99) "tab all connections" worked just fine.

**Comment by giox069** [comment]
I can confirm it. I will fix in the next days. Thank you for reporting.

**Comment by mihaig11** [comment]
Works OK, thank you for fixing.

**Comment by giox069** [comment]
You are welcome :smile:
