### ISSUE TITLE
webbrowser support

### ISSUE THREAD

**Issue by vcordes79** [FreeRDP/Remmina#551]
I'd like a possibility to connect to a webserver (directly or tunneled through ssh).

**Comment by giox069** [comment]
What do you mean with "connect to a webserver" ? Remmina is not a browser, nor a telnet client.

**Comment by muflone** [comment]
@vcordes79
I've deloped a separated plugin to browse web pages using an integrated WebKit browser for Remmina 1.1.
You can find it here 
http://www.muflone.com/remmina-plugin-webkit/english/
I'm not sure if it works with the latest Remmina, in the case please file an issue in GitHub.

**Comment by vcordes79** [comment]
Hello, that's exactly what I mean. Any Chance this could be officially added to remmina? I would like to use remmina as a central cockpit to connect to my servers (this works via rdp / ssh / vnc) and devices. For devices an integrated browser plugin would be nice (printers / smart switches / nas, ...). Mostly the connections need to be tunneled, so I cannot use a plain webbrowser.

**Comment by antenore** [comment]
@vcordes79 
Beside we don't have control and ownership on external plugins, adding or rewriting a new one makes sense only if when we have enough users using or asking for it.

What we can do for you is trying to support in case you have some specific issue. What I recommend you is to advertise this feature or to try to implement it yourself and join us.

I close this, but you can reopen it in the future if things will change.
