### ISSUE TITLE
undefined symbol: freerdp_channels_pop_event in remmina-plugin-rdp.so

### ISSUE THREAD

**Issue by ekoleszar** [FreeRDP/Remmina#558]
On Archlinux 3.19.3-3-ARCH I installed Remmina 1.1.2-1, remmina-plugin-rdesktop 1.1.1.0-2 and compiled freerdp-git 1.2.0.beta1.android7-1 from source. RDP isn't working, when I launch Remmina from the terminal i'm getting the below error

remmina: symbol lookup error: /usr/lib/remmina/plugins/remmina-plugin-rdp.so: undefined symbol: freerdp_channels_pop_event

**Comment by giox069** [comment]
As explained in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) under "CURRENT STATUS", remmina 1.1 works with freerdp 1.1. Remmina 1.2 works with freerdp 1.2. You cannot exchange the versions.
So: go to AUR and compile also remmina-git, it will bring you remmina 1.2.

**Comment by ekoleszar** [comment]
Oh my mistake! Thanks for your quick response.
