### ISSUE TITLE
Missing connection icons in tray menu

### ISSUE THREAD

**Issue by clsv** [FreeRDP/Remmina#563]
The problem is that the icons in tray menu are not displayed. In version 1.0 all good. I was testing in debian, ubuntu and xubuntu, in all systems same problem. 
Thanks for the good program, and sorry for the poor english.

![ubuntu_0 9](https://cloud.githubusercontent.com/assets/5821199/7383524/8e810024-ee29-11e4-904e-72aa3d34e4b3.png)
![ubuntu_1 2](https://cloud.githubusercontent.com/assets/5821199/7383523/8e80d900-ee29-11e4-90b7-3f153b620096.png)

**Comment by antenore** [comment]
Under GTK3, icons in the system tray are not supported anymore.
