### ISSUE TITLE
Remmina nx won't connect with Ubuntu 15.04

### ISSUE THREAD

**Issue by 4nanook** [FreeRDP/Remmina#567]
Previously Remmina was working fine with nx plugin on Ubuntu 14.04 and 14.10.  Today I upgraded to 15.04 and it will no longer connect using NX protocol.  It starts up the display like it's going to and then just disappears.  I tried uninstalling and reinstalling, no help.  I then built Remmina 1.1.2 with plugins from source and I am getting exactly the same behavior.

**Comment by giox069** [comment]
Unfortunately I have no NX server to test. Can you launch remmina from a terminal windows, connect to the NX server and look if there is some interesting message in the terminal windows when the connection fails ? You can also copy&paste here the text you have in your terminal window after the failure.

**Comment by 4nanook** [comment]
You can go ahead and kill this bug report, though if you need a machine
to test let me know and I'll be glad to help.  But as it turns out a reboot
made it work with the Ubuntu 15.04 distribution version.  I'm used to having
to reboot to make things work on Windows but not on Linux, so sorry didn't try
that first.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by giox069** [comment]
Thank you @4nanook.

**Comment by 4nanook** [comment]
You're welcome and sorry for the trouble submission without really having
done adquate troubleshooting on my end first.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
