### ISSUE TITLE
provide Gnome 3 indicator

### ISSUE THREAD

**Issue by mfuhrmann** [FreeRDP/Remmina#570]
Remmina systray feature is placed in the notification area. It's a really nice feature, but in my humble opinion a Gnome indicator should be more practicable.

Just an idea...

**Comment by giox069** [comment]
We know that. In the meanwhile, for Gnome Shell under ubuntu and other distributions with canonical's libappindicator support (Fedora), you can install this Gnome Shell extension:
[Gnome Shell appindicator support](https://extensions.gnome.org/extension/615/appindicator-support/)

**Comment by mfuhrmann** [comment]
Thanks. The app indicator works fine!

**Comment by giox069** [comment]
Issue closed, and question added to the FAQs.
