### ISSUE TITLE
Workflow for batch import?

### ISSUE THREAD

**Issue by mfuhrmann** [FreeRDP/Remmina#571]
Hello!
Is there a solution to import many profiles from (eg.) a csv file?

Thanks for feedback!

**Comment by giox069** [comment]
Usually you can just copy all "*.remmina" files in ~/.remmina/ folder (the .remmina hidden subfolder of your home directory). All settings will be preserved, but passwords will not be included, because they are safely stored under gnome keyring and not into .remmina files.

**Comment by giox069** [comment]
Also please note that remmina configuration files will not stay there (into ~/.remmina) for a long time. We have two issues open https://github.com/FreeRDP/Remmina/issues/129 and https://github.com/FreeRDP/Remmina/issues/197 to move configuration files in a more XDG compliant place.

**Comment by mfuhrmann** [comment]
Hey Giovanni,
thanks for your fast response. But I don't have the remmina files yet. I am searching for a solution to import ~100 new profiles. All should get the same configurations (logins, display etc.). The only difference is the hostname/ip.

**Comment by giox069** [comment]
@mfuhrmann I apologize for the big delay in the answer. There is no direct support in remmina for importing profiles. You can write a script in the language you want which creates .remmina files. Just take a file as a template. The only thing you cannot write in this way, is the user password: when remmina finds gnome keyring in your system, passwords are not stored in .remmina files but inside gnome keyring.

**Comment by mfuhrmann** [comment]
Thanks for your help.
Are there any plans to create a mass-import-function like this? If not, feel free to set the *newfeature* tag :-)

Have a nice day!

**Comment by antenore** [comment]
@mfuhrmann 

At the moment, we are really busy with other issues, we work on Remmina in the free time, it would be great if you'd like to implement them yourself.

We will be more than happy to evaluate your pull request and eventually merge it in our main development branch.

In the meanwhile, sorry for this, we will close this as it's not an issue nor a feature request we can support.
