### ISSUE TITLE
How to add custom keyboard layouts to RDP?

### ISSUE THREAD

**Issue by Bebef** [FreeRDP/Remmina#573]
Hi everyone!

In the mailinglist I was told to raise this issue here, so here it is:

How can I add keyboard layouts to the RDP plugin? I can't seem to find ANY references to the keyboard layout section in the preferences dialouge.

I also had a quick look at the github repo but couldn't find anything either.

Sooo... where do the layouts come from?

Regards
  Steffen

**Comment by giox069** [comment]
Dear @Bebef , currently Remmina has only two (partly) active developers. None of us developed the keyboard mapping section for Remmina or the RDP plugin. The original developers can no longer be found.
So the only thing I can suggest to you, is to have a look at the [source code of the rdp plugin of the "next" branch in this repo](https://github.com/FreeRDP/Remmina/tree/next/remmina-plugins/rdp). The file rdp_event.c has some code for the keyboard mapping.

**Comment by giox069** [comment]
Can I close this issue ?

**Comment by Bebef** [comment]
Well, I still can't figure out where the list of keyboard layouts comes from or how they seem to magically appear out of thin air, but when even the guys who develop the tool have no idea I guess all hope is lost. :expressionless:

Well, that may have sounded a little more desperate than I really meant it, but still I'm left scratching my head... :confused:

Anyway, I'll close this...

**Comment by giox069** [comment]
As far as I can understand, **un**-mapping is done in rdp_event.c here (look at the first part of the "if", when use_client_keymap is false):
```
		if (!rfi->use_client_keymap)
			{
				scancode = freerdp_keyboard_get_rdp_scancode_from_x11_keycode(event->hardware_keycode);
				rdp_event.key_event.key_code = scancode & 0xFF;
				rdp_event.key_event.extended = scancode & 0x100;
			}
			else
			{
				//TODO: Port to GDK functions
				display = gdk_display_get_default();
				//cooked_keycode = XKeysymToKeycode(GDK_DISPLAY_XDISPLAY(display), XKeycodeToKeysym(GDK_DISPLAY_XDISPLAY(display), event->hardware_keycode, 0));
				cooked_keycode = XKeysymToKeycode(GDK_DISPLAY_XDISPLAY(display), XkbKeycodeToKeysym(GDK_DISPLAY_XDISPLAY(display), event->hardware_keycode, 0, 0));
				scancode = freerdp_keyboard_get_rdp_scancode_from_x11_keycode(cooked_keycode);
				rdp_event.key_event.key_code = scancode & 0xFF;
				rdp_event.key_event.extended = scancode & 0x100;
			}

		if (rdp_event.key_event.key_code)
			remmina_rdp_event_event_push(gp, &rdp_event);

		break;
```
And un-mapping means: reconverting the X11 keycode to the original hardware keyboard scancode.  
Unmapping is done by `freerdp_keyboard_get_rdp_scancode_from_x11_keycode()`  
Then, after un-mapping, the hardware keyboard scancode is pushed to the remote RDP server.
Real mapping is then done at the RDP server side.
