### ISSUE TITLE
Sorting of hosts in notification pop-up area should not be case sensitive

### ISSUE THREAD

**Issue by rsyring** [FreeRDP/Remmina#574]
The sorting of hosts in the notification pop-up area is case sensitive.  So visually scanning for a host by name is hard b/c it's location depends on whether or not I capitalized the name, which isn't consistent.  

The main window sorts host names regardless of capitalization, which i believe is the better approach.  

I'd like to see the pop-up listing of host names sort be case insensitive.  

Thanks.  :)

**Comment by giox069** [comment]
Fix pushed, let us know if the problem is solved.
Thank you.

**Comment by rsyring** [comment]
Looks great!  Thanks for being so responsive!
