### ISSUE TITLE
fullscreen multiple screens

### ISSUE THREAD

**Issue by audricd** [FreeRDP/Remmina#577]
hello,
using remmina 0.9.99.1 on debian wheezy

When I go fullscreen it always goes fullscreen on the same desktop host screen, not the one the window is originally from.

using fglrx

Could that be looked into please?

thanks.

**Comment by giox069** [comment]
Currently we maintain Remmina version 1.2 only. You can find compilation instructions on the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). We do not provide precompiled packages for Debian. After re-testing, you can report here if the problem is still here or not.

**Comment by antenore** [comment]
Closed because no feedback.
