### ISSUE TITLE
no puedo ver la impresora por remmnia

### ISSUE THREAD

**Issue by jubaronfl** [FreeRDP/Remmina#578]
Tengo instalado linux mint, ingreso por remmina a la plataforma de Windows Server 2008 R2, pero cuando deseo imprimir, la impresora no me sale reflejada, y ya esta instalada y probada en Linux Mint
##

**Comment by antenore** [comment]
Mi español no es bueno @jubaronfl

**Comment by antenore** [comment]
@jubaronfl 
You're probably using an old version of Remmina, try to follow the wiki and compile an updated version.

I'll close this issue in the next days, except you will have some news for us.

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina, now we support only version 1.2.*.
