### ISSUE TITLE
Remmina 1.1.2 does not compile against FreeRDP 1.0.2

### ISSUE THREAD

**Issue by boeckmann** [FreeRDP/Remmina#579]
FindFREERDP.cmake checks for FreeRDP >= 1.0. But Remmina does not compile with FreeRDP 1.0.2. Can it be that Remmina requires at least FreeRDP 1.1?!?

Library dependencies for  freerdp-client were introduced in https://github.com/FreeRDP/Remmina/commit/0ea7182893418b855ef5b271fbd39e1e50dd8b98

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREERDP_CLIENT_LIBRARY
    linked by target "remmina-plugin-rdp" in directory /usr/pkgsrc/net/remmina112/work/Remmina-1.1.2/remmina-plugins/rdp
FREERDP_LOCALE_LIBRARY
    linked by target "remmina-plugin-rdp" in directory /usr/pkgsrc/net/remmina112/work/Remmina-1.1.2/remmina-plugins/rdp
```

**Comment by giox069** [comment]
Yes. Read [the wiki](https://github.com/FreeRDP/Remmina/wiki)

**Comment by giox069** [comment]
We are working to integrate full RDP sourcecode into remmina 1.2, this will hopefully solve a lot of freerdp dependencies problem. I hope we come to a solution in 15-20 days.
