### ISSUE TITLE
Fullscreen windows open on the monitor next to them

### ISSUE THREAD

**Issue by wrouesnel** [FreeRDP/Remmina#580]
Minor but slightly irritating problem: when clicking fullscreen on an open Window, Remmina always opens the fullscreen window on the monitor to the right of it rather then the monitor it is sitting on.

Wondering if there's an off-by-1 problem with the code - if I put it on the highest numbered monitored it does successfully open on that window.

**Comment by giox069** [comment]
Which verson of remmina are you using and uder which OS ?

**Comment by wrouesnel** [comment]
0.9.99.1 from the Ubuntu Trusty packages.

**Comment by giox069** [comment]
Try to upgrade to the latest 1.2.X version. For ubuntu 14.04 and above use the PPA "remmina-next" as explained in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki)

**Comment by antenore** [comment]
Closed because no feedback.
