### ISSUE TITLE
Crash when using TortoiseGit over a remote Windows through Remmina 

### ISSUE THREAD

**Issue by mvonthron** [FreeRDP/Remmina#582]
Looks crazy but I repeated it over and over :)

I am connecting from Linux (Xubuntu 15.04, same thing in previous version) to a Windows 7 machine through a VPN. AKA "I work from home on the week-ends".

Remmina's connection is a regular RDP configuration.
Each time I try to use TortoiseGit on the remote machine, the connection closes and I get the "Remmina has closed unexpectedly" message with "double free or corruption (fasttop)".

When I try to reconnect, the remote screen does appear but Remmina crashes very quickly (IMHO when it's time to render the TortoiseGit  window). I have to connect from a Windows machine to close  TortoiseGit so it works again :O 

AFAIK it's the only software I use on the remote that brings that.

```
% lsb_release -rd
Description:	Ubuntu 15.04
Release:	15.04

% apt-cache policy remmina
remmina:
  Installed: 1.1.1-1ubuntu1
  Candidate: 1.1.1-1ubuntu1
  Version table:
 *** 1.1.1-1ubuntu1 0
        500 http://ca.archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
```

Link to Apport crash report: https://drive.google.com/file/d/0B5Ma0U_6GIfXUzdPTHhZekVvalE/view?usp=sharing

**Comment by giox069** [comment]
Can you try to use our Ubuntu PPA `ppa:remmina-ppa-team/remmina-next` as explained in the [Wiki](https://github.com/FreeRDP/Remmina/wiki) ?

**Comment by mvonthron** [comment]
I works perfectly! Thanks a lot!
