### ISSUE TITLE
Configure location of RDP shared folder

### ISSUE THREAD

**Issue by laurentmartelli** [FreeRDP/Remmina#594]
Shared folder does not work for me when connecting on Windows 2003 with RDP. But it looks like the reason is I can't access the shared folder on the windows remote because of restrictions on the account I use. I've read that Remmina creates the shared folder somewhere under \Network, which I can't access.

It would be nice to be able to configure the location of the share folder on the remote Windows server. Or choose a default location less likely to be restricted, like rdesktop does (it shows in "Workstation"). 
##

**Comment by ic3d** [comment]
Hi @laurentmartelli, sorry for this late answer. Did you try updating Remmina to the latest release. We only support Remmina 1.2.*?
Thanks.

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects only old versions of Remmina.
