### ISSUE TITLE
Remmina hangs when using xdmcp

### ISSUE THREAD

**Issue by hugosthlm** [FreeRDP/Remmina#601]
Remmina hangs when I try to use xdmcp. It works with vnc. Xephyr works when I use it separately. I get the same problem on a different user on the same machine. I use Arch linux. I recently updated xorg server and Xephyr to 1.17.2-2. I also updated the catalyst drivers to 15.7-1. I did not manage to find any information whatsoever about why this application hangs. Nothing in any logs, debug window empty. No man pages, no info or user guide with descriptions of how to troubleshoot. strace didn't seem to show anything of interest. 
##

**Comment by antenore** [comment]
Thanks for the report.
The xdmcp plugin is quite old, hopefully, we'll work on it in the future as we  are extremely busy with other (Remmina's) tasks.

In the meanwhile, you can try to provide a backtrace with gdb.

Which remmina version are you using (AUR or community)?

**Comment by wols** [comment]
+1
I use `1.0.2` - is `remmina-1.2.0_rc3-r1` on Gentoo.

**Comment by ic3d** [comment]
Hi @hugosthlm @wols , we are reviewing all the open issues. I think this one affects only an old version of Remmina (we only support Remmina 1.2.*) so I will close it. If it still happens, feel free to open another issue.
