### ISSUE TITLE
Reverse layout switching doesn't work

### ISSUE THREAD

**Issue by sfesfizh** [FreeRDP/Remmina#605]
Hi!

I'm using Remmina for connect via RDP to windows 7 terminal.
When I used KRDC on the same host it was no problem with layout switching on both directions (Left Ctrl+Shift from 1st to last layout and Right Ctrl+Shift from last to 1st layout) but in Remmina I can switch only in one direction (Left Ctrl+Shift).
Problem is on Ubuntu and OpenSUSE (tested with)
Please help

**Comment by giox069** [comment]
Hi.
In remmina, the "Right Ctrl" key is reserved as "host key". You can change it in the global remmina preferences.

**Comment by sfesfizh** [comment]
It works, thanks!

Sorry for bothering with simple local problem ;-)

**Comment by giox069** [comment]
No problem :)
