### ISSUE TITLE
xfce4 applet gone?

### ISSUE THREAD

**Issue by yorrd** [FreeRDP/Remmina#609]
Does the xfce4 panel plugin not exist anymore? Cannot find it since remmina has been moved to its own domain.
##

**Comment by larchunix** [comment]
According to git history, this plugin has been removed in 508fb00. Although the reason is not mentionned, I guess it is because the systray icon makes it obsolete.

**Comment by giox069** [comment]
I think the plugin has been removed back in 2011 as told by larchunix.
There is no plan to develop and support plugins for specific desktop environments. If someone can develop and support that plugin, we can include it in remmina.
