### ISSUE TITLE
Old POT file for launchpad

### ISSUE THREAD

**Issue by glixx** [FreeRDP/Remmina#613]
It is old POT file with 220 strings, but now must be 344 strings for remmina
https://translations.launchpad.net/remmina/trunk
##

**Comment by antenore** [comment]
Hi @glixx , can you please enlighten more what's the issue,

**Comment by glixx** [comment]
Current POT file for remmina should contents 344 strings, but there is 220 strings only on launchpad.
So, translators think remmina is translated, but translations are out dated.
Does launchpad work for remmina translations or not? If yes, please submit there new POT file for translators. If not, then what is instead of launchpad?

**Comment by glixx** [comment]
>can you please tell me from where did you take that numbers?

For example, for Russian:

https://translations.launchpad.net/remmina/trunk/+lang/ru
Length - 220 strings, 100% translated.

in git here:
Length - 344 strings, 89% translated.

**Comment by antenore** [comment]
Yes, sorry now it is clear I'll discuss this with @giox069

**Comment by giox069** [comment]
I'm not an expert of launchpad translation service. But the current version of remmina included in ubuntu is 1.1.1, fully translated. Here on github we are developing remmina 1.2.X (not yet stable). Will launchpad accept to translate a software which is not yet stabled, releases and included in ubuntu ?

**Comment by glixx** [comment]
It seems Ubuntu has own translations then. Your source Remmina-1.1.1 for Russian is 94%.
If launchpad does not work for your development, then let's use transifex for translations.
You will upload POT file there when new strings will be available and download ready translations before release. So, translation process will be more comfortable for your team and for translators.
