### ISSUE TITLE
screen won't refresh when connecting to a Windows 7 machine

### ISSUE THREAD

**Issue by nakic** [FreeRDP/Remmina#614]
Observed behaviour:
- connect to a Win 7 machine
- remmina screen completely blank (grey)
- resizing the window triggers a screen refresh and from then on, I can interact with the remote computer

Expected behaviour: the remote screen should be shown immediately, without having to resize the window to trigger a refresh

Repeatability: 100%

Note that sometimes the resize workaround doesn't help: I have to close the connection and try again.
##

**Comment by weberhofer** [comment]
Which version of remmina are you using? I have seen this issue with the current stable version and newer gtk versions.

**Comment by nakic** [comment]
0.9.99.1

**Comment by giox069** [comment]
@nakic please try to upgrade remmina to the latest devel version (1.2.X). Read the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) to see if you can find an upgrade procedure valid for your operating system.

**Comment by nakic** [comment]
I need to be able to access an RDP server to get work done so, regretfully, I won't experiment with upgrading to a development version. That basically means using whatever latest official version was released for Ubuntu 14.04.

**Comment by giox069** [comment]
I'm sorry but it's impossible for us to fix an old product which is distributed inside a linux distribution. Here you can find Remmina 1.2.X ("next") which is in development. Installing the ubuntu PPA "remmina-next" is quite simple. You can also try with Remmina 1.1.X (on [this PPA](https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-master)). Remmina 1.1.X is the stable version, which means that we will not implement new features on it, only critical bug fixes (crashes and security advisories).

**Comment by nakic** [comment]
No problem, I fully understand. I may add the PPA to see if 1.1 works better and report back. Thanks for the support.

**Comment by byron-hawkins** [comment]
I'm having this issue using Remmina `1.2.0-rcgit.5` on Ubuntu 14.04 while connecting to a Windows 7 VirtualBox guest via RDP. The screen also gets stuck frequently during the session, forcing me to continually nudge the window edge so I can see the remote screen. Is there a way to turn off the refresh optimization so it doesn't try to figure out when to refresh, and instead just does it every-time-no-matter-what?

There are no issues when connecting to the same Windows machine from any other Windows machine.

**Comment by ic3d** [comment]
Hi @nakic @byron-hawkins , we are reviewing all the open issues. I think this one affects only an old version of Remmina (we only support Remmina 1.2.*) so I will close it. If it still happens on our latest release, feel free to open another issue.

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects only old versions of Remmina.
