### ISSUE TITLE
Remmina crashes on Ubuntu 15.04

### ISSUE THREAD

**Issue by cristianobertolini** [FreeRDP/Remmina#615]
When i try to use remmina on Ubuntu I connected to a server and then the remmina closes and it is not possible to open anymore. I will be able to open remmina again when my remote section expires.
##

**Comment by giox069** [comment]
Try to upgrade to remmina 1.2 as described in the wiki. Sometimes also rebooting the RDP server may help. Does remmina crashes/exit and you have to restart it, or does remmina only disconnect from the server ?

**Comment by Techman35** [comment]
It happen to me on archlinux... i have the lasted version 1.1.2 and remmina keep crashing every time im connected in my rdp server, im able to reconnect but it eventually keep crashing :(

**Comment by Techman35** [comment]
i switch back to version 0.9.99.1 and i don't have any crash, i think i will stick with this version for a while

**Comment by giox069** [comment]
I'm closing this for lack of fresh and detailed data. If remmina still crashes, please reopen another issue describing your setup (clent OS, server OS, remmina version, xfreerdp version), ensure that you are using the latest Remmina 1.2.X version and provide a backtrace if possible.
Thank you.
