### ISSUE TITLE
Update Wiki page: "Compile-on-Ubuntu-14.04-and-14.10"

### ISSUE THREAD

**Issue by lanoxx** [FreeRDP/Remmina#618]
I think the following wiki page needs an update: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10

When I try to build freerdp on Ubuntu I got the following error when running cmake:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_1_0_APP_INCLUDE_DIRS
    used as include directory in directory
    [...]/FreeRDP/channels/tsmf/client/gstreamer
GSTREAMER_1_0_APP_LIBRARIES
    linked by target "tsmf-client-gstreamer-decoder" in directory
    [...]/FreeRDP/channels/tsmf/client/gstreamer
GSTREAMER_1_0_VIDEO_INCLUDE_DIRS
    used as include directory in directory
    [...]/FreeRDP/channels/tsmf/client/gstreamer
GSTREAMER_1_0_VIDEO_LIBRARIES
    linked by target "tsmf-client-gstreamer-decoder" in directory
    [...]/FreeRDP/channels/tsmf/client/gstreamer
```

The wiki still lists gstreamer0.10 as a dependency but I think it should be gstreamer1.0:

```
 libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
```

vs.

```
libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```

I have edited the wiki page to include both `0.10` and `1.0` but I guess someone more familiar with this guide should have a second look and possibly remove the `0.10` packages
##

**Comment by giox069** [comment]
Hi @lanoxx, thank you for reporting the problem and fixing the wiki. I really can't understand why newer FreeRDP cannot find gstreamer 0.10. I have encountered the same problem it in one recent Ubuntu installation (maybe 15.04). But I was in a hurry and I have no time to deeply test it.
Under which verson of Ubuntu did you compile FreeRDP ?

**Comment by lanoxx** [comment]
> I really can't understand why newer FreeRDP cannot find gstreamer 0.10.

You are mistaken. It looks for **1_0** not **0_10**, so it is looking for the newer gstreamer version but the sample `sudo apt-get install` command only lists the 0.10 packages, so the newer version does not get installed and thus cannot be found.

I am installing under *Ubuntu 14.04*.

**Comment by antenore** [comment]
@lanoxx thanks a lot for helping.
If you want you can propose a pull request of that wiki page, would you like to contribute?

**Comment by ic3d** [comment]
That wiki page does not exist anymore, and the new one is correct. Closing this bug.
