### ISSUE TITLE
RDP component not installed

### ISSUE THREAD

**Issue by clipboard** [FreeRDP/Remmina#620]
Hi.
I installed the last version of remmina and I need to use RDP but I get an error that says rdp is not installed. Is there any way to solve this? If is not, how can I use a version that works fine.

Thanks

**Comment by giox069** [comment]
Please add the following data:
1. Which OS are you using ?
2. Which Desktop environment ?
3. Which CPU and architecture ?
4. How did you install it ? Have you compiled the latest "next" branch following the instructions on the wiki ? Or did you use some prebuilt binary (ubuntu PPA ?).
5. Can you start remmina from the command line and copy and paste the text output here ?
Thank you

**Comment by clipboard** [comment]
1. OS Ubuntu 14.10 x64
2. Unity
3. AMD Turion II Neo 2.2 GHz
4. I followed the instructions on the wiki. I have already done it this way with a lot of computers with the exact same characteristics
5. Error: libfreerdp-core.so.1.2: cannot open shared object file: No such file or directory

**Comment by giox069** [comment]
Thank you. Another question:

4. On the wiki there are both instructions for
   a) Compiling remmina from our current "branch"
   b) Installing the PPA "remmina-next", which will provide you with a precompiled binary

Did you follow a) or b) ?

**Comment by clipboard** [comment]
I did it compiling remmina but now I did it installing the PPA and works fine

**Comment by giox069** [comment]
Ok, I think the problem could be around step 7 when determining the correct directory where freerdp libraries are installed:
```
echo /opt/remmina_devel/freerdp/lib | sudo tee /etc/ld.so.conf.d/freerdp_devel.conf > /dev/null
```
It's not ` /opt/remmina_devel/freerdp/lib` in every installation, you must find manually where libfreerdp is. In the future I will update the guide to find libfreerdp .so file automatically.

If the PPA is enough for you, you can close this issue now.
Thank you for reporting.
