### ISSUE TITLE
Redirection of audio to local fails

### ISSUE THREAD

**Issue by dhugh** [FreeRDP/Remmina#626]
Running CentOS 7 on an Ideapad z500 laptop, connecting to a Windows 10 desktop using Remmina 0.9.99.1 w/RDP, when I turn audio on in local mode don't hear anything, the task bar icon in Windows 10 reflects a problem (unspecified).  When I have audio on in remote mode can hear audio on the Windows 10 machine, Windows 10 icon does not reflect an issue. Audio works fine on CentOS 7 laptop, can play tunes with Rythmbox without issue

**Comment by giox069** [comment]
Remmina 0.9.99.1 is too old and we cannot make patches it into your distribution. You can try to upgrade to remmina 1.2.X and FreeRDP 1.2.X. See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki)

**Comment by dhugh** [comment]
Thanks Giovanni. Any by the way, what an excellent product! Beats the
many other remote access products I have tried.

**Comment by dhugh** [comment]
Just to close out, suggestion worked and now have audio when connecting fromn CentOS 7 laptop to Windows 10 desktop and VMWARE Player and Horizon images I run underneath it.  Again, a very cool product!

**Comment by giox069** [comment]
:+1: Thank you @dhugh, from all the remmina team.
