### ISSUE TITLE
Smartcard slot selection

### ISSUE THREAD

**Issue by rbrad0615** [FreeRDP/Remmina#628]
Smartcard redirection does not allow you to select a slot on the smartcard. Smartcard that I am using has multiple certificates in different slots so I need to be able to select a different slot than 0.
##

**Comment by giox069** [comment]
@rbrad0615: do you know if xfreerdp has a similar commandline switch ? Remmina is based on freerdp, so if xfreerdp has this switch, we can have it in remmina too.

**Comment by rbrad0615** [comment]
I am wondering if it is a pkcs library that is used. I am using opensc to access the smartcard. What library does the remmina/xfreerdp use to attach to the smartcard?

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects only old versions of Remmina.
