### ISSUE TITLE
Shortcuts on the remote computer does not work

### ISSUE THREAD

**Issue by parkersonik** [FreeRDP/Remmina#631]
Keyboard shortcuts do not work or is it a bug?
##

**Comment by giox069** [comment]
Can you better explain the exact steps needed to reproduce the problem ?

Also please include:
  1. which version of remmina are you using. Please check to be using 1.2.X. See the [wiki](https://github.com/FreeRDP/Remmina/wiki) for upgrading.
  2. the name of the operating system (name of distribution and version)
  3. which desktop you are using (LXDE, Unity, KDE, XFCE...)
  4. which protocol plugin are you using to connect to remote computer: RDP ? VNC ? SSH ? ...
  5. which OS is running the remote server
  6. don't forget to explain how to reproduce the problem

**Comment by parkersonik** [comment]
ОС Ubuntu unity, remmina 1.2.0, RDP, remote server Windows server 2003, Hotkeys running programs are not  in the workplace , but on the remote computer, in other programs RDP connection everything worked fine.

**Comment by nerfpops** [comment]
If you're thinking about hotkeys that involve alt, you need to press windows+alt to send that key to the remote desktop.

**Comment by kongdeyuan** [comment]
Can I customize my settings? This operation is too much trouble

**Comment by ic3d** [comment]
This is not a Remmina bug, I'm closing this issue.
