### ISSUE TITLE
Remmina does not connect to remote host by FQDN

### ISSUE THREAD

**Issue by zurapa** [FreeRDP/Remmina#632]
xubuntu 14.04
Remmina 0.9.99.1
After udating system Remmina do not connect to remote host by FQDN (hostname.example.com).
But if i connect to remote host by hostnsme (hostname) it's work.

**Comment by giox069** [comment]
I don't think it's a remmina related problem. Check that your system can resolve FQDN. Also please, upgrade to the latest development remmina version (now 1.2.X, see the [wiki](https://github.com/FreeRDP/Remmina/wiki)) before opening an issue: we cannot patch the older remmina which you installed into your system.
