### ISSUE TITLE
Time on remote server will not change to local time

### ISSUE THREAD

**Issue by Jediknight1** [FreeRDP/Remmina#633]
When I login to a remote Windows 2008 server the time on the server does not change to match the time on my local computer. This is creating errors in data entry, time stamps etc... I am currently on ubuntu 14.04 I have tried 15.04 but it seemed there was a bug with remote printing. The cups pdf printer did not redirect. The printing was more important to me then the time. However the time is still a problem. I am back on 14.04 now. The time on the server remains at UTC. Time on my machine is correct local time. I have opened and checked it via terminal. 
##

**Comment by ian-abbott** [comment]
Perhaps you need to set the "Allow time zone redirection" Group Policy setting on your server. See https://technet.microsoft.com/en-us/library/cc725887(v=ws.10).aspx

**Comment by ic3d** [comment]
This is not a Remmina bug, I'm closing this issue.
