### ISSUE TITLE
RDP: Fix extended mouse event to register the click for forward/back buttons

### ISSUE THREAD

**Issue by angelstam** [FreeRDP/Remmina#638]
The extended mouse buttons, back/forward (button 4/5), is not passed through to the RDP server. 

This issue is fixed upstream in FreeRDP: https://github.com/FreeRDP/FreeRDP/pull/1532

**Comment by antenore** [comment]
Remmina, behind the scenes, uses xfreerdp, can you test it from the command line?

**Comment by angelstam** [comment]
Yes, in FreeRDP version 1.2.1_pre20150326 it works.

    xfreerdp /f /v:192.168.2.64

If you look in [rdp_event.c@378](https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/rdp/rdp_event.c#L378) it doesn't forward events for other buttons than 1 to 3.

**Comment by antenore** [comment]
Thanks. So I'll take a look and fix it ASAP.

**Comment by colonelchlorine** [comment]
Hi, I can see a commit was made back in Oct 2015 that seems to resolve this case. Is there a reason it hasn't been published to a release of Remmina? I'm running remmina-next ppa on Ubuntu and it still doesn't work.

**Comment by antenore** [comment]
Because I forgot it :-\

**Comment by antenore** [comment]
BTW, are you sure is it fixed? It shouldn't.

Are you able to test it? The commit you should checkout is  5679b57

**Comment by antenore** [comment]
@giox069 any clue?

**Comment by giox069** [comment]
Unfortunately I have no 4-5 buttons mouse now at home. I will try to find one tomorrow at work.

**Comment by dexx086** [comment]
@giox069 did you manage to get a 5 button mouse? :) Would be great to have @antenore's mentioned commit to be released if it solves the issue. Do you have any plan when it could happen? We really miss this button from the remote session when navigating. Thx.

**Comment by antenore** [comment]
@dexx086 the easier is that you test it ;-)

I personally don't have, don't need and don't want a 5 buttons mouse (I rarely use a mouse), so I really cannot test this patch and I think Giox069 has similar arguments.

If my patch works, it is easy to integrate it in the "next" branch, if it doesn't you can maybe help me/us to debug it.

Please don't forget that behind Remmina, today, there only volunteers that works for free in their free time, so we give a great priority to issues and feature requests that have a greater impact (often) or that we personally need in our day to day job (rarely).

That said, @angelstam , @dexx086 , @colonelchlorine are you guys able to test this patch for us?
Thanks in advance for your support.

**Comment by dexx086** [comment]
@antenore about volunteerness: I'm absolutely aware of it and I didn't mean to demand anything, I was just curious if this patch is about to be tested/released by anyone.

But to contribute myself too, I started to test it (checkouted last master commit and applied your modifications to them). The first thing that made problems is with the following changes (for all 1-3 buttons):
```
flag = PTR_FLAGS_DOWN | PTR_FLAGS_BUTTON1;
```
In the commit you added PTR_FLAGS_DOWN, and it made the mouse to act like if it was always pressed down. Couldn't initiate any click, the mouse became unresponsive. I removed these PTR_FLAGS_DOWN for 1-3 button codes, the basic buttons now work again.

Then I tried to test the forward/back buttons, but when I press it, the RDP session is immediately closed with the following error output in the console.

```
ERRINFO_INVALID_INPUT_PDU_MOUSE (0x000010D0):
(a) A Slow-Path Mouse Event (section 2.2.8.1.1.3.1.1.3) or Extended Mouse Event (section 2.2.8.1.1.3.1.1.4) has been received with an invalid pointerFlags field.
(b) A Fast-Path Mouse Event (section 2.2.8.1.2.2.3) or Fast-Path Extended Mouse Event (section 2.2.8.1.2.2.4) has been received with an invalid pointerFlags field.
SSL_read: I/O error: Connection reset by peer (104)
```

What can I try to help moving forward with this issue?

**Comment by antenore** [comment]
Thanks for your tests and comprehension. 

I've to review completely the code and I've finally decided to buy a 5 buttons mouse, so I'll be able to test it.

Now, personally I will be busy till the beginning of June and and than I'll have quite long TODO list ( #708 #647 #853 #849 #818 #733 ), @giox069 is quite busy as well, so it's hard to say when we will take a look at this (and each of all opened issues).

Remmina needs contributors :-) and mainly developers (at least to clean the opened issues), so if you guys want to code or know someone that can join us (of any experience level), it'd be great.

**Comment by giox069** [comment]
@dexx086 5 buttons mouse not found, I will try again tomorrow and next week when I will be at another customer facility, but I don't think I will be so lucky.
In the meanwhile @antenore  wrote that he will be a 5 buttons mouse, and I'm happy :)
If you need to take inspiration for your contribution, look at the xfreerdp working mouse code here:

**Comment by giox069** [comment]
Previous comment updated with URL:
https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_event.c

**Comment by dexx086** [comment]
Thanks for your support guys.
Meanwhile I tried to analyze what could be the problem. I used to code in C a very long time ago, so it's a bit hard for me to dive into the code, especially as it's a fully new project for me.

But what I've figured out is that there's a difference in handling the 'normal' and 'extended' mouse events int freerdp. For extended mouse event (like what we want) the following method is called:
```
input->ExtendedMouseEvent(input, flags, x, y);
```
Here's the link to the full ending block at handling mouse events:
https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_event.c#L362

And that ExtendedMouseEvent possibly sets a different message type (or whatever it's called here) for the message that's sent to the server, I guess because of this define:
```
#define Input_ExtendedMouseEvent				5
```

Code: https://github.com/FreeRDP/FreeRDP/blob/master/include/freerdp/message.h#L233

So I guess what we only miss in Remmina is handling extended mouse event messages separately. (I guess the PTR_XFLAGS_DOWN is what invalid for normal mouse event, it possibly requires the 'extended' event type which is unhandled right now).

I couldn't figure out where the normal code (in freerdp: #define Input_MouseEvent 4) is sent in Remmina for basic mouse event, possibly that should have additional handling for 'extended' mouse event message sending. Do you guys maybe know where and how basic mouse events are sent to the server?

**Comment by giox069** [comment]
5 buttons mouse found. I'm working on it. Do you know a windows application I can use to test buttons 4 and 5 ?

**Comment by giox069** [comment]
and yes... it seems an ExtendedMouseEvent is needed instead of a MouseEvent. So the modifications are not so simple.

**Comment by antenore** [comment]
Thanks @giox069 !!!!!!!!!!!!!!!!

**Comment by giox069** [comment]
It seems to be fixed. I tested it under windows with [ShowOff](http://www.donationcoder.com/Software/Skrommel/index.html#ShowOff) tool. If you find any problem, open another issue :-)

**Comment by dexx086** [comment]
@giox069: Thank you !!!!
I tested it too, it works! I'm glad you could allocate time so shortly to figure out the solution. Thanks again!
