### ISSUE TITLE
Remmina VS freerdp on 1.2.0 version

### ISSUE THREAD

**Issue by david-geiger** [FreeRDP/Remmina#639]
Hi,

I tried to update, on Mageia, remmina to latest v1.2.0-rcgit.3 version with latest freerdp 1.2.0-beta1+android9 but it does not built due to a missing 'clipboard.h' file.

So what version or commit should I use to make that remmina built with freerdp and with 1.2.0 version?

Thanks in advance.

Best regards David.

**Comment by giox069** [comment]
Hi. The last version of remmina (our "next" branch), compiles only with the last version of FreeRDP, their master branch. The freerdp release 1.2.0-beta1+android9 is too old.
In the [remmina wiki](https://github.com/FreeRDP/Remmina/wiki) you can find some compilation guides for Fedora, Ubuntu and Arch. There is not Mageia, unfortunately.

**Comment by david-geiger** [comment]
So ok!

If I use the two latest commit from master branch of remmina and of freerdp, remmina should compile fine?

- freerdp: 72d901454c45f87e625e474b2ee7f94e1b1b64d8
- remmina: b024598fa5eab15c7c5147b2f7593de124e9d0a3

**Comment by giox069** [comment]
Yes. I just compiled it 5 minutes ago with these commits. Please uninstall old freerdp and remmina packages from your system before start compiling.

**Comment by david-geiger** [comment]
Yes looks good! thanks giox069 :)

freerdp and remmina have built properly on our Mageia Build System.

http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20150903161547.daviddavid.valstar.16742/freerdp-1.2.0-4.git72d9014.1.mga6/build.0.20150903161605.log

http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20150903163634.daviddavid.valstar.10492/remmina-1.2.0-0.gitb024598.1.mga6/build.0.20150903163703.log

Time to close this issue.
