### ISSUE TITLE
Error on smartcard sharing to Windows 2012

### ISSUE THREAD

**Issue by LordPicard** [FreeRDP/Remmina#643]
Hello there,

I'm using the Remmina to connect from a Ubuntu 15.04 to a Windows 2012 Server (and a 2016 Technical Preview 3, just for testing of thie issue, but none work).

Steeps to reproduce:

1 - device is correctly attach and configured, and I can use it localy; check with dmesg also
2 - try to connect to a RDP using Windows 2012 or 2016 TP 3 (I don't have any licencing for 2008, so I can't tell if it does work)
3 - use the card with Windows software and you see that you can't

Is there something I'm doing wrong? Or is there any issue conserning my particular card?
Please node my card have two certificates (PKCS#11).

Thanks.

LP
##

**Comment by antenore** [comment]
Hi,

can you please specify the remmina and freerdp versions?

For the remmina version we need the one that appear in the about dialog.
For freerdp run
```sh
xfreerdp --version 
```

**Comment by LordPicard** [comment]
Hello,

Sorry not to be more specific in the first place.

Here you go:
- FreeRDP 1.1.0-beta1 (git n/a)
- Remmina 1.1.1.1ubuntu1

LP

PS: if you need me to update the software, can you let me know how? I'm not so good with the terminal, I'm switching from Windows just a few weeks and learning as I go.

**Comment by antenore** [comment]
Thanks for your quick feedback.

Yes, if you want to have the most updated and working remmina you should update to our stable or development version, we cannot support anymore the 1.1.1 version unlucky.

You can follow the easy way, using the official remmina PPA as described in our wiki home page at  https://github.com/FreeRDP/Remmina/wiki or you can try the hard, but more satisfactory one, compiling remmina by yourself as described in our dedicated wiki page at:

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10 

Give both a try and don't hesitate to come back here if you need more support.

**Comment by LordPicard** [comment]
Hello,

Thanks for ytour help.

dpkg -l shows I've the new version. However I have the same problem.

I was about to try the second link (compiling manualy) when I notice it was not for Ubuntu 15.04.
Should I do it anyway regardless of the version?

Thanks for your help.

LP

**Comment by giox069** [comment]
If you have installed the remmina-next ppa, there is no need to compile remmina manually: the PPA is updated every 24 hours from the sources (only remmina, not freerdp).
Compilation is only needed if you are a C/GTK developer and want to contribute with your code.
In this case, yes, you can follow the guide for ubuntu 14.04 also for compiling on 15.04.

**Comment by antenore** [comment]
Thanks @giox069 , so @LordPicard have a real problem (that I don't too much how to investigate honestly), it's something more related with xfreerdp and you should try to use xfreerdp from the command line to see what happens.

Take a look at the xfreerdp command line tool help and try to choose the options you need, plus the 
/smartcard:<device> :

```sh
xfreerdp --help
```

Ask also for help here  https://github.com/FreeRDP/FreeRDP/issues and feel free to come back to us if you need more support on remmina.

**Comment by LordPicard** [comment]
Thank you both.

I've just created an issue there - https://github.com/FreeRDP/FreeRDP/issues/2891 - since I'm not so familier with the Terminal and choosing randoms stuff is probabily a bad ideal. :)

Will wait for any hint on that topic -- thanks for helping out!

LP

**Comment by ic3d** [comment]
This is not a Remmina bug, I'm closing this issue.
