### ISSUE TITLE
Screenshot of remote machine [feature request]

### ISSUE THREAD

**Issue by peter-gsellmann** [FreeRDP/Remmina#644]
Would be very nice to have a button "Screenshot" on the toolbar, which saves the current target window as PNG.
This is different to take a screenshot on the local machine as a local screenshot would produce a scaled-down or clipped image.
The "screenshot"-button should save the remote image with the size and resolution of the remote machine.
There should be no "Save-as" dialog, increment a number in the filename.
The directory and template for the automatically numbered filename should be in a new page of the "settings"-dialog

**Comment by giox069** [comment]
Great idea. To save a bit of work, we could save directly to the user's pictures dir XDG_PICTURES_DIR...
I have marked this issue as "newfeature".

**Comment by antenore** [comment]
:+1:

**Comment by hugokoopmans** [comment]
:+1:

**Comment by giox069** [comment]
Ok, let's start a new contest: a new icon is needed for the toolbar for this feature. Is anyone able to design one ?

**Comment by ozbek** [comment]
Are there any requirements for the icon?

Would [this](https://github.com/google/material-design-icons/blob/master/action/drawable-xxxhdpi/ic_camera_enhance_black_48dp.png) work? The license seems compatible.

**Comment by giox069** [comment]
I like material design, but this icon should use the same style of the currently available icons. They are not perfect, we would like to change it, but every new icon should follow the same style.
Here are the current remmina icons: https://github.com/giox069/Remmina/tree/next/remmina/icons
I think we need two .png files, one 16x16 and one 22x22.

**Comment by ozbek** [comment]
With a window in the middle, it more looks like a briefcase (paste button?:)

![remmina_screenshot](https://cloud.githubusercontent.com/assets/452620/11013326/43033502-852a-11e5-9a9a-45a5db5fe8e9.png)

What do you say?

**Comment by antenore** [comment]
@ozbek I like this last design and thanks for your suppert.

But I think the best is to have a camera icon. It's what most application use to take screenshots. 

Something similar to this.

![farm-fresh_camera_small](https://cloud.githubusercontent.com/assets/5975/11160151/ae444e5a-8a66-11e5-9d0c-46ca1cea1abb.png)

**Comment by antenore** [comment]
@giox069 do you already have some code ? I was playing around today and I think I should be able to implement this feature (or share ideas with you).

**Comment by antenore** [comment]
it's done, tomorrow will be available on most distributions.

Let us know what do you think
