### ISSUE TITLE
Generate a new secret?

### ISSUE THREAD

**Issue by richardkennedy** [FreeRDP/Remmina#645]
Could anyone shed any light on how you would go about generating a new secret within remmina.prefs?

**Comment by antenore** [comment]
Hi Richard,

We didn't develop that part of Remmina code that generate the secret properties, but looking at the code, it looks like the key is generated only one time, when it doesn't exists.

If you tell me why you need to regenerate it I can take a further look in the code and I'll try to help you out. 

If you are just curious, you are more than welcome to dive into the code and helping document it, adding comments in the code or even improving it if you are up to it.

**Comment by richardkennedy** [comment]
Hi antenore - I'm cloning Micro SD Cards (for Raspberry Pi), but obviously the same Remmina key key is present on each , so if I can identify how the key is generated, I'll execute a shell script on the first boot to automatically generate a new key, so any help would be appreciated.

**Comment by antenore** [comment]
The secret is generated when the file is created the first time, so, simply move away the remmina.pref file, start and close remmina again (even from command line), and replace the options you need. 

Is this enough?

**Comment by antenore** [comment]
A side note.

@giox069 was pointing out that if you have gnome keyring installed, the secret attribute should be used, so you can just replace it with whatever you want.

Otherwise you move the file as I told you or you have to write (again @giox069 advise) a lttle c program that uses the function  remmina_pref_gen_secret() inside remmina_pref.c

**Comment by richardkennedy** [comment]
Many thanks, that's very helpful! cc @giox069
