### ISSUE TITLE
doesn't process keyboard pressing in session RDP

### ISSUE THREAD

**Issue by GLADtr** [FreeRDP/Remmina#646]
## Hi!

Data on system:
Debian 8.2 - Gnome 3.14.2?
## Remmina v1.2.0-rcgit.4

on 1 step -install of packages in system 
apt-get refused to put a libgnutls-dev package:
"Package libgnutls-dev isn't available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgnutls-dev' has no installation candidate"

the following steps according to the instruction were successful
Options of compilation of cmake it was added - DWITH_LIBSSH=OFF
Compilation took place without uniform mistake
make and make install also passed without mistakes
At login on pressing rdp aren't processed by the keyboard in general.
thus pressing of a mouse are processed normally
It is also noticed that if to carry out an entrance to RDP session in a command line:
everything works with xfreerdp/v:hostname/u:username correctly.

What it is possible to make in my situation? There are suspicions that the established package just should.
##

**Comment by antenore** [comment]
Hi @GLADtr 

I'm so sorry, but I'm not sure I understood what is your problem.

Can you write in your own language or can you ask help to your friends?

Here we speak English, French, Italian, a little bit Russian and we can get help with German and other languages.

**Comment by GLADtr** [comment]
My system:
Debian 8.2 - Gnome 3.14.2?
Remmina v1.2.0-rcgit.4

on 1 step - install of packages in system 
apt-get don't install the libgnutls-dev package with error:
"Package libgnutls-dev isn't available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgnutls-dev' has no installation candidate"

All next steps according to the instruction were successful.
Options for cmake compilation it was added - DWITH_LIBSSH=OFF.
Compilation was without mistake.
make and make install also passed without mistakes
At login on rdp session aren't grab any the keyboard stroke.
a mouse working normally.
I'm noticed that RDP session in a command line work normally with xfreerdp/v:hostname/u:username

What it is possible to make in my situation? There are suspicions that the established package just should.
Is the text understanding?
Sorry my language. I'm from Russia. Thanks.

**Comment by antenore** [comment]
@GLADtr thanks, it's much better now.

Try this way:

```sh
# INSIDE THE REMMINA PROJECT DIRECTORY
apt-get install libgnutls28-dev 
make clean
rm CMakeCache.txt
# NOTE THE DOT AT THE END OF THE cmake COMMAND LINE
cmake --build=build -DWITH_TRANSLATIONS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
make && sudo make install
```
 
Спасибо

**Comment by GLADtr** [comment]
Thanks for the help!

I correctly understand sequence of actions?
since step 11:
cd ~ / remmina_devel/Remmina
apt-get install libgnutls28-dev
apt-get say that package was installed
make clean
rm CMakeCache.txt
cmake - DCMAKE_BUILD_TYPE=Debug - DCMAKE_INSTALL_PREFIX:PATH =/opt/remmina_devel/remmina - DCMAKE_PREFIX_PATH =/opt/remmina_devel/freerdp - build=build - DWITH_TRANSLATIONS=ON - DCMAKE_BUILD_TYPE=Debug - DWITH_SSE2=ON - DWITH_LIBSSH=OFF.
make & & sudo make install

the situation unfortunately didn't change

**Comment by antenore** [comment]
You should remove **-DWITH_LIBSSH=OFF** 

But I don't know why you have this issue, @giox069 how do you build remmina on Jessie?

**Comment by GLADtr** [comment]
Hi
You should remove -DWITH_LIBSSH=OFF"
it is made.
the situation unfortunately didn't change

**Comment by giox069** [comment]
@GLADtr: recompile both FreeRDP and remmina. The "-DWITH_SSE2=ON" parameter is for FreeRDP, not for remmina.

So, to recompile all, start with a big cleanup:
``
rm -rf ~/remmina_devel/
sudo rm -rf /opt/remmina_devel/
sudo rm /etc/ld.so.conf.d/freerdp_devel.conf /usr/local/bin/remmina /usr/local/bin/xfreerdp
sudo ldconfig
``
and restart from step 3 of the guide.

I just tested the procedure in a fresh installed debian 8.2 amd64, and it works. The only difference from the wiki, as pointed out by @antenore, is that you need to install libgnutls28-dev instead of libgnutls-dev.

**Comment by giox069** [comment]
@GLADtr: but I cannot well understand the true problem:

"At login on rdp session aren't grab any the keyboard stroke."

Are you using some special keyboard device/hardware ?
What do you see exaclty on the screen ?
Are you connecting to a windows machine ? Which version ?
Do you notice the problem at the login prompt (typing username and password) or after the logon to your destkop ?

Thank you
Giovanni

**Comment by GLADtr** [comment]
Hi! 
excuse, there was no opportunity to deal with this problem. 

Are you using some special keyboard device/hardware ?
 - no. standard notebook keyboard

What do you see exaclty on the screen ?
- after session creation I can work with a mouse, but the remote server doesn't react to pressing of keys in my local keyborad

Are you connecting to a windows machine ? Which version ?
2008r2 I didn't work with others versions.

Do you notice the problem at the login prompt (typing username and password) or after the logon to your destkop ?
no. no problems are present.

if I create session here so:
: ~$ xfreerdp /f /u:administrator /v:10.10.10.1 /p:'hiremmina' and other options(drive, certs, etc)  everything works with perfectly!!!

**Comment by antenore** [comment]
@GLADtr  @giox069 
As a side note, recently FreeRDP has moved to XImput2 (XI2), in fact I'm having an hard time to understand how to enhance Remmina to support additional mouse buttons #638 

So, it may be related (or not). 
 
I'll take a look as well, but have no ideas at the momnet.

Would you mind trying to compile an older version of FreeRDP? In that case I can provide you a precise commit to use.

Thanks for your support anyway.

**Comment by GLADtr** [comment]
Hi!
Thanks all for the help!
 giox069 you said:
@GLADtr: recompile both FreeRDP and remmina. The "-DWITH_SSE2=ON" parameter is for FreeRDP, not for remmina.

So, to recompile all, start with a big cleanup:
rm -rf ~/remmina_devel/ sudo rm -rf /opt/remmina_devel/ sudo rm /etc/ld.so.conf.d/freerdp_devel.conf /usr/local/bin/remmina /usr/local/bin/xfreerdp sudo ldconfig
and restart from step 3 of the guide.

I not understood this moment - and restart from step 3 of the guide.
it is possible to specify in more detail what steps it is necessary to execute?

**Comment by giox069** [comment]
@GLADtr the guide for compiling remmina on Ubuntu is here:
https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10
and it should work with your Debian installation if you start from step 3. There are two "step 3" on that guide. Use the first one.

**Comment by GLADtr** [comment]
Hi! Thanks for support!
I`m have the error  while compiling remmina:

Linking C shared module remmina-plugin-xdmcp.so
[ 90%] Built target remmina-plugin-xdmcp
Scanning dependencies of target remmina-plugin-rdp
[ 91%] Building C object remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o
In file included from /home/kmm/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:36:0:
/home/kmm/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.h:50:29: fatal error: winpr/clipboard.h: Нет такого файла или каталога
 #include <winpr/clipboard.h>
                             ^
compilation terminated.
remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build.make:54: ошибка выполнения рецепта для цели «remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o»
make[2]: *** [remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o] Ошибка 1
CMakeFiles/Makefile2:407: ошибка выполнения рецепта для цели «remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/all»
make[1]: *** [remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/all] Ошибка 2
Makefile:117: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by giox069** [comment]
1. Unfortunately cannot read both your language and your alhpabet. The next time try to post error codes in eglish. Just try to prepend "make" with `LC_ALL=C`. So the full commandline will be `LC_ALL=C make && sudo make install` (I'm not sure LC_ALL is enough :( :)
 2. It seems that you have a freerdp already installed on your system. So you should start from step 2 of the guide to remove the installed freerdp.

**Comment by ic3d** [comment]
Hi @GLADtr do you still have this issue?

**Comment by ic3d** [comment]
I'm closing this issue, because no answers to our suggestions and questions, and there are not enough data to solve it. Feel free to open it again if it is still there.
