### ISSUE TITLE
Remmina doesn't support ssh-rsa hostkeys

### ISSUE THREAD

**Issue by n-st** [FreeRDP/Remmina#647]
Trying to establish an SSH tunnel to a server that only offers an RSA hostkey fails with the message
> Failed to startup SSH session: kex error : no match for method server host key algo: server [ssh-rsa], client [ecdsa-sha2-nistp256]

Connecting to the same server with the normal OpenSSH client works:
> OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
[…]
debug1: Connecting to example.com [192.0.2.1] port 1022.
debug1: Connection established.
[…]
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.0p1 Debian-4+deb7u2
debug1: match: OpenSSH_6.0p1 Debian-4+deb7u2 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5 none
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: RSA 34:07:57:d6:75:5c:22:e7:8c:3a:25:61:f8:b0:d4:22
debug1: found 4 secure fingerprints in DNS
debug1: matching host key fingerprint found in DNS
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
[…]

**Comment by antenore** [comment]
Can you please provide Remmina version (Help -> About) and OS type/version?

Thanks in advance

**Comment by n-st** [comment]
@antenore Remmina 1.2.0-rcgit.4 (from the [Ubuntu PPA](https://launchpad.net/%7Eremmina-ppa-team/+archive/ubuntu/remmina-next)) on Ubuntu 14.04.3.
The version from the official Ubuntu repos had the same problem, which is why I installed the version from the PPA in the first place. Didn't help, unfortunately.

**Comment by antenore** [comment]
@n-st looks like a libssh issue https://red.libssh.org/issues/138 to me.

In libssh-0.6.1 the default HOSTKEYS is "ecdsa-sha2-nistp256,ssh-rsa,ssh-dss", so according to the above bug, it's seems really the same issue.

Are you using the default libssh package or a PPA? Can you see if you have a patched version of it?

If it's the good one I'll try to create a test environment, in that case can you please provide me more informations about the server sshd config? 

I hope I'm wrong otherwise I'm afraid I can do nothing to solve your problem.

**Comment by n-st** [comment]
@antenore
I used to have the `libssh-4` from Ubuntu's official repos:
> libssh-4:
  Installed: 0.6.1-0ubuntu3.1
  Candidate: 0.6.1-0ubuntu3.1
  Version table:
 *** 0.6.1-0ubuntu3.1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages

I've now backported and installed [libssh-4 (0.6.3-3ubuntu3) from vivid](http://packages.ubuntu.com/vivid/libssh-4), but the problem still exists.

Just to be sure I've also removed all entries for the failing host from `.ssh/known_hosts` (they're no longer necessary with `VerifyHostKeyDNS` anyway), which didn't change anything either.

The only interesting thing about the remote host's `sshd_config` is that I've disabled the DSA and ECDSA hostkeys:
```
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
```

**Comment by n-st** [comment]
Hang on…
I just managed to connect to the server, with the only difference between the working and non-working Remmina connection presets being the hostname: `myvm.vmhost.example.com:1022` works, `ipv4.vmhost.example.com:1022` doesn't. (Port 1022 on the vmhost is forwarded to port 22 on the VM.)
Both domain names have identical A records, but `myvm.vmhost.example.com` also has an AAAA record.

In other news, libssh seems to wildly misunderstand my `~/.ssh/config`, ignoring a `Match` clause that's supposed to restrict a `ProxyCommand` to a certain subset of hosts…
I'm starting to doubt that it's a good idea to use libssh at all…

**Comment by antenore** [comment]
Good point! libssh does not support most of the ssh_config options, I was considering other solutions, but the only suitable alternatives I'm aware of are libssh2, that has other issues, and openssh itself, where you have to write everything you need yourself. I'll investigate more about this.

If you have any advises you are more than welcome. :-) 

Let's keep this thread opened for discussion if you want, and maybe you can change the title.

**Comment by antenore** [comment]
BTW will be fixed in a future (0.7.X) release https://red.libssh.org/issues/101

**Comment by n-st** [comment]
@antenore
Turns out it was [libssh bug #138](https://red.libssh.org/issues/138) after all: `known_hosts` still contained an ECDSA hostkey for `ipv4.vmhost.example.com:1022`, which the server no longer provides, so libssh aborted prematurely with an error.
After I deleted all occurences of that hostkey, connecting to `ipv4.vmhost.example.com:1022` worked too.
Oddly, the patch (commit fdc660f) [referenced in the libssh bug report](https://red.libssh.org/issues/138#note-8) seems to be included in libssh 0.6.3, but upgrading to that version didn't change libssh's behaviour. Am I missing something there?

Using OpenSSH directly would have avoided this issue entirely, so I'm going to vote for migrating away from libssh/libssh2 to a wrapper around the proven implementation that is OpenSSH.

Also, since libssh does such a terrible job at parsing the config file, could we perhaps have an option in Remmina to *not* parse `~/.ssh/config`? ;)

**Comment by antenore** [comment]
Honestly I don't know regarding the commit fdc660f.

> libssh migration

Yes and no, the big issue is that we don't have so much free time.
We are just two developers and we work in our relatively limited free time, if you (or people you know) want to help us, welcome on board! 

Than I think Vic, years ago, opted for libssh because of license coherence (GPL), we should cast a vote probably.

> .ssh/config optional parsing

Yes, this is something that should be done.

Do you want to open an additional issue, as enhancement/newfeature ?

BTW, thanks a lot for your precious feedbacks.

@giox069

**Comment by n-st** [comment]
@antenore Apologies for my rather demanding attitude…
I haven't had time to dig through Remmina's code since I encountered the issue, but I'll hopefully get around to checking if I can implement any of my requests myself sometime soon. :)

**Comment by antenore** [comment]
:joy_cat:

**Comment by antenore** [comment]
@n-st I close this as I'm well aware of the libssh limitations and in the future I'll look for a better solution.
