### ISSUE TITLE
freeze when rdp over ssl goes to locked screen

### ISSUE THREAD

**Issue by daniel-sciome** [FreeRDP/Remmina#649]
os environment: Elementary OS Freya 0.3.1
nvidia 546 driver
remmina 1.1

i connect to remote windows server 2008 over ssl tunnel through secondary ssl server.

when remote server goes to locked screen, and then i try to lock it. remmina freezes. after the timeout period, i get the "do you want to wait" dialog box. i click "no", and remmina shuts down.
##

**Comment by giox069** [comment]
Please try to upgrade to the latest remmina 1.2.0-rcgit.4. You can find instructions in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki). I think you could use the Ubuntu's "remmina-next" PPA on Elementary OS, as explained in the wiki, but I'm not an expert of Elementary.

**Comment by daniel-sciome** [comment]
I was mistaken.

I’m on version rcgit.4-1.2.0

**Comment by ic3d** [comment]
Hi @daniel-sciome do you still get this issue? Thanks!

**Comment by daniel-sciome** [comment]
I haven’t used remmina for a long time.

--------------------------------------------------
Dan Svoboda, PhD
Sciome LLC
Enabling Science via Analytical Informatics
www.sciome.com<http://www.sciome.com/>
daniel.svoboda@sciome.com<mailto:daniel.svoboda@sciome.com>

**Comment by ic3d** [comment]
@daniel-sciome ok, no problem. I will close this issue because it affects an old version of Remmina. Feel free to open another issue if it's needed.
