### ISSUE TITLE
RDP Plugin Issue on Raspberry PI (ARMv7)

### ISSUE THREAD

**Issue by austinwhitley** [FreeRDP/Remmina#651]
Since there isn't a PPA build available for the ARM architecture, I went through the instructions for compling the source on my Raspberry Pi 2 (Ubuntu Mate 15.04) and everything seems to be fine except when launching Remmina I get the following error:

Failed to load plugin: /opt/remmina_next/remmina/lib/remmina/plugins/remmina-plugin-rdp.so .
Error: libfreerdp.so.1.2: Cannot open shared object file: No such file or directory.

I'm pretty new at this, so any help is appreciated.

**Comment by giox069** [comment]
It could be a wrong /etc/ld.so.conf.d/freerdp_devel.conf generated in step 7:
```
echo /opt/remmina_devel/freerdp/lib | sudo tee /etc/ld.so.conf.d/freerdp_devel.conf > /dev/null
sudo ldconfig
```
The wrong part could be `/opt/remmina_devel/freerdp/lib`: you should find in which directory the files libfreerdp.so.1.2* have been installed, and put the directory name into the file /etc/ld.so.conf.d/freerdp_devel.conf
After this fix, do a `sudo ldconfig` again and try to start remmina.

**Comment by austinwhitley** [comment]
That took care of it.  I had a typo that I didn't notice.  Thanks for your help!  This can be closed.
