### ISSUE TITLE
Minus "-" instead of slash "/" from numpad

### ISSUE THREAD

**Issue by angerangel** [FreeRDP/Remmina#656]
I use linux mint to connect to a Windows server.  My keyboard (italian) has the slash on the 7 button and this works great: SHIFT+7 = /
The numpad has a button for each operation (+,-,*,/); but the slash,button ouput the minus sign "-".  So it's like to have 2 minus button on the numpad.
Is there any file to edit in order to have the correct behavior? 
##

**Comment by antenore** [comment]
What version of Mint and Remmna do you use?

**Comment by angerangel** [comment]
My version is:  0.9.99.1

**Comment by antenore** [comment]
@angerangel 

Unlucky, that version is too old and we don't support it anymore.

You can follow our wiki to upgrade it https://github.com/FreeRDP/Remmina/wiki 

If you have troubles let me know.

**Comment by angerangel** [comment]
Wow, solved with last remmina version!
