### ISSUE TITLE
Simple identity manager for non SSH connections?

### ISSUE THREAD

**Issue by ELadner** [FreeRDP/Remmina#660]
In the case of RDP connections (and other non SSH based connections) a simple identity manager would be helpful.  Typically administrators use one or two ID's for many servers.  Having a username,  password, and domain embedded in each connection makes changing passwords tedious for large server groups.  

SSH solves this issue, of course, by authenticating with the agent locally and the prior set up of SSH keys.  RDP doesn't have that option.

**Proposal:**  Decouple the username/password/domain from the server definition.
1. Create a simple identify manager to store encrypted username/password/domain information for different accounts separate from the definitions of server connections.
2. Multiple servers would then just reference either an identity or a one-off supplied user/pass.  When the password is changed on the identity, the next use of a server that references that identity would pull the new password.  

NX and VNC don't required a domain, but domain is required for RDP connections (domain could be an optional part of the identity store to be useful for other services besides RDP).

Granted this can be accomplished with VNC and SSH, but in organizations that disallow the use of VNC and SSH daemons on Windows machines, RDP is the only option.

Your thoughts?
##

**Comment by antenore** [comment]
It's something I've to think about.

In the meanwhile...

#625 has a similar proposal

Each remmina server definition has its own plain text file either under ~/.local/share/remmina or ~/.remmina

Password are stored there or inside a keyring if you use a gnome-keyring like daemon. 

libsecret provide a secret-tool utility to manage secrets inside the the keyring, and there are also other tools available like  https://wiki.archlinux.org/index.php/GNOME_Keyring#Useful_tools

I think some scripts can do the job till we will have the time to improve the the profile management in Remmna.

**Comment by evilhamsterman** [comment]
I +1 this. I have a large number of servers and services I access that all use my AD credentials. I'm required to change my password quarterly so it is very annoying everytime I have to reset the password in each server settings. [RoyalTS](http://www.royalapplications.com/ts/win/features) which I have used on Windows does this very well, you can define credentials at a global level and then folders and all their children or even individual servers can inherit.
