### ISSUE TITLE
Optimize screen space usage

### ISSUE THREAD

**Issue by tessiof** [FreeRDP/Remmina#661]
This is a feature request.
I think the menus from the connection screen should be placed at the sides, not at the top.
The vast majority of computers monitors today are widescreen, so it's most appropriate to leave the vertical space free from non essential visual information.
![rdp connection 2](https://cloud.githubusercontent.com/assets/2301644/10797323/eb67a356-7d80-11e5-849d-57a337544ee9.png)

GNOME and Unity are examples of this "new" design tendency, since they place their menus at the left screen corner by default.

**Comment by giox069** [comment]
Very good idea. I will start investigating on it in the next days. Thank you for reporting.

**Comment by giox069** [comment]
Feature implemented. The toolbar is now on the left, and you can drag&drop it to move on the other edges of the window. If you are using the ubuntu PPA, the update will be availabe in the next hours automatically. Let us know what you think.

**Comment by tessiof** [comment]
Awesome work! Remmina is now even better software;.. :dancers:
