### ISSUE TITLE
When I open a RDP connexion on Microsoft Windows PC, SSH Client display is messing

### ISSUE THREAD

**Issue by dschaefer79** [FreeRDP/Remmina#663]
Hi, When I open a RDP connexion with KRDC or Remmina on Microsoft Windows PC, SSH Client display is messing I use Putty on Windows and Secure Shell Client on Windows. 
When I resize the SSH window or move it, it display again correctly. But after the bugs comes again. When I do the same on Windows PC with RDP connection on Windows PC, there is no bug. 

Reproducible: Always Steps to Reproduce: 
1. Open Remmina
2. Connect to remote Microsoft Windows PC with RDP 
3. Open SSH session with Putty or SSH Secure Shell 

Actual Results: Display is not good 
Expected Results: Display should be good. 

KDE Bugs
https://bugs.kde.org/show_bug.cgi?id=354537
##

**Comment by dschaefer79** [comment]
![krdc](https://cloud.githubusercontent.com/assets/7472357/10813311/98e3dba6-7e1e-11e5-9e7e-6ad69b758cd0.png)

**Comment by dschaefer79** [comment]
I have the same problem with xfreerdp command

**Comment by antenore** [comment]
which version of freerdp and remmina are you using? Is this a cygwin installation?

**Comment by dschaefer79** [comment]
I use xfreerdp version 1.1.0 beta1

**Comment by antenore** [comment]
This is an old version, from 2013. It would be a good idea to compile it by hand till the FreeRDP team won't release a new official version.

Take a look at our wiki.
