### ISSUE TITLE
Local cursor is shown in XDMCP mode even if not set

### ISSUE THREAD

**Issue by fraang** [FreeRDP/Remmina#664]
I have installed Remmina from the official PPA on Xubuntu 14.04 and have the problem that the local cursor is shown even if I set to off in the connection preferences. I have tried it with a Xfce and KDE session on the remote host. Is this a bug or is the option "Use local cursor" only relevant for certain connection modes?

EDIT: What infos do you need to be able to sort this out?
##

**Comment by antenore** [comment]
It should work.

When you set that option, Xephyr is executed with 

```sh
-host-cursor
```
From the man page:

```sh
-host-cursor
               set 'cursor acceleration': The host's cursor is reused. This is
               only  really  there  to aid debugging by avoiding server paints
               for the cursor. Performance improvement is negligible.
```

**Comment by ic3d** [comment]
Hi @fraang we're reviewing old issues, do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina.
