### ISSUE TITLE
apt-get broken on ubuntu 15.10

### ISSUE THREAD

**Issue by poiuty** [FreeRDP/Remmina#666]
```
# sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
# sudo apt-get update
# sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
# apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libfreerdp-plugins-standard : Depends: libavcodec56 (>= 6:11~beta1) but it is not installable or
                                        libavcodec-extra-56 (>= 6:11) but it is not installable
                               Depends: libavutil54 (>= 6:11~beta1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
##

**Comment by guntbert** [comment]
Confirming problems on Ubuntu 15.10

There seems to be an issue with *libavcodec*, I "suddenly" (I know...) was not able to connect to rdp servers (while `rdesktop-vrdp` worked).
Then calling `xfreerdp` from CLI brought the error message: 

>    xfreerdp: error while loading shared libraries: libavcodec.so.56: cannot open shared object file: No such file or directory

To remedy I added the ppa for 1.2 - now I don't even have the rdp-plugin installed and `xfreerdp` still balks (same error message)

Starting `remmina` from CLI gives now two error messages

>     Failed to load plugin: /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so.
>     Error: libavcodec.so.56: cannot open shared object file: No such file or directory

**Comment by ic3d** [comment]
I'm closing this issue because it affects an out of date version of Ubuntu and Remmina. You need to update both Ubuntu and Remmina. Thanks!
