### ISSUE TITLE
rdp plugin does not load

### ISSUE THREAD

**Issue by ObiWahn** [FreeRDP/Remmina#667]
Hi,

I have just build remmina from source. Unfortunately the rdp plugin can not be loaded. http://paste.debian.net/318952/

Best Regards

Jan

**Comment by giox069** [comment]
The rdp plugin is loaded dynamically at remmina startup, so you can't see it in the ldd output. You should execute remmina from the terminal, and look at the output.
Have you followed the [Ubuntu guide in the wiki](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10) to build remmina ? If yes, please check that the directory you put in /etc/ld.so.conf.d/freerdp_devel.conf file (step 7) is really the one with freerdp .so library files.

**Comment by ObiWahn** [comment]
i have followed the most of the guide but installed to /user/local. As you can see in the link above freerdp.so is found by the plugin:

libfreerdp.so.1.2 => /usr/local/lib/libfreerdp.so.1.2 (0x00007fbecfbb1000)

There is nothing to be seen on the console. Only a box "Protocol plugin RDP is not installed." when I try to open a rdp connection. That what i take for the plugin can be found in /usr/local/lib/remmina/plugins

**Comment by ObiWahn** [comment]
Strange - I have recompiled Remmina with CMAKE_BUILD_TYPE=Debug in order to have a look with gdb. Now everything is working just fine. If I should find something out while installing Remmina on my laptop I'll let you know.
