### ISSUE TITLE
Unable to do control any key

### ISSUE THREAD

**Issue by pingpong1109** [FreeRDP/Remmina#682]
When I press control+c or really any key it does not detect that I am pressing control. I have done some searching and have not found any real fix. I am running Solus RC 1
##

**Comment by antenore** [comment]
Hi @pingpong1109 

Solus provide a quite old version of Remmina, you should try to build the devlopment version (it's quite stable) and see if you still have the problem.

https://github.com/FreeRDP/Remmina/wiki

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we support only the Remmina 1.2.* branch.
