### ISSUE TITLE
RDP fails with TLS handshake failure if TLS 1.0 is disabled on Windows

### ISSUE THREAD

**Issue by internetstaff** [FreeRDP/Remmina#684]
I have Windows 2012 servers with TLS 1.0 disabled and RC4 ciphers disabled, but is otherwise stock. RDP works fine with just RC4 disabled, but as soon as TLS 1.0 is disabled in the SCHANNEL configuration, RDP from Remmina fails with EventIDs 36874, 36888. The error code in event 36888 is 40, handshake failure.

I can connect via openssl and gnutls-cli, so it seems like it's something specific to Remmina.

As TLS 1.0 and 1.1 are being phased out by PCI-DSS, this is going to become a significant problem soon.

Thanks!
##

**Comment by skwd** [comment]
Same problem for me

**Comment by giox069** [comment]
Remmina uses libfreerdp to connect to an RDP server. So you can test your TLS handshake with the xfreerdp commandline client and check if in xfreerdp commandline you can find a switch which solves the problem. Then report the correct switch here and we will try to make it work on remmina.

Also please check tat you are running the latest version of remmina (1.2.0-rcgit.5) and libfreerdp (1.2 or 2.0). See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for more info.

**Comment by skwd** [comment]
I think freeRDP have an issue with tls 1.1 and 1.2 :
https://github.com/FreeRDP/FreeRDP/issues/2828

in libfreerdp/crypto/tls.c it's use TLSv1_client_method() to connect in TLS

**Comment by skwd** [comment]
FreeRDP fix the issue in the last release with PR #3046 https://github.com/FreeRDP/FreeRDP/pull/3046

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina AND it's due to a (closed) old issue of RDP.
