### ISSUE TITLE
copy / paste and charset

### ISSUE THREAD

**Issue by ComputingFroggy** [FreeRDP/Remmina#685]
When I copy / paste between the host (on Bodhi 3.1) and a remote computer on Windows (using VNC - Remmina), the accentuated characters don't come out OK.

Is there a way to configure the charset used for the clipboard management ?
##

**Comment by antenore** [comment]
Which version of Remmina do you have? Bodhi does not provide a Remmina package.

**Comment by ComputingFroggy** [comment]
Bodhi uses Ubuntu 14.04 repository, so I have Remmina 0.9.99.1

**Comment by antenore** [comment]
That is really toooooo old for us, please follow our wiki to update Remmina from the PPA.

**Comment by ComputingFroggy** [comment]
I have added the ppa and I am now running v. 1.2.0-rcgit.8.

But the problem is still there
Here is what I get when I paste from Remmina session to one my Linux program:
=== begin text ===
l'Ã©tÃ© aux Muriers
et Ã  NoÃ«l dans l'abÃ®me.
=== end  text ===
when copying this :
=== begin text ===
l'été aux Mûriers
et à  Noël dans l'abîme.
=== end  text ===

Any ideas on how to solve that ?


Cheers,
L@u
PS: also I get a strange problem, if I switch from a remmina session to another program when I get back to remmina, I can not type in anymore ... but that's another story and I will create another Issue.

**Comment by ic3d** [comment]
Hi @ComputingFroggy we're reviewing old issues, do you still get this one? Thanks!

**Comment by ComputingFroggy** [comment]
No, you can close it.
It's working fine with v. 1.2.0-rcgit-20
