### ISSUE TITLE
\\tsclient shares disconnect when accessed by certain programs on server

### ISSUE THREAD

**Issue by awilkins** [FreeRDP/Remmina#686]
Problem : 
- Connect to Win2k8 server win Remmina
- Share a local folder
- Explorer accesses this folder at \tsclient\folder just fine, can transfer files
- Trying to view folder in another program, Beyond Compare (file diff tool) fails to open folder, and causes folder to be unavailable to all programs including Explorer until you disconnect / reconnect your session.

Tried the same steps with a Windows VM and it works fine. My conclusion is that BCompare.exe does something that Explorer does not that breaks the server FreeRDP implements client folder sharing with.

Reproduced with FreeRDP ( 1.0.2 ) in the hope that it would cough up some extra information to STDERR. Alas, no.

See also 

http://www.scootersoftware.com/vbulletin/showthread.php?14673-Problems-with-tsclient-drives
##

**Comment by ic3d** [comment]
Hi @awilkins we're reviewing old issues, do yuo still get this one? Thanks!

**Comment by awilkins** [comment]
Hi, sadly I no longer have the opportunity to test this - the Win2k8 server in question has left my sphere of responsibility and I don't have another to try it out on.

**Comment by giox069** [comment]
Ok, I'm closing this issue now. Reopen a new one if needed.
