### ISSUE TITLE
Indicator menu gone?

### ISSUE THREAD

**Issue by aperomsik** [FreeRDP/Remmina#688]
After the last update from the PPA, I seem to have lost the indicator menu.

Remmina package version is 1.1.2-ppa1+797+next+201511240446~ubuntu15.10.1 amd64 .

**Comment by giox069** [comment]
On which desktop ? Unity ?

**Comment by aperomsik** [comment]
Yes.

**Comment by aperomsik** [comment]
Now it's showing again. Not sure what happened. Closing.

**Comment by giox069** [comment]
:+1:
