### ISSUE TITLE
Remmina windows open behind other desktop windows

### ISSUE THREAD

**Issue by wsgcsysadmin** [FreeRDP/Remmina#691]
Ubuntu 14.04(Trusty Tahr) x86_64

Any Remmina windows that open from actions performed via the tray icon open behind other desktop windows.

To reproduce:
1. Open Remmina and enable tray icon
2. select another window
3. Perform some action from the tray icon that opens a window, Preferences for example.
4. Preferences Window opens just underneath the window selected in step 2.
5. Go to the preferences window so that it is active.
6. Close it.
7. Open Preferences again.
8. This time it opens on top because Remmina is somehow remembering where in the Z order it is.

This has been an issue for at least two years.

**Comment by giox069** [comment]
It's a feature, not a bug. A feature of almost all window manager, and is called "focus stealing prevention".
See issue #542
We can do almost nothing to solve it. One day maybe we will remove the systray icon and bring its full menu of connection inside a remmina toolbar.

**Comment by wsgcsysadmin** [comment]
Understood. I've modified Compiz settings.  Thank you.
