### ISSUE TITLE
Copy&Paste of formatted text not working.

### ISSUE THREAD

**Issue by markohrastovec** [FreeRDP/Remmina#693]
When I have clipboard sync enabled the clipboard on the remote machine connected via remmina shows strange behaviour when copying. It looks like the formatting is stripped of from the clipboard and I can copy only unformatted text. If I switch the clipboard sync off the copying on the remote machine works as it should. I am not copying from remote to local or vice versa. It looks like remmina is messing up the clipboard on the remote when sync is on.

The behaviour is manifested for instance when I copy a table in MS Word and try to paste it it only pastes plain text. It does not do it every time but most of the time.

I am using version 1.2.0-rcgit.5.
##

**Comment by giox069** [comment]
Which version of libfreerdp are you using ? Did you follow our compile instructions or are you using the Ubuntu PPA version ?

**Comment by markohrastovec** [comment]
I am using Ubuntu PPA.

On Sat, Dec 5, 2015 at 10:33 AM, Giovanni Panozzo <notifications@github.com>
wrote:

> Which version of libfreerdp are you using ? Did you follow our compile
> instructions or are you using the Ubuntu PPA version ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/Remmina/issues/693#issuecomment-162167314>.
>



-- 
Marko Hrastovec [marko.hrastovec@gmail.com]

**Comment by giox069** [comment]
Unfortunately the ubuntu ppa is carrying an old outdated version of libfreerdp. We will update and post here know when ready.

**Comment by giox069** [comment]
Hi @markohrastovec. I totally forgot this issue, I'm sorry. Did you tried to update remmina with the ubunut's remmina-next PPA ? If yes, did it work and we can close this issue ?

**Comment by markohrastovec** [comment]
I think I am using remmina PPA because I get new remmina almost every day.
However, I checked it back then and it still did not work. I disabled
clipboard sync then and I am not using it anymore since then. Iw would be
nice if it worked.

On Sat, Mar 19, 2016 at 5:05 PM, Giovanni Panozzo <notifications@github.com>
wrote:

> Hi @markohrastovec <https://github.com/markohrastovec>. I totally forgot
> this issue, I'm sorry. Did you tried to update remmina with the ubunut's
> remmina-next PPA ? If yes, did it work and we can close this issue ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/Remmina/issues/693#issuecomment-198738728>
>



-- 
Marko Hrastovec [marko.hrastovec@gmail.com]

**Comment by giox069** [comment]
Yes, if you get updates, you are using the remmina-next PPA.

mmm... if possible, in the next days, can you confirm the following ?
1. Copying a msword table from a RDP connection to the same RDP connection works
2. Copying a msword table from a RDP connection to another RDP connection, strips all formatting
3. Copying a msword table from a RDP connection to a local linux, strips all formatting

In the meanwhile I'm changing the issue subject.

**Comment by markohrastovec** [comment]
Hi,

I will get the access to the computer where I noticed the problem on Monday
and will try it then. Before I try it I would like to point out that I
noticed the problems copying test on RDP connection within the same msword
document. The problem was that I was able to copy a table one time. When I
tried to paste it second or third time the problem occured. As least it is
how I remember it. I will test it again on Monday and let you know.


On Sat, Mar 19, 2016 at 5:32 PM, Giovanni Panozzo <notifications@github.com>
wrote:

> Yes, if you get updates, you are using the remmina-next PPA.
>
> mmm... if possible, in the next days, can you confirm the following ?
> 1. Copying a msword table from a RDP connection to the same RDP connection
> works
> 2. Copying a msword table from a RDP connection to another RDP connection,
> strips all formatting
> 3. Copying a msword table from a RDP connection to a local linux, strips
> all formatting
>
> In the meanwhile I'm changing the issue subject.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/Remmina/issues/693#issuecomment-198745308>
>



-- 
Marko Hrastovec [marko.hrastovec@gmail.com]

**Comment by markohrastovec** [comment]
Hi,

I have tested the clipboard bug on remmina 1.2.0-rcgit.11 (git n/a). With
disabled clipboard sync I can copy within remote desktop without problems.
If clipboard sync is enabled I can copy a table within MS Word and paste it
once or maybe twice. To paste it the third time it almost never works any
more. Sometimes it won't paste at all and sometimes it will paste only
text. So, one copy and paste work. To paste the same content over and over
again is impossible for me.

I have observed the same problem in Outlook Calendar. I can copy an
appointment and paste it to another day. After a few pastes only text is in
the clipboard and I cannot paste the appointment any more. I am sure in
other applications the problems as very similar.

I hope this description will help you find the bug.

Kind regards
Marko

On Sat, Mar 19, 2016 at 5:32 PM, Giovanni Panozzo <notifications@github.com>
wrote:

> Yes, if you get updates, you are using the remmina-next PPA.
>
> mmm... if possible, in the next days, can you confirm the following ?
> 1. Copying a msword table from a RDP connection to the same RDP connection
> works
> 2. Copying a msword table from a RDP connection to another RDP connection,
> strips all formatting
> 3. Copying a msword table from a RDP connection to a local linux, strips
> all formatting
>
> In the meanwhile I'm changing the issue subject.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/Remmina/issues/693#issuecomment-198745308>
>



-- 
Marko Hrastovec [marko.hrastovec@gmail.com]

**Comment by markohrastovec** [comment]
I think the title is now wrong. The error was observed on remote machine only when clipboard sync is on.

**Comment by antenore** [comment]
I can confirm the issue, but it happens whenever I enable or disable the clipboard sync.
Well, if I disable the clipboard sync I can't copy&paste at all.

```sh
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git 52f1e6b)
$ remmina --version
1.2.0-rcgit.11 (git f01807d)
```

**Comment by markohrastovec** [comment]
This problem occurs for me only if I have clipboard sync enabled. That is why I have it disabled all the time. The consequence is that I cannot copy between remote and local system.

**Comment by ic3d** [comment]
Hi @markohrastovec  we're reviewing old open issues, do yuo still get this one with the latest version of Remmina?

**Comment by markohrastovec** [comment]
I checked it on one of the computers again and the error is not occuring there. That is very good news. I will try it on other setups on Monday. It seems that you can close this issue.

**Comment by ic3d** [comment]
Thanks @markohrastovec. I'll wait a couple of days just to be sure.

**Comment by markohrastovec** [comment]
Hi,
I tried it elsewhere and it seems that it works in all cases. Thanks a lot.

Regards
Marko

**Comment by ic3d** [comment]
OK, closing.
