### ISSUE TITLE
RDP SEGFAULTS under fedora rawhide

### ISSUE THREAD

**Issue by wgianopoulos** [FreeRDP/Remmina#694]
When you try to use Remmina to connect to a widows server via RDP it crashes.  Here is the terminal window output:

[wag@rawhide ~]$ remmina

(remmina:4193): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[11:30:51:608] [4193:4197] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr

(remmina:4193): Gtk-WARNING **: Theme parsing error: <data>:13:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:4193): Gtk-WARNING **: Theme parsing error: <data>:14:31: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:4193): Gtk-WARNING **: Theme parsing error: <data>:19:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:4193): Gtk-WARNING **: Theme parsing error: <data>:20:31: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
Segmentation fault (core dumped)
##

**Comment by wgianopoulos** [comment]
My crashing enviornment is:

kernel - 4.4.0-0.rc3.git4.1
remmina - 1.2.0-0.9.git.8855df7
freerdp - 2:2.0.0-1.git.be8f8f7
gtk2 - 2.24.28-2
gtk3 - 3.19.4-1

**Comment by wgianopoulos** [comment]
The fedora bug on this is https://bugzilla.redhat.com/show_bug.cgi?id=1286468

**Comment by giox069** [comment]
I installed rawhide, and I can confirm that I can reproduce it.
But... the crash is in the deep inside of GTK: it seems that gtk_css_widget_node_get_style_provider() is calling gtk_widget_get_scale_factor() on something similar to an invalid widget, or a NULL pointer. I can't debug further, because it will take hours and recompilation of GTK in debug mode.
Is it possible to have some help from a GTK internals expert ?

**Comment by ic3d** [comment]
The Fedora bug is closed, so therefore this issue.
