### ISSUE TITLE
tot remmina crashes when marking text in the client iff clipboard sync is disabled

### ISSUE THREAD

**Issue by ObiWahn** [FreeRDP/Remmina#695]
Remmina crashes when i mark some text in the client window. This happens only when "clipboard sync" is disabled. I am using Debian/SID with xmonad. I have started remmina as WM and had the same result.

**Comment by antenore** [comment]
Which Remmina/FreeRDP version?

**Comment by ObiWahn** [comment]
FreeRDP b5880750987e892234fae937017f4af420aad403
Remmina 6f1306f02d1b30dfe57eac5609d622c0b12f93a3

**Comment by antenore** [comment]
I've tried to replicate your issue on two different distributions, using dwm and i3wm, but I don't have any crash.

Which clipboard manager do you use? I personally use gpaste as with parcellite I was experiencing several problems.

Can you attach a gdb backtrace (be sure to install all the debug packages needed).

**Comment by ObiWahn** [comment]
Hi,
could you give me a few instructions where to break? The main UI is still there and [Inferior 1 (process 22890) exited normally] If you give me a bit guidance i will do my best to pull some useful information out of the thread. I think last time i tried catch throw and some other stuff but i was not able to locate the problem.

Kind Regards

**Comment by antenore** [comment]
Remmina must be compiled with -DCMAKE_BUILD_TYPE=Debug , follows the wiki in case you need.

Start remmina with

```sh
gdb remmina
```

If gdb advices to install some debug packages you have to do it.

As soon as remmina crashes, execute the command (inside gdb) **bt**

Then you should have a list of frames that you can analyse with the command frame (frame 1, or frame 15, etc) , the frame command will show you the code that has been executed and you can print the values of variables for instance.

But just copy&paste them here for now (at lease the bt result).

**Comment by ObiWahn** [comment]
» objdump --syms  /opt/remmina_devel/remmina/bin/remmina | grep debug
0000000000000000 l    d  .debug_aranges	0000000000000000              .debug_aranges
0000000000000000 l    d  .debug_info	0000000000000000              .debug_info
0000000000000000 l    d  .debug_abbrev	0000000000000000              .debug_abbrev
0000000000000000 l    d  .debug_line	0000000000000000              .debug_line
0000000000000000 l    d  .debug_str	0000000000000000              .debug_str
0000000000430d6f g     F .text	0000000000000018              remmina_main_on_action_help_debug

Reading symbols from /opt/remmina_devel/remmina/bin/remmina...done.
(gdb) r
Starting program: /usr/opt/remmina_devel/remmina/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec580700 (LWP 26314)]
[New Thread 0x7fffebd7f700 (LWP 26315)]
[New Thread 0x7fffeb57e700 (LWP 26316)]
[Thread 0x7fffeb57e700 (LWP 26316) exited]
[Thread 0x7fffebd7f700 (LWP 26315) exited]
[Thread 0x7ffff7f11a40 (LWP 26310) exited]
[Inferior 1 (process 26310) exited normally]
(gdb) bt
No stack.
(gdb)

**Comment by antenore** [comment]
I think that is your clipboard manager that crashes (could be because of remmina, freerdp, or not) 
What clipboard manger are you using?

**Comment by ObiWahn** [comment]
What is a clipboard manager? I use xmonad as desktop environment . The same happens when i start remmina as x client directly.

I use startx to enter my graphical environment and use the following configuration:
» cat .xinitrc
#!/bin/sh
xsetroot -solid "#333333"
xsetroot -cursor_name left_ptr
exec dbus-launch /usr/bin/xmonad-session
#exec dbus-launch /opt/remmina_devel/remmina/bin/remmina

**Comment by antenore** [comment]
Well you don't have one, so you are using directly the standard selections defined by the ICCCM (through X).

Honestly I'm buffed... I've tried the most similar configuration that you have (I just use dwm instead of xmonad) but I cannot replicate your issue.

**Comment by antenore** [comment]
two more things, did you have any other old version of remmina and freerdp installed before?

If yes can you check you don't have old files still installed ?

Do you have the same issue using xfreerdp from a terminal?

**Comment by ObiWahn** [comment]
xfreerdp crashes as well

» ./xfreerdp /v:xxxxx
[10:51:31:003] [29955:29956] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: yyyyyy
[10:51:31:010] [29955:29956] [INFO][com.freerdp.client.x11] - Property 346 does not exist
[10:52:43:103] [29955:29956] [ERROR][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[10:52:43:103] [29955:29956] [ERROR][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3

(gdb) c
Continuing.
(gdb) [Thread 0x7f8a014b3700 (LWP 29956) exited]
[Inferior 1 (process 29955) exited with code 014]
(gdb) bt
No stack.
(gdb) 

/opt/remmina_devel/freerdp/bin
» ldd xfreerdp 
	linux-vdso.so.1 (0x00007ffe5afba000)
	libxfreerdp-client.so.2.0 => /usr/opt/remmina_devel/freerdp/bin/./../lib/libxfreerdp-client.so.2.0 (0x00007fd0fa22d000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fd0f9fea000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fd0f9ddf000)
	libXv.so.1 => /usr/lib/x86_64-linux-gnu/libXv.so.1 (0x00007fd0f9bda000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fd0f99c9000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd0f97bf000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd0f95b9000)
	libfreerdp-client.so.2.0 => /usr/opt/remmina_devel/freerdp/bin/./../lib/libfreerdp-client.so.2.0 (0x00007fd0f92e5000)
	libavcodec-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 (0x00007fd0f7f01000)
	libavutil-ffmpeg.so.54 => /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 (0x00007fd0f7c92000)
	libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007fd0f7971000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd0f7662000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd0f740f000)
	libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007fd0f71ab000)
	libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007fd0f6f9e000)
	libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007fd0f6d1b000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd0f6b08000)
	libfreerdp.so.2.0 => /usr/opt/remmina_devel/freerdp/bin/./../lib/libfreerdp.so.2.0 (0x00007fd0f673c000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd0f63f9000)
	libxkbfile.so.1 => /usr/lib/x86_64-linux-gnu/libxkbfile.so.1 (0x00007fd0f61d2000)
	libwinpr.so.1.1 => /usr/opt/remmina_devel/freerdp/bin/./../lib/libwinpr.so.1.1 (0x00007fd0f5ecf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd0f5cc7000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fd0f5c44000)
	libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007fd0f59db000)
	libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007fd0f5579000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd0f5273000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd0f5056000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd0f4e52000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd0f4c36000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fd0f493b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd0f4597000)
	libswresample-ffmpeg.so.1 => /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 (0x00007fd0f437a000)
	libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007fd0f415e000)
	libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007fd0f3ecf000)
	libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007fd0f3bb8000)
	libx265.so.68 => /usr/lib/x86_64-linux-gnu/libx265.so.68 (0x00007fd0f2fc8000)
	libx264.so.148 => /usr/lib/x86_64-linux-gnu/libx264.so.148 (0x00007fd0f2c23000)
	libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007fd0f29c3000)
	libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007fd0f279a000)
	libvpx.so.2 => /usr/lib/x86_64-linux-gnu/libvpx.so.2 (0x00007fd0f2396000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fd0f20ed000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fd0f1ec1000)
	libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007fd0f1c9c000)
	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007fd0f1a5d000)
	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007fd0f1842000)
	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007fd0f1628000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007fd0f1420000)
	libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007fd0f1213000)
	libschroedinger-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0 (0x00007fd0f0f3d000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007fd0f0cf4000)
	libopenjpeg.so.5 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5 (0x00007fd0f0acf000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007fd0f0857000)
	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007fd0f064a000)
	libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007fd0f042f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd0f020b000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd0f0007000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd0efd99000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fd0efb90000)
	liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007fd0ef909000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd0ef6e7000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd0ef4c5000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fd0ef1e3000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559598b80000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fd0eefbd000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fd0eedb1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd0eea36000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd0ee81f000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007fd0ee616000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd0ee412000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd0ee20b000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fd0edff800

**Comment by antenore** [comment]
So I can do nothing but asking you to open the same bug report to the FreeRDP guys, sorry.
