### ISSUE TITLE
Remmina doesn't map printers

### ISSUE THREAD

**Issue by lexuv** [FreeRDP/Remmina#697]
Remmina doesn't map printers
##

**Comment by antenore** [comment]
First of all, which version of Remmina and FreeRDP are you using?

Remmina uses FreeRDP behind the scenes, so the first tests you should do is to connect from the command line with xfreerdp, if it doesn't work, you should open an issue to the FreeRDP team.

If it works with xfreerdp, be sure you have installed the last Remmina version (see the wiki).

If it doesn't work only within Remmina let me know, we will investigate further.

**Comment by virtkit** [comment]
Have you tried to enable sound? We have had that issue with terminal server windows server 2008. After enabling local sound (despite not needing it) the printer worked. Without enabling sound the printer wouldn't connect. Give it a try.

**Comment by ic3d** [comment]
We won't fix this issue because it probably affects an old version of Remmina - we only support Remmina 1.2.* branch. Feel free to open another issue if needed. Thanks!
