### ISSUE TITLE
Icons not shown at the correct size in the main window's listview/treeview

### ISSUE THREAD

**Issue by nekohayo** [FreeRDP/Remmina#701]
You have nice bitmap icons for the various types of remote servers, but in the main window they all appear blurry because they are shown at a non-native size. Instead, they should be shown at the exact size of the icons.

**Comment by antenore** [comment]
Thanks for the report, can you please post a screen-shot?

**Comment by nekohayo** [comment]
Sure. Compare the icons on the left with the one on the right:
![fuzzy icons](https://cloud.githubusercontent.com/assets/479401/11747111/67052d18-9fef-11e5-8c6a-4bd30cd36a64.png)

**Comment by antenore** [comment]
We only have icons (in png format) of 16x16 and 22x22, so at the moment we cannot do better.

Sometime ago, we have tried to redesign the icons, but the designers (that we have payed) didn't produce something that was appealing for most of our main contributors.

If you want to take a look we still have a branch with all of them: 

https://github.com/FreeRDP/Remmina/tree/newicons

... and  a pull request as well with some screenshot #608 

Have a look inside remmina/icons, remmina/desktop and inside each remmina-plugins/subdir

Now, the main issue, is that we don't have money to pay someone else and we don't have the time and the competencies to design something better.

Obviously, if you have the competencies and the time, you are more than welcome to contribute.

Merci beaucoup!

**Comment by nekohayo** [comment]
I do have design skills (and I do find the icons from #608 fairly unappealing :) but lack time lately. 

However, my initial suggestion here was to simply reduce the size in the listview so that the current type icons (which look mostly OK to me anyway) show at their native, pixel-perfect size. Would probably be a one-liner in your code to set the pixmap's size property or something.

**Comment by antenore** [comment]
:-) it's not that easy but I'll take a look

**Comment by nekohayo** [comment]
gtk_image_set_pixel_size ? (or something like that, dunno if you're using pixmaps/pixbuf, GtkImage or something else ;)

**Comment by antenore** [comment]
No, GtkCellRendererPixbuf

https://github.com/FreeRDP/Remmina/blob/next/remmina/ui/remmina_main.glade#L913

and I've already have done some tests today and the result was not nice at all.

**Comment by nekohayo** [comment]
Well, bumping that down to size 2 seemed to have worked for me :)

![worked for me](https://cloud.githubusercontent.com/assets/479401/11755735/6360642e-a022-11e5-8d21-f1a670b56789.png)

**Comment by antenore** [comment]
Weird, this morning I had the feeling the icons were too small and I thought I was looking in the wrong place. 

I've just tried in my home office and it's fine, I'll do a pull request and ask to test it.

**Comment by antenore** [comment]
#702
