### ISSUE TITLE
Remmina RDP hangs after second certificate confirmation when using RD gateway

### ISSUE THREAD

**Issue by cen1** [FreeRDP/Remmina#706]
I use RD gateway and the machine address is a .local domain. Every other setting is default.

First it asks me to confirm RD certificate and then it asks to confirm the .local certificate. After that it hangs with empty message in the screenshot. Debug window is empty (do I have to enable anything to see debug output?).

![remmina1](https://cloud.githubusercontent.com/assets/1158861/11894739/7d391678-a579-11e5-87db-88819b4b5082.png)
##

**Comment by giox069** [comment]
Which version of remmina are you using ? Under which distribution ?

**Comment by cen1** [comment]
Fedora 23, About says 1.2.0-rcgit.3

**Comment by antenore** [comment]
This it means to work now.
Check #933 for last RD Gateway enhancements.

We will close this as soon as the new branch will be merged.
