### ISSUE TITLE
the checkbox, 'Save SSH Password',  greyed out.

### ISSUE THREAD

**Issue by MagiCarbon** [FreeRDP/Remmina#708]
OS: Arch Linux, XFCE4
Remmina Version: 1.1.2

i've googled but got nothing.

help plz. thanks.
##

**Comment by antenore** [comment]
Do you have libsecret?

**Comment by MagiCarbon** [comment]
@antenore hi, thanks for ur reply.
i've checked and libsecret get installed.

BTW, My Arch Linux is a fresh installation.


what information do u need? let me know.

**Comment by pandidan** [comment]
Hi there,
I've the same issue on my Ubuntu 15.10 and libsecret-1-0 was already installed. I can save RDP passwords without any problem but It's not the same about SSH passowrds. "Save SSH password" is grayed out, Any ideas?
Thanks

**Comment by MagiCarbon** [comment]
@pandidan hi, i've tried tons of Linux Distributions in my VMware. but all not working :(

**Comment by guustflater** [comment]
Same here. 
Ubuntu 14.04 & Remmina v. 1.2.0-rcgit.8 installed from ppa:remmina-ppa-team/remmina-next

**Comment by fevangelou** [comment]
Likewise, on Ubuntu 16.04.

**Comment by antenore** [comment]
I'll fix this asap.

**Comment by antenore** [comment]
:-) this has never been implemented 

In the old code, in the master branch, https://github.com/FreeRDP/Remmina/blob/master/remmina/src/remmina_ssh.c#L343 the "Save SSH password" field is at FALSE.

Unlucky it's not enough to make it TRUE, to save the passwords, but it's good starting point.

I continue my experiments and I'll let you know.

**Comment by MagiCarbon** [comment]
@antenore  maaaaaaaaany thanks !!

**Comment by giox069** [comment]
I agree with antenore: it never worked. But I will be very happy to see my password saved in my gnome keyring. I'm marking this as "newfeature".

**Comment by pandidan** [comment]
antenore This is great. Looking forward to that!

**Comment by TamiasSibiricus** [comment]
Is it any chance to see merge from branch issue-708_save-ssh-password to next soon? And update in PPA of course. Thanks.

**Comment by skewty** [comment]
I am running remmina-next from ubuntu ppa and this is still not fixed.

I'd prefer not to save any remmina passwords in gnome keyring or save all of them in gnome keyring.  Having them spread between the two as is currently implemented is not ideal.

**Comment by antenore** [comment]
@TamiasSibiricus I'm very far to have a solution, the logic behind the ssh plugin is quite ****complex. I'm thinking to another solution but I need a feedback for an other issue around ssh.

@skewty your point is much more large and it deserve its own issue, can you open a new one please?

For both I need much more time, sorry :-\ I'm extremely busy lately, but I won't forget.

**Comment by zeronug** [comment]
I love using this software on Fedora... the saving of the passwords is the only downside.  Too bad you can't integrate keepass somehow.  I know PhpStorm uses KeePass to store passwords for the programs.

**Comment by justinnichols** [comment]
Any update on this?  I'm looking to convert from using PAC Manager to Remmina because Remmina just seems to function better in my opinion (in various ways).  I'd love to be able to save an SSH password and it's still greyed out (version: remmina 1.2.0-rcgit-18~snap1 ).

**Comment by antenore** [comment]
I was working on this but I didn't have the time to continue.
It's not an easy task because the SSH code is mixed up between the core and the plugin, so I was trying to rewrite completely the plugin, to also add other features.

I've tried to just implement a quick fix but I don't see how I can do it (the same reason why others have failed before me)

My best enemy it's the lack of time, having some support I could help out guiding someone to fix this, otherwise you have to be patient till I'll get some free time.

I'm adding the tag "help wanted", just in case...

**Comment by justinnichols** [comment]
Roger that.  Thanks for all your efforts.  If I find time I may look at it myself, but I suspect you all have dug into this in great detail that my looking at it would probably come to the same conclusion (not to mention I'm not a C programmer exactly).

Much appreciated!

**Comment by antenore** [comment]
> (not to mention I'm not a C programmer exactly) 
I'm not either ;-) 
Thank you.

**Comment by antenore** [comment]
I've just fixed this and will be soon merged in next. Hopefully in a couple of weeks we will publish a new Remmina release.

**Comment by TamiasSibiricus** [comment]
@antenore Thank you for your work on this issue!

**Comment by Hypocritus** [comment]
@antenore 

Thank you so much!! You did it!!
