### ISSUE TITLE
crashing when switch to window other program or just minimize the window

### ISSUE THREAD

**Issue by LetArch** [FreeRDP/Remmina#709]
OS: 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
arch i686

version remmina:
1.2-ppa1+8 i386

/var/log/syslog:
[ 2258.424338] remmina[3209]: segfault at ff212121 ip b6a6e896 sp 992f70a8 error 5 in libc-2.19.so[b69ea000+1a8000]

~/.config/remmina/remmina.pref
[remmina_pref]
secret=sssssssssssssssssssssecret
save_view_mode=true
save_when_connect=true
invisible_toolbar=false
floating_toolbar_placement=0
toolbar_placement=3
always_show_tab=true
hide_connection_toolbar=false
default_action=0
scale_quality=3
ssh_loglevel=1
ssh_parseconfig=true
hide_toolbar=false
hide_statusbar=false
show_quick_search=false
hide_quick_connect=false
small_toolbutton=false
view_file_mode=0
resolutions=640x480,800x600,1024x768,1152x864,1280x960,1400x1050
keystrokes=Send hello world§hello world\n
main_width=700
main_height=400
main_maximize=false
main_sort_column_id=1
main_sort_order=0
expanded_group=
toolbar_pin_down=false
sshtunnel_port=4732
applet_new_ontop=false
applet_hide_count=false
applet_enable_avahi=false
disable_tray_icon=true
recent_maximum=10
default_mode=0
tab_mode=0
show_buttons_icons=0
show_menu_icons=0
auto_scroll_step=10
hostkey=0
shortcutkey_fullscreen=0
shortcutkey_autofit=0
shortcutkey_nexttab=0
shortcutkey_prevtab=0
shortcutkey_scale=0
shortcutkey_grab=0
shortcutkey_minimize=0
shortcutkey_disconnect=0
shortcutkey_toolbar=0
vte_font=
vte_allow_bold_text=true
vte_lines=512
vte_system_colors=false
vte_foreground_color=rgb(192,192,192)
vte_background_color=rgb(0,0,0)
rdp_use_client_keymap=1
rdp_quality_0=6F
rdp_quality_1=7
rdp_quality_2=1
rdp_quality_9=80
##

**Comment by ic3d** [comment]
Hi @LetArch we're reviewing old issues, do yuo still get this one? We only support Remmina 1.2.* Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably only affects an old version of Remmina.
