### ISSUE TITLE
Constantly and often breaks the connection. It started about 1-2 months ago.

### ISSUE THREAD

**Issue by bw1945** [FreeRDP/Remmina#710]
Remmina
1.2.0-rcgit.7

cat /proc/version

Linux version 3.13.0-48-generic (buildd@orlo) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015

cat /etc/*-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

/home/bw/.remmina/1414078374255.remmina

[remmina]
disableclipboard=0
ssh_auth=0
clientname=
quality=0
ssh_charset=
ssh_privatekey=
console=0
resolution=1400x1050
group=Kran
password=cKJdkjwF5I9wFA9peuXZTQ==
name=1C
ssh_loopback=0
shareprinter=0
ssh_username=
ssh_server=
security=
protocol=RDP
execpath=
sound=off
exec=
ssh_enabled=0
username=bvv@zemz.net
sharefolder=/media/bw/Data/BVV/Работа/ФОП/Кран/Timochin/Разработки
domain=zemz.net
server=10.95.16.18:3389
colordepth=8
window_maximize=0
window_height=1099
viewmode=4
window_width=1480
scale=1
keyboard_grab=0
cert_ignore=0
loadbalanceinfo=
gateway_server=
disablepasswordstoring=0
sharesmartcard=0
gateway_usage=0
precommand=
scaler_expand=1

**Comment by giox069** [comment]
Could you also provide:
 1. The libfreerdp version you are using
 2. How did you get remmina (Ubuntu PPA ? Compiled by hand ?)
 3. The operating system running on the destination server. I noticed some disconnections when connected to XP and 2003 only on my pc, nothing more.

**Comment by bw1945** [comment]
1. /usr/share/doc/libfreerdp1/changelog.Debian.gz:
freerdp (1.2.0~git20150207+dfsg-0trusty2) trusty; urgency=medium

  * libfreerdp1 depends on libfreerdp-plugins-standard.

 -- Luca Falavigna <dktrkranz@debian.org>  Sun, 15 Mar 2015 10:17:29 +0100
...

2, I do not remember, but it is automatically updated.

3. MS Windows Server 2003 R2 Standard x64 Edition Service Pack 2


BUT: I repeat that the problem appeared 1-2 months ago, before that the
connection has been quite stable.

Thank you for attention!

2015-12-28 15:48 GMT+02:00 Giovanni Panozzo <notifications@github.com>:

**Comment by bw1945** [comment]
Unfortunately, yesterday's update did not help.
Thank you.

2015-12-28 16:22 GMT+02:00 Валентин Бочаров <bw1945@gmail.com>:

**Comment by bw1945** [comment]
There were two updates. Today, little has worked. Good!
Thank you so much!

2016-01-06 13:04 GMT+02:00 Валентин Бочаров <bw1945@gmail.com>:

**Comment by bw1945** [comment]
Unfortunately, I hastened to rejoice. Today again the same story. All I
apply updates in a timely manner.
Thank you

2016-01-11 16:17 GMT+02:00 Валентин Бочаров <bw1945@gmail.com>:

**Comment by giox069** [comment]
@bw1945: I'm moving this discussion to issue #723
