### ISSUE TITLE
Domain/Username/Password database

### ISSUE THREAD

**Issue by AsmGuy** [FreeRDP/Remmina#711]
Hello folks,

I happen to support a very large quantity of Windows servers belonging to several domains.
When I need to change a password for a certain domain, I have to update dozens of server definitions.

It would really help if you manage the Domain/Username/Password like "Resolution", ie: you define it somewhere else, and then you can use the same credentials in any number of servers as you want.
Also this would drastically reduce the credentials stored in Gnome Keyring.

Kind regards,
AsmGuy
##

**Comment by evilhamsterman** [comment]
This sounds like the same idea as #660

**Comment by AsmGuy** [comment]
Yes, you're totally right: it's the same thing.
