### ISSUE TITLE
VNC over SSH tunnel very slow

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [FreeRDP/Remmina#713]
remmina 1.1.2-ppa1+809+next+201512281759~ubuntu15.10.1

from Ubuntu 15.10 to tigervnc-server on RHEL 7.2, LAN connection
Uncheck enable SSH tunnel, it runs flawlessly. With enable SSH tunnel checked, I can notice a 5 to 20s delay for any action in the VNC session making it unusable.
##

**Comment by antenore** [comment]
Closed by #1196
