### ISSUE TITLE
Screen Resolution over LAN using Remmina

### ISSUE THREAD

**Issue by obtim** [FreeRDP/Remmina#715]
In the program there is no ability to scale the remote screen. Other VNC client have such opportunity. This creates difficulties at work with the programm.
##

**Comment by giox069** [comment]
Which version of remmina are you using ? Under which operating system/distribution ?

**Comment by obtim** [comment]
Tried 1.1.2 and now last 1.2.0 from git. Use Ubuntu 15.10 with Mate 1.10.2. Other side is Win 7 X64 with UltraVNC server 1.1.6

**Comment by giox069** [comment]
In every remmina connection window there is an icon to enable/disable scaling
![selezione_232](https://cloud.githubusercontent.com/assets/5477803/12120817/bc96d280-b3d2-11e5-8446-d1fdd3a8a100.png)
is it enough ?
If not, could you post a screenshot to explain better your problem ?

**Comment by Mad-Onion** [comment]
I would love to have Remmina open the connection in the correct resolution to fit the tabbed main-window. This way you can use the tabbed view and wouldn't have to scale down anything.

I hope it is clear what I mean ;-)

**Comment by giox069** [comment]
@Mad-Onion: I think this is a pending request in issue #6.
@obtim: have you solved your problem using the remmina scaler icon ?

**Comment by ic3d** [comment]
Hi @obtim we're reviewing old issues, do yuo still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably only affects an old version of Remmina.
