### ISSUE TITLE
Suddenly fails to RDP to any server 

### ISSUE THREAD

**Issue by madchap** [FreeRDP/Remmina#717]
Hi all,

I've been running Remmina for months, and all of a sudden today, I can't RDP to any of my Windows Servers. I even had a session running when that happened. No updates on the servers themselves (for too long actually ;-))

I am running on Linux Mint 17.3., and have just installed the PPA next repo, and upgraded to the latest 'next' version. I upgraded because the stable version of the ubuntu/mint repo failed before, and I thought the update would help me.

➜  ~  dpkg -l |grep -i remmina
ii  remmina                                                     1.1.2-ppa1+813+next+201601042336~ubuntu14.04.1      amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                              1.1.2-ppa1+813+next+201601042336~ubuntu14.04.1      all          common files for remmina remote desktop client
ii  remmina-plugin-rdp                                          1.1.2-ppa1+813+next+201601042336~ubuntu14.04.1      amd64        RDP plugin for remmina remote desktop client

FreeRDP libs
ii  freerdp-x11                                                 1.2.0~git20150207+dfsg-0trusty2                     amd64        RDP client for Windows Terminal Services
ii  libfreerdp-plugins-standard:amd64                           1.2.0~git20150207+dfsg-0trusty2                     amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp1:amd64                                           1.2.0~git20150207+dfsg-0trusty2                     amd64        RDP client for Windows Terminal Services (library)
ii  libpam-freerdp                                              1.0.1+13.10.20130724-0ubuntu1                       amd64        PAM Module to auth against an RDP server using FreeRDP

[16:11:03:977] [4497:213464832] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core] - credssp_recv() error: -1
[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x20009
[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core.transport] - Authentication failure, check credentials.If credentials are valid, the NTLMSSP implementation may be to blame.
[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

Of course, it truly impacts me in my work :-/

Thanks for your feedback and help.
Best,
fred

**Comment by giox069** [comment]
It seems it's a gnome keystore backend, read the last antenore post on issue #679
The workaround is... re-input all your passwords.

**Comment by madchap** [comment]
Well, it started failing before I do any kind of upgrade. As a matter of fact, I just upgrade to Mint 17.3 30mn ago, to see if that would help as well.

If the fact of simply retyping the password in remmina should fix it, then it is not the problem, same issue. Sorry, but thanks for the super quick response!

I will continue investigating at this very moment, as I need to get it working to get work done...

Cheers,
fred

**Comment by madchap** [comment]
I have just removed entirely the .remmina folder, so now empty of any saved connections I had and performed a quick connect thus re-entering all info. Same issue.

**Comment by giox069** [comment]
Does remmina ask you to enter password when connecting for a second time to the same server ? It should ask it again after the 1st failed authentication.
Also please keep looking at the terminal window output: freerdp_set_last_error 0x20009 means that authentication failed.
`[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x20009
[16:11:09:736] [4497:213464832] [ERROR][com.freerdp.core.transport] - Authentication failure, check credentials.If credentials are valid, the NTLMSSP implementation may be to blame.`

**Comment by madchap** [comment]
OK.. I feel stupid.

I don't know what happened today, but I just asked a colleague to reset my password to the same password I had, and I could connect.

Jeez, I am so sorry about that.

Thanks a lot for your quick response though. That rocked :-)

**Comment by giox069** [comment]
:+1: :)
