### ISSUE TITLE
openpty(3) support for Remmina

### ISSUE THREAD

**Issue by mpieuchot** [FreeRDP/Remmina#73]
The patch linked [0] allows the ssh and ssh-based plugins to be enable on platforms like OpenBSD that support openpty(3) but not the Unix98 PTY function family to allocate a pseudo-tty. It is based on a similar diff included [1] in the last vte release. We are already using this diff in our OpenBSD package of Remmina.

Would it be possible to include it in remmina? Don't hesitate to ask if I missed something.

Martin

[0] http://mamao.nolizard.org/0001-Support-allocating-PTYs-through-openpty-on-BSD.patch
[1] https://mail.gnome.org/archives/commits-list/2012-March/msg03376.html

**Comment by antenore** [comment]
@mpieuchot 
Is it too late to ask your support? The first link is not available anymore.

We have implemented tons of new features and fixed tons of bugs and we would love to have Remmina working also on OpenBSD

**Comment by ajacoutot** [comment]
Actually we do not need this patch anymore. OpenBSD has support for grantpt, ptsname, unlockpt... now.

**Comment by antenore** [comment]
Thanks @ajacoutot , if you want to see any OpenBSD patch included in the Remmina development branch, just let me know, I'll be happy to support you.

**Comment by ajacoutot** [comment]
Thank you. I'll have a look whether there's anything we use locally and open a pull request if anything warrants it.
