### ISSUE TITLE
Unable to Control-drag inside OSX

### ISSUE THREAD

**Issue by vadi2** [FreeRDP/Remmina#745]
I'm connected to OSX remotely and I'm unable to Control-drag inside it - Control does not seem to be recognised.

**Comment by vadi2** [comment]
Using the built-in Keyboard Viewer, I see that Control is recognised when I press it - however Control-drag still does not work, using 1.2.0-rcgit.8.

Does anyone else have the same issue?

**Comment by antenore** [comment]
Looks like is a known issues with most of the VNC server implementations (you are connecting through VNC, right?) that don't translate correctly to XCode, even if you see from the keyboard viewer that the ctrl has been  pressed.

I'm investigating on libvnc (what we use in remmina), to see if there is a workaround, but I doubt it's something we can fix in Remmina.

**Comment by vadi2** [comment]
It's RDP actually - but I've tested it using the Remote viewer in Windows, and it had the same problem. So I think Reminna is OK here actually!
