### ISSUE TITLE
Feature Request: After Command (opposite to precommand)

### ISSUE THREAD

**Issue by virtkit** [FreeRDP/Remmina#746]
I like to be able to execute a command after terminating a connection. Like the "pre command" before a connection is established I would like to execute a script after the connection is terminated/disconnected. Is that duable?
Cheers
Dan

**Comment by antenore** [comment]
I've just implemented it in another branch https://github.com/FreeRDP/Remmina/tree/postcommands

I took advantage of it to clean a bit the code, so we need to test it before to merge it.

Can you please test it? For any troubles let us know.

In the next says I'll try also to fix some minor issues.

**Comment by virtkit** [comment]
I am pretty new hear, how can I test it? Just downloading the newest version or what I am supposed to do?
Cheers Dan

**Comment by antenore** [comment]
Depending on your Linux distribution, you follow

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10

or

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20

You have only to adapt the git url to use from https://github.com/FreeRDP/Remmina.git -b next to

```
https://github.com/FreeRDP/Remmina.git -b postcommands
```

**Comment by antenore** [comment]
Implemented
