### ISSUE TITLE
RDP Plugin Not Found

### ISSUE THREAD

**Issue by a-war-of-gifts** [FreeRDP/Remmina#751]
Hey guys,

I followed the guide for compiling remmina on 14.04 and when I try to run remmina from command line, it gives me the following error:

```
Failed to load plugin: /opt/remmina_devel/remmina/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so.
Error: libfreerdp.so.2: cannot open shared object file: No such file or directory

```

I saw a similar problem where updating and upgrading fixed the issue, but it didn't work for me. I checked and the `libfreerdp.so.2` file in question most definitely exists in opt/remmina/devel/freerdp/.../, and I'm at a loss for how to fix it. Is anyone else experiencing this issue? Is there a way to make the plugin aware of the missing file?

If there are any questions, please ask. I appreciate your time.
##

**Comment by giox069** [comment]
Check step#7 of the guide: the path `/opt/remmina_devel/freerdp/lib` may be wrong, because it changed with newer versions of freerdp. You should change it with the direchtory where libfreerdp*.so files are located.

**Comment by a-war-of-gifts** [comment]
Thanks for the response!
`/opt/remmina_devel/freerdp/lib` is correct. I the directory in changed step 7 to `/opt/remmina_devel/freerdp/lib/x86_64-linux-gnu/` just to be sure, but I still got the same error.

**Comment by a-war-of-gifts** [comment]
Glox, Thanks for your assistance. Your suggestion about changing step 7 ended up being correct after all. I ended up removing everything I had compiled previously, and starting over from the beginning. However, I changed the path in step 7 to `/opt/remmina_devel/freerdp/lib/x86_64-linux-gnu/`and continued with the rest of the steps, and it worked. 

If you've already completed the guide and try to go back and change the path like I tried he first time, it won't work. You have to uninstall everything and start over, using the correct path, for it to work.

I very much appreciate your time and knowledge! TYSM.

**Comment by YoungJuleke** [comment]
> If you've already completed the guide and try to go back and change the path like I tried he first time, it won't work. You have to uninstall everything and start over, using the correct path, for it to work.

Finally, this is what got RDP working for me (thanks @a-war-of-gifts)!

Perhaps the guide needs updating, as others may be hit by the same problem...

**Comment by ic3d** [comment]
Guide updated, closing this issue.
