### ISSUE TITLE
NumLock in RDP sessions

### ISSUE THREAD

**Issue by mahescho** [FreeRDP/Remmina#758]
For me for all versions up to 1.1.2-ppa1+850 NumLock state is not propagated to Windows 2012 servers in RDP sessions. I've NumLock always on. when I type, numbers get typed. When I open a RDP session NumLock is off in this session but outside (any other Linux application) it is still on. I've to press NumLock one time in the RDP session to make it work there but then it is disabled outside of the RDP session for all the other Linux applications. When I use "rdesktop" this problem does not exist.

**Comment by antenore** [comment]
Be sure you have selected the option "grab all keyboard events" in the Remmina toolbar


![remmina_toolbar](https://cloud.githubusercontent.com/assets/5975/12784553/17cce4b6-ca88-11e5-8cb8-12f5a64ff81c.png)

**Comment by mahescho** [comment]
Thanks, but this makes no difference.

**Comment by weberhofer** [comment]
This never worked for me with older versions of remmina. For me, it started working with 1.2.x versions.

**Comment by giox069** [comment]
@weberhofer: there is a versioning problem on the "remmina-next" PPA: packages files name are "1.1.2*", but Remmina is really 1.2.X.
So, @mahescho, could you please check the real remmina vesrion using one of the following

- Menu Help -> About
- from the commandline, type `remmina --version`

Thank you

**Comment by mahescho** [comment]
gui shows: 0.9.99.1
dpkg reports 1.1.2-ppa1+850+next
I use "ppa:remmina-ppa-team/remmina-next"

**Comment by giox069** [comment]
Ok, for some unknow reason, you are running the old version of remmina included with Ubuntu 14.04, and not the one in the remmina-ppa (1.2.0-rcgit8). Really I don't know why. Have you rebooted your PC at least one time after adding the PPA ? Try to uninstall all remmina packages and then reinstall them.

**Comment by mahescho** [comment]
My fault, sorry for the noise ...

While I updated to the ppa version the wrong instance of remmina was still active in system tray. I failed to notice this. Now with 1.2 every thing works as expected. Thanks for the help and again sorry for the noise.

**Comment by giox069** [comment]
:+1:

**Comment by lavdnone** [comment]
Same s..t on Remmina - Version 1.2.0-rcgit-24 (git rcgit-24)
never ending Num Lock issue

```
dpkg -l | grep remmina
ii  libfreerdp-client2:amd64                                         2.0.0~git201710191115-0+remmina201710192147.r86bb1e0.d29dd283~ubuntu17.10.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp2:amd64                                                2.0.0~git201710191115-0+remmina201710192147.r86bb1e0.d29dd283~ubuntu17.10.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libwinpr2:amd64                                                  2.0.0~git201710191115-0+remmina201710192147.r86bb1e0.d29dd283~ubuntu17.10.1 amd64        Windows Portable Runtime library
ii  remmina                                                          1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                                   1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        all          common files for remmina remote desktop client
ii  remmina-dbg                                                      1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        remote desktop client - debug pakcage
ii  remmina-plugin-gnome                                             1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        GNOME plugin for remmina remote desktop client
ii  remmina-plugin-nx                                                1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                                               1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-spice                                             1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        Spice plugin for remmina remote desktop client
ii  remmina-plugin-telepathy                                         1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        Telepathy plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                               1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        VNC plugin for remmina remote desktop client
ii  remmina-plugin-xdmcp                                             1.2.0-rcgit-24-0~remmina201710252018.r73bfd1e.ddd444db~ubuntu17.10.1        amd64        XDMCP plugin for remmina remote desktop client
```

```
sudo killall remmina
sudo apt-get purge remmina* -y
rm -Rf /home/`whoami`/.remmina/remmina.pref

sudo add-apt-repository ppa:remmina-ppa-team/remmina-master
sudo apt-get update

sudo apt-get install remmina* -y

```

year 2017 wtf
