### ISSUE TITLE
SSH cursor and scrolling / display issues

### ISSUE THREAD

**Issue by danboid** [FreeRDP/Remmina#760]
I am running remmina 1.2.0rcgit.8 under Arch Linux / MATE.

When I resize the remmina SSH terminal window above a certain horizonal width,  the cursor disappears under apps such as less and vim and there are redraw issues when you scroll up and down if there is more text than can be displayed vertically in the terminal. It can be fixed by making the remmina SSH window narrower.

I'm not sure exactly how wide in characters or pixels the terminal needs to be for this bug to occur but it always heppens when I make the SSH window full-screen on one of my FullHD (1920x1080) displays. terminator and other xterms don't have this issue when I SSH into the same machines, make it full screen and then scroll in less/vi etc.

**Comment by antenore** [comment]
I cannot reproduce it or I didn't get how it happens.

Is it too much if I ask you to create an animated gif and upload it here? Or even a video on youtube/vimeo...

Thanks in advance

**Comment by danboid** [comment]
I was having this problem when running the Arch linux-4.4.1-2 kernel but I was experiencing severe system instability so I've reverted to linux-4.3.3-3 and not only is my overall system much more stable, I don't get the remmina SSH scrolling and disappearing cursor issues so I don't think this was a problem with remmina after all.

Sorry about that!

**Comment by giox069** [comment]
@danboid: I'm having similar problems on arch and video refresh in two different situations. Which graphics card/driver are you using ? I'm using an old NVIDIA Quadro NVS 160M and the nouveau driver.

**Comment by danboid** [comment]
Intel HD Graphics 2500

**Comment by giox069** [comment]
Thank you
