### ISSUE TITLE
Applet/Indicator Appearing Multiple Times

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#766]
In Ubuntu 16.04, running Remmina Next, the Applet/Indicator ( ![Remmina Indicator](http://neartalk.com/ss/2016-02-15_001_44x28.png) ) is appearing multiple times on the top-right panel by the clock, when it is suppose to appear only once. Over the course of a workday, I've seen it appear as many as 3 or 4 times.

Remmina's working great, so to me, this is a minor issue, but I thought I should let you guys know about it.
##

**Comment by giox069** [comment]
With remmina 1.2.0-rcgit8 from the PPA ?

**Comment by ic3d** [comment]
Hi @Lonniebiz  we're reviewing old open issues. Now, we only support Remmina 1.2.* branch. Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.
