### ISSUE TITLE
compile remmina not working

### ISSUE THREAD

**Issue by zuriy** [FreeRDP/Remmina#771]
At step 12 of compile:

> as@asbook:~/remmina_devel/Remmina$ make && sudo make install
> [ 33%] Built target remmina
> [ 86%] Built target remmina-translations
> [ 89%] Built target remmina-plugin-nx
> [ 90%] Built target remmina-plugin-xdmcp
> [ 91%] Building C object remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_event.c.o
> /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_event.c: In function ‘remmina_rdp_event_init’:
> /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_event.c:624:89: error: ‘WINPR_FD_READ’ undeclared (first use in this function)
>    rfi->event_handle = CreateFileDescriptorEvent(NULL, FALSE, FALSE, rfi->event_pipe[0], WINPR_FD_READ);
>                                                                                          ^
> /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_event.c:624:89: note: each undeclared identifier is reported only once for each function it appears in
> In file included from /opt/remmina_devel/freerdp/include/winpr/collections.h:31:0,
>                  from /opt/remmina_devel/freerdp/include/freerdp/types.h:80,
>                  from /opt/remmina_devel/freerdp/include/freerdp/freerdp.h:43,
>                  from /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.h:40,
>                  from /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_event.c:38:
> /opt/remmina_devel/freerdp/include/winpr/synch.h:351:35: error: too many arguments to function ‘CreateFileDescriptorEventA’
>  #define CreateFileDescriptorEvent CreateFileDescriptorEventA
>                                    ^
> /home/as/remmina_devel/Remmina/remmina-plugins/rdp/rdp_event.c:624:23: note: in expansion of macro ‘CreateFileDescriptorEvent’
>    rfi->event_handle = CreateFileDescriptorEvent(NULL, FALSE, FALSE, rfi->event_pipe[0], WINPR_FD_READ);
>                        ^
> /opt/remmina_devel/freerdp/include/winpr/synch.h:342:18: note: declared here
>  WINPR_API HANDLE CreateFileDescriptorEventA(LPSECURITY_ATTRIBUTES lpEventAttributes,
>                   ^
> remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build.make:77: recipe for target 'remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_event.c.o' failed
> make[2]: *** [remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_event.c.o] Error 1
> CMakeFiles/Makefile2:407: recipe for target 'remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/all' failed
> make[1]: *** [remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/all] Error 2
> Makefile:116: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by weberhofer** [comment]
@zuriy, do you have the latest version of freerdp installed?

**Comment by benkohler** [comment]
I'm pretty sure that this issue goes away if you use a more recent FreeRDP source, I'd suggest closing this issue if we can't get any more info from the original reporter

**Comment by larchunix** [comment]
@zuriy Ping.

**Comment by zuriy** [comment]
Sorry, but now i'm use 1.2.0-rcgit.11(git n/a) and all work fine.
