### ISSUE TITLE
Share some usage statistics dialog cannot be disabled!!!

### ISSUE THREAD

**Issue by reddot15** [FreeRDP/Remmina#772]
Do you agree to share some usage statistics with us?
By pressing the yes button, you're not yet sending any data.
**Do not show again check mark does not work on 1.2.0-rcgit.8 (git n/a).**
 selecting **NO** and checking do not ask again does not work, upon every launch on linux mint 17.2 mate and 17.3 mate dialog appears no matter what!!!

**Comment by giox069** [comment]
@reddot15 @antenore: I have just pushed a small fix. I hope it will work. If you are using the ubuntu's PPA, wait 1 day for automatic refresh of the PPA.

**Comment by reddot15** [comment]
ty giox069 works great, yes im using the ubuntu ppa just grabbed the update now. ty again!!!!

**Comment by giox069** [comment]
:+1:
