### ISSUE TITLE
Connection folders

### ISSUE THREAD

**Issue by danboid** [FreeRDP/Remmina#774]
It would be very handy to be able to create folders and sub-folders to organise connections/servers within the main remmina connections window.

**Comment by giox069** [comment]
"group membership" automatically organizes connection in 1 level subfolders if you enable View->Tree View. And in the systray menu (not available under Gnome Shell), all connections are grouped by group name.
Do you need more sublevels ?

**Comment by danboid** [comment]
I've seen the tree view and that does help with navigation but I think it would be nice to be able to have at least a couple of sub-levels / groups.

In my case I'd like to organise them by datacentre (top/first group), classification (UAT/production - second sublevel) and then OS being the final sub-level. Of course I'm not trying to enforce or recommend this structure or naming for remmina or others - as far a remmina is concerned it would be group 1, group 2 and group 3 etc.

**Comment by CS-JS** [comment]
Same here - would be nice to group e.g. servers an clients (level 1) to customers (level 2). Actually I got clients and servers mixed up when they are grouped by customers.

**Comment by antenore** [comment]
Out of curiosity how many profiles do you have? Did you submit the survey form? It's quite useful for us to understand our users needs.

I see the point of having a better structure in the remmina editor, but we are quite busy at trying to keep Remmina working (we do not work on Remmina for money but for pleasure and needs).

It would be awesome having some help from you @ALL guys with some patches and new features. 
After all is not so hard to start to code some lines of code a week. 

What about taking a look at https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_file_editor.c and try to add a new field (start with one). If you don't have programming experience, try with something as simple as possible.

I can help out in that case. 

I'll start to work on the remmina file editor in not less than some weeks.

**Comment by antenore** [comment]
I'm working on several improvements, including this one under the branch https://github.com/FreeRDP/Remmina/tree/remmina_main

**Comment by antenore** [comment]
Subgroups are already supported, it's enough to separate the group names with "**/**" (slash)

@danboid can you confirm it's what you were looking for?

**Comment by CS-JS** [comment]
@antenore Confirmed working for me, exactly what I was looking for! Thank you!

**Comment by antenore** [comment]
Thanks, I close the issue.
