### ISSUE TITLE
Gnome 3 freezes completely after a while when using Remmina 1.2 with keyboard grabbing enabled

### ISSUE THREAD

**Issue by svendsenrobin** [FreeRDP/Remmina#777]
Like the title indicates, when using keyboard grabbing in an RDP session, Remmina 1.2, Gnome 3 (GDM) freezes competely and becomes unusable. In order to be able to use the desktop again, the gdm service has to be restarted through another console. (Ctrl+Alt+F2).

When not using keyboard grabbing, when clicking on the RDP session when another window has focus, the right-click menu appears. In order to shift focus to the Remmina RDP session, one has to click on the actual session on the taskbar. Still, there are some glitches sometimes, that if one clicks the mouse where the Remmina startup window's located, below the RDP session, the startup window gets selected.

At least the famous, or infamous, NumLock bug from version 1.0 is solved.

Package name:
remmina-1.2.0-0.5.git.b3237e8.el7.nux.x86_64 (built by nux-dextop

Link to nux-dextop thread reporting the problem:
https://forums.nux.ro/index.php?t=msg&th=629&start=0&S=ac5fb9eeb71cf4488b64e0bfbf74fc6d

OS:
CentOS 7.2
##

**Comment by antenore** [comment]
Are you sure Remmina and FreeRDP are installed correctly with the right version?

Something around:

```sh
$ remmina --version 
Remmina - Version 1.2.0-rcgit.9 (git 379433f)
$ xfreerdp --version 
This is FreeRDP version 2.0.0-dev (git 52f1e6b)
```

Remmina must be linked to the newest possible version of FreeRDP

Make sure you have only one version of FreeRDP and Remmina installed

```sh
rpm -qa | grep -i remmina
```

**Comment by svendsenrobin** [comment]
I see. The version installed on my system is:
$ xfreerdp --version
This is FreeRDP version 1.2.0-beta1 (git n/a)

The version of Remmina I'm running is 1.2.0-rcgit.3

So there's an explanation. I'm not compiling for myself, but using the
nux-dextop repository. I'll forward this information to the maintainer. In
order to use Remmina on a CentOS system one has to use the nux-dextop
repository. EPEL doesn't provide Remmina anymore, and I need Remmina for
working purposes.

**Comment by antenore** [comment]
@svendsenrobin cool! Thanks, this is a really appreciated.

We can keep this opened till you'll have an answer.

**Comment by ic3d** [comment]
Hi @svendsenrobin we're reviewing old open issues. Now, we only support Remmina 1.2.* branch. Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.
