### ISSUE TITLE
Is remmina between Ubuntu and Windows 10 secure?

### ISSUE THREAD

**Issue by mayuso** [FreeRDP/Remmina#782]
Sorry for this question, it is not really an issue, but I have tried e-mail and did not get any answer in like a week. (Also, sorry for my english).

Is remmina between Ubuntu and Windows 10 secure?

I have never used any RD client so I am not sure if this question makes sense or not. If it is, perfect, silly question, if it is NOT, how can I improve security?

Thank you, and sorry. I will close this "issue" as soon as possible.

**Comment by giox069** [comment]
We are not security expert to analyze all implications of security. It depends on what you mean with "secure".
I can only tell you that remmina uses FreeRDP to connect to windows, and by default the connection channel si encrypted using TLS (SSL), provided that you are using "Negotiate, TLS or NLA" in profile security settings. You can force windows at the server side to accept only RDP client with encrypted connection.
But... my above comment only analyzes the communication channel. Nothing can be said if someone placed an hardware keylogger on your client pc to steal your passwords or a webcam behind your shoulders.

**Comment by mayuso** [comment]
Please, correct me if I am mistaken; I need to leave a port open on my Windows 10 machine if I want to access it via Remmina from my Ubuntu laptop, right? Isn´t that "dangerous"?

**Comment by giox069** [comment]
Yes, port 3389, but it's as dangerous as leaving any other port open for any other kind of service. Which means: if it's in your home lan there are usually no problems. If it's on the Internet, keep your windows updated with the latest patches, use complex passwords for all windows users, disable the "Administrator" account and if possible don't expose port 3389 but use a much higher port number.

**Comment by mayuso** [comment]
Seems hard. I might try later today, although I don´t expect me to be capable of making this work haha. Thank you :)

**Comment by weberhofer** [comment]
I'd not recommend to have an open RDP server for direct access via the internet. I'd only make it accessible via a VPN.
A very interesting article can be found here: https://community.rapid7.com/community/infosec/blog/2016/03/01/the-attackers-dictionary

**Comment by mayuso** [comment]
The thing is I do not need it on lan, it is for personal use, and I don´t have a 200km house.  Now VPNs, this is getting harder and harder every second.
