### ISSUE TITLE
VNC connections terminate immediately 

### ISSUE THREAD

**Issue by vext01** [FreeRDP/Remmina#784]
Hi,

I was looking for a nicer VNC client than SSVNC and found remmina.

On version 1.1.1 and 1.1.2 I can connect to my VNC server (which is a remote virtualbox instance) over an SSH tunnel. The viewer window appears, but immediately closes. Sometimes it stays open long enough to see the screensaver on the remote machine.

Remmina is not _crashing_ per-se (the host list remains once the viewer window closes). No clues are emitted on the terminal.

This is OpenBSD-current/amd64 with XFCE4.

Cheers
##

**Comment by vext01** [comment]
It seems that changing the colour settings from 256 colours to 16-bit works around this. Perhaps virtualbox doesn't support that colour mode?

**Comment by pommetjehorlepiep** [comment]
I ran into the same issue with version 1.1.0 running on Debian Jessie. 
(Version is 1.1.1-2 according to the package manager, but About shows 1.1.0....)

Changing the colour setting to something else than 256 colours did the trick for me as well.

**Comment by ic3d** [comment]
Hi @vext01 @pommetjehorlepiep we're reviewing old issues, do yuo still get this one? We only support Remmina 1.2.* Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.
