### ISSUE TITLE
Don't close connection windows when main window is closed

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/Remmina#785]
This is a follow-up ticket to #744.
##

**Comment by linuxturtle** [comment]
IMO, this is a regression bug, not an enhancement request.  There is no way to close the main window once you've opened it without exiting remmina completely.

**Comment by gbolo** [comment]
This should be fixed

**Comment by weberhofer** [comment]
This issue has been fixed, I think in rcgit20. Thanks!
