### ISSUE TITLE
RDP Connection fails, but only the first time

### ISSUE THREAD

**Issue by nicocrm** [FreeRDP/Remmina#789]
When I first launch Remmina, RDP connections fail with the following errors:

[05:48:23:138] [14773:15421] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[05:48:27:520] [14773:15421] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[05:48:27:520] [14773:15421] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

However, if I kill and relaunch Remmina, it works fine.

Connecting directly via xfreerdp works fine also.  I have tried with and without network level authentication enabled and it didn't seem to make a difference.  If I close X and restart it, then I get the error again, but after restarting Remmina, as long as I stay within the same X session it works.  Weird!  Rdesktop connections work fine by the way, so I have switched to using rdesktop for now, the only problem with it is it does not seem to support network level authentication so there are a couple servers I can't connect to with it.

This is using 1.2.0-rcgit.8 and freerdp 1.2.0_20160107-6

**Comment by nicocrm** [comment]
I used xfreerdp for a while because of this issue but just tried today and it works fine - not sure if an update fixed it, or if something else was off!  Either way - thanks, I love the app!

**Comment by antenore** [comment]
Thanks, sorry I missed this issue.
Please come back in case of other problems.
