### ISSUE TITLE
Can't hear remote audio (local)

### ISSUE THREAD

**Issue by sabbia001** [FreeRDP/Remmina#790]
Hi,

I'm using Remmina on Ubuntu 15.10.
I can't hear sound of the remote pc (RDP connection to a Windows 10 pc). Using rdesktop audio is ok.
I've tried all possible configurations (local audio, all quality levels).
I've noticed that remmina audio is not shown in pulseaudio (or unity) volume control (applications tab).

I have installed these packages:

ii  remmina                                       1.1.2-2ubuntu3                             amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                1.1.2-2ubuntu3                             all          common files for remmina remote desktop client
ii  remmina-plugin-rdp                            1.1.2-2ubuntu3                             amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc                            1.1.2-2ubuntu3                             amd64        VNC plugin for remmina remote desktop client

Thanks

**Comment by sabbia001** [comment]
Hi,

I don'k know it this could be useful. I have the same problem using xfreerdp, and I get this messages:

LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-pulse.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-alsa.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-macaudio.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-winmm.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
Warning rdpsnd_process_connect (690): no sound device.

So I did this:
sudo cp librdpsnd-client-alsa.so rdpsnd-client-alsa.so
sudo cp librdpsnd-client-pulse.so rdpsnd-client-pulse.so

Now I can hear audio via xfreerdp.

Thank you very much for your great software!

**Comment by sabbia001** [comment]
Sorry, now it's working, I don't know why.
I made a radical uninstallation of everything around remmina and freerdp (stable and unstable packages I had tried to install). Then I reinstalled remmina stable and now it's working perfectly.

**Comment by antenore** [comment]
You probably had some old freerdp library... that happens also to me :-P
