### ISSUE TITLE
Quick Find cleanups

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#791]
1. The label at the left of Quick Find text field, on the toolbar, is "Quick_Find" with an underscore inside. The underscore should be removed and text localized.
2. After an "add" or "duplicate" operation in the remmina profile editor, the Quick Find field should be blanked, so the full list will be redisplayed. Or users will add and readd profiles because they don't appear.

**Comment by antenore** [comment]
Gio, where you planning to solve it yourself?

Do we profit of this to fix some translations?

**Comment by antenore** [comment]
1. Quick Find label is fixed 
2. Translations is something we have to fix at a higher level. We have some issues a PR opened and several strings not translated.
2. Quick Find clean

I fixed this adding in the remmina_main_on_action_connections_new function

```C
remmina_main_load_files(TRUE);
```

I'm going to PR and merge it in next.
