### ISSUE TITLE
Remmina crash on having files or images in clipboard

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#792]
I have reproduceable crashes of current remmina 1.2.0-rcgit.9, if i copy a file or image. Kubuntu 16.04.
GDB backtrace is available at http://pastebin.com/jceCGgkR

Fell free to post here if I can provide further information.

**Comment by giox069** [comment]
Are you using remmina on the PPA or did you compiled it by yourself ?

**Comment by giox069** [comment]
It happened to me also, 1 hour ago. Small fix pushed now.

**Comment by CS-JS** [comment]
Thanks for the quick fix, seems fine after I tried the new build right now. I'll keep testing over the workday :)
