### ISSUE TITLE
[1.2.0-rcgit.9] Unable to Compile in Centos 7

### ISSUE THREAD

**Issue by mnlandicho** [FreeRDP/Remmina#793]
I am following through the procedure to compile the “next” branch on my Centos 7. I get to compile Remmina 1.2.0-rcgit.8 but is receiving error with this particular update. Hope you can help me.

Command:
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/remmina -DCMAKE_PREFIX_PATH=/opt/remmina_devel/freerdp –build=build .

Error:
…
— Found GTK3: /usr/lib64/libgtk-3.so
— Finding suggested package ZLIB.
— Disable this using “-DWITH_ZLIB=OFF”.
— Found ZLIB: /usr/lib64/libz.so (found version “1.2.7”)
— Found LIBSECRET: /usr/include/libsecret-1;/usr/include/glib-2.0;/usr/lib64/glib-2.0/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WINPR_INCLUDE_DIR
used as include directory in directory /root/remmina-devel-rcgit9/Remmina/remmina-plugins/rdp

— Configuring incomplete, errors occurred!

Thanks!

I see the variable in this file FindFREERDP.cmake

...
find_path(WINPR_INCLUDE_DIR NAMES winpr/winpr.h
        HINTS ${PC_FREERDP_INCLUDEDIR} ${PC_FREERDP_INCLUDE_DIRS} ${CMAKE_PREFIX_PATH}/include/winpr1/)

find_library(FREERDP_LIBRARY NAMES freerdp
        HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})

find_library(FREERDP_CLIENT_LIBRARY NAMES freerdp-client
        HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})

find_library(FREERDP_WINPR_LIBRARY NAMES winpr
        HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(FREERDP DEFAULT_MSG FREERDP_LIBRARY FREERDP_INCLUDE_DIR)

set(FREERDP_LIBRARIES ${FREERDP_LIBRARY} ${FREERDP_CLIENT_LIBRARY} ${FREERDP_WINPR_LIBRARY} )
set(FREERDP_INCLUDE_DIRS ${FREERDP_INCLUDE_DIR} ${WINPR_INCLUDE_DIR})
...

**Comment by giox069** [comment]
Use `git pull` inside the Remmina subdir: I have just committed a fix for the winpr dir name, which changed from winpr1 to winpr2 in FreeRDP.

**Comment by mnlandicho** [comment]
Thanks! Now working! Successfully compiled version 1.2.0-rcgit.10!
