### ISSUE TITLE
1.2.0-rcgit.10 (git n/a) vnc connector not installed

### ISSUE THREAD

**Issue by pdnmusic** [FreeRDP/Remmina#794]
Good morning,

Yesterday 'remmina' was updated under a apt-get update/apt-get upgrade in my Ubuntu 14.04 x64.
So now, it shows current version is: 1.2.0-rcgit.10

When I try to connect to a VNC server computer of my list (90% is VNC, the rest is RDP) a message appears that show the text "VNC protocol connector is not installed" (more or less, I just literal translated as the message appears in my language).

Tried to install that connector with the command: sudo apt-get install remmina-plugin-vnc
System informs this software is still on its last version on my computer.
So, removed and reinstalled. The set-up ends OK but the connector is not present on Remmina.

FYI: The Remmina VNC Connector installed is 'remmina-plugin-vnc (1.1.2-ppa1+874+next+201603091832~ubuntu14.04.1)'

Thanks in advance.

![20160310_remmina_connectors](https://cloud.githubusercontent.com/assets/17780422/13698404/240e37bc-e774-11e5-9820-a9632247af24.png)

**Comment by giox069** [comment]
Hi @pdnmusic, thank you for reporting.
Are you able to start remmina from a terminal window and copy&paste the output of remmina startup here ? Problems in loading plugins are usually visible when launching remmina from a terminal window.
Also try to reboot the PC, and execute `sudo ldconfig`

**Comment by avoidik** [comment]
I had similar issue, maybe this is it,
https://github.com/FreeRDP/Remmina/issues/768

**Comment by pdnmusic** [comment]
> I had similar issue, maybe this is it,
> [#768 ](https://github.com/FreeRDP/Remmina/issues/768)

Thanks @avoidik , that's exactly the same case.
I did what you suggest on your issue and now it works back again.

**Comment by pdnmusic** [comment]
#768

**Comment by pdnmusic** [comment]
#768
