### ISSUE TITLE
Remmina Crashes

### ISSUE THREAD

**Issue by mnlandicho** [FreeRDP/Remmina#797]
I am experiencing very frequent crash of remmina. I am not able to click anything on it and I need to kill the process and start again to use it. I opened the debug window but even it crashed. 

I already reinstalled and recompiled remmina but still the problem persists.

I noticed that crashing of remmina happens when this specific log entry occured.

**Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.**

Here is the logs.
[~]$ remmina 

(remmina:13636): GLib-GIO-WARNING **: Ignoring invalid ignore_hosts value 'X.X.X.X:16311/ibm/console'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[15:20:04:369] [13636:13784] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[15:20:04:370] [13636:13784] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[15:20:04:370] [13636:13784] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:20:04:689] [13636:13787] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)
[15:20:09:943] [13636:13787] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: mnlandicho (type=8 id=1)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[15:20:10:736] [13636:13801] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[15:20:10:737] [13636:13801] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[15:20:10:737] [13636:13801] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:20:11:374] [13636:13804] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)
[15:20:12:102] [13636:13804] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: mnlandicho (type=8 id=1)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[15:20:19:996] [13636:13812] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[15:20:19:996] [13636:13812] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[15:20:19:996] [13636:13812] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:20:19:183] [13636:13815] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)
[15:20:20:998] [13636:13815] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: mnlandicho (type=8 id=1)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[15:20:35:161] [13636:13819] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkDrawingArea': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaProtocolWidget': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkViewport': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkScrolledWindow': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkNotebook': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `GtkGrid': invalid matrix (not invertible)

(remmina:13636): Gtk-WARNING **: drawing failure for widget `RemminaConnectionWindow': invalid matrix (not invertible)

**Comment by antenore** [comment]
Can you please provide OS, remmina and freerdp version?

Why do you have an IBM netcool console link in the remmina config? 

x.x.x.x:16311/ibm/console

If you work in IBM you can contact me on sametime so that we can have a chat about your issue.

**Comment by mnlandicho** [comment]
Hi,

I am running Centos 7 with the latest kernel 4.5. Here's my versions of remmina and freerdp.

[~]# remmina --version
Remmina - Version 1.2.0-rcgit.11 (git 73aa84a)
[~]# 
[~]# xfreerdp --version
This is FreeRDP version 2.0.0-dev (git 75ae3f5)

I do not work in IBM. I used to access that server before. I do not know why it shows up in the log file.

**Comment by antenore** [comment]
Ok, there is something weird then...

When you switch between the 0.9 to the 1.2 version be sure to remove completely the other version.

I've the feeling you have both version installed.

If you cannot solve, can you please provide a back trace with gdb? 

```sh
gdb remmina
run
...
bt
```

**Comment by mnlandicho** [comment]
I am sure I have completely removed the old version 0.9 whenever I switch to 1.2. I will feedback the back trace on my next post.

**Comment by antenore** [comment]
Can you do a back trace?

- Be sure both remmina and freerdp are compiled with "-DCMAKE_BUILD_TYPE=Debug"
- install `gdb`
- close all remmina windows
- start gdb from a terminal window: `gdb remmina`
- start remmina with `run`
- when remmina crashes, take a look at the terminal window, and copy & paste the detailed error here
- now type `bt`, this will tell gdb to produce a full backtrace. Copy & paste it here.
- quit gdb with `q`

This http://www.cprogramming.com/gdb.html is a quite good tutorial on using gdb.. As much information you can provide as easier will be to identify the bug.

Thanks a lot for your support

Just in case I cannot answer back till next Tuesday

**Comment by mnlandicho** [comment]
Hi Antenore,

Apologies for replying late. My Linux laptop has been experiencing a lot of problems lately. The problem I think is with the update to the latest kernel. I moved back down to kernel 4.4 from 4.5. reinstall my gnome desktop suite and also a fresh install of remmina. It all suddenly worked. I am closing this thread now. Sorry for the trouble.
