### ISSUE TITLE
\\tsclient shares list blank files and folders

### ISSUE THREAD

**Issue by mgruben** [FreeRDP/Remmina#799]
Hey there,

I've enabled a "Share" folder on my remmina connection.  This used to work [from Arch Linux, to Windows 7 x64 professional] without issue.
Currently running `remmina` 1:1.2.0rcgit.8-1 and `freerdp` 1:1.2.0_20160107-6

(1) The name of the shared folder ("Share") displays correctly on the remote desktop \\tsclient 
![tsclient share name](https://cloud.githubusercontent.com/assets/6686712/13834842/3aa24f72-ebc0-11e5-8b52-65269b6fbf2e.png)

(2) The shared folder contains 2 folders of blank name (".." and "."?), with proper time stamps [forgot to `import` this one]

(3) After `touch`ing two named files with known extensions [below], the \\tsclient share displays two files of blank name, with proper time stamps
```
[user@local Share]$ ls -alh
total 8.0K
drwxr-xr-x 2 user users 4.0K Mar 16 21:31 .
drwxr-xr-x 3 user users 4.0K Mar 16 21:31 ..
[user@local Share]$ touch nano.txt
[user@local Share]$ touch test.dwg
[user@local Share]$ ls -alh
total 8.0K
drwxr-xr-x 2 user users 4.0K Mar 16 21:35 .
drwxr-xr-x 3 user users 4.0K Mar 16 21:31 ..
-rw-r--r-- 1 user users    0 Mar 16 21:35 nano.txt
-rw-r--r-- 1 user users    0 Mar 16 21:35 test.dwg
```
![tsclient share contents](https://cloud.githubusercontent.com/assets/6686712/13834941/21a8c6d0-ebc1-11e5-9934-ffdb76551dad.png)

(4) After `rm -rfv` both touched files, the \\tsclient share displays only the two blank folders, the second of which ("."?) has an updated timestamp
![tsclient after delete](https://cloud.githubusercontent.com/assets/6686712/13834905/c0a08cba-ebc0-11e5-8f4d-5bcba2e31777.png)

edit: English errors

**Comment by antenore** [comment]
Would you mind testing it also with xfreerdp ? Which graphic card do you have?

Thanks in advance

**Comment by mgruben** [comment]
**Testing with `xfreerdp`**
Folder and files appeared to display correctly with xfreerdp:
`$ xfreerdp /drive:Share,/path/to/the/Share /v:localhost:9001 /u:WindowsUser /d:Domain`
The empty folder from above does not display phantom folders:
![xfreerdp 1](https://cloud.githubusercontent.com/assets/6686712/13909007/eeed27f4-eedb-11e5-845e-c98f5d7edad0.png)
`[user@linuxmachine Share]$ touch testfile.txt`
After refreshing in Windows, the folder correctly displays testfile.txt
![xfreerdp 2](https://cloud.githubusercontent.com/assets/6686712/13909019/0f41e6de-eedc-11e5-867f-2d13c601385e.png)

**Video Card**
`lspci` (snipped):
`01:05.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RS880M [Mobility Radeon HD 4225/4250]`
```
[user@linuxmachine ~]$ pacman -Qs radeon
local/opencl-mesa 11.1.2-1
    OpenCL support for AMD/ATI Radeon mesa drivers
local/radeontop 0.9-1
    Radeon cards monitoring utility
```

**Comment by mgruben** [comment]
This issue is mooted, as the files and folders have started displaying correctly again for me, despite still having
`remmina` 1:1.2.0rcgit.8-1
`freerdp` 1:1.2.0_20160107-6
`opencl-mesa` 11.1.2-1

This suggests that the issue was entirely outside of the `remmina` code base, but I appreciate your looking into it just the same :+1:
