### ISSUE TITLE
Japanese keyboard mapping

### ISSUE THREAD

**Issue by ehkuso** [FreeRDP/Remmina#805]
Using VNC, Remmina works properly Ubuntu-Japanese -> Windows 7-Japanese.

Using RDP, I have found no combination of Remmina settings that works properly.

When the Remmina client on the Ubuntu-Japanese machine is set to a Japanese keyboard, Remmina sends the wrong codes to the Windows 7-Japanese target.  Remmina appears to be sending US keyboard codes to the Windows 7-Japanese target.

**Comment by antenore** [comment]
We are looking at it.

**Comment by ehkuso** [comment]
Sorry, it was a false alarm.  I found a bad keyboard file on the Windows 7
machine.

EHK

**Comment by antenore** [comment]
I'm happy you solved it.

I'm going to close this issue, but we will open a new one, in the next days, because Remmina doesn't have a good input management. We should, at least, move to GDK.

Thanks for the report.
