### ISSUE TITLE
Shared clipboard with rdp

### ISSUE THREAD

**Issue by Neotric** [FreeRDP/Remmina#806]
Only recently I found out about remmina. Before that, I was stuck with rdp from win10, but win10 is not my favourite. So, I am happy working with Mint en remmina now, but I would like to have the option of a shared clipboard, so I can easily copy files from remote to local and vise versa. I could do that on the windows platform, not with remmina on Mint. My request is: shared clipboard, please.
##

**Comment by giox069** [comment]
The clipboard in remmina is working fine with text and images, if you are using the "remmina-next" PPA for Ubuntu and its derivateives, Mint included.
File copy operation is currently not implemented, but we are working on it.

**Comment by affinityv** [comment]
Linux Mint 18 -- Cinnamon (LiveDVD)

Copy and Paste is not working with Win7 desktop.
Also, sound doesn't work.

I thought that copy and paste worked.... perhaps once it did?

**Comment by ic3d** [comment]
I'm closing this issue, feel free to open it again if needed.
