### ISSUE TITLE
Vertical resolution of RDP host not being determined correctly

### ISSUE THREAD

**Issue by sirlark** [FreeRDP/Remmina#81]
If I connect to a host with a higher vertical resolution than my client machine is capable of, I get a scrollable window. I can scroll all the way across the host's horizontal display, but the vertical scroll dimensions are limited by my client's display resolution. This means I can't scroll down to see a task bar in a windows system for example. I'm using remmina 0.9.3 on Bodhi Linux 1.4 (a debian wheezy/sid spin). Let me know if you need any more info.

**Comment by Hubbitus** [comment]
It looks very outdated. Current remmina versions 1.1.2 works great for me in all modes: scrolling, scaling, full mode. @sirlark, could you retest it?

**Comment by sirlark** [comment]
Trying to, but presently it doesn't render anything at all (but I don't think that's a remimina issue)

**Comment by sirlark** [comment]
I can't get it into scrolling mode. It's not an option available. I suspect this might be because I'm connecting to windows terminal server, so there is no physical monitor, and the session is rescaled to my window size.

**Comment by antenore** [comment]
I'm closing this because this problem has been fixed since almost two years.

Be sure you have the last remmina installed. thx.
