### ISSUE TITLE
Please make survey & webkit-gtk dependency optional

### ISSUE THREAD

**Issue by benkohler** [FreeRDP/Remmina#812]
Starting in rc9, Remmina now has the HUGE webkit-gtk dep, non-optionally.  Could we make this optional behind a cmake option?

Thanks!

**Comment by antenore** [comment]
Ok, I'll do it the next week

**Comment by antenore** [comment]
@benkohler can you please test  the https://github.com/FreeRDP/Remmina/tree/nosurvey branch?

You can compile with -DWITH_SURVEY=OFF the default behaviour is ON

@giox069 tested on FC22

**Comment by benkohler** [comment]
Wow, thanks for looking at this so quickly.  It builds ok with -DWITH_SURVEY=ON but I get a build failure when I turn it off:
[remmina-log.txt](https://github.com/FreeRDP/Remmina/files/187919/remmina-log.txt)

**Comment by antenore** [comment]
I'm puzzled... I had the same error before but I don't know how I solved it, it disappeared as it came...

But, as nothing happens by causality... I'm taking a look

**Comment by antenore** [comment]
I fixed it, can you kindly try one more time?

Thanks and sorry...

**Comment by benkohler** [comment]
Looks good.  I tested with both OFF and ON, and tested the build and at runtime.  Everything looks perfect, as far as I can tell.

Thanks!

**Comment by antenore** [comment]
Perfect! I'll merge it as soon as we will test it on most platform we support and after my vacation :-P 

See you next week :-)

**Comment by antenore** [comment]
Tested on:

- Fedora 23
- Ubuntu 15.10
- FreeBSD 10.2 
 
I'm going to merge and close.
Thanks for your support
