### ISSUE TITLE
Feature request - Option - Floating Desktop Name [$5]

### ISSUE THREAD

**Issue by StuWhitby** [FreeRDP/Remmina#815]
I'm regularly using Remmina with simultaneous connections to multiple systems which I need to swap between.  To know which one I'm on, or which ones I'm ctrl+->ing to (I'm sure that's a word) I need to pin the desktop bar at the top, which I rarely need to use.

Is there any chance of getting an option to show the system/connection name overlaid at the top of the pane if the bar's not pinned?  Opaque, uninteractive, but just visible for quick reference whenever you need to see which desktop you're on.

Thanks for a great piece of software.
##

**Comment by antenore** [comment]
:+1: 

Do you mean in fullscreen mode?

Would you want something like a "Alt+Tab" combination of some desktop environments (showing the preview of the window) or crtl+arrows showing the preview/name/number of the workspace?

For example let's say Lctrl-right make you switch to the next connection showing you an overlay of the profile name?

**Comment by StuWhitby** [comment]
Yes, this request is relevant for fullscreen mode (I normally have Remmina running that way on one of my screens)

Personally I'd prefer it if the connection name was shown at all times (opaque, non-interactive in a reasonably small font at the top of the workspace).  If you want to link this to a key though, I'd personally link it to whenever Rctrl is held, as that's what I'm holding when "arrowing" between workspaces.

**Comment by antenore** [comment]
I've implemented it.

If it's not what you were looking for or if you have issues, let me know.

Within gnome-shell the notifications works in a weird way. We've found that in all desktop environments, but gnome, the notifications works as "the user" expect/want it.

**Comment by antenore** [comment]
I've implemented this in another way.
Now the floating toolbar pop up everytime you switch profile, to immediately (1 second later) disappear.
This is enough to see the server name.
