### ISSUE TITLE
Usage stats request window -> Any individual data will be shared with public or any other third party.

### ISSUE THREAD

**Issue by YoungJuleke** [FreeRDP/Remmina#816]
This message appears in the window where you ask to collect usage statistics... is it perhaps missing the word 'not' ????

**Comment by antenore** [comment]
Yes, sorry you are right I'm not English mother tongue so it didn't poped at me till you highlighted it.

I'll correct it as soon as I can.

**Comment by antenore** [comment]
Fixed, let me know if it needs any other improvements.

Thanks a lot again!!!
