### ISSUE TITLE
Remmina forces its windows to appear at the center of the screen

### ISSUE THREAD

**Issue by Vladimir-csp** [FreeRDP/Remmina#817]
It is probably better to let window manager do its job.

**Comment by antenore** [comment]
What do you mean exactly?
I'm using a tiling window manager so I don't see any particular issue.

Can you also provide some more background? OS, window manager, Remmina version, libfreerdp version, etc (the more the better)

**Comment by Vladimir-csp** [comment]
Debian testing
Openbox 3.6.1-2
Remmina 1.2.0~rcgit-11 (this was the case for 1.1 too).

Main window and connection window of Remmina always created at the center of the screen overriding placement policy of window manager.

**Comment by antenore** [comment]
Thanks.

If I provide a temporary development branch, would you mind testing it for me (a full test, with some different scenarios)? 

I can write code but I cannot test at the moment and I don't want to break the "next" (our master).

I'll work on it in the next days.

**Comment by Vladimir-csp** [comment]
I suppose, I would be able to build it by putting the code through the packaging setup from 'next' ppa, so I'll test it.

**Comment by antenore** [comment]
thx. I'll let you know. In the wiki we have instructions on how to build (quite straight forward)

**Comment by antenore** [comment]
You can test this.

Please try any scenario you can imagine about (full screen, multi monitor, multi window, etc)

Thanks for your support!!!

@giox069 , @weberhofer if you have time to test as well it would be great. Thanks!

**Comment by Vladimir-csp** [comment]
I will not be able to test multiple monitors for a couple of days, but everything else seem to check out. Main window and connection window are being placed by WM where it wants them. Child dialog windows are placed at the center of parent windows, which makes sense. So, initial issue is resolved.

Perhaps not related, but I've stumbled upon this problem just now: if I hide the panel with Host+T, connection window shrinks by height of a panel, but when when panel is revealed, the window does not grow. So the window is always shrinking. If panel is vertical, the window still shrinks vertically, by very large amount.

**Comment by antenore** [comment]
> Perhaps not related, but I've stumbled upon this problem just now: if I hide the panel with Host+T, connection window shrinks by height of a panel, but when when panel is revealed, the window does not grow. So the window is always shrinking. If panel is vertical, the window still shrinks vertically, by very large amount. 
 
This is a nice one! You are a good tester :-) 

@giox069 I can also replicate this. If the toolbar is vertical (on the side), the main connection window shrinks and grows till the height of the main connection window, is equal the sum of the height of all the toolbar icons (WTF!!!) :-D 

```
(remmina:7952): Gtk-CRITICAL **: gtk_window_resize: assertion 'height > 0' failed
```

This is another bug, I'm tempted to close this and open a new one... Yes. I'll include you both in the conversation
