### ISSUE TITLE
Please support XDG base directory spec

### ISSUE THREAD

**Issue by Vladimir-csp** [FreeRDP/Remmina#818]
Currently default configuration placed in `${XDG_CONFIG_DIRS%%:*}/remmina/remmina.pref` (`/etc/xdg/remmina/remmina.pref`) has no effect on fresh launch.
Connection profiles placed in `/usr/share/remmina` (resolved from `${XDG_DATA_DIRS##*:}/remmina/` for example) are not shown in the list.

**Comment by antenore** [comment]
Thanks. 
How urgent is this for you?

**Comment by Vladimir-csp** [comment]
Not urgent, just for sake of completeness. Please take your time.

**Comment by antenore** [comment]
@Vladimir-csp I was checking now the code and we already use the XDG_CONFIG_HOME and XDG_DATA_DIRS . It's something I've implemented in #590 and #738 , are you using  a recent version of Remmina? Also, be sure to use what is defined in your environment

**Comment by Vladimir-csp** [comment]
I am currently using 1.2.0~rcgit-11+896+next+201605022146 (version after those commits). User-level structure works fine, but global configuration and data do not apply.  Connections placed to `/usr/share/remmina/` are not listed. Placing config in /etc/xdg/remmina/remmina.pref has no effect on default configuration.

**Comment by antenore** [comment]
Ongoing.

$XDG_DATA_DIRS it's done and it should be good.
$XDG_CONFIG_DIRS in progress

**Comment by antenore** [comment]
$XDG_CONFIG_DIRS is done as well.
