### ISSUE TITLE
Problem with changing key assignment in the "Keyboard" tab (rcgit.11)

### ISSUE THREAD

**Issue by IgorFilth** [FreeRDP/Remmina#819]
Hi!  After updating to version rcgit.11 I can't change the key assignment in the “Keyboard” tab.
The same problem in the "Options" tab on buttons "Configure Resolutions" and "Configure the keystrokes"

**Comment by antenore** [comment]
Fixed, closing it.

Thanks for the report

**Comment by antenore** [comment]
The fix will be available in the next PPA update

**Comment by antenore** [comment]
@giox069 remember to merge this fix in your branches.

**Comment by IgorFilth** [comment]
Tnx!
