### ISSUE TITLE
Feature request: Implement "Credential Groups"

### ISSUE THREAD

**Issue by Fjodor42** [FreeRDP/Remmina#82]
I use remmina extensively at work - thank you for it!

Our password policy, however, stipulates pw changes every 3 months, and, to some extent, different passwords for different domains.

The need for me to connect varies widely between servers, and I'm not always sure whether remmina has saved the currently active credentials for the server I connect to (leading me, nearly always, to open the connection editor and type in the current password - diminishing the advantage of saving passwords at all.

Proposal: Implement "Credential Groups" that one can assign connections to be part of _or_, alternatively, expand the current grouping functionality to cover this.
##

**Comment by glazeus** [comment]
Please, please, implement feature "inherit from parent" and secure store credentials as MS RDCM do.
Thank you in advance

**Comment by giox069** [comment]
I'm working on a similar gadget: "multiple password changer". The MPC dialog will appear every time you change a password for a RDP connection and the same DOMAIN\username is used in other profiles...

**Comment by antenore** [comment]
@Fjodor42 we've released new Remmina version that implement this feature. I'm closing this.

**Comment by giox069** [comment]
starting from remmina 1.2.0-rcgit.19 the "Multiple password changer" can be activated from the main remmina menu.
