### ISSUE TITLE
ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]

### ISSUE THREAD

**Issue by freddyrv** [FreeRDP/Remmina#820]
Hello, I have just updated remmina to the latest version and I am not able to connect to a Windows 2012 server after upgrading.
This is the error I am getting, I have completely removed xfreerdp, rdesktop and remmina with purge and install it from scratch, issue is still happening.
Any help would be appreciate it,
This is the complete error I am getting when trying to connect: 

[11:16:29:854] [29341:29354] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[11:16:45:659] [29341:29354] [ERROR][com.freerdp.core] - failed to connect to 10.19.6.22
[11:16:45:659] [29341:29354] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[11:16:45:660] [29341:29354] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[11:16:45:660] [29341:29354] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
##

**Comment by giox069** [comment]
Did you compiled remmina by yourself or are you using a prepackaged version ? (ubuntu PPA ?). Which version are you exactly running (type `remmina --version`) ?
Also check the freerdp version with xfreerdp --version.
Try also to reboot the PC, if not already done.

**Comment by freddyrv** [comment]
Hello @giox069, I am using ubuntu PPA.

Remmina - Version 1.2.0-rcgit.11 (git n/a)
This is FreeRDP version 2.0.0-dev (git n/a)

I will go ahead and reboot now, thanks.

**Comment by freddyrv** [comment]
Hello all, @giox069 rebooting did not solve the issue, do you have any other suggestions?
Appreciate your help, thanks!

**Comment by ic3d** [comment]
Hi @vext01 @freddyrv we're reviewing old issues, do yuo still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.

**Comment by art-ist** [comment]
After it was working perfectly for a while I suddenly got that error and could resolve with [this](https://bluehatrecord.wordpress.com/2016/12/30/remmina-error/) solution.

> **edit the connection** in Remmina, head to the **Advanced** tab, and choose **TLS** for Security (by default, it is “Negotiate”)  I don’t know why the security negotiation appears to be failing in my case, but that resolved the issue for me.
