### ISSUE TITLE
Add a issues-templates to the project

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/Remmina#822]
Following all the issues on remmina I have recognized that on so many reported issues important information are missing. There is an feature to add issue-templates which could be very useful. The feature is documented here: https://github.com/blog/2111-issue-and-pull-request-templates

I'd recommend to add such an text like this one to the project:

```
We are supporting Remmina version 1.2+ versions only. Please do not bugs occuring on older versions!

Please give us some details about the system you are using:
* Clients OS:
* Remmina version: 
* Connecting to (OS and version):
* Connecting via (RDP, VNC, ...):
```

@antenore, @giox069 what do you think about that?

**Comment by antenore** [comment]
:+1: 

Johannes this is absolutely needed! Thanks a lot for the suggestion, I didn't find this feature in the past.

If Giovanni agrees as well we can go ahead.

Do you have time to do it? Otherwise I'll take a look in the following days.

**Comment by weberhofer** [comment]
I'll see if I can. Do you have any suggestions regarding the text?

**Comment by giox069** [comment]
:+1:
I agree. Me too, I tryed to find a similar thing but I never found one.
Suggestions for the text:

1. Client OS --> Client OS name and version
2. Add xfreerdp version
3. Add "Desktop environment (GNOME, Unity, KDE..:)"

If space is enough, add also instructions to obtain remmina and xfreerdp versions.
For newer versions is `--version` switch, for older, the user should search on the about menu of remmina.

**Comment by antenore** [comment]
For me it's fine.. Following Gio comments:

```
We are supporting Remmina version 1.2+ versions only. Please do not bugs occurring on older versions!

Please give us some details about the systems you are using: 

* Client (OS name and version):
* Remmina version (remmina --version): 
* Desktop environment (GNOME, Unity, KDE, ..):
* Connecting to (OS and version):
* Connecting via (RDP, VNC, ...):
* RDP issues only, freerdp version (xfreerdp --version):  
```

**Comment by antenore** [comment]
I love you guys!!!!
