### ISSUE TITLE
Remmina main connection window loose it's minimum height when the toolbar is hidden

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#829]
Followup of #817  

> Perhaps not related, but I've stumbled upon this problem just now: if I hide the panel with Host+T, connection window shrinks by height of a panel, but when when panel is revealed, the window does not grow. So the window is always shrinking. If panel is vertical, the window still shrinks vertically, by very large amount. 
 
This is a nice one! You are a good tester :-) 

@giox069 I can also replicate this. If the toolbar is vertical (on the side), the main connection window shrinks and grows till the height of the main connection window, is equal the sum of the height of all the toolbar icons (WTF!!!) :-D 

```
(remmina:7952): Gtk-CRITICAL **: gtk_window_resize: assertion 'height > 0' failed
```

@giox069 I assigned this to me, but if you know quickly how to solve it...

@Vladimir-csp

**Comment by antenore** [comment]
https://github.com/FreeRDP/Remmina/commit/f3276605405fd6b31e1b5b287fc835f12096e1b2 

It should work now

**Comment by Vladimir-csp** [comment]
Window now does not change size at all when toggling panel.
I would leave it as it is now. It's predictable and there is always Host+1
