### ISSUE TITLE
[Feature Request] Focus on 'server' box during 'New Connection'

### ISSUE THREAD

**Issue by tomswartz07** [FreeRDP/Remmina#838]
Hi there:

Thanks very much for this project. I use the program daily.
I'd like to suggest that the 'flow' for connecting to a new client be re-worked a bit.

*What currently happens:*
- Click on tray icon, select 'New Connection'
- Window appears, with focus immediately on 'Name'

*What should happen:*
- Click on tray icon, select 'New Connection'
- Window appears, with focus immediately on 'Server'

Why this is bothersome:
- When quickly connecting to a host 90% of the time, it's a single-instance, so it's not necessary to name the connection. The default name of 'Quick Connect' is fine.
- Because focus is taken to the 'Name' field and the words "Quick Connect" are highlighted, text stored in the Linux middle-click Selection Buffer is lost. Almost 100% of the time, I have a hostname selected and stored in the buffer before opening the new connection window; which requires an extra step once the window is open.

I'd greatly appreciate if it were possible to change this workflow.
It only makes sense to immediately allow a user to begin typing a hostname/IP address into the window right away.

Information:
* Client (OS name and version): Arch Linux
* Remmina version (remmina --version): `Remmina - Version 1.2.0-rcgit.11`
* Desktop environment (GNOME, Unity, KDE, ..): Gnome, i3WM
* Connecting to (OS and version): Windows 8.1, Other Linux.
* Connecting via (RDP, VNC, ...): Any

**Comment by antenore** [comment]
The point a like and understand more about this is:

>  Because focus is taken to the 'Name' field and the words "Quick Connect" are highlighted, text stored in the Linux middle-click Selection Buffer is lost. 

So yes, I definitively agree with you and I'll implement it right now.

I was just thinking what if I use what is in the clipboard primary selection as the "Quick connect" label (in place of "Quick connect")? In most cases you should have a hostname or an IP address in the clipboard.

Well, I don't know if it's easily possible, but I can  investigate about it. I'm just worried if someone could have highlighted some compromising text before to start to work.

@giox069 , @weberhofer what do you guys think about this?

**Comment by antenore** [comment]
Here it is  b54ea4a

I'll merge in upstream as soon as it will be tested.

Let me know what do you think about my second proposal.

**Comment by tomswartz07** [comment]
Awesome!

Thank you for the quick response.

In regards to your 'auto-paste' feature, perhaps it could be an option in the settings?
This way end-users can opt-in to the feature, rather than accidentally having passwords or sensitive info automatically entered.

I'm testing the latest commit now.

**Comment by tomswartz07** [comment]
Latest build from the [Focus_server-box](https://github.com/FreeRDP/Remmina/compare/Focus_server-box) branch works like a dream. :+1:

**Comment by antenore** [comment]
Ok thanks, so I'll merge and close the issue.

Regarding the clipboard integration I'll open a new feature request ( it could be also a button next to the Profile  and Server name).
