### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by SimpleTechGuy** [FreeRDP/Remmina#840]
remmina  1:1.2.0rcgit.11-1 not working after update...  Tested on desktop and laptop computers - same problem.  

..-Syyu - update to Remmina  1:1.2.0rcgit.11-1
..Remmina is working
..reboot computer
..Remmina not working 

Anybody else getting this?

Please give us some details about the systems you are using:
* Client (OS name and version): 
Linux 3.18.30-1-MANJARO #1 SMP PREEMPT Wed Apr 6 21:22:27 UTC 2016 x86_64 GNU/Linux

* Remmina version (remmina --version): 
Failed to load plugin: /usr/lib/remmina/plugins/remmina-plugin-vnc.so.
Error: libvncclient.so.0: cannot open shared object file: No such file or directory
Remmina - Version 1.2.0-rcgit.11 (git n/a)

* Desktop environment (GNOME, Unity, KDE, ..): 
XFCE

* Connecting to (OS and version): 
ALL Connections Affected

* Connecting via (RDP, VNC, ...): 
All connections

* RDP issues only, freerdp version (xfreerdp --version):

**Comment by SimpleTechGuy** [comment]
Seems to be affecting only the Teamviewer Plugin...  VNC and RDP are working fine.

**Comment by antenore** [comment]
At the moment we are experiencing some issues due to GTK+3.20 and the new VTE, we have fixed some but we are still working.

Regarding Teamviewer I can't do anything at the moment, you can submit a bug report to @Muflone 

I'll close this as it's out of scope, but I can reopen as soon as we will be sure that is related to Remmina and not to the Teamviewer plugin.

**Comment by SimpleTechGuy** [comment]
Verified the issue was related to remmina-plugin-teamviewer for a change in the remmina code that's incompatible with older plugins.  Teamviewer plugin was quickly updated by @Muflone and everything is working now as it should!  This issue was fixed in the 1.2.3.0 release.
