### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by rlees85** [FreeRDP/Remmina#842]
Following on from this issue:
[Issue 835, GTK 3.20 and VTE3 issues](https://github.com/FreeRDP/Remmina/issues/835)

It seems under certain circumstances Remmina will start to use 100% CPU.

For the context of this issue report, '_**old Remmina**_' is version **1.2.0-rcgit.11 (git: n/a)**. This is the current version that is in the Arch Linux repositories.

- 'old Remmina' works fine with VTE version libvte-2.91.so.0.4200.5.
- 'old Remmina' does NOT work with VTE version libvte-2.91.so.0.4400.1. Remmina shows a blank screen and this is covered in Issue 835 above. What is NOT covered is that whilst the blank terminal screen is OPEN, the CPU is pegged at 100%. When the terminal/SSH session is CLOSED the CPU returns to its standard usage.

For the context again of this issue report, '**_new Remmina_**' is a compiled version from the vte3 branch. The exact version is: **1.2.0-rcgit.11 (git 11396fc)**

**Now the bits that matter:**

- 'new Remmina' with the old VTE version libvte-2.91.so.0.4200.5, DURING the SSH connection, the CPU usage is fine, but after closing the SSH connection the CPU goes to 100%.
- 'new Remmina' with the new VTE version libvte-2.91.so.0.4400.1, again DURING the SSH connection, the CPU usage is fine, but again after closing the SSH connection, CPU goes to 100%.

Interestingly, when opening another SSH connection, the CPU will come back down to normal values.

**OS Details:**
Arch Linux (all packages up to date as of 22/04/2016)
Remmina versions discussed above.
Cinnamon 2.8.8 / GTK3.20

Thanks!

**Comment by antenore** [comment]
Thanks for the report.

@giox069 this is the issue I was speaking about, I have no clues at the moment...

I'll add additional details as I discover anything interesting.

**Comment by antenore** [comment]
A trace obtained with strace

```
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1645) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
 9160: poll({ 4/POLLIN 11/POLLIN 13/POLLIN 20/POLLIN 26/POLLIN },5,1644) = 1 (0x1)
 9160: recvmsg(0xb,0x7fffffffe390,0x0)           ERR#35 'Resource temporarily unavailable'
```

**Comment by antenore** [comment]
Got it!
It's fixed by 21d1b68dbed059008014e7848a38045c52e90873 

Let me check  with Giovanni about the best way to handle the PR

**Comment by rlees85** [comment]
Well.... that was quick lol, thanks a lot :+1:

**Comment by antenore** [comment]
Not at all... But thanks for the appreciation :-)
