### ISSUE TITLE
Drop libvte-2.90 support?

### ISSUE THREAD

**Issue by egmontkob** [FreeRDP/Remmina#843]
libvte-2.91 (tarball version 0.38+) was released 1.5 years ago, obsoleting libvte-2.90 (tarball up to 0.36).

As of now I believe all libvte-2.9x based apps managed to port to the new one. Debian Unstable and Ubuntu 16.04 Xenial LTS don't even ship libvte-2.90 anymore. I'm quite certain that libvte-2.91 is available in all modern distros.

I'm wondering that instead of maintaining an ifdef-maze and testing two kinds of builds in parallel, it might be a good choice to go with the newer one only??

**Comment by egmontkob** [comment]
(Inspired by commit 0fb13e1.)

**Comment by giox069** [comment]
It's currently needed by Ubuntu LTS 14.04, the most used linux distribution by remmina users.
Today, sunday, after our late morning update, more than 640 users updated their remmina using the PPA "remmina-next" for Ubuntu 14.04. All other PPA supported ubuntu versions summed up together only counts half of the 14.04 users.

Really... we can't abandon them :)

I think also Debian 8 stable uses libvte 2.90.

**Comment by egmontkob** [comment]
Okay :)

**Comment by giox069** [comment]
Just take a look to remmina_connection_window.c to understand what is a real big mess of code and #ifdef tue to big GTK+3 changes up to 3.10-3.12 :)
