### ISSUE TITLE
Duplicate of issue#99 on Remina 1.2.0

### ISSUE THREAD

**Issue by sqlsolver** [FreeRDP/Remmina#844]
ALT+TAB only shows most recently opened remote desktop and mgmt console for Remina.

Selecting the previous connection logs into it again, does not appear to support multiple RDP sessions.

Remina tabbed interface not visible.

Ubuntu 14.04
##

**Comment by ic3d** [comment]
Hi @sqlsolver we're reviewing old issues, do yuo still get this one?

**Comment by sqlsolver** [comment]
I deleted that VM, so probably best to close the issue. Great that you're
actively developing though, as there aren't lots of good options for RDP
clients in Linux.

*Please visit www.sqlsolver.com <http://www.sqlsolver.com/>*
* <http://www.sqlsolver.com/>530-237-4SQL*

**Comment by ic3d** [comment]
Thanks for your answer. Feel free to open this issue again if needed.
