### ISSUE TITLE
Cannot redirect microphone to VDI- Win10 HyperV- Raspberry Pi3- Rasbian Jessie

### ISSUE THREAD

**Issue by daniellelollis** [FreeRDP/Remmina#846]
Testing Raspberry Pi3 for virtual call center. Have installed all Remmina packages, and run all updates. Microphone seems to work through Audacity on Pi and is seen through Alsa settings, but when I log into the virtual machine, it states no audio devices installed. 
The microphone does work when using Windows Remote Desktop Connection from my primary PC, so it is not the virtual machine. 
This is my first time posting, please be easy on me :).

**Comment by antenore** [comment]
Can you give us some details about your setup?

* Client (OS name and version): 
* Remmina version (remmina --version): 
* Desktop environment (GNOME, Unity, KDE, ..): 
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): 
* RDP issues only, freerdp version (xfreerdp --version): 

Thanks

**Comment by daniellelollis** [comment]
•Client (OS name and version): Raspbian Jessie 
•Remmina version (remmina --version): 1.1.0
•Desktop environment (GNOME, Unity, KDE, ..): Where do I find this?
•Connecting to (OS and version): Windows 10 Hyper-V
•Connecting via (RDP, VNC, ...): RDP
•RDP issues only, freerdp version (xfreerdp --version): 
Testing Raspberry Pi3 for virtual call center. Have installed all Remmina packages, and run all updates. Microphone seems to work through Audacity on Pi and is seen through Alsa settings, but when I log into the virtual machine, it states no audio devices installed. 
 The microphone does work when using Windows Remote Desktop Connection from my primary PC, so it is not the virtual machine.

**Comment by weberhofer** [comment]
Please update to Remmina 1.2 as we do no longer support older versions.
Thank you for your understanding.
