### ISSUE TITLE
Cannot break from a command using CTRL + C since enhancement 833 was implemented

### ISSUE THREAD

**Issue by box293** [FreeRDP/Remmina#847]
Please give us some details about the systems you are using:

    Linux Mint 17.3 Rosa MATE
    Remmina version 1.2.0-rcgit.11
    Desktop environment : MATE
    Connecting to (OS and version): any linux SSH session
    Connecting via (RDP, VNC, ...): SSH

Since this enhancement https://github.com/FreeRDP/Remmina/issues/833 was implemented, I can no longer break out of programs like ping or tail while in an SSH session.

I understand that my host key (left ctrl) + c is now used for copying text, however it would be good if the right ctrl key could still be used for 'breaking'.

I know the host key can be defined in the preferences, so if someone had the host key as right ctrl then the left ctrl key could be used for 'breaking'.

**Comment by gnumdk** [comment]
Here my host key is Alt and Ctrl + C doesn't work...

**Comment by giox069** [comment]
Also CTRL+Z (susp) is not working in my ubuntu 16.04.

**Comment by giox069** [comment]
I have just pushed a fix (also for #858 @munsta0). If you are using the PPA, please wait for an automatic update tomorrow and let me know if it works.

**Comment by munsta0** [comment]
Thanks! I'll definitely check it tommorow.

**Comment by box293** [comment]
Just updated and issue is fixed, Thanks very much.

**Comment by munsta0** [comment]
ppa also updated and somewhat fixed the issue. I had to change the host key back to left alt because if it's binded to left control, break is not called, copy is.

While this is not an issue for me, it could be an issue in the future.

Thanks for the fix!

**Comment by antenore** [comment]
@munsta0 why don't you use right ctrl?
