### ISSUE TITLE
Error when compiling Remmina

### ISSUE THREAD

**Issue by hansa7** [FreeRDP/Remmina#848]
* Client (OS name and version): CentOS Linux release 7.2.1511
* Remmina version (remmina --version):  https://github.com/FreeRDP/Remmina/tree/next
* Desktop environment (GNOME, Unity, KDE, ..):  GNOME
* Connecting to (OS and version): Windows Server 2012 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): FreeRDP version 2.0.0-dev

I would like to compile Remmina on my CentOS Linux release 7.2.1511. 
For this I use the quick and dirty guide for compiling Remmina on Fedora 20 (https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20).
Step 12. (Compile remmina and install it) doesn´t work.

Error:
[root@localhost Remmina]# make && sudo make install
Scanning dependencies of target remmina
[  0%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_about.c.o
[  1%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_applet_menu.c.o
[  2%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_applet_menu_item.c.o
[  3%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_avahi.c.o
[  4%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina.c.o
[  5%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_chat_window.c.o
[  6%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_crypt.c.o
[  7%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_exec.c.o
[  8%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_file.c.o
[  9%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_file_editor.c.o
[ 10%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_file_manager.c.o
[ 11%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_ftp_client.c.o
[ 12%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_icon.c.o
[ 13%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_init_dialog.c.o
[ 14%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_key_chooser.c.o
[ 15%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_log.c.o
[ 16%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_main.c.o
[ 16%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_marshals.c.o
[ 17%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_masterthread_exec.c.o
[ 18%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_plugin_manager.c.o
[ 19%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_plugin_cmdexec.c.o
[ 20%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_pref.c.o
[ 21%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_pref_dialog.c.o
[ 22%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_protocol_widget.c.o
[ 23%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_public.c.o
[ 24%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_scrolled_viewport.c.o
[ 25%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_sftp_client.c.o
[ 26%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_sftp_plugin.c.o
[ 27%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_ssh.c.o
[ 28%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_ssh_plugin.c.o
[ 29%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_string_array.c.o
[ 30%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_string_list.c.o
[ 31%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_widget_pool.c.o
[ 32%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_external_tools.c.o
[ 33%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_sysinfo.c.o
[ 33%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_connection_window.c.o
Linking C executable remmina
CMakeFiles/remmina.dir/src/remmina_crypt.c.o: In function `remmina_crypt_init':
/root/remmina_devel/Remmina/remmina/src/remmina_crypt.c:54: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_exec.c.o: In function `remmina_exec_command':
/root/remmina_devel/Remmina/remmina/src/remmina_exec.c:108: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_exec.c:108: undefined reference to `remmina_survey_valid_profile'
/root/remmina_devel/Remmina/remmina/src/remmina_exec.c:111: undefined reference to `remmina_survey_cb'
CMakeFiles/remmina.dir/src/remmina_file.c.o: In function `remmina_file_new':
/root/remmina_devel/Remmina/remmina/src/remmina_file.c:121: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_file.c.o: In function `remmina_file_store_group':
/root/remmina_devel/Remmina/remmina/src/remmina_file.c:352: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_file_editor.c.o: In function `remmina_file_editor_update_resolution':
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:450: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_file_editor.c.o: In function `remmina_file_editor_browse_resolution':
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:460: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:464: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:465: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_file_editor.c.o: In function `remmina_file_editor_create_resolution':
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:501: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_file_editor.c.o: In function `remmina_file_editor_on_default':
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:1171: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_file_editor.c.o: In function `remmina_file_editor_on_connect':
/root/remmina_devel/Remmina/remmina/src/remmina_file_editor.c:1204: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_icon.c.o: In function `remmina_icon_enable_avahi':
/root/remmina_devel/Remmina/remmina/src/remmina_icon.c:119: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_icon.c:125: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_icon.c.o: In function `remmina_icon_populate_additional_menu_item':
/root/remmina_devel/Remmina/remmina/src/remmina_icon.c:157: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_icon.c.o: In function `remmina_icon_populate_extra_menu_item':
/root/remmina_devel/Remmina/remmina/src/remmina_icon.c:260: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_icon.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_icon.c:315: more undefined references to `remmina_pref' follow
CMakeFiles/remmina.dir/src/remmina_main.c.o: In function `remmina_main_on_action_help_survey':
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:928: undefined reference to `remmina_survey_start'
CMakeFiles/remmina.dir/src/remmina_main.c.o: In function `remmina_main_file_list_on_row_activated':
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:982: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_main.c.o: In function `remmina_main_quick_search_on_changed':
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:1030: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_main.c.o: In function `remmina_main_init':
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:1081: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:1083: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_main.c:1083: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_main.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_main.c:1084: more undefined references to `remmina_pref' follow
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_gen_secret':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:87: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:88: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:90: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_gen_uid':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:127: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:130: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:131: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:133: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_birthday':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:150: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:155: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:156: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:158: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_init':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:256: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:260: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:263: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:265: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:268: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:270: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:274: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:276: more undefined references to `remmina_pref' follow
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_save':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:625: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:627: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:628: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:630: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:632: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:633: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:634: more undefined references to `remmina_pref' follow
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_save':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:687: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_add_recent':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:703: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:709: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:716: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:728: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_get_recent':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:744: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_clear_recent':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:765: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:780: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_get_scale_quality':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:835: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:837: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:839: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_get_ssh_loglevel':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:845: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_get_survey':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:852: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:859: more undefined references to `remmina_pref' follow
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_set_value':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:876: undefined reference to `remmina_pref_file'
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:879: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref.c.o: In function `remmina_pref_get_value':
/root/remmina_devel/Remmina/remmina/src/remmina_pref.c:893: undefined reference to `remmina_pref_file'
CMakeFiles/remmina.dir/src/remmina_pref_dialog.c.o: In function `remmina_pref_on_button_resolutions_clicked':
/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:78: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:82: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:83: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref_dialog.c.o: In function `remmina_pref_on_button_keystrokes_clicked':
/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:105: undefined reference to `remmina_pref'
/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:109: undefined reference to `remmina_pref'
CMakeFiles/remmina.dir/src/remmina_pref_dialog.c.o:/root/remmina_devel/Remmina/remmina/src/remmina_pref_dialog.c:110: more undefined references to `remmina_pref' follow
collect2: error: ld returned 1 exit status
make[2]: *** [remmina/remmina] Error 1
make[1]: *** [remmina/CMakeFiles/remmina.dir/all] Error 2
make: *** [all] Error 2

**Comment by giox069** [comment]
The failure in the link phase can be due to another remmina left installed in your system.
Can you check if you uninstalled all remmina and freerdp packages ? (use a rpm package manager, like rpm itself :)).

**Comment by hansa7** [comment]
I uninstalled all remmina an freerdp packages.
I get the error again.

**Comment by Stolb27** [comment]
@hansa7 I have the same error. I had resolve it by add package libwebkit2gtk-4.0-dev

**Comment by larchunix** [comment]
@hansa7  Please provide the options given to `cmake` and the output of its execution.

**Comment by maramon** [comment]
remmina_pref is defined in remmina_survey.c.  If Webkit2 is not found, remmina_survey.c is not compiled.  Maybe cmake processing should be stopped if Webkit2 is not found?  See attached diff.

[diff.txt](https://github.com/FreeRDP/Remmina/files/288421/diff.txt)

**Comment by larchunix** [comment]
@maramon You're right, applied in 1901fc6. Thanks

@hansa7 Could you retry to build Remmina from git and close this issue if it works fine ?
