### ISSUE TITLE
Enhancement - Variables for pre- and post-commands

### ISSUE THREAD

**Issue by CS-JS** [FreeRDP/Remmina#849]
I'd like to suggest adding variables for pre- and post-commands like $host for the specific hostname the connection is created for.

My use-case is that many of my hosts I'd like to reach via rdp are behind an on-demand openvpn router, which means the vpn itself is connected, when the first packages arrive for a host in that subnet. However, if I just double-click my remmina connection, it will timeout the first time due to the connection being established first. What I'd like to do, would be a pre-command which does something like "ping $host -c 2", just so the vpn-connection gets established before remmina connects the rdp session.
##

**Comment by antenore** [comment]
I'll profit to improve also other limits of the pre/post commands.

As the "host" variable, do you mean the server name in the remmina profile (sorry if it's a stupid question)? So do you need something like the ssh %h %p (what else?)? 

Regarding your specific case, did you try to use a script as a pre/post command?

**Comment by CS-JS** [comment]
There are no stupid questions, only stupid answers :)

Maybe I can clarify the enhancement a little more, if I tell something about my background - I migrated from Windows to Ubuntu on my laptop at work and we have to manage lots of servers via RDP. On Windows I used mRemoteNG as RDP management software, which had a neat little feature called external programs. You can run scripts, start other programs, whatever has a commandline, and you can substitude the properties of the actual connection as a variable to those commands.

So, for example, I defined a "ping"-Command as following and mRemote executed it, before I connected to servers, which I know had a small bandwith for their internet connection and took longer till the vpn-tunnel to the server was established.

"ping $host -n 3"

The command was defined once, and could be applied to any connection by right-clicking the connection and enabling the command.

From what I found in remmina (which is a really great tool by the way :) ) I can only add a pre command for a connection, so I have to "hard code" the IP address or hostname in the connection file. Since we have quite many connections and the commands are likely to change once in a while, my point is, if I hardcode every connection file, some will be overlooked. It would be very nice to have a central configuration for those commands, and as suggested in the opening post those variables.

**Comment by antenore** [comment]
Slowly but surely :-) 

I've implemented the host niddle (%h), let me know if you think we need anything else.

#1378

**Comment by antenore** [comment]
It's not possible to build it right now because I've forgot to add a new file, it's on my local repository at home, I'll add it later.

**Comment by antenore** [comment]
Fixed, it'd be possible to test it. Let me know
