### ISSUE TITLE
[Enhancement] Start in background

### ISSUE THREAD

**Issue by prometheanfire** [FreeRDP/Remmina#85]
I can't find a way to start it in the background.

I'd like to autostart on login, but the popup gets annoying to have to clear every login.

**Comment by muflone** [comment]
Is this issue still valid? Please provide better information.
Actually I'm closing this two years old issue

**Comment by prometheanfire** [comment]
remmina -i works, but isn't documented in the help, if it could be documented I think that's all that's needed.

**Comment by muflone** [comment]
The command line arguments are shown using the --help or -h arguments only ATM.
We'll add some documentation soon.
