### ISSUE TITLE
Quick find is slow with a lot of profiles

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#852]
Using remmina compiled from the latest "next" branch, ubuntu 16.04 and arch.

I have 184 .remmina files on the remmina dir. When I type a single character on the quick find search box, it can take from 0.1 to 2 sec to refresh the filtered profile list.

This usually doesn't happen on first remmina startup, but after some minutes of use (maybe when these files are no longer in the filesystem cache ?).

I did a bit of tracing, and it seems that for every keypress, remmina_main_quick_search_on_changed() calls remmina_main_load_files(), which in turn reopens all 184 profile files and reparse them.

**Comment by giox069** [comment]
It seems that just removing `remmina_main_load_files(FALSE);` from `remmina_main_quick_search_on_changed()` the search is very fast again.
@antenore: what do you think of this fix ?

**Comment by antenore** [comment]
I'll take a look why I needed that function there, moreover without refresh.

**Comment by antenore** [comment]
Calling this function was needed to refresh the list of profiles while typing in the search box.

Not sure how to deal with this issue, if reopening it, creating a new one or just forget about the refresh.

What do you think?

**Comment by giox069** [comment]
The refresh for every keystroke is still working now, but it takes data from the local remmina cache and not from the disk. And it's very fast.
I think it's ok. It's not needed to re-read data from the disk for every keystroke: there are no other processes that can modify remmina config files during remmina usage. Only one session of remmina can exists. Yes, the user can still modify these files with a text editor, but he usually knows that a remmina restart may be needed.
