### ISSUE TITLE
Continual flicker due to redraw (VNC from Windows to Ubuntu)

### ISSUE THREAD

**Issue by rgayler** [FreeRDP/Remmina#857]
This is probably a configuration problem rather than an issue. Please accept my apologies for raising it here but I couldn't find help anywhere else online.

* Client OS: Ubuntu 14.04 64-bit
* Remmina: 1.2.0-rcgit.11 (git n/a) - installed from PPA 
* Desktop environment: Unity
* Connecting to: Windows 8.1 Basic
* Connecting via: VNC (tightVNC Server 2.7.10 & DFmirage driver 2.0.301): 

I installed Remmina 1.2.0-rcgit.11 (git n/a) remote desktop client on Ubuntu 14.04 64-bit, to connect to a Windows 8.1 Basic machine running tightVNC Server 2.7.10 . When I first connected, the display of the Windows machine on Ubuntu was very smooth (just a little delayed - I had the two machines next to each other and could see the delay).

After a while mucking around with other things, removing the screen from the Windows machine, and rebooting both machines a few times the quality of the Windows display on Ubuntu had changed - there was an obvious redraw of the screen approximately once or twice every second. The whole display is blacked out then redraws from the top down in large blocks. This makes it very hard to view and interact with the displayed remote screen.

I presume I must have changed some setting in Remmina, and have looked at all the settings but can't work out what the problem is. Any suggestions for what to look at would be greatly appreciated.

Thanks

Ross

**Comment by antenore** [comment]
Which GPU do you have (and which kernel module)?

Your environment it's quite unusual for me, can you also try with other**s** vnc client**s** (just to confine the problem) ?

**Comment by rgayler** [comment]
Thanks for the suggestion to try another VNC client - I will do that.

It got stranger after I posted the issue - after a while the problem went
away, then later on it came back again. I didn't make any software or
configuration changes during that period. So, I think it's less likely to
be an issue with the GPU on the Ubuntu (client) machine. I wonder whether
there is some intermittent process on the Windows (server) machine that is
interfering with the send.

**Comment by rgayler** [comment]
I also get the flashing with the vinagre client - so I think it's either the TightVNC server, something that Windows or the LAN is doing to TightVNC server, or something about the graphics on Ubuntu.  I'll keep looking elsewhere.
