### ISSUE TITLE
Can't move tabs between windows

### ISSUE THREAD

**Issue by gnumdk** [FreeRDP/Remmina#861]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version):  Archlinux
* Remmina version (remmina --version): 1.2.0-rcgit.11 (git f3307c8)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): Any
* Connecting via (RDP, VNC, ...): Any
* RDP issues only, freerdp version (xfreerdp --version): None

Since using current git (to fix VTE3 issue), I can't move tabs between windows.

Regards,

**Comment by giox069** [comment]
I did some testing on arch.
It seems it happens after the upgrade of GTK from 3.20.3-4 to 3.20.4-2: dragging a GtkNotebook tab seems to be in some cases constrained to the source window.
If you revert back to GTK 3.20.3-4 it works again.
To downgrade:
```
cd /var/cache/pacman/pkg
pacman -U gtk3-3.20.3-4-x86_64.pkg.tar.xz
reboot
```

**Comment by giox069** [comment]
Ok. It seems that in arch GTK 3.20.4-2 if a GtkNotebook tab is both detachable and reorderable, it cannot be detached.
Here is a python script to reproduce it. Just remove the "reorderable" lines and DnD will work again:
```
#!/usr/bin/env python

import gi
gi.require_version('Gtk','3.0')
from gi.repository import Gtk

class DraggableTabWin(Gtk.Window):
	def __init__(self, title):
		Gtk.Window.__init__(self, title=title)
		self.set_default_size(400,300)
		self.set_border_width(3)


		self.nb = Gtk.Notebook()
		self.nb.set_group_name("grp01")

		self.add(self.nb)
		self.nb.set_hexpand(True)
		self.nb.set_vexpand(True)

		self.page1 = Gtk.Box()
		self.page1.set_border_width(10)
		self.page1.add(Gtk.TextView())
		self.nb.append_page(self.page1, Gtk.Label("Page1/"+title))

		self.page2 = Gtk.Box()
		self.page2.set_border_width(10)
		self.page2.add(Gtk.TextView())
		self.nb.append_page(self.page2, Gtk.Label("Page2/"+title))

		self.nb.set_tab_detachable(self.page1, True)
		self.nb.set_tab_detachable(self.page2, True)

		self.nb.set_tab_reorderable(self.page1, True)
		self.nb.set_tab_reorderable(self.page2, True)

		self.connect("destroy", Gtk.main_quit)
		self.connect("delete-event", Gtk.main_quit)


if __name__ == "__main__":
	win1 = DraggableTabWin("win1")
	win2 = DraggableTabWin("win2")
	win1.show_all()
	win2.show_all()

	Gtk.main()
```

**Comment by gnumdk** [comment]
Can reproduce with Gnome Terminal... Closing and reporting on GTK side...

**Comment by giox069** [comment]
Thank you. If you can also post a link to your GTK report (just to track it), we will be happy. Thank you.

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=766442

**Comment by giox069** [comment]
:+1:
