### ISSUE TITLE
Location of saved connections is wrong in Wiki

### ISSUE THREAD

**Issue by iamnotzerocool** [FreeRDP/Remmina#866]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): 
* Remmina version (remmina --version): 
* Desktop environment (GNOME, Unity, KDE, ..): 
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): 
* RDP issues only, freerdp version (xfreerdp --version):

**Comment by iamnotzerocool** [comment]
Ubuntu 16.04
Remmina 1.2.0
GNOME

Information on https://github.com/FreeRDP/Remmina/wiki is incorrect.  The new location for saved connections is located at /home/.local/share/remmina

**Comment by giox069** [comment]
Fixed FAQ#1. Can you check
https://github.com/FreeRDP/Remmina/wiki/Remmina-Usage-FAQ
and then close this issue ?
Thank you very much.

**Comment by Fr3llD** [comment]
Hi, i found out the FAQ on the main website is also referencing a not complete picture of the location of the files: http://www.remmina.org/wp/faq/

I would suggest removing the FAQ from the main website and referencing the github wiki. 

It's a minor issue offcourse, but it threw me off.
