### ISSUE TITLE
Remmina hangs after clicking minimize 

### ISSUE THREAD

**Issue by cjscholten** [FreeRDP/Remmina#867]
Whenever I have an open session in a maximized window that I want to minimize, the session hangs and won't respond anymore.
I have three monitors and changing focus to another monitor causes the session to minimize.
If I activate it again the session works fine again, so just minimizing doesn't work.

I'm using:

Remmina 1.2.0-rcgit.3
Fedora 23 - Gnome
Connecting to RDP (Windows 2012) or SSH (Various linux distros)
##

**Comment by antenore** [comment]
Can you please upgrade remmina and FreeRDP and test it again?

**Comment by ic3d** [comment]
Hi @cjscholten we're reviewing old open issues. Did you try @antenore suggestion? Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.
