### ISSUE TITLE
Remmina SPICE doesn't show the connections anymore

### ISSUE THREAD

**Issue by snaumov** [FreeRDP/Remmina#885]
Hi,

after the last update 1.2.0-rcgit.12 the connections list is empty

![selection_018](https://cloud.githubusercontent.com/assets/5119578/15673743/b6548f6c-2749-11e6-9794-532ea1e695b6.png)

It remains empty when I add new connection item (the amount of connections increments however).

Please give us some details about the systems you are using:
* Client (OS name and version): Linux sup-a1107 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Remmina version (remmina --version): remmina - Version 1.2.0-rcgit.12 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): Gnome Flashback
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version):

**Comment by giox069** [comment]
The last update from the Ubuntu PPA should report 1.2.0-rcgit.13, not 12. Or we have a problem on the PPA, but I cannot test on a ubuntu 14.04 today.
Have you tryed to reboot your PC ?

**Comment by antenore** [comment]
I was answering as well but @giox069 is faster :-)

I don't have as well an Ubuntu 14.04 to test.

Can you also execute Remmina from the command line and copy&paste the output?

**Comment by snaumov** [comment]
@giox069 That was quick, thank you! On reboot the issue is resolved! 
Have a good day!
