### ISSUE TITLE
Remmina closes even if I press "No" when it asks if I'm sure

### ISSUE THREAD

**Issue by colemickens** [FreeRDP/Remmina#888]
* Client (OS name and version): `Arch Linux -- community/remmina 1:1.2.0rcgit.12-1`
* Remmina version (remmina --version): `remmina - Version 1.2.0-rcgit.11 (git n/a)`
* Desktop environment (GNOME, Unity, KDE, ..): `GNOME 3`
* Connecting to (OS and version): `Windows boxes`
* Connecting via (RDP, VNC, ...): `RDP`
* RDP issues only, freerdp version (xfreerdp --version): `This is FreeRDP version 2.0.0-dev (git c3ce0c3)`

If I open two RDP session and then try to close the main remmina window, I am asked "There are two active connections in this window. Are you sure to close to close?"

No matter if I pick Yes or No, remmina exits and takes my sessions with it.

As a sidenote, it'd be nice to be able to close the remmina connection list window and not have it close all of the existing RDP sessions......

EDIT: Antenore: Removed part of the header.

**Comment by antenore** [comment]
Hi @colemickens 

Thanks for the report.

I can reproduce it, I'll take a look.

In the meanwhile, if you like, we released a new version with several new features and fixes (rcgit.13).
