### ISSUE TITLE
I do not see the button "Creane a new connection profile"

### ISSUE THREAD

**Issue by SpoolerX** [FreeRDP/Remmina#897]
* Client (OS name and version): 
Arch linux 4.5.4-1-ARCH
* Remmina version (remmina --version): 
remmina - Version 1.2.0-rcgit.13 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): 
Qt: 5.6.0
KDE Frameworks: 5.22.0 with default theme

Problem:
I dont see create a new connection in left corner.
https://zapodaj.net/241bbd0779733.png.html

**Comment by antenore** [comment]
This is weird :-( 

Out of curiosity, does it work with another desktop environment (the rest all the same)?

Can you execute remmina from the command line and cut&paste here any message you have?

**Comment by SpoolerX** [comment]
_[wojtek@Archi ~]$ remmina
Failed to load plugin: /usr/lib/remmina/plugins/remmina-plugin-vnc.so.
Error: libvncclient.so.0: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu

** (remmina:2996): CRITICAL **: secret_service_load_collections_sync: assertion 'paths != NULL' failed

** (remmina:2996): CRITICAL **: secret_service_read_alias_dbus_path_sync: assertion 'SECRET_IS_SERVICE (self)' failed

(remmina:2996): Gtk-WARNING **: Theme directory actions/48 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/16 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/22 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/48 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory devices/48 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(remmina:2996): Gtk-WARNING **: Theme directory actions/48 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/16 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/22 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory categories/48 of theme breeze has no size field


(remmina:2996): Gtk-WARNING **: Theme directory devices/48 of theme breeze has no size field_

**Comment by antenore** [comment]
Unlucky it's clearly a theme issue I can't do anything but advising you to use another theme.
Check also if you can tune the interoperability between KDE and GTK+ , it was possible in previous releases.

I'm closing this because it's out of scope (not a development issue)... You can still ask support in our Remmina Google Plus community.

https://plus.google.com/communities/106276095923371962010

**Comment by SpoolerX** [comment]
Thanks a lot!
