### ISSUE TITLE
RemoteApp support

### ISSUE THREAD

**Issue by SpoolerX** [FreeRDP/Remmina#898]
Hi!
In Microsoft Server 08-12r2 have option "RemoteApp", this function can generate .rdp file. After running I have the ability to run specific applications without the entire Windows desktop environment. Application look like local installed application. 

RDP File look like this:

redirectclipboard:i:1
redirectposdevices:i:0
redirectprinters:i:1
redirectcomports:i:1
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:15
prompt for credentials on client:i:1
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:0
promptcredentialonce:i:1
authentication level:i:2
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:0
gatewaycredentialssource:i:0
full address:s:10.50.50.254
alternate shell:s:||PSI-JFox
remoteapplicationprogram:s:||PSI-JFox
gatewayhostname:s:
remoteapplicationname:s:PSI-JFox.exe
remoteapplicationcmdline:s:

More about file: http://www.donkz.nl/overview-rdp-file-settings/

This is a very convenient feature allows you to quickly deploy the files on the computers and the user does not even know that the application is running remotely. Automatically redirected printer and RS232 ports allow to cool and fast service positions store sales.

**Comment by antenore** [comment]
Isn't the the Startup Program in Remmina?

![selection_155](https://cloud.githubusercontent.com/assets/5975/15889487/a8c7097e-2d6b-11e6-940f-772b950a1173.png)

**Comment by SpoolerX** [comment]
Yes, sorry is same function! Sorry!

**Comment by antenore** [comment]
No worries
