### ISSUE TITLE
apt-get fresh install error on Ubuntu MATE 15.10

### ISSUE THREAD

**Issue by ensisnoctis** [FreeRDP/Remmina#903]
While trying to install remmina for the first time on my Rapsberry Pi 2 (Ubuntu MATE 15.10) with
`sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard`
(copied from main git page) I get:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina : Depends: remmina-common (= 1.1.2-3ubuntu1) but 1.2.0~rcgit-11+936+next+201606162233~ubuntu15.10.1 is to be installed
           Recommends: remmina-plugin-vnc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by antenore** [comment]
You still have an old remmina version on you Pi2, you have to purge it.

    - Update your ubuntu, if you have limited bandwidth, you can ignore this.

	apt-get update.

    - Remove all remmina and freerdp packages

	sudo apt-get --purge remove freerdp-x11 remmina remmina-common remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-gnome remmina-plugin-nx remmina-plugin-telepathy remmina-plugin-xdmcp
    
    - Install the new remmina version

	sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
	# the following line is optional if you have limited bandwidth.
	sudo apt-get update
	sudo apt-get install remmina remmina-plugin-rdp


Careful, don't just execute blindly the commands because I usually don't use ubuntu. :-P

**Comment by antenore** [comment]
@giox069 is telling me that it won't probably work.

The best solution is to compile Remmina, using the Ubuntu 14.04 and 16.04 guides in our wiki, but there are some modifications for the ARM platform compared to the standard way to go.

Try to follow the guides removing the -DSSE2=on options. It should be a good start. Let me know and blocking errors, I'll try to help you.

**Comment by giox069** [comment]
@ensisnoctis we just added the armhf architecture to the ubuntu PPA. You can retry to install remmina from the PPA as you did in your first post. I tested it on my Rapsberry PI2 with ubuntu mate 16.04. I hope it will work with 15.10 also.

**Comment by ensisnoctis** [comment]
It installs fine now :)
It's a shame I was mistaken Remmina is an RDP server. I need to connect TO Ubuntu, not FROM it ;) Thanks for fixing this package for future generations, though!
