### ISSUE TITLE
missing remmina settings icon ubuntu 14.04

### ISSUE THREAD

**Issue by specialist-ilya** [FreeRDP/Remmina#906]
Hi! im using remmina 1.2.0~rcgit-11+936+next+201606162233~ubuntu14.04.1 on ubuntu 14.04, missing settings menu icon
icons theme: ubuntu-mono-dark, gtk theme: Ambiance

screenshot
![2016-06-18 22 51 49](https://cloud.githubusercontent.com/assets/20018142/16173343/bfdc1fa4-35af-11e6-8941-3b3cf1a3808a.png)

sorry for my bad english)

**Comment by antenore** [comment]
Duplicated of #902
