### ISSUE TITLE
SSH terminal color customization

### ISSUE THREAD

**Issue by Psykar** [FreeRDP/Remmina#91]
Allow customization of terminal foreground and background colors.
Wishlist, but still!

There was a patch submitted to sourceforge quite some time ago:
http://sourceforge.net/tracker/index.php?func=detail&aid=3315460&group_id=278330&atid=1181676

Even better would be a way to override the default terminal patlette (gnome-terminal etc. style)

The patch is no longer able to be applied immediately as a few file names have changed, but it looks OK overall (yet to test it)

**Comment by muflone** [comment]
The branch https://github.com/FreeRDP/Remmina/tree/Issues/91 contains initial code to this issue.
A new setting for specify system theme colors was added
![preferences-dialog](https://cloud.githubusercontent.com/assets/1284163/5603179/59710a8a-9377-11e4-814a-39159a333094.png)

Default SSH colors
![default-colors](https://cloud.githubusercontent.com/assets/1284163/5603180/64adf96c-9377-11e4-83e4-115c66ab561b.png)

System theme SSH colors
![system-theme-colors](https://cloud.githubusercontent.com/assets/1284163/5603181/711f63fc-9377-11e4-8372-c1406d406529.png)

**Comment by muflone** [comment]
Added the support for custom foreground and background colors in the preferences window

Preferences window
![schermata da 2015-01-04 23 27 32](https://cloud.githubusercontent.com/assets/1284163/5607776/8c05b908-9469-11e4-9e38-454d62a5b14b.png)

Color selection
![schermata da 2015-01-04 23 27 37](https://cloud.githubusercontent.com/assets/1284163/5607777/9c9ab138-9469-11e4-80c7-7c54edd9c379.png)

Customized colors in SSH session
![schermata da 2015-01-04 23 27 45](https://cloud.githubusercontent.com/assets/1284163/5607778/ac0306fc-9469-11e4-8422-a9bd8ab684c3.png)

**Comment by muflone** [comment]
Please test the Issue/91 branch https://github.com/FreeRDP/Remmina/tree/Issues/91

**Comment by muflone** [comment]
Fixed in the branch 'next'

**Comment by saslann** [comment]
@muflone the link "https://github.com/FreeRDP/Remmina/tree/Issues/91" isn't reachable. can someone provide it again.

**Comment by giox069** [comment]
@saslann This issue has been fixed and merged on the "next" branch, and the "Issues/91" branch has been deleted.
If you want the sources, just clone locally the "next" branch.
Binary packages in Ubuntu's PPA "remmina-next" already contains the fix.
