### ISSUE TITLE
"Unable to connect to RDP server $HOST"  More verbose error request

### ISSUE THREAD

**Issue by derjur** [FreeRDP/Remmina#912]
Ubuntu 16, using gnome-shell.  
Connecting over RDP to a Windows server host. 

"Unable to connect to RDP server $HOST" error message could be more verbose, to assist in troubleshooting.  An incorrect password appears the same as a down host, which unfortunately lead me into a multi-hour troubleshooting session.

**Comment by antenore** [comment]
Can you provide remmina and freerdp version?

For more debug run remmina from the command line, if you need even more you can activate traces at compile time and you have a debug window in the Remmina menu.

I close the issue, if you need more let me know.,

**Comment by masip85** [comment]
Ok.

Same problem to connect to windows server 2012 R2: nla doesn't works here.With remmina either.

You have to force rdp. But command flags order is quite important. /sec-rdp doesn't work either. So I can using this order:

 xfreerdp +clipboard /log-level:TRACE /sec:rdp /v:xxxx /d:Ixxxx /u:xxxxx /p:xxxxx
