### ISSUE TITLE
SSH - Blank Window After Upgrading Fedora 23 to 24

### ISSUE THREAD

**Issue by Dolphykins** [FreeRDP/Remmina#913]
After upgrading a fairly fresh install of Fedora 23 Workstation to Fedora 24, SSH sessions (saved and new) are launching a blank window with a blinking cursor for me. This procedure was followed for the OS upgrade: https://fedoramagazine.org/upgrading-fedora-23-workstation-to-fedora-24/

Client: Fedora 24, Kernel 4.5.7-300.fc24.x86_64
Remmina Version 1.2.0, Release 0.13.rcgit.7.fc24
Gnome Shell 3.20.2
Connecting to: FreeBSD 7.x-10.x, Kubuntu 15.10
Connecting via: SSH

SSH connections work fine in Gnome-terminal, attached a screenshot of the SSH window after connecting and entering credentials.

![screenshot from 2016-06-23 14-01-02](https://cloud.githubusercontent.com/assets/20116277/16318161/17facff2-394b-11e6-8232-831bad49e55f.png)

**Comment by antenore** [comment]
Hi and thanks for this report, but this is duplicated of #899 

As soon as possible I'll test myself and let you know.

I'm going to copy&paste your post and close this one.
