### ISSUE TITLE
Copy/paste between Windows 10 guest and Remmina 1.2.0-rcgit.14 (git n/a) host

### ISSUE THREAD

**Issue by yuriw** [FreeRDP/Remmina#916]
I don't see that this copy/past is actually working on this configuration.
Not sure if this is a bug or there is some documentation on how to enable it?
##

**Comment by abeidson** [comment]
I am having a similar problem trying to copy from a Windows 2012 R2 remote session to my Fedora box.

**Comment by antenore** [comment]
Can you provide also the FreeRDP version?

```sh
xfreerdp --version
```

Do you have TeamViewer running? Has been reported that steal the clipboard...

**Comment by yuriw** [comment]
@abeidson No TeamViewer running
 xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)

**Comment by antenore** [comment]
I cannot reproduce any clipboard issues unlucky :-\

I actually work on FreeBSD 10.3, Fedora 23, Arch Linux and Ubuntu 16.04.

There must be something that "steal" your clipboard content or the clipboard manager used by your distro that doesn't detect the call remmina does to the clipboard (through GDK).

May be unrelated but are you using wayland or X?
If you are using wayland, do you mind trying to install xwayland (restart desktop session) and test it again?

@giox069 do you think the issue could be around xwayland?

**Comment by yuriw** [comment]
i am using x11vnc
Pls let me know how to test that "steal" issue.  I'd be happy to find a root for this issue as it annoys many people :/

**Comment by abeidson** [comment]
Antenore,

 I am running the same version of xFreeRDP on Fedora 24 and no TeamViewer
running either.

After running it in a Terminal I did find this

(remmina:12326): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates:
assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is
discouraged.
[13:20:03:598] [12326:12330] [INFO][com.freerdp.client.common.cmdline] -
loading channel cliprdr

**Comment by antenore** [comment]
@abeidson thx , nothing (so) bad there.
@yuriw I'll test with VNC ASAP, I thought you had the issue with RDP :-P

**Comment by yuriw** [comment]
and I see:

  yuriw@yuriw-RH ~/sources/ceph [13:25:51]> 
(remmina:8221): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[13:26:04:996] [8221:8232] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr

I run both :)

**Comment by antenore** [comment]
Meanwhile Giovanni is saying to check which is your running clipboard manager and try another one.

I'm using gpaste and I don't have these kind of issues.

*Careful* don't install and run 2 different clipboard managers at the same time.

**Comment by yuriw** [comment]
@abeidson unclaer on gpaste, pls elaborate

**Comment by abeidson** [comment]
Looks like Fedora uses Parcellite for the clipboard manager. Will give gpaste a try.

**Comment by yuriw** [comment]
@abeidson how can I check "check which is your running clipboard manager" ?
I'd install gpaste and see if that helps.

**Comment by abeidson** [comment]
@yuriw I found it in some documentation for Fedora.. You can also go to distrowatch.com and find the version of Linux your running, there is a link for full package list to show what is installed by default. 

Though after installing Gpaste I am still not able to copy/paste. Parcellite is no longer running on my system. Still trying to determine if another clipboard manager may be running.

**Comment by yuriw** [comment]
@abeidson tried `diodon`, works fine between ubuntu-host<=>ubuntu-guest and does not work for ubuntu-host<=>winodws10-guest

**Comment by ic3d** [comment]
Hi @yuriw @abeidson we're reviewing old open issues, do you still get this issue? Thanks!

**Comment by yuriw** [comment]
@ic3d no my copy/paste working fine Windows 10/Ubuntu 16.04

**Comment by abeidson** [comment]
After I upgraded to Fedora 25 the issues I had disappeared. I recently
upgraded to Fedora 26 and it has been just as stable.

Thank you
