### ISSUE TITLE
Connect windows PC using windows PC name in Linux Mint 18

### ISSUE THREAD

**Issue by rahulkane** [FreeRDP/Remmina#918]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Linux Mint 18 
* Remmina version (remmina --version): latest
* Desktop environment (GNOME, Unity, KDE, ..): Mate or Cinnamon
* Connecting to (OS and version): Windows 10 Pro 
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 

I am trying to connect to a windows 10 based PC over LAN using its PC name. I do not wish to used the IP. Remmina doesnt connect an RDP using the PC name. It does connect if I use the windows PC's IP instead. Please guide.

**Comment by box293** [comment]
Can your Linux Mint machine resolve the PC name?
```
ping thePCname
nslookup thePCname
nslookup thePCname.yourdomain.local
```
If it doesn't then you'll need to add it to your DNS server.

**Comment by antenore** [comment]
Hi @rahulkane,

This is not a remmina bug.

You can get more support on our [Remmina G+ community](https://plus.google.com/communities/106276095923371962010) or through some of the following generic communities (these are only some examples I know and not recommendations) 

* Reddit

https://www.reddit.com/r/linuxquestions
https://www.reddit.com/r/linux4noobs

* Stack Exchange

http://serverfault.com/
http://askubuntu.com/
http://superuser.com/

Thanks @box293 for your support :+1:
