### ISSUE TITLE
View bug

### ISSUE THREAD

**Issue by zuriy** [FreeRDP/Remmina#920]
I'm use 1.2.0-rcgit.14 (git n/a) and ubuntu 16.04(x86)  FreeRDP version 2.0.0-dev (git n/a)

When i'm working on windows 2008 r2  on RDP I have visualuzation problem:
http://storage1.static.itmages.com/i/16/0707/h_1467914793_1005195_25b72a7ef8.png
This is not very big problem, but when insert end line. On video 
https://yadi.sk/i/vLEI6mZEt6apw
and 
https://yadi.sk/i/Ys5ROpxXt6aqA
When I connect to this session from windows rdp all work correct.

**Comment by antenore** [comment]
Can you please test using xfreerdp from the command line?

Do you have the same problem?

**Comment by zuriy** [comment]
Yes. I have. --С уважением Задачин ЮрийОтдел разработки дистрибуторских решенийКомпания "Украинские интеллектуальные технологии"www.uit.kiev.uayuriy.b.z@uit.kiev.uaskype: yuriy.b.z   13.07.2016, 12:56, "Antenore Gatta" <notifications@github.com>:Can you please test using xfreerdp from the command line?Do you have the same problem?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by antenore** [comment]
:-( so this is a FreeRDP issue and I cannot help you.

Please open a new issue here  https://github.com/FreeRDP/FreeRDP/issues reference this (remmina) issue, so that thgey have a bit more background.

I'll close this as "out of scope"

Spasibo.

**Comment by giox069** [comment]
Plase note: the FREERDP package contained in our PPA is a bit outdated if compared with the latest version of FreeRDP. The FreeRDP team provides more updated .deb packages fro ubuntu.

**Comment by zuriy** [comment]
Thanks. How can I check my version?  
➜  ~ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)
➜  bin ls xfreerdp --format=long
-rwxr-xr-x 1 root root 5640 Июн 20 11:49 xfreerdp

**Comment by giox069** [comment]
this is fery difficult, beacuse all are reporting 2.0.0.
The correct thing to do is to uninstall all freerdp and remmina packages, remove the PPA and then install freerdp ones. But... It's a bit complex to explain in detail.
