### ISSUE TITLE
minimize button does not function well

### ISSUE THREAD

**Issue by he-loop** [FreeRDP/Remmina#921]
When in remote session in full-screen mode, using the minimize button of the Remmina toolbar seems to have no effect.

After pressing the button, if I immediately right-click, it produces some effect : the remote desktop window disappears showing the local desktop and its right-click menu.
That seems to indicate the window was already minimized and the screen did not refresh properly.

edit : This seems to occur in Gnome-Classic  session only

Thank you for your work,

Ubuntu-Gnome 16.04, Gnome 3.18 (Classic mode)
RDP to Windows 10

PPA  "remmina-next"
libfreerdp1   2.0.0~dev~git20160331+dfsg-0xenial3
Remmina    1.2.0~rcgit-11+937+next+201606230432~ubuntu16.04.1
##

**Comment by antenore** [comment]
I also notified some weird behaviour with that control in the past, but I never investigate it further.

Before I take a look, @giox069 do you know why is like this?

**Comment by ic3d** [comment]
Hi @he-loop we're reviewing old open issues, do you still get this one? Thanks!

**Comment by he-loop** [comment]
Hi @ic3d,
I'm actually using Remmina 1.2.0-rcgit-20 on Fedora26 and it works like a charm (even in Gnome Classic session).
I cannot tell you if the bug is still present in Ubuntu-Gnome 16.04 + reminna-next PPA.

Thank you for your work

**Comment by ic3d** [comment]
Thanks @he-loop, I'm closing this issue because it's probably solved - I'm not sure about it, because we didn't released a specific fix. Feel free to open it again if still happens.
