### ISSUE TITLE
Invisible Add-Button due to color

### ISSUE THREAD

**Issue by MaFreiberger** [FreeRDP/Remmina#924]
Kubuntu 16.04
remmina 1.2.0-rcgit.14 (git n/a)

![remmina-no-add-button](https://cloud.githubusercontent.com/assets/20354079/16800468/c0c382b4-48f5-11e6-9602-5eabe13ebd3c.png)

![Uploading Remmina-No-Add-Button.png…]()

**Comment by antenore** [comment]
This is a theme issue. You should ask to the theme maintainer to add the icon you need, or you can modify it by hand.

See #902 for reference on how to work around it.

Closed as duplicated of #902
