### ISSUE TITLE
windows key always captured

### ISSUE THREAD

**Issue by karlsebal** [FreeRDP/Remmina#925]
Thank you for Remmina. I am on an ubuntu 16.04 running Remmina 1.2.0-rcgit.14 (git n/a) installed via ppa. I have Unity installed but am using i3. I am connecting to a windows7 virtual machine.

The windows-key is always captured no matter if capturing is on or off (toggling by strg_r)

**Comment by antenore** [comment]
That happens also to me and it's normal.

Every time I'm in the Windows window and I switch to another i3 workspace,  I use Mod4+number , Windows steal the windows key and you hand up with the Start Menu opened.

You can:

1) Change or Mod key in i3
or
2) Change the windows key on window.
