### ISSUE TITLE
how do I do dual-monitor RDP sessions?

### ISSUE THREAD

**Issue by rj11** [FreeRDP/Remmina#927]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): 
- Remmina version (remmina --version): 
- Desktop environment (GNOME, Unity, KDE, ..): 
- Connecting to (OS and version): 
- Connecting via (RDP, VNC, ...): 
- RDP issues only, freerdp version (xfreerdp --version): 
##

**Comment by antenore** [comment]
Is it the same question as #376

If it's that the case, it's hard to implement it and we are thinking about it.

**Comment by antenore** [comment]
Duplicated of #376

**Comment by ic3d** [comment]
Closing because it's a duplicate.
