### ISSUE TITLE
Arch Linux: Unable to load RDP plugin

### ISSUE THREAD

**Issue by christian-raedel** [FreeRDP/Remmina#931]
* Client (OS name and version): **Arch Linux (x86_64) 4.6.4**
* Remmina version (remmina --version): **1.2.0-rcgit.14 (git 10f7f9f)**
* Desktop environment (GNOME, Unity, KDE, ..): **i3wm**
* Connecting to (OS and version): **Windows 10**
* Connecting via (RDP, VNC, ...): **RDP**
* RDP issues only, freerdp version (xfreerdp --version): **2.0.0-dev (git 50649ac)**

Hi,

since an update of the ```openh264``` package from AUR, remmina is unable to load its RDP plugin, because it cannot find ```libopenh264.so.1```.
An **symbolic link** between ```libopenh264.so.3``` and ```libopenh264.so.1``` fixed this issue:

    $> sudo ln -s /usr/lib/libopenh264.so.3 /usr/lib/libopenh264.so.1

Regards,
Christian

**Comment by antenore** [comment]
Thanks for the report. I'll take a look at the make files.

**Comment by antenore** [comment]
This is more a FreeRDP issue. Did you install the last available freerdp package? The git commit you are referring to is more than one month old.

I would remove/clean FreeRDP and reinstall it and remmina as well.

It could also a build issue, so you should ask the guys managing the FreeRDP AUR to update it.

**Comment by antenore** [comment]
Closed as no answer

**Comment by masterviana** [comment]
I know its closed, but have same issue not able to use RDP protocol. So I follow @antenore tip install last freerdp package and its work for me.
