### ISSUE TITLE
RD Gateway Doesn't Support different username/password

### ISSUE THREAD

**Issue by thisSIDEofRANDOM** [FreeRDP/Remmina#933]
xfreerdp has support for different user/pass for rdgateway connections however there is no way in remmina to specify a different username/password at this time.

A field or even just a check box for a prompt for this would go a long ways.
`
Options:

```
   /g
       <gateway>[:port]

   /gu [<domain>\]<user> or <user>[@<domain>]
       [<domain>\]<user> or <user>[@<domain>]

   /gp <password>
       <password>

   /gd <domain>
       <domain>
```

`
##

**Comment by antenore** [comment]
Let us check internally how much work it is and when we will be able to do it.

FYI @giox069

**Comment by giox069** [comment]
I think somewhere we already have another open issue for this ehnancement...

**Comment by giox069** [comment]
... but we do not have a RD gateway to test on :(

**Comment by thisSIDEofRANDOM** [comment]
I would love to help here, but unfortunately this is at my place of work and the RD gateway is a proprietary vendor appliance. I can't offer out a testing environment for this enhancement. :(

**Comment by thisSIDEofRANDOM** [comment]
Just wanted to update and see if there was any development or potential for adding this feature in. Most people using RDGateway do not use the same credentials for the gateway as the destination. T

**Comment by Beerey** [comment]
+1

**Comment by giox069** [comment]
It should not be too complex to add, but we need a RD gateway and proper configuration to test. If anyone is available to provide one, we will be happy. I think I could provide hardware on which install a windows server VM, but we need someone able to configure RD gateway and find how to handle possible licensing problems (trial period??).
As an alternative to the RD gateway for testing, we can develop this feature and then someone @thisSIDEofRANDOM or @Beerey, should compile a separate code branch of remmina and test it with its own RD gateway...

**Comment by jackdozier** [comment]
I can provide a temporary RD gateway test setup. Give me some time (later today) and I'll post the info here. I can help test the new code as well.

**Comment by antenore** [comment]
@jackdozier this is really cool! Thanks. Instead of posting it over here, for your infrastructure safety, I'd say that is better to send us (myself and Giovanni) an email. Our emails are in the about widget in Remmina.
Take your time, we are quite busy with "physical life" as well.

**Comment by jackdozier** [comment]
@antenore Will do. I'll also email you and Giovanni about the VM offer. If it stands, I bet I can work with you to set up a more permanent test instance that you guys can spin up at will.

**Comment by antenore** [comment]
That would be amazing ^^

**Comment by antenore** [comment]
We have implemented it in the issues_933-rdpgateway branch. Whoever is willing to help with testing is really welcome.

The RD settings have been moved in the Advanced tab.
At this point we'd like to revolutionize the UI as it's really not good at the moment. So if you have any ideas...

**Comment by thisSIDEofRANDOM** [comment]
Happy to help test! Will report back :)
