### ISSUE TITLE
SSH - Secure Shell Issue

### ISSUE THREAD

**Issue by zeronug** [FreeRDP/Remmina#936]
Fedora 24
Latest Remmina version.
GNOME
CentOS 7 
SSH - Secure Shell

I setup a SSH connection, it connects, I enter my password.  

On the Remmina terminal screen the cursor just flashes and doesn't allow me to do anything.  I know it's connecting because the server I'm trying to connect to sends me an email whenever someone connects.

Not sure what is happening.  But I don't have any access to the server via SSH.

I found this issue, which seems to be the same thing that is happening to me.  https://github.com/FreeRDP/Remmina/issues/899 though, I'm having the issue.

**Comment by antenore** [comment]
It's surely due to the vte library you are using. Check which version you have installed and which version are available and try to switch between them and let me know.

**Comment by ryankpaul** [comment]
Debug looks like it is a switch passed to the command line for GSSAPI Auth?

Debug Window Output:
[SSH] ssh_config_parse_line: Unsupported option: GSSAPIAuthentication, line: 59

[SSH] ssh_config_parse_line: Unsupported option: ForwardX11Trusted, line: 63

[SSH] ssh_config_parse_line: Unsupported option: SendEnv, line: 65

[SSH] ssh_config_parse_line: Unsupported option: SendEnv, line: 66

[SSH] ssh_config_parse_line: Unsupported option: SendEnv, line: 67

[SSH] ssh_config_parse_line: Unsupported option: SendEnv, line: 68

[SSH] socket_callback_connected: Socket connection callback: 1 (0)
[SSH] ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.2 FreeBSD-20160310
[SSH] ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.2 FreeBSD-20160310
[SSH] ssh_analyze_banner: We are talking to an OpenSSH client version: 7.2 (70200)
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,keyboard-interactive

Helpful?  I _LOVE_ this program BTW

**Comment by ryankpaul** [comment]
remmina-1.2.0-0.21.git.679bb8e.fc25 http://koji.fedoraproject.org/koji/packageinfo?packageID=10031 resolves this issue for me, as reported in #899 

Thanks!!
