### ISSUE TITLE
Possibility to enter a remote command in SSH when I use it for VNC

### ISSUE THREAD

**Issue by Nicolas01** [FreeRDP/Remmina#94]
I use REMMINA as a VNC client, I really like the scale/zoom feature !!!
I use the REMMINA SSH tunneling to connect to my VNC server, but I would like to start my VNC server after the SSH connection and before the VNC connection.
Usually I use the SSH remote command :
ssh -C -L 9999:localhost:5900 user@ip 'x11vnc -display :0 -auth /var/run/slim.auth'
But in REMMINA it seems there is no place to enter such a SSH remote command like the one to start my VNC server.

Please, could you add a textbox to enter a SSH remote command? Thanks :)

**Comment by antenore** [comment]
Sorry for the huge late 

Does #520 can solve your issue?

Otherwise I'll look into it.

**Comment by hasues** [comment]
I'm not sure.  Does this allow one to set up a VNC session by executing a command to a remote server to spawn the VNC service and then activate the listener or some such?  I'm sure I'm not using the version of Remmina that is being referenced in #520.  Nicolas01's description is adequate in how this is achieved, but it Remmina had no configuration for such in the past.  I provided the the documentation on setting that up in libssh, which is what Remmina uses.
  I'll have to check out the latest source on Remmina, but this will not be immediate.

**Comment by antenore** [comment]
Prior commands is a feature I've implemented, that let you execute any commands or scripts before to connect to the server.

In this case, you could execute 

```
ssh -C -L 9999:localhost:5900 user@ip 'x11vnc -display :0 -auth /var/run/slim.auth'
```
Before to initiate the connection.

Otherwise I didn't get what is your requirement :-P

**Comment by hasues** [comment]
Looks like this is simply an issue of verbiage.  If the feature allows you to execute remmina VNC connection with a command that you listed, that is what we are needing.  The confusion is the term "prior", as I thought you were discussing prior the the SSH session being established.  Yes, I think this should work.  Apologies for the confusion.

**Comment by antenore** [comment]
No needs to ask sorry :-) , the important thing is the result.

I close this, but don't hesitate to reopen it in the case you will have an issue.
