### ISSUE TITLE
Starting the Remmina connection from commandline in full screen

### ISSUE THREAD

**Issue by charlessmith499** [FreeRDP/Remmina#941]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): 
- Remmina version (remmina --version): 
- Desktop environment (GNOME, Unity, KDE, ..): 
- Connecting to (OS and version): 
- Connecting via (RDP, VNC, ...): 
- RDP issues only, freerdp version (xfreerdp --version): 
  How can i get the connection to open in full screen every time from a command line in ubuntu 
##

**Comment by Kh4l3tH** [comment]
I wasnt able to achieve this via the command line but rather via the .remmina configuration file. Find the line with viewmode and change it to viewmode=3.

**Comment by ic3d** [comment]
Hi @charlessmith499 @Kh4l3tH we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by Kh4l3tH** [comment]
yes, this way of starting remmina in fullscreen from command line still works ;)

**Comment by ic3d** [comment]
Thanks @Kh4l3tH, closing this issue.
