### ISSUE TITLE
Import Plugin Dialog

### ISSUE THREAD

**Issue by Justinzobel** [FreeRDP/Remmina#954]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 16.04
* Remmina version (remmina --version): 1.2
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): N/A
* Connecting via (RDP, VNC, ...): N/A

When opening the import plugins dialog, the "Select/Open" button is named "document-open"
![screenshot from 2016-08-12 18-39-38](https://cloud.githubusercontent.com/assets/1370117/17617969/265d2048-60bc-11e6-9be8-a3b9e20ec3e4.png)

**Comment by antenore** [comment]
Found : 

https://github.com/FreeRDP/Remmina/blob/d2f6ebe484a2caf997398c789e2b848c84e77f11/remmina/src/remmina_main.c#L835 

Let's call it "Import" ?

**Comment by Justinzobel** [comment]
Sounds good to me!

**Comment by antenore** [comment]
Would you like to try it yourself (I can guide if you don't have git experience)?

**Comment by Justinzobel** [comment]
Done :D

**Comment by antenore** [comment]
:-) thank you
