### ISSUE TITLE
spice plugin missing on Ubuntu PPA

### ISSUE THREAD

**Issue by facboy** [FreeRDP/Remmina#958]
I can't seem to find the spice plugin on the Ubuntu PPA, am I doing something wrong?

* Client (OS name and version): Ubuntu 16.0.4.1
* Remmina version (remmina --version): remmina - Version 1.2.0-rcgit.14 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): MATE
* Connecting to (OS and version): CentOS 7.2
* Connecting via (RDP, VNC, ...): SPICE

**Comment by antenore** [comment]
No, you are right, Matteo is working on it.

You can test it if you want (it's not official and will be removed as will be merge with the official PPA)

```

sudo add-apt-repository ppa:nastasi/remmina-exp3
sudo apt-get update

```

**Comment by antenore** [comment]
Did has been fixed in the last release.

**Comment by coolemza** [comment]
1.2.0-rcgit-15 (git n/a) still no spice plugin, is it ok?

**Comment by antenore** [comment]
Do you have spice packages installed? (protocol, spice-gtk, spice-glib).

From the remmina menu --> plugins do you see the spice plugin?

Somewhere (probably under /usr/local/lib64/remmina/plugins/) you should have a file named remmina-plugin-spice.so 

Can you search find for it? Using dpkg-query should be easy:

```sh
dpkg-query -L <package_name>
```
