### ISSUE TITLE
SSH Tunneling

### ISSUE THREAD

**Issue by Jean-Dom** [FreeRDP/Remmina#96]
First of all, thanks for this software. It is clearly the best I have tested, because it works (:-)) and is fast.

Also, I wonder why there is no tab, when creating an SSH connection, for tunneling application...

I use this software to connect to other sites. In VNC mode, it is perfect and I am glad to find the SSH tunneling for the VNC mode.
Because it is easy to use it, and to reduce the number of software I use, I also setup my SSH connections in Remmina... And I cannot setup a Tunnel for my PostgreSQL connection !

I am setting up a new Linux server, and I do not want to open the PostgreSQL port to outside connections. So, I have to establish a tunnel.

Thanks in advance for considering my request.

Jean-Dominique, Annecy, France, Europe, Earth, Sun system, Milky Way, Somewhere.

**Comment by Hubbitus** [comment]
It some sort of duplication of https://github.com/FreeRDP/Remmina/issues/83, #223 and #235 (or in different order). If ~/.ssh/config will be properly handled all ControlMaster, tunnels, agent forwardings and proxy commands may be defined there.

**Comment by antenore** [comment]
Can you test https://github.com/FreeRDP/Remmina/commit/6bd5bb59b6bdd60318ac2b17bf86302e89b2c682 ?

It adds support to ~/.ssh/config, but not all the options are supported.

**Comment by antenore** [comment]
Closed by #235
