### ISSUE TITLE
Unicode copy leads to crash

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#967]
Hi.

Description of problem:
Used Ctrl-C to copy a selection from a Windows app on the remote machine. Doing so consistently crashes Remmina.

Version-Release number of selected component:
remmina-1.2.0-0.4.git.b3e339e.fc22

Truncated backtrace:
Thread no. 1 (5 frames)
 #0 _wcslen at /usr/src/debug/FreeRDP-24a752a70840f3e4b027ba7c020af71f2bcfd94a/winpr/libwinpr/crt/string.c:110
 #1 cliprdr_process_format_list at /usr/src/debug/FreeRDP-24a752a70840f3e4b027ba7c020af71f2bcfd94a/channels/cliprdr/client/cliprdr_format.c:144
 #2 cliprdr_order_recv at /usr/src/debug/FreeRDP-24a752a70840f3e4b027ba7c020af71f2bcfd94a/channels/cliprdr/client/cliprdr_main.c:363
 #3 cliprdr_virtual_channel_client_thread at /usr/src/debug/FreeRDP-24a752a70840f3e4b027ba7c020af71f2bcfd94a/channels/cliprdr/client/cliprdr_main.c:778
 #4 thread_launcher at /usr/src/debug/FreeRDP-24a752a70840f3e4b027ba7c020af71f2bcfd94a/winpr/libwinpr/thread/thread.c:257

Please look at https://bugzilla.redhat.com/show_bug.cgi?id=1210245 for details

**Comment by antenore** [comment]
Pavel this is old. The rcgit.5 has been released almost one year ago  and since then we solved these kind of issues.

Can you try with the rcgit.15 (and also a new version of freerdp)?

**Comment by Hubbitus** [comment]
Yeh, this is indeed very old. Sorry. I go to close it.
