### ISSUE TITLE
VNC server/client not working

### ISSUE THREAD

**Issue by furai** [FreeRDP/Remmina#968]
Hello,

As requested during our chat on IRC I'm opening an issue for not working VNC Client/Server in remmina.
- Client: GNOME Ubuntu 16.04.1 LTS
- Remmina version: remmina - Version 1.2.0-rcgit.14 (git n/a)
- Desktop environment: GNOME
- Connecting to: GNOME Ubuntu 16.04.1 LTS
- Connecting via: Remmina's VNC Server, same version of remmina

If you need any additional information let me know.

Regards,
Furai
##

**Comment by kowash** [comment]
It seems like I am having the same problem.
Remina remote desktop stopped working since yesterday after the latest update on ubuntu was done.

**Comment by ic3d** [comment]
Hi @furai @kowash we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably afflicts an old version of Remmina. Feel free to open it again if needed.
