### ISSUE TITLE
Remmina deletes password, even if correct, and yet some other connection bug prevented connecting. 

### ISSUE THREAD

**Issue by mystica555** [FreeRDP/Remmina#974]
Please give us some details about the systems you are using:
- Client (OS name and version): 
  sabayon, current (*is this really the definition of "client?" my grammar indicates that "remmina" is the "client" adjective here)
- Remmina version (remmina --version): 
  Remmina - Version 1.2.0-rcgit.11 (git fd7bdc6)
- Desktop environment (GNOME, Unity, KDE, ..): 
  kde plasma 5.6.5
- Connecting to (OS and version): 
  windows, often 2008>2012R2.
- Connecting via (RDP, VNC, ...): 
  rdp
- RDP issues only, freerdp version (xfreerdp --version): 
  This is FreeRDP version 2.0.0-dev (git 470e147)

I've found a bug that seems to occur after remmina has remained open for some lengthy period, and then I try to connect to a server, which has not had its password changed, and which has worked before. 

Instantly upon trying to connect, it says my credentials are invalid. 
[13:10:27:606] [29380:3488] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
was the actual error.

As soon as I try again, my saved password is gone.

I do not want the saved password automatically deleted.

The bug appears to be in TLS/SSL routines screwing up, constantly, over many years of using freerdp, even prior to remmina integrating properly with it to the point that running remmina was not a surefire way to have 5 RDP sessions CRASH at random points when the GUI became unstable.

So, _stop deleting the password immediately_
##

**Comment by ic3d** [comment]
Hi @furai @mystica555 we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue, because it probably affects only old versions of Remmina. Feel free to open a new one if needed.
