### ISSUE TITLE
Screen capture software crashes remmina client

### ISSUE THREAD

**Issue by ghost** [FreeRDP/Remmina#98]
I'm using Remmina on ubuntu 12.04 x64 and if I use the print screen button or the snip-it capture program on a remote desktop, the remminia client usually crashes.  I can close out and re-connect and everything is fine as long as I do not try using copy/paste.  If I restart Ubuntu, I can use copy/paste again and do 1 or 2 screen captures before it starts to crash again.

I'm using the version that is currently available through the Ubuntu software center and listed as version 1.0.0.1.  However, after I install it, it shows up as version 0.9.99.1 in the about section of the client.  This is on Ubuntu 12.04 x64.

**Comment by muflone** [comment]
The remmina 0.99/1.0.0 is too old, please update your version of remmina. Follow our wiki page https://github.com/FreeRDP/Remmina/wiki to obtain instructions how to update Remmina for Ubuntu.

If this issue persists please reopen. For the moment I'm closing it.
