### ISSUE TITLE
remmina.org down

### ISSUE THREAD

**Issue by ComputingFroggy** [FreeRDP/Remmina#988]
Hi,
remmina.org is down !
The page http://www.remmina.org/wp/ keeps loading for ever.
Hopefully, it is just a hosting problem ... but I thought I would let you know, in case you can do something about it !

**Comment by antenore** [comment]
Thanks for your vigilance!

It seems sn hosting issue, where I live is accessible.

**Comment by antenore** [comment]
Seems fine now, thanks again for your support
