### ISSUE TITLE
VNC connection doesn't work if color is set to 256 colors (8 bpp)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [FreeRDP/Remmina#989]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Xubuntu 16.04
* Remmina version (remmina --version): 1.2.0-rcgit-15 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): Xfce
* Connecting to (OS and version): Raspbian 4.1.19+ running on Raspberry Pi B+
* Connecting via (RDP, VNC, ...): VNC
* RDP issues only, freerdp version (xfreerdp --version): NA

VNC connection doesn't work if color is set to 256 colors (8 bpp). It simply opens for a split second then closes, *exactly* like this issue says here: https://github.com/FreeRDP/Remmina/issues/699

Short-time user workaround (per the closed issue above): use a higher quality color setting: example: 15 bpp. Then it works fine. 

Short-time developer workaround: change the default color setting when using VNC to the 15 bpp color option. 

Long-time developer fix: fix it; make VNC work with 8 bpp color, like it should. 

Thanks! Great work on Remmina.

**Comment by ssieb** [comment]
I have 1.2.0-rcgit.7 on Fedora and I don't have any problem using 8bpp mode.  Is the server a factor here?  It works connecting to vino and tigervnc-server.

**Comment by ElectricRCAircraftGuy** [comment]
I don't know. Can you try using the x11vnc server to see what happens for you? I'm running the x11vnc server on a Raspberry Pi, and Remmina on Xubuntu 16.04 LTS. Try this command to start the x11vnc server on the Pi: `x11vnc -forever -usepw -display :0 -ultrafilexfer`. (I followed this tutorial here: http://www.megaleecher.net/Raspberry_Pi_VNC_Setup).

**Comment by antenore** [comment]
@ssieb same for me with rcgit.15

@ElectricRCAircraftGuy I'll try with x11vnc ASAP

**Comment by antenore** [comment]
I can confirm it's not reproducible with most of the VNC servers. With x11vnc I can reproduce it form time to time.

As it is out of scope I'll close this, but don't hesitate to contact us through G+, reddit or irc if you need support.
