### ISSUE TITLE
Remmina Won't Maintain Multiple RDP Sessions at the Same Time

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#99]
I first submit this bug here:
https://bugs.launchpad.net/bugs/1041759

I typically need to connect to multiple windows machines over RDP at the same time (rdesktop was able to do this). However, with Remmina, as I connect to an additional Windows machine, it disconnects me from the other one that I'm currently logged into.

Every once in a while, I can maintain connections to two Windows machines (at the same time), but never 3. The number connections should only be limited by resources, but currently the limitation seems to be due to a bug.

This bug can certainly be reproduce by simply attempting to maintain 3 separate simultaneous RDP connections. You'll be lucky to maintain 2 connections.

BTW, Remmina is great, it just needs a little last-mile-perfection.

**Comment by muflone** [comment]
Remmina activity is started again, do you still have this issue?
If so please reopen this issue

**Comment by cpaulik** [comment]
I still have this problem in remmina 1.2.0 on Ubuntu 14.04. I can open multiple sessions but only one is visible through the unity interface (alt-tab or the task switcher). If I close a session the one I've opened previously becomes visible and so on.

**Comment by giox069** [comment]
@cpaulik this issue has been closed. Please open a new one better describing your problem. Please keep in mind also that Remmina groups more sessions in a single window under different tabs (choose the grouping mode here: Edit->Preferences->Appearance->Tab interface).

**Comment by cpaulik** [comment]
@giox069 Thank you. The problem was the Tab interface. Now I see all the connections. I can however not figure out how the tabbed interface is supposed to work. I'll research and if I can not find a solution I'll open an issue for that.
